### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by vinaysoni** [dherges/ng-packagr#1]
Hi David, 

Learnt about ng-packagr from the "Create boilerplate for library 1692"
I read through the documentation and I can understand how to setup a library project.
Was wondering 
- how to install the ng-packagr tool?
- how to trigger a build to package the library?

Thanks,
Vinay

**Comment by dherges** [comment]
Hi,

I've added a demo app at [dherges/ng-packaged](https://github.com/dherges/ng-packaged)

**Comment by dherges** [comment]
There is an update sample in the README that ships with the tool, is shown on the github repository homepage and also on npm/yarn websites.

Also, the `integration/sample*` packages show how to use the tool as does the dherges/ng-packaged demo.

I'm closing this issue for the above reasons.
