### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by Dastardl** [dherges/ng-packagr#100]
#### Type of Issue

- [x] Bug Report
- [ ] Feature Request

#### Description

Whenever a Kendo ui element is included into the app, sorceryJs goes mental. It does not matter if it is added as a dependency or as a peerDependency.

#### How To Reproduce

I have setup a small example project [here](https://github.com/Dastardl/packagerKendoExample). In short what I did was:

1. Create new app with Angular CLI
2. Add new button component
3. Add Kendo UI button module to app
4. Use the Kendo ui button component in the apps' button component
5. Run npm run build.lib (ng-packagr -p ng-package.json)

Increasing the max amount of memory node can use did not solve this (it just went right up to 10Gb, so I assume there must be some circular reference?)

I have tried to get this working for a couple of days now, but I can't seem to figure it out. The Kendo module provides es2015 so I thought this would work, but apparently something goes amiss. Is this due to the module being way to big?

#### Expected Behaviour

When running the ng-packagr command I would expect it to bundle everything.

#### Version Information

ng-packagr: latest (also tested with incoming [PR#83](https://github.com/dherges/ng-packagr/pull/83) for commonJS compatability)
node: v6.11.1
refer to the example project for dependencies

**Comment by dherges** [comment]
Hi @Dastardl,

I looked into your repo and confirm that the build hangs up!

When I remove the import from `@progress/kendo-angular-buttons`, it works fine! For ng-packagr, I can say that external dependencies must be added to the `lib.externals` property: see your [ng-package.json](https://github.com/Dastardl/packagerKendoExample/blob/master/ng-package.json#L8-L9)

How this should look like w/ Kendo UI, please ask them, since they are offering commercial support and keep their source code internal.

**Comment by skorunka** [comment]
@Dastardl Hi, did you resolve this issue with sorcery?

**Comment by Dastardl** [comment]
@skorunka I did not. In the end I created my own build script that does a subset of things that this package does tailored to our project.

[This article](https://medium.com/@trekhleb/how-to-create-aot-jit-compatible-angular-4-library-with-external-scss-html-templates-9da6e68dac6e) helped me a great deal to get on the right track. It's not perfect, but gave enough information for me to get something working.

**Comment by skorunka** [comment]
@Dastardl Thank you for sharing, it is a good reading. What helped me, was to put all @kendo scripts in `externals` section of `ng-package.json`:

{
	"$schema": "../node_modules/ng-packagr/ng-package.schema.json",
	"dest": "../dist/my-lib",
	"lib": {
		"entryFile": "../ts/src/app/public_api.ts",
		"externals": {
			"eyc-sdk-ng-host-typings": "eyc-sdk-ng-host-typings",
			"@progress/kendo-angular-dateinputs": "@progress/kendo-angular-dateinputs",
			"@progress/kendo-angular-dropdowns": "@progress/kendo-angular-dropdowns",
			"@progress/kendo-angular-excel-export": "@progress/kendo-angular-excel-export",
			"@progress/kendo-angular-grid": "@progress/kendo-angular-grid",
			"@progress/kendo-angular-inputs": "@progress/kendo-angular-inputs",
			"@progress/kendo-angular-intl": "@progress/kendo-angular-intl",
			"@progress/kendo-angular-l10n": "@progress/kendo-angular-l10n",
			"@progress/kendo-data-query": "@progress/kendo-data-query",
			"@progress/kendo-drawing": "@progress/kendo-drawing"
		}
	}
}
