### ISSUE TITLE
Custom referenced typings breaks compilation.

### ISSUE THREAD

**Issue by bthharper** [dherges/ng-packagr#1007]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have an existing angular project which I am trying to convert into an angular library package, the library depends on some widget written in jQuery.  I am hitting some issues getting the custom widget typings to work.

#### How To Reproduce

Create an angular-cli (6.0.x) project, with an angular library, as follows:

```
ng new my-lib-app
cd my-lib-app
ng generate library my-lib
ng generate component my-button --project my-lib
```

Then export 'my-button' component in `public_api.ts` and `my-lib.module.ts`.

Add `MyLibModule` to `app.module.ts` and then add `lib-my-button` into `app.component.html`.

```
ng b my-lib
ng s
```
Run the app, http://localhost:4200/, and you'll see the simple component.

Now, `lib-my-button` depends on a widget for which we defined some typings for, these require jQuery.

```
npm i @types/jquery@3.3.1 -D
npm i @types/jquery@3.3.1 -S
```

Create a file called `button-widget.d.ts` in the `my-button` folder, consisting of:

```
interface ButtonWidgetOptions {
  toggleOnIcon?: string;
  toggleOffIcon?: string;
}

interface ButtonWidgetStatic {
  destroy(): void;
}

interface JQueryStatic {
  button: ButtonWidgetStatic;
}

interface JQuery {
  button(options?: ButtonWidgetOptions): JQuery;
}
```

Add a `widgets.d.ts` in the `lib` containing:

```
/// <reference path="my-button/button-widget.d.ts"/>
```

Add usages to `my-button.component`:

```
export class MyButtonComponent implements OnInit, AfterViewInit, OnDestroy {
  private jQueryElement: JQuery;
  private button: ButtonWidgetStatic;

  constructor(private element: ElementRef) { }

  ngOnInit() {
  }

  ngAfterViewInit(): void {
    this.jQueryElement = jQuery(this.element.nativeElement);
    this.jQueryElement.button({});
    this.button = this.jQueryElement.data('button');
  }

  ngOnDestroy(): void {
    this.button.destroy();
  }

}
```
Compile the library

```
ng b my-lib
```

All okay!

Now build the app:

```
ng b
Date: 2018-07-19T15:12:51.466Z
Hash: 4f1f357db84fb2877627
Time: 14640ms
chunk {main} main.js, main.js.map (main) 616 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 671 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]

ERROR in dist/my-lib/lib/my-button/my-button.component.d.ts(1,22): error TS6053: File 'C:/git/library/my-lib-app/dist/my-lib/lib/my-button/button-widget.d.ts' not found.
dist/my-lib/lib/my-button/my-button.component.d.ts(5,20): error TS2304: Cannot find name 'JQuery'.
dist/my-lib/lib/my-button/my-button.component.d.ts(6,13): error TS2304: Cannot find name 'ButtonWidgetStatic'.
```

If I remove the typings reference from `my-button.component` the library won't compile, if I leave it in then the consuming project fails.  I am sure there is something obvious I am missing here, but I am unclear what it is.  

As `button-widget.d.ts` has been moved to the root of `dist\my-lib` rather than being left in `dist\my-lib\lib\my-button`, I would have thought the reference in `my-button.component.ts` would be changed to `..\button.widget.d.ts`.  Alternatively, `button.widget.d.ts` should have been left where it is

Making this change to `dist\my-lib\lib\my-button\my-button.component.d.ts` allows me to compile the project.
``` 
/// <reference path="../../button-widget.d.ts" />
```

_Can you reproduce the error in the integration tests in ng-packagr?_

_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_

Yes

_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

#### Version Information

```
PS C:\git\library\my-lib-app>  node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.3
@angular/compiler:     6.0.9
rollup:                0.59.4
tsickle:               0.29.0
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by bthharper** [comment]
Add a copy of the project (as I suspect I've missed a step or two above) 

[my-lib-app.zip](https://github.com/dherges/ng-packagr/files/2210602/my-lib-app.zip)

**Comment by alan-agius4** [comment]
Hi @bthharper, I have looked into this, and can confirm it is a bug. I have create a PR with the fix.

Your reproduction was a key factor to solve this issue.

Thanks,
Alan
