### ISSUE TITLE
Feature Request: Provide a way to extract css into a separate file

### ISSUE THREAD

**Issue by dougludlow** [dherges/ng-packagr#1014]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Please provide a way to extract css into a separate file, similar to angular cli's `--extract-css` flag. When providing a library, users may not want to use the default styles. It seems necessary to provide a way to split css out of the bundles and provide a separate css file.

**Comment by alan-agius4** [comment]
This is not possible at the moment even from Angular and Angular CLI. 

`extract-css` doesn't work on component css, as these will transformed to javascript code when compiled with AOT. `--extract-css` only works on global styles and not styles referenced using `styleUrls`.

I suggest you take a look at (Angular Material)[https://github.com/angular/material2] to see how to handle different styles

**Comment by dougludlow** [comment]
@alan-agius4 thanks, will do!
