### ISSUE TITLE
Ionic + Webpack Sub-Entry Points failing

### ISSUE THREAD

**Issue by ehorodyski** [dherges/ng-packagr#1015]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When trying to create a repository with the following package structure below, Ionic (through Webpack) notes that it cannot find module `@eh/test/components`.

Package Structure:
`@eh/test`
`@eh/test/components`

#### How To Reproduce

Please find a sample repo here: https://github.com/ehorodyski/ng-packagr-issue

To run, `npm i` then `ionic serve`.

I do path linking in `tsconfig.json` which the IDE resolves to, but for the Webpack build, the path linking is in `config/webpack.config.js`.

#### Expected Behaviour

To run the sample app. 

I think there might be an issue with the project structure itself. Current information on this lib is hard to find, and the examples are not very intuitive to follow. For instance, when does one use `ng-package.json` or not? What are the possible values of the `package.schema.json`, and what do they control?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^3.0.3
@angular/*: 5.2.11
typescript: ~2.6.2
rxjs: 5.5.11
node: 8.11.2
npm: 6.1.0
ionic-angular: 3.9.2
```

**Comment by alan-agius4** [comment]
You have a couple of configuration issues. You should point to the bundled code and not typescript library code.

To get this working you need to update the below in your tsconfig;
```json
    "baseUrl": ".",
    "paths": {
      "@eh/test": [
        "libs/dist"
      ],
      "@eh/test/*": [
        "libs/dist/*"
      ]
    }
```

And in webpack.config.js the following;
```js
useDefaultConfig[env].resolve.alias = {
    "@eh/test": path.resolve('./libs/dist')
};
```

**Comment by ehorodyski** [comment]
Thanks for the response @alan-agius4 -- I'm almost there!

My last issue is that VSCode will toss this error in my `libs` folder:

```
[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

Would placing a `tsconfig.json` at the `libs` level help?

**Comment by ehorodyski** [comment]
Awesome, thank you so much @alan-agius4!

I've made a few deviations:
* I left the `src` paths in `tsconfig.json` -- it wasn't picking up the modules if I didn't do it this way.
* I changed the `entryFile` in both the package and sub-package to `index.ts`. I can't explain why, but it seems to be how Ionic will correctly pick up my custom components.
* I need to change the entry file from `public_api.ts` to `index.ts` for VS Code to run experimental decorators in the `libs` folder. Not sure why...

It's a lot for me to ask, but do you mind checking my latest commit and seeing if I'm packaging up my dependencies correctly?
