### ISSUE TITLE
'ENOENT: no such file or directory' when packaging project

### ISSUE THREAD

**Issue by denver-HJS** [dherges/ng-packagr#102]
#### Type of Issue

- [x] Help Wanted
- [ ] Bug Report
- [ ] Feature Request

#### Description

I have an Angular-CLI project that I'm trying to package as an NPM module, and when I target/include my child module containing components the script results in error with status 111.

#### How To Reproduce

The packaging script works properly when the WebWrapper components are not imported. Everything's been generated using the Angular CLI, but is it possible an export is missing?

*Child Module of the App*
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UiComponentsModule } from "./ui-components.module";
import { FlexLayoutModule } from '@angular/flex-layout';
import { CookieModule } from 'ngx-cookie';

import { WebWrapperHeaderComponent } from '../components/web-wrapper-header/web-wrapper-header.component'; // when commented out the script runs successfully
import { WebWrapperFooterComponent } from '../components/web-wrapper-footer/web-wrapper-footer.component'; // when commented out the script runs successfully

@NgModule({
  imports: [
    CommonModule,
    UiComponentsModule,
    FlexLayoutModule,
    CookieModule.forChild()
  ],
  exports: [
    WebWrapperHeaderComponent,    // when commented out the script runs successfully
    WebWrapperFooterComponent     // when commented out the script runs successfully
  ],
  declarations: [
    WebWrapperHeaderComponent,    // when commented out the script runs successfully
    WebWrapperFooterComponent      // when commented out the script runs successfully
  ]
})
export class WebWrapperModule { }
```

*WebWrapperFooter component that fails the script*
```
import { Component, OnInit } from '@angular/core';
import { FooterLink } from "../../classes/footer-link";					// class
import { WebWrapperLinksMap } from "../../web-wrapper.constants";		// const (Map)
import { WebWrapperLinks } from "../../enums/web-wrapper-links";		// const (enum)
import { FontAwesomeIcons } from "../../enums/font-awesome-aliases";	// const (enum)

@Component({
  selector: 'web-wrapper-footer',
  templateUrl: './web-wrapper-footer.component.html',
  styleUrls: ['./web-wrapper-footer.component.scss']
})
export class WebWrapperFooterComponent implements OnInit {

  contextLinks:Array<FooterLink> = [];
  socialLinks:Array<FooterLink> = [];

  constructor() {
    this.contextLinks.push(new FooterLink("Terms of Use", WebWrapperLinksMap.get(WebWrapperLinks.TERMS_OF_USE)));
    this.contextLinks.push(new FooterLink("Company Store", WebWrapperLinksMap.get(WebWrapperLinks.COMPANY_STORE)));
    this.contextLinks.push(new FooterLink("Privacy Policy", WebWrapperLinksMap.get(WebWrapperLinks.PRIVACY_POLICY)));
    this.contextLinks.push(new FooterLink("Safe Harbor", WebWrapperLinksMap.get(WebWrapperLinks.SAFE_HARBOR)));
    this.contextLinks.push(new FooterLink("Register", WebWrapperLinksMap.get(WebWrapperLinks.REGISTER)));
    this.contextLinks.push(new FooterLink("Employee Login", WebWrapperLinksMap.get(WebWrapperLinks.EMPLOYEE_LOGIN)));

    this.socialLinks.push(new FooterLink("Facebook", WebWrapperLinksMap.get(WebWrapperLinks.SOCIAL_FACEBOOK), FontAwesomeIcons.FACEBOOK));
    this.socialLinks.push(new FooterLink("Twitter", WebWrapperLinksMap.get(WebWrapperLinks.SOCIAL_TWITTER), FontAwesomeIcons.TWITTER));
    this.socialLinks.push(new FooterLink("Linked In", WebWrapperLinksMap.get(WebWrapperLinks.SOCIAL_LINKED_IN), FontAwesomeIcons.LINKED_IN));
  }

  ngOnInit() {
  }

}
```

*Console output containing the error*
```
> web-wrapper@0.0.0 build-npm C:\src\git\web-wrapper
> ng-packagr -p ng-package.json

Building Angular library from ng-package.json

BUILD ERROR
ENOENT: no such file or directory, open 'C:\src\git\web-wrapper\.ng_build\ts\web-wrapper.js'
Error: ENOENT: no such file or directory, open 'C:\src\git\web-wrapper\.ng_build\ts\web-wrapper.js'

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! web-wrapper@0.0.0 build-npm: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the web-wrapper@0.0.0 build-npm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bohling.denver\AppData\Roaming\npm-cache\_logs\2017-08-10T22_20_09_083Z-debug.log

C:\src\git\web-wrapper>
```

The behavior is the same for the *WebWrapperHeaderComponent*, but due to it's length I've omitted it.

#### Version Information

```
ng-packagr: v1.0.0-pre.13
node: v7.2.1
@angular: v4.3.2
TypeScript: 2.4.2
```

Verbose log file:
[2017-08-10T22_20_09_083Z-debug.txt](https://github.com/dherges/ng-packagr/files/1216545/2017-08-10T22_20_09_083Z-debug.txt)

I'm not sure what could be causing the problem at this point, so any help is appreciated.

**Comment by dherges** [comment]
Actually, I do have the same issue at my workplace on a windows 7 machine when using VS Code.

At my private place on a Mac OS I didn't run into this a single time.

Is this Windows 7? [list of version numbers](https://www.gaijin.at/lstwinver.php)

```16 verbose Windows_NT 6.1.7601```

Do you use VS Code?

**Comment by denver-HJS** [comment]
@deebloo if that were the case, then wouldn't Webpack fail when performing the module loading?

@dherges that's a good call. I *am* on Windows 7: Version 6 (Build 7601: Service Pack 1)

I've tried running it from a bash terminal opened in Administrator mode, but the error still occurs. I'm running WebStorm from IntelliJ.

I'll keep tinkering and provide an update if I'm able to figure it out.

**Comment by dherges** [comment]
Hm. I always had VS Code in question for keeping some file reference open or resource busy. When I open/close some folders in the VS Code file tree, the error randomly comes and goes. Now that you have it with IntelliJ, too, looks more of a Windows thing.

If you find anything, that's cool! 😎  thoguh if it's not much we can do about it, then we can keep it documented here for others who come across it too!

**Comment by denver-HJS** [comment]
I've narrowed it down to the Angular CLI compiler. I turned on the debug logging and added some of my own, and you can see it was failing at the `ngc` step:

[2017-08-14-ng-packagr-debug.txt](https://github.com/dherges/ng-packagr/files/1223792/2017-08-14-ng-packagr-debug.txt)

It appears that the `@angular/tsc-wrapped` compiler doesn't support any files used outside of the Angular-CLI *app* directory

**ngc.ts**:
`import { main as tsc } from '@angular/tsc-wrapped';`

# 

The process was successful after changing lines in my **web-wrapper.constants.ts** file from:

`import { environment } from '../../environment';`
```
C:.
----app
--------classes
--------components
------------xpo-web-wrapper-footer
------------xpo-web-wrapper-header
--------enums
--------_web-wrapper-constants.ts_
----assets
----environments
--------_environment.ts_
```
to

`import { environment } from './environment-variables';`
```
C:.
----app
--------classes
--------components
------------xpo-web-wrapper-footer
------------xpo-web-wrapper-header
--------enums
--------_web-wrapper.constants.ts_
--------_environment-variables.ts_
----assets
----environments
```

While I'm relieved to have the packaging working (I love the idea of this project :+1: ), this makes me wonder how someone is supposed to incorporate environment specific values into their projects. Do you have any suggestions or thoughts?

**Comment by dherges** [comment]
Uh, glad you found out!

On the environment question: I would not try to include environment variables from the app in a library build. It's like the `enableProdMode()` call in Angular: the library is not built with either a `prod` or `debug` flag, but rather the application using it tells the library whether it is in prod (or not).

**Comment by denver-HJS** [comment]
Alright yeah that makes sense. Well I appreciate the feedback and this project in general. Thank you for the hard work! :clap: :smiley: 

Seeing as this has been sorted out, I'll go ahead and close this issue.
