### ISSUE TITLE
Path / reference problem with equal types

### ISSUE THREAD

**Issue by Jefiozie** [dherges/ng-packagr#1025]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description
When using two the same type(s) in different namespaces the resolving of the path is not correct.
To see te example I have made a repo so you can look at the code: [example repo](
https://github.com/Jefiozie/enum-problem)

The types are present in  [addAdministrationItemCommand.ts](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/model/addAdministrationItemCommand.ts#L21) and [changeAdministrationItemCommand.ts](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/model/changeAdministrationItemCommand.ts#L21)

The problem can bee seen [here](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/dist/model/changeAdministrationItemCommand.d.ts#L22)

#### How To Reproduce
1. Clone the repo
2. Run `npm run build`

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version

ng-packagr:            2.4.5
@angular/compiler:     5.2.11
@angular/compiler-cli: 5.2.11
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.9.2
```

**Comment by alan-agius4** [comment]
Hi, I have looked into this, and it seems that the bug is from TypeScript.

 I have cloned your repo created a `tsconfig.json`
```js
{
  "compilerOptions": {
    "baseUrl": "",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "out-tmp",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["dom", "es2015"]
  },
  "files": ["index.ts"]
}

```

and ran

```bash
node_modules/.bin/tsc
```

And it still produced the same result.

**Comment by Jefiozie** [comment]
Okay, thanks for the effort I will create a issue at typescript.
