### ISSUE TITLE
How to configure Hammerjs in ng-package.json?

### ISSUE THREAD

**Issue by sheikalthaf** [dherges/ng-packagr#1035]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

I want to use hammerjs in my [@ngu/carousel](https://github.com/sheikalthaf/ngu-carousel) library and i can able run the project locally. then i created the library project using angular 6. then i try to build the library it throwing the error as `Cannot find name 'Hammer'`.

Here is my `ng-package.json`

```javascript
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/carousel",
  "lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "@types/hammerjs": "Hammer",
      "@types/hammerjs/index": "Hammer",
      "hammerjs/hammer.js": "Hammer"
    }
  }
}
```

I don't have an idea what to write in `lib.external`

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.3
@angular/*: 6.0.5
typescript: 2.7.2
rxjs: 6.2.1
node: 8.10.0
yarn: 1.7.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
`externals` is no longer valid in `v3`.

That error should be solved by installing the types;
```cmd
npm install @types/hammerjs --save-dev
```

Can you confirm that the types is installed correctly?

**Comment by alan-agius4** [comment]
Can you share a small reproduction? Or also check what’s the value of types
in your tsconfigs

**Comment by alan-agius4** [comment]
Most likely you have an empty array, in that case you need to add hammerjs to it

**Comment by sheikalthaf** [comment]
@alan-agius4 Yes. Will you please help me how to include it?

**Comment by alan-agius4** [comment]
Replace that with ‘hammerjs’

 Check here:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by sheikalthaf** [comment]
@alan-agius4 Thanks for suggestion

Mentioning the hammerjs in projects lib `tsconfig.lib.json` file solves the issue

`"types": ["hammerjs"]`

This will help someone with this issue
