### ISSUE TITLE
[BUG] Setting "dest" in json doesn't change build location

### ISSUE THREAD

**Issue by zentoaku** [dherges/ng-packagr#1038]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

Setting "dest" in json doesn't change build location.
```{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "index.ts",
    "dest": "../../dist/test"
  }
}
```
or
```{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "index.ts",
    "dest": "./dist-test/"
  }
}
```
always creates ./dist folder in current package.

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._
1. set the ng-package.json like one of the above
2. run build

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_
Expected is to have the build result in different path set as "dest" param in ng-package.json

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 1.7.0
@angular/*: 4.4.7
typescript: 2.9.2
rxjs: 5.5.11
node: 8.11.3
npm: 5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JoostK** [comment]
Please move the `dest` property one level up:

```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "./dist-test/",
  "lib": {
    "entryFile": "index.ts"
  }
}
```

**Comment by alan-agius4** [comment]
Thanks @JoostK for answering this. Indeed `dest` should be outside of the `lib` property.

**Comment by zentoaku** [comment]
@JoostK @alan-agius4 thanks, it's working, I feel so dumb now :)
