### ISSUE TITLE
Import library in library - error TS2307: Cannot find module

### ISSUE THREAD

**Issue by dgroh** [dherges/ng-packagr#1058]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have two libraries generated with **Angular CLI**. I also use **Nrwl Nx**

1. `<@scope>/hello-world-a`
2. `<@scope>/hello-world-b`

When I import `hello-world-b` in `hello-world-a` and try to build, I get the following error:

> BUILD ERROR
libs/hello-world-a/src/lib/hello-world-a.module.ts(3,35): error TS2307: Cannot find module '@<@scope>/hello-world-b'.
libs\hello-world-a\src\lib\hello-world-a.module.ts(6,27): Error during template compile of 'HelloWorldAModule'
  Could not resolve @<@scope>/hello-world-b relative to D:/Projekte/Git/<@scope>-maps/libs/hello-world-a/src/lib/hello-world-a.module.ts..
libs\hello-world-a\src\lib\hello-world-a.module.ts(6,27): Error during template compile of 'HelloWorldAModule'
  Could not resolve @<@scope>/hello-world-b relative to D:/Projekte/Git/<@scope>-maps/libs/hello-world-a/src/lib/hello-world-a.module.ts..

#### How To Reproduce

1. `ng generate library hello-world-a`
2. `ng generate library hello-world-b`

in `hello-world-a.module.ts` import `HelloWorldBModule`

This should look like this:

```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HelloWorldBModule } from '@<scope>/hello-world-b';

@NgModule({
  imports: [CommonModule, HelloWorldBModule]
})
export class HelloWorldAModule {}
```

Then run:  `ng-packagr -p libs/hello-world-a/package.json`

#### Expected Behaviour

I expect to import one library in another library without error

#### Version Information

```
ng-packagr: 4.1.0
@angular/*: 6.1.0
typescript: 2.7.2
rxjs: 6..2.2.
node: 8.11.3
npm: 5.6.0
@nrwl/nx: 6.2.1
```

**Comment by alan-agius4** [comment]
Running `ng-packagr -p libs/hello-world-a/package.json` like that won't work as `ngc` won't be able to resolve`hello-world-b`. In order to do something like that. You need to use the `API` and provide a tsconfig with paths that are able to resolve `hello-world-b`

Something like 

```json
	"compilerOptions": {
		"declaration": true,
		"paths": {
			"@scope/*": [
				"packages/dist/*"
			]
		}

```

If you are using `Angular-CLI` however, you don't need to do anything, as when using the `ng generate library` all the paths are generated for you. However to build a library, you need to use `ng build <project name>`. More details here https://github.com/angular/angular-cli/wiki/stories-create-library

**Comment by dgroh** [comment]
Do you mean, if I use `Angular CLI` and `Nrwl` I don't need `ng-packagr` at all? How do I publish my libraries to **npm** ? Doing like you said, I would have to publish all my libraries instead of single ones. I thought that is the reason for this sample: `https://github.com/dherges/nx-packaged`

**Comment by alan-agius4** [comment]
You need ng-packagr, but as a dependencies. As Angular CLI have a wrapper
for it.

I think what you are describing is secondary entry points
https://github.com/dherges/ng-packagr/blob/master/docs/secondary-entrypoints.md

**Comment by dgroh** [comment]
Ok I see, the the problem was that `nrwl` was not generating the files for publishing the packages. I had to explicitly pass `--publishable` to `ng generate library` command to get `ng-package.json` and `package.json` generated and now I understand why `ng-packagr` command is not necessary. So closing the issue!
