### ISSUE TITLE
Package secondary entrypoints (e.g. "@my/lib/testing")

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#107]
#### Type of Issue

- [ ] Bug Report
- [x] Feature Request

#### Description

Angular Package Format "describes secondary entry points": https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

We should add a possibility to compile and package such secondary entry points.

#### How To Reproduce

n/a

#### Expected Behaviour

TBD

Usage w/ ng-packagr must be further specified!

End result should be, say our already existing lib is `@my/lib`:

```ts
import { TestingStuff } from '@my/lib/testing';
```

#### Version Information

```
ng-packagr: v1.0.0-pre.14
```

**Comment by deebloo** [comment]
Would this be limited to a single secondary entry? Would it be possible to provide an array of entries?

**Comment by dherges** [comment]
@deebloo Why not?!

First straight-forward idea would be a simple key-value object:

```json
{
  "lib": {
    "secondaryEntries": {
       "testing": "src/testing_api.ts",
       "foobar": "foobar.ts"
    }
  }
}
```

Don't know if this is too simple?!?

Or an array of secondaries??

```json
{
  "secondaries": [
     { "name": "testing", "entryFile": "src/testing_api.ts"" }
    /* .. */
   ]
}
```

**Comment by deebloo** [comment]
@dherges I would argue for the second option, the key names make it more explicit what you are doing and also makes it more flexible if new properties need to be added in the future

**Comment by dherges** [comment]
Needs to investigste further: secondaries produce a separate package.json

Technically its just another independent npm package which is (physically) embedded in the location of the main package

So - w/o changes to current version - it should be possible to write a second ng-package.json producing the output contained in the main ng-package's dist folder.

Cheers, David

**Comment by martinmcwhorter** [comment]
@dherges 

This sounds interesting.

So in essence it would be a "cascade" of something like this?

1.  Run ng-packagr -p ng-package.json that creates the package output in ./dist
2.  Run ng-packagr -p ng-package-testing.json that creates package output in ./dist/testing

Is this how it should be done?

**Comment by dherges** [comment]
Generated dist output:

![2017-09-27 12_54_39-package json u-client-framework visual studio code](https://user-images.githubusercontent.com/901354/30909932-2714283c-a383-11e7-9c2e-7267b121909c.png)

**Comment by dherges** [comment]
@martinmcwhorter you could try whether this works, but I haven't done sofar ...

**Comment by dherges** [comment]
Generated dist folder structure

![2017-09-27 12_57_10-package json u-client-framework visual studio code](https://user-images.githubusercontent.com/901354/30910001-6b1b9420-a383-11e7-9947-387c01cd86be.png)
