### ISSUE TITLE
How to configure "lib.externals" in ng-package.json ('BusyModule' is not exported)

### ISSUE THREAD

**Issue by Arikael** [dherges/ng-packagr#119]
## Type of Issue

- [ ] Bug Report
- [ ] Feature Request
- [x] Question, I guess

## Description

I'm trying to create a simple angular library in which I use angular2-busy as an npm package,
I import it normally and everything works when compiling my source with webpack or directly with tsc.

But I alway get the error when using ng-packagr
`'BusyModule' is not exported by ..\..\node_modules\angular2-busy\index.js`

the file looks like
```
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./build/index"));
//# sourceMappingURL=index.js.map
```

Since I'm fairly new to the JS-World, my question is:
Can I solve this on my side or is this something ng-packagr has to solve.
Or is this this something I have to bring to angular2-busy's authors attention?

#### How To Reproduce

include angular2-busy as dependency and import it somewhere.

#### Expected Behaviour

compile it

#### Version Information

```
ng-packagr: v1.0.1
node: v8.4.0
@angular: v4.3.6
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
Do you have externals set in `ng-package.json`?

```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts".
    "externals": {
      /* ... *(
    }
  }
}
```

See https://github.com/dherges/ng-packagr/issues/85#issuecomment-321256775 

We should have better documentation in ng-packagr for this.... Oo

**Comment by dherges** [comment]
Also #108

**Comment by Arikael** [comment]
I tried it with externals and without
But I actually dont have an idea what I should put in.
As far as I know this is from Rollup, right?
it's the first time I come in contact with Rollup
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "index.ts",
    "externals": {
      "anguldar2-busy/index.js": "angular2-busy"
    }
  }
}
```

**Comment by Arikael** [comment]
Just had a look at #85 and saw in the example ng-bootstrap that they define `libraryName` in their webpack.conf.js 
Couldn't find that in angular2-busy. Maybe it doesn't register itself properly in the global namespace?

**Comment by dherges** [comment]
Don't know tbh. Noticed that they ship individual compiled .js files in a `build` folder:

https://github.com/devyumao/angular2-busy/tree/master/build

So angular2-busy is not bundled to a FESM. My educated guess is that the `externals` should probably be configured similar to rxjs.

https://github.com/dherges/ng-packagr/blob/master/src/lib/conf/rollup.globals.ts#L18-L67

**Comment by Arikael** [comment]
thanks

whatever I input into `externals` the error message and the path in it remains the same.

Unfortunately I have not the slightest idea how I should configure my `externals` :(
What exactly do I have to put in (theoretically speaking)?

**Comment by dherges** [comment]
These are the `external` and `globals` properties passed thru to rollup.

Rollup says for external:

> - the name of an external dependency
> - a resolved ID (like an absolute path to a file)

Globals is essentially the same but being used for the UMD bundle:

> ...we want to tell Rollup that the jquery module ID equates to the global $ variable:

https://rollupjs.org/#big-list-of-options


I try to re-phrase how to set the `externals` of ng-packagr: `lib.externals` is key-value pair of external dependencies of an Angular library. The key should be the import path (as used in TypeScript `import {} from ""` statement. The value should be the module ID for the UMD bundle. In rxjs, this is `Rx.Classname` or the `Rx.Classname.prototype`. In `@angular` packages, this is the token that they have configured in their build chain.

**Comment by markDrigola** [comment]
"embedded": [] - use this.
