### ISSUE TITLE
Css imports

### ISSUE THREAD

**Issue by bokzor** [dherges/ng-packagr#122]
## Type of Issue

- [X] Bug Report
- [ ] Feature Request

## Description

I'm not sure why but all the css import are not correctly inlined.

Same for fonts.

Is it the normal behaviour ?

#### How To Reproduce

`@import "../assets/style.scss"; in app.component.scss
`
Same for fonts

`@font-face{font-family:'Glyphicons Halflings';src:url(./fonts/glyphicons-halflings-regular.eot);src:url(./fonts/glyphicons-halflings-regular.eot?#iefix) format("embedded-opentype"),url(./fonts/glyphicons-halflings-regular.woff2) format("woff2"),url(./fonts/glyphicons-halflings-regular.woff) format("woff"),`

#### Expected Behaviour

_please describe what behaviour or result you expected_

#### Version Information

```
ng-packagr: v1.x.y
node: v8.x.y
@angular: v4.x.y
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
Hi,

#### SCSS Import

```
@import "../assets/style.scss";
```

What exactly is not inlined?


#### CSS/Font Imports

`url()` and `@import` in css files

Yes, I think angular cli does it by [css-loader](https://github.com/webpack-contrib/css-loader#usage). The behaviour is not implemented in ng-packagr

We would need to mimick the behaviour or try to use the css-loader directly w/o webpack

**Comment by bokzor** [comment]
When I look into the generated sources, 
`@import "../assets/style.scss"; 
`
is not replaced by the content of the file nor the file is present into the build directory.

**Comment by dherges** [comment]
Do you have a repro so that I can look at the files? Maybe in a GitHub repository?

If not, is it possible to reproduce this in one the integration samples? Can you [add a repro in one of these packages](https://github.com/dherges/ng-packagr/tree/master/integration/samples)?

**Comment by bokzor** [comment]
I added a PR

**Comment by dherges** [comment]
As there is no more activity in the last few weeks, I'll close it for now.

Should there still be open issues, please feel free to commend and/or re-open!

**Comment by ralberts** [comment]
+1

**Comment by Mani2693** [comment]
Hi, 

Exactly same case for me , My css file includes 

src:  url('fonts/icon-amat-eng.eot?p3naiw');

which is not bundled by ng-packagr, Please help to provide fix 

Thanks, 
Mani

**Comment by qqnc** [comment]
I couldn't get my font files in css inlined. any ideas?  
for example: 
src: url('fonts/line-awesome.woff2?v=1.1') format('woff2')
