### ISSUE TITLE
Inclusion of assets, or hooks during build for inclusion

### ISSUE THREAD

**Issue by ronnyek** [dherges/ng-packagr#123]
## Type of Issue

- [ ] Bug Report
- [x ] Feature Request

## Description
I currently have a convoluted build process for one of my component libraries. I've been able to almost completely replace with ng-packagr, but I have places where I manually create some core assets like images for these components as well as some scss. 

I don't know if/how this fits into the ng-packagr story. I'd like the assets folder to be included in the build, but don't know if a current method exists for inclusion.

**Comment by dherges** [comment]
Hi,

What do you mean by "include during build"?

Should the assets be inlined as base64 encoded into the js bundle? Kind of image-in-js?

Should the assets be copied from the source folder to the dest folder? Are assets intended to be imported individually by consumers?

Are there transformations to the assets applied during build? E.g. scaling to different predefined resolutions for images? Combining SVG icons to a web font?



Cheers, David

**Comment by ronnyek** [comment]
no no, just mean I would like to get an assets folder in my library that contains a few of the icons I include with my library... and no I dont htink that should necessarily be modifications made to ng-packagr. Thats why I was hoping there was some way to add some steps between building and packaging, all though I suppose I could just copy them into the dist folder post package

**Comment by dherges** [comment]
I d just copy them post package to the dust folder then 

Cheers, David

**Comment by dherges** [comment]
#### Summary

How to copy static assets to the npm pacakge? The assets are not preprocessed in any way.

Recommended: let ng-packagr create the `dist` folder with the npm package for the Angular library. Then copy the assets to the `dist` folder (after the packaging, before publishing).

**Comment by yonigo** [comment]
Hey, How do I update the reference to the assets path in the main app? 
Even if I manually copy all assets to dist folder, I still get a 404 because the assets are not in the main assets folder.

Thanks, Yoni

**Comment by rousseaufiliong** [comment]
+1

**Comment by BenjaminDobler** [comment]
The way i do it right now when i use my lib in an angular cli project is to copy the assets to the dist folder in a separate step like described here. 
The in my angular cli project i have to set the path in the .angular-cli.json i have to set the path to the lib assets and map them to the assets folder like this:
{ "glob": "**/*", "input": "../node_modules/my-lib/assets", "output": "./assets/my-lib/" }

It does not seem ideal because you have to tell everyone who uses your lib how to do this but at least it works.

**Comment by alirezamirian** [comment]
@dherges, Though it's possible to copy static assets (e.g. scss mixin files) in a separate step after bundling, [as you said](https://github.com/dherges/ng-packagr/issues/123#issuecomment-330029214), it's really nice to have an option in ng-packagr to just take care of it. It could be a configuration entry like `assets: ['path1', 'path2']` under `ngPackage`.

**Comment by alirezamirian** [comment]
Now I'm thinking handling scss files is often more than just copy-pasting because they may import other stuff, and supporting something like [this suggestion](https://github.com/dherges/ng-packagr/issues/273#issuecomment-344988878) (by using [scss-bundle](https://github.com/SimplrJS/scss-bundle) out-of-the-box is a really useful feature.

**Comment by pasapsi** [comment]
Hello, Tell me please by steps how to do it that would work. Is there anywhere working example? I will be very grateful

**Comment by AnthonyNahas** [comment]
Im facing a similar problem with [ngx-auth-firebaseui](https://github.com/AnthonyNahas/ngx-auth-firebaseui)! My library have some assets and the developer should add theme manually to the `angular.json` file .... [e.g:](https://github.com/AnthonyNahas/ngx-auth-firebaseui/blob/master/demo/angular.json#L97-L103)

**Comment by pasapsi** [comment]
@AnthonyNahas, Thanks you. I have a lot of modules that I make up, is there a way of not manual adjustment, but what would it work out of the box? 

Since the coded module I post to npm, and connect through package.json.

**Comment by pasapsi** [comment]
ng-packagr can not connect local files in automatic mode?

**Comment by AnthonyNahas** [comment]
@pasapsi I don't think so! Maybe with angular schematics.... I am still searching of an appropriate solution for my 📦

**Comment by westwick** [comment]
I don't know if this will work for all cases but for me it was pretty simple to just update my build script definition in package.json:

`"build": "ng-packagr -p ng-package.json && cp -r ./src/assets ./dist/src/assets"`

**Comment by ptrzyna** [comment]
@westwick's suggestion works great!

**Comment by isanka88** [comment]
I also got same problem when I packaging using ngPackagr. So I wrote my own small node script to copy them to the dist folder manually.

> npm install wrench

create new js file in the root **assets-copy.js**





    var wrench = require("wrench"),
      util = require("util");

    var source = "./src/assets";
    var target = "./dist/src/assets";

    wrench.copyDirSyncRecursive(source, target, {
      forceDelete: true
    });

    console.log("Asset files successfully copied!");




add build script to **package.json** like below,I called it as **manual:assets-copy**





      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "packagr": "ng-packagr -p ng-package.json",
        "assets-copy": "node assets-copy.js"
      }




After you run
> npm run packagr

Also run our script
> npm run manual:assets-copy

It'll copy them to the dist folder manually.

**Comment by 378740021** [comment]
wrench.js is deprecated!  fs-extra solve my problem

`const fse = require("fs-extra");
const path = require("path");

async function copyAssets() {
  try {
    const sourceFile = path.join(__dirname, "../../lib/assets");
    const destPath = path.join(__dirname, "../../lib/dist/assets");
    await fse.copy(sourceFile, destPath);
    console.log("files in assets has been copy to dist");
  } catch (err) {
    console.error(err);
  }
}
copyAssets();`

**Comment by SaranSank** [comment]
> I don't know if this will work for all cases but for me it was pretty simple to just update my build script definition in package.json:
> 
> `"build": "ng-packagr -p ng-package.json && cp -r ./src/assets ./dist/src/assets"`

How to use it?

**Comment by imnickvaughn** [comment]
> > I don't know if this will work for all cases but for me it was pretty simple to just update my build script definition in package.json:
> > `"build": "ng-packagr -p ng-package.json && cp -r ./src/assets ./dist/src/assets"`
> 
> How to use it?

It looks like this is all for the old ng-packagr
