### ISSUE TITLE
Ng-packagr can't read property 'toString()' of undefined

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#126]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

ng-packagr experiences an exception in fs.js:12 -> resolve(buffer.toString()); can't read property 'toString()' of undefined.

My guess is that fs is failing, but resolve is still attempting to execute after reject in the [fs.ts](https://github.com/dherges/ng-packagr/blob/master/src/lib/util/fs.ts) file. This operates under the assumption that `buffer` is undefined when an error has occurred. If that assumption is not correct, then an additional check would need to be added to the follow fix:
```ts
if (err) {
    reject(err);
} else {
    resolve(buffer.toString());
}
```

#### How To Reproduce

Clone [my repo](https://github.com/DavidParks8/ng-library-template/tree/ng-packagr-bug), `npm install`, then `npm run build:lib`

#### Expected Behaviour

ng-packagr should either succeed or print a helpful error message.

#### Version Information

```
ng-packagr: v1.1.0
node: v8.5.0
@angular: v4.4.1
rxjs: v5.4.3
zone.js: v0.8.17
```

**Comment by dherges** [comment]
Yes, you found the right code place.

There's a bug when the files does not exist (maybe a mis-spelled path) and then it errors because `buffer` is `undefined`.
