### ISSUE TITLE
someModule is not exported by node_modules\someModule

### ISSUE THREAD

**Issue by tauinbox** [dherges/ng-packagr#127]
## Type of Issue

- [?] Bug Report
- [ ] Feature Request

## Description

I've just updated packagr to version 1.2.0 and getting this error:

Building Angular library from ng-package.json
'default' is not exported by 'node_modules\whatwg-fetch\fetch.js'
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification

BUILD ERROR
'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
Error: 'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
    at error (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:8390:3)
    at Module.trace (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:8487:10)
    at ModuleScope.findVariable (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:8093:22)
    at Node.bind (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:6996:31)
    at eachChild.child (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:5819:34)
    at keys.forEach.key (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:5847:5)
    at Array.forEach (native)
    at Node.eachChild (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:5840:13)
    at Node.bind (C:\Projects\assent-compliance\ng-survey-player\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:5819:8)

#### How To Reproduce

have pako in dependencies, I suppose

#### Expected Behaviour

successfully built Angular module

#### Version Information

```
ng-packagr: v1.2.0
node: v7.10.0
@angular: v4.4.3
rxjs: 5.4.3
zone.js: 0.8.17
```

```
"dependencies": {
    "@progress/kendo-angular-dateinputs": "^1.0.5",
    "@progress/kendo-angular-dropdowns": "^1.1.2",
    "@progress/kendo-angular-excel-export": "^1.0.3",
    "@progress/kendo-angular-grid": "^1.2.3",
    "@progress/kendo-angular-inputs": "^1.0.7",
    "@progress/kendo-angular-intl": "^1.2.2",
    "@progress/kendo-angular-l10n": "^1.0.2",
    "@progress/kendo-data-query": "^1.0.6",
    "@progress/kendo-drawing": "^1.1.2",
    "@progress/kendo-theme-default": "^2.39.0",
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14",
    "bootstrap-sass": "^3.3.7",
    "ng2-formio": "1.0.0-rc.34",
    "text-mask-all": "github:text-mask/text-mask",
    "dateformat": "^2.0.0",
    "pouchdb": "6.2.0"
  }
```

**Comment by JoaoPintoM** [comment]
More or less the same issue with ng2-charts

BUILD ERROR
'ChartsModule' is not exported by node_modules/ng2-charts/index.js
Error: 'ChartsModule' is not exported by node_modules/ng2-charts/index.js

**Comment by cnadeau** [comment]
I have a similar issue when I import a Typesript lib to output as CommonJS.

Here is a repo to reproduce the issue:

https://github.com/cnadeau/demo-bug-lib

```
BUILD ERROR
'<class>' is not exported by <path>
```

OR

```
BUILD ERROR
Cannot read property 'flags' of undefined
```

**Comment by dherges** [comment]
Hi,

can you please check #129 whether the question is answered this?

**Comment by cnadeau** [comment]
It really answers the question very clearly and obviously works 👍 

Thank you very much for this lib, explanation and keep up the good work!

Cheers! 🎉

**Comment by tauinbox** [comment]
I got the same error

BUILD ERROR
'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
Error: 'deflate' is not exported by node_modules\pako\dist\pako_deflate.js

**Comment by dherges** [comment]
I don't what the current status of the issue. As there is no more feedback and activity in the last few weeks, I close it for now.

If there are still open issues, please feel free to commend and/or re-open!

**Comment by cnadeau** [comment]
This is still a problem, but I don't have much time to help you at the moment.

1-  thing I'm sure: rollup-plugin-json should be added

The other problem seems to be related to the way the plain Typescript object are exported in the shared lib. I'll keep you posted when I get there

**Comment by dherges** [comment]
Ok, can you describe what the use case is? Re-exporting symbols from another library?

**Comment by dherges** [comment]
Then, is it the same use case that was reported by @tauinbox and @JoaoPintoM ?

**Comment by cnadeau** [comment]
ui lib including e.g.: a Pipe that converts a Typescript Model to a string

that model is defined in a Typescript models lib

**Comment by dherges** [comment]
Ok. Why you need to re-export the symbol? Is it sufficient to export "model" from the ts-lib and export the pipe from the ng lib?

**Comment by cnadeau** [comment]
This is the actual reason why we're getting this error: 
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

I've found an ugly workaround... 

```
export * from './MyClass';
```

leads to the error

BUT

```
import {MyClass} from './MyClass';
export {MyClass};
```

seems to go through

**Comment by skorunka** [comment]
@tauinbox HI, how did you fix that `paco` issue? I have the same problem. Thanks.

**Comment by tauinbox** [comment]
@skorunka hi! I haven't fixed it and later had faced another [issue](https://github.com/dherges/ng-packagr/issues/210), so I settled on [this one](https://github.com/dherges/ng-packagr/issues/210#issuecomment-342066674) (without ng-packagr).
