### ISSUE TITLE
Output verbosity settings

### ISSUE THREAD

**Issue by ronnyek** [dherges/ng-packagr#128]
## Type of Issue

- [ ] Bug Report
- [x] Feature Request

## Description

A way to increase verbosity of output errors

#### How To Reproduce

I'm currently converting a large library I've previously completely managed all the inlining/buildscripts/etc. I am running into a problem after applying ng-package.json and the necessary updates, an error (below) that is almost undoubtedly something I am doing wrong... but the error has not much to do with my code. Infact the error appears to point at gulp-inline-ng2-template, which I'm not sure if your library calls, or if its remnants of my old build process which shouldn't be consumed.

```
undefined:1
({styleUrls: string[]})
                    ^

SyntaxError: Unexpected token ]
    at replaceFrag (C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\gulp-inline-ng2-template\parser.js:188:32)
    at C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\async\dist\async.js:3853:24
    at replenish (C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\async\dist\async.js:946:17)
    at iterateeCallback (C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\async\dist\async.js:931:17)
    at C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\async\dist\async.js:906:16
    at C:\Users\wweems\Source\Repos\IQMS.FrontEnd\node_modules\async\dist\async.js:3858:13
```

#### Expected Behaviour

_please describe what behaviour or result you expected_

I suppose just being able to better see what the actual problems were
#### Version Information

```
ng-packagr: v1.2.0
@angular: v4.x.y
```

**Comment by ronnyek** [comment]
I have no idea if this is related or not, but seems like ng-packagr spits out information when doing a build:lib like in the example repo, from the parent testing apps package.config rather than the inner package.config in the my-lib folder.

**Comment by ronnyek** [comment]
for those of you curious
```
set DEBUG=* & npm start build:lib
```
did the trick for me

**Comment by dherges** [comment]
Yes, the environment variable sets the logging output to debug
