### ISSUE TITLE
A package.json and README.md per module

### ISSUE THREAD

**Issue by BioPhoton** [dherges/ng-packagr#131]
## Type of Issue
- [X] Feature Request

## Description
I need a way to configure a `package.json` and `README.md` on a module layer.

#### How To Reproduce
Currently the dist folder contains the `package.json` and `README.md` from the root directory.  I would need a way to provide these files per module.   
i.e.  `./src/app/my-lib/package.json` and `./src/app/my-lib/README.md`

We could have some options for this in the `ng-package.json` file.

best
Michael

**Comment by dherges** [comment]
Please check since the [samples](integration/samples/material) do that. A `package.json` and a `README.md` alongside each `ng-package.json`

**Comment by BioPhoton** [comment]
Here is the working link: [samples](https://github.com/dherges/ng-packagr/tree/master/integration/samples/material)
