### ISSUE TITLE
Handling Dependencies

### ISSUE THREAD

**Issue by f-aubert** [dherges/ng-packagr#135]
## Type of Issue

- [ ] Bug Report
- [x] Feature Request

## Description

Enjoying your promising Library Packager, would it be possible to better handle peer dependencies? I tried specifying them as dependencies or as peerDependencies + devDependencies, but the Translate Code is always bundled in my output javascript flattened file (es5, es2015).

#### How To Reproduce

Here my package.json,
dependencies: {
    "@ angular/animations": "^4.2.4",
    "@ angular/common": "^4.2.4",
    "@ angular/compiler": "^4.2.4",
    "@ angular/core": "^4.2.4",
    "@ angular/forms": "^4.2.4",
    "@ angular/http": "^4.2.4",
    "@ angular/platform-browser": "^4.2.4",
    "@ angular/platform-browser-dynamic": "^4.2.4",
    "@ angular/router": "^4.2.4",
    "@ ng-bootstrap/ng-bootstrap": "^1.0.0-beta",
    "@ ngx-translate/core": "^7.2.0",
    "@ ngx-translate/http-loader": "^2.0.0",
    "bootstrap": "next",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
}

Here is my first attempt using lib.externals, in ng-package.json
    "externals": {
      "@ ngx-translate/core": "ngx-translate-core"
    }

#### Expected Behaviour

None of my dependencies should in principle be part of the bundled library, as I don't want to inflate my library with unnecessarily code. These dependencies only make sense for the original Angular CLI Demo Project, so just to run the DEMO

I wasn't able to exclude for example @ ngx-translate using externals properties, and I think we shouldn't have to fight our way for each dependency looking for the exact entry to put in externals in order to have it ignored. Isn't the dependency list either in package.json or repeated in ng-package.json enough to filter out peer libraries? I'm not sure how @ angular is itself ignored, do you provide default externals somehow?

Would you think something is doable? Or will I have to leave with these hard to figure out exclude...

#### Version Information

ng-packagr: v1.2.0
@ angular: v4.4.3

Best regards

**Comment by dherges** [comment]
Hi @f-aubert,

while in theory it would be possible to "auto-magically" set up configuration from `peerDependencies` it isn't that easy in practice.

Would you try to set the `lib.externals` property in `ng-package.json`?

This property configures a set of "external" libraries, being used by rollup during the bundling step. External Libraries are not bundled into your library (thus, you should list them to be a `peerDependency` in the library's `package.json`).

The configuration in `lib.externals` is a key-value pair. They key is the TypeScript import path. The value is the the module ID for the UMD bundle.

Here is a screenshot how to find out the module ID for `@angular/animations`. This should be the same for most other packages. 

![2017-09-28 07_13_04-animations umd js visual studio code](https://user-images.githubusercontent.com/901354/30950391-dd38b6de-a41c-11e7-9231-c2718093ccf3.png)

Regarding specific to `@ngx-translate`: there are some issues caused for a variety for reasons. See the other GitHub issues. The configuration I use is:

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "externals": {
      "@ngx-translate/core": "ngx-translate-core",
      "@ngx-translate/core/index": "ngx-translate-core"
     }
  }
}

```

**Comment by f-aubert** [comment]
Thank you for your wonderful/quick feedback, as well as your work for the open source / ng community. I will try as soon as I'm back to my dev environment. 

Being new to the world of Angular Libraries, I have however a question following Nikolas LeBlanc's Tutorial. The (only) package.json I'm writing/editing is the one generated by angular-cli, which include pretty much all main dependencies as "dependencies" and not as "peerDependencies". It should be so in order for the demo app, which is a full standard angular-cli app making use of some modules of my new library, to work. But the package.json "generated"/copied in the library dist folder should be thinner, in theory. There I should only see a couple of peer dependencies. Is there a way to make this package.json thinner?  Where am I supposed to write "dependencies"/"peerDependencies"? The consumer of my lib would find it obviously clearer.

**Comment by dherges** [comment]
#### Question

How should external dependencies of a library be handled in `package.json`?


#### Answer

For distribution (e.g. publishing to npm registry), a `package.json` of the library is required and needed. ng-packagr generates parts of that `package.json` during the build. That `package.json` should be placed in the same location (and next to) `ng-package.json`, e.g.:

```
|- ng-package.json
|– package.json
|- public_api.ts
|- ...
```

In that package.json, (most of the time) external dependencies should be added to [`peerDependencies`]. The motivation for [peerDependencies is explained in this angular.io guide](https://angular.io/guide/npm-packages#why-peerdependencies).

For the development workflow of a library, adding only `peerDependencies` is not enough (as peerDeps are not insalled by npm/yarn). For the development workflow, external dependencies should be added to `devDependencies`.

It's possible to use two separate `package.json` files – e.g., one for ng-packagr in a sub-directory and one for dev in the root directory – but it's also possible to use one `package.json` file (in this case, the `ng-package.json` and `package.json` would both be placed in the root directory).

**Comment by dherges** [comment]
Hi @f-aubert , I hop this answers your question. I close this issue and add it to a list of questions. If there are still questions, feel free to re-open!

**Comment by loicsalou** [comment]
great explanation, I'm currently facing issues with my lib wrapping both primeng's DataTable and ngx-translate (for header translations) and I hope this article will help me

**Comment by kylecordes** [comment]
re: "but it's also possible to use one package.json file"

So far in my work I have found that if I use a single package.json file, the output package.json contains all of the extra cruft (for example, a list of scripts) which are at best, noise and at worst erroneous.  To get fully correct output, it seems I have to manually maintain a second file and strip out the excess bits, or is there something I missed that lets packagr strip down the package file in the output to omit scripts and other irrelevancies?

**Comment by dherges** [comment]
No. You could automatically by another prepublish script (or similar) strip these things. Or you have a second package.json for your lib and replace version numbers with those from your root package.json

Cheers, David

**Comment by kylecordes** [comment]
@dherges  I've actually done that shuffle in the past programmatically as you described.  It seems to me that would make packages produced via ng-packagr better - because many users won't go to the effort of a custom script or separate file.  That's why I was wondering if it was in the box. :-)

If I get a little farther along this path here, would you be interested in a PR that makes ng-packagr cleanup the generated package file in a few obvious ways?

**Comment by fetis** [comment]
@dherges Could you please provide some guidance for a library development setup from Angular 6 CLI? 

By default, it has main package.json in the root and separate ng-package.json & package.json per library. My question is what a correct way to sync up 3rd party dependencies between root package.json (they listed there as `dependencies`) and library package.json (they listed as `peerDependencies`.

Is it correct they I install all 3rd party dependencies in the root node_modules for development?
