### ISSUE TITLE
Lazy loading modules from component library

### ISSUE THREAD

**Issue by yonigo** [dherges/ng-packagr#136]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

Hey, I would like to lazy load a module from a component library but unable to do so.

In my-component-library I have a models/feature folder which contains:

**feature.module.ts:** 
`import { NgModule } from '@angular/core';`
`import { CommonModule } from '@angular/common';`
`import { FeatureRoutingModule } from './feature-routing.module';`
`import { featureComponent } from './feature.component';`

`@NgModule({
    declarations: [ featureComponent ],
    imports: [ CommonModule, FeatureRoutingModule ]
})`
`export class FeatureModule {}`

**feature-routing.module.ts:**
`import { NgModule } from '@angular/core';`
`import { Routes, RouterModule } from '@angular/router';`
`import { featureComponent } from './feature.component';`
`const routes: Routes = [`
`    {path: 'component', component: featureComponent}`
`];`
`@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})`
`export class FeatureRoutingModule {}`

**public_api.ts:** 
`export * from './src/app/modules/feature/feature.module'` 

In my main app I have the **app-routing.module.ts**:
`import { NgModule }              from '@angular/core';`
`import { Routes, RouterModule }  from '@angular/router';`
`export function getRoutes() {
  return [
    { path: 'feature', loadChildren: 'my-component-library#FeatureModule' }
  ];
}`
`export const routes: Routes = getRoutes();`
`@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})`
`export class AppRoutingModule {}`

running ng serve from the main app results in:

ERROR in ./node_modules/my-component-library/my-component-library.d.ts
Module build failed: Error: Debug Failure. False expression: Output generation failed
    at Object.assert (C:\Projects\ngTests\my-main-app\node_modules\typescript\lib\typescript.js:3329:23)
    at Object.transpileModule (C:\Projects\ngTests\my-main-app\node_modules\typescript\lib\typescript.js:80449:18)
    at TypeScriptFileRefactor.transpile (C:\Projects\ngTests\my-main-app\node_modules\@ngtools\webpack\src\refactor.js:166:27)
    at Promise.resolve.then.then.then.then (C:\Projects\ngTests\my-main-app\node_modules\@ngtools\webpack\src\loader.js:505:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/$$_gendir lazy
 @ ./node_modules/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

What am I wrong here?
Thanks, Yoni

**Comment by dfbaskin** [comment]
I created a project as an experiment around building libraries and doing lazy-loading using a (lerna) monorepo and the Angular CLI:
https://github.com/dfbaskin/lerna-angular-cli-monorepo

I initially tried building the libraries into a `dist` path within the package's local folder. Then I would reference the `dist` path using the standard NPM package references (using lerna's symlinks). The two issues that I ran into were:

1) When referencing a library, the compiler picks up the `node_modules` path from the library project rather than the local path, which causes build errors. I think there is some magic that can be applied to WebPack to make this work, but probably would require ejecting from the CLI scripts.

2) The router would not lazy-load a route from the package, using either a standard NPM reference or a direct reference to the `dist` path.

The work around was to build the libraries directly into the local path of the project that references them (the project above does that).

Unfortunately, this seems like it is just working around NPM package management just to make the Angular compiler happy.

**Comment by yonigo** [comment]
Thanks @dfbaskin  but this means both folders have to be published together, and I cannot separate development of different feature modules into different repositories.. All I want to do is to be able to develop feature modules separately from my main app, and then lazy-load then back in.

**Comment by dherges** [comment]
Does it work like this?

```ts
import { MyFeatureModule, FEATURE_ROUTES } from '@my/lib';

@NgModule({
  imports: [
    MyFeatureModule,
    RouterModule.forChild(FEATURE_ROUTES)
  ]
})
class LazyModule {}
```

btw: what exactly is the error? Is ng cli / webpack not generating the async context from `loadChildren` properly? I do not know if `loadChildren: 'package name pointing to node_modules/somewhere'` works at all ...

**Comment by dfbaskin** [comment]
@yonigo understand. It's a work-around but I'm not happy with it.  I'd much rather figure out how to make it work a better way. 🙂

**Comment by dfbaskin** [comment]
@dherges I didn't expect referencing a lazy-loaded module through an npm reference (i.e. `my-library\dist`) would work, but I thought that at least a direct reference (`../node_modules/my-library/dist` or `../my-library/src/module/my-module` might work).

If you go back to this commit:
https://github.com/dfbaskin/lerna-angular-cli-monorepo/tree/e14fb64e9a9e2679d5601035cfed3d7ab29b1de0

you can see the references I tried:

```
  // // None of these options work:
  // {
  //   path: "four",
  //   //loadChildren: "demo-app-example-four/dist#ExampleFourModule"
  //   //loadChildren: "../../node_modules/demo-app-example-four/dist#ExampleFourModule"
  //   //loadChildren: "../../../demo-app-example-four/src/app/modules/example-four/example-four.module#ExampleFourModule"
  // },
```

**Comment by dfbaskin** [comment]
I'm not exactly sure why building the library to the `src\app\libs` path allows the library to be lazy-loaded. I expect it has to do with module resolution within WebPack, but haven't really dug into it.

**Comment by yonigo** [comment]
[This ](https://github.com/angular/angular-cli/issues/6373#issuecomment-319116889)solution worked for me.

Wrapping the module from the package in an inner module, and referencing it as the lazy-module in the router.

**Comment by dherges** [comment]
I close this issue here as it's a `ng`CLI / webpack thing.

**Comment by Xelpha** [comment]
> I'm not exactly sure why building the library to the `src\app\libs` path allows the library to be lazy-loaded. I expect it has to do with module resolution within WebPack, but haven't really dug into it.

Did you put `src\app\libs` as a subdirectory in the dist folder?

**Comment by evigkein** [comment]
ERROR in ./src/app/app.routes.ts
Module not found: Error: Can't resolve './../../../../dist/@ims/auth/lib/auth.module.d.ngfactory' in '/Users/macbook/Documents/storm/Angular/ims/apps/ims/src/app'

Error only in lazy modules. Same issue.
