### ISSUE TITLE
Handle standalone .scss files

### ISSUE THREAD

**Issue by BioPhoton** [dherges/ng-packagr#140]
## Type of Issue

- [x] Feature Request

## Description
How to handle .scss files that are not part of a component? An example would be the styles.scss file in an angular-cli project

#### How To Reproduce
If you build a folder that includes a unimported .scss file it will not show up in the dist folder

#### Expected Behaviour
The .scss file, or a compiled version of it, should show up in the dist folder

**Comment by dherges** [comment]
Hi @BioPhoton,

you can copy those "static" assets to the `dist` folder in a separate build steps.

Currently, there are no plans to include hooks for such assets that are not referenced by/included in the Angular package. Such "out-of-band" data should be handled independently of ng-packagr. See also #123
