### ISSUE TITLE
How can I use external library like moment.js in my angular package?

### ISSUE THREAD

**Issue by jcimoch** [dherges/ng-packagr#163]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

Let's say I want to use momen.js library.  When I do
```js
import * as moment from 'moment';
```
ng-packgr will inline whole library to the bundle. How should I use it to act as peerDependecy so it would use packge installed in module where my library would be consumed? 

By the way, despite the moment.js is inlined it seems it is not working when library is consumed by the target application :(

I use same configuration as in https://github.com/dherges/ng-packaged

**Comment by dherges** [comment]
Hi @jcimoch,

please check #129.

If there is a concrete issue and something is not working, please give a precise description of what is not working.

**Comment by dherges** [comment]
moment.js registers on the global scope with `moment`, see [moment.js#L10](https://github.com/moment/moment/blob/develop/moment.js#L10).

Usage of moment.js in TypeScript is `import { ... } from 'moment';`

According to #135, `lib.externals` configuration should be:

```json
{
  "lib": {
     "externals": {
        "moment": "moment"
     }
   }
}
```

**Comment by JoostK** [comment]
If you want to use moment both with Rollup (bundling using ng-packagr) and Webpack (if you use the library's sources directly with Angualar CLI for example) you may find that the `import * as moment from 'moment'` import is not compatible with Angular CLI's stack. For a compatible syntax for both bundlers, use the following:

```ts
import * as momentNs from 'moment';

const moment = momentNs;
```

**Comment by kum-deepak** [comment]
Suggestion from @JoostK worked for me when I was trying to use `moment-timezone`. No other approaches listed in this page worked for me (there are no es6 version for `moment-timezone`):

```typescript
import * as momentNs from 'moment-timezone';

const moment = momentNs;
```

**Comment by JanneHarju** [comment]
This externals didn't do much for me but using moment-es6 does. https://github.com/ng-packagr/ng-packagr/issues/290#issuecomment-345107593

**Comment by watofundefined** [comment]
Adding ` "allowSyntheticDefaultImports": true` to tsconfig.json helped me with lodash.
Now imports like `import _ from "lodash"` are ok.

https://www.typescriptlang.org/docs/handbook/compiler-options.html
