### ISSUE TITLE
less parser chokes on empty input ("Cannot read property 'replace' of undefined")

### ISSUE THREAD

**Issue by riccardomariani** [dherges/ng-packagr#165]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

BUILD ERROR
Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.parse (.../odata-v4-ng/node_modules/less/lib/less/parser/parser.js:114:22)
    at Object.parse (.../odata-v4-ng/node_modules/less/lib/less/parse.js:61:18)
    at Object.render (.../odata-v4-ng/node_modules/less/lib/less/render.js:25:18)
    at .../odata-v4-ng/node_modules/ng-packagr/lib/steps/assets.js:98:14
    at .../odata-v4-ng/node_modules/ng-packagr/lib/steps/assets.js:97:44

#### How To Reproduce

ng-packagr version 1.2.0 works as expected. 
Starting from version 1.2.1 ng-packagr produces this error

#### Expected Behaviour

Compilation should work

#### Version Information

```
ng-packagr: v1.2.1 and 1.3.0
node: v6.11.4
@angular: v4.4.4
rxjs:5.4.3
zone.js:0.8.18
```

**Comment by dherges** [comment]
Hi @riccardomariani,

do you have a repro where I can take a look at it?

**Comment by riccardomariani** [comment]
Hi @dherges,
I'm developing a npm library called odata-v4-ng.
The current ng-packagr version used to pack the library is 1.2.0. 
If you try to use ng-packagr version 1.2.1 or 1.3.0 you will get the mentioned error.
Let me know if I can help in any other way. 
Thanks.

**Comment by dherges** [comment]
Can you try to reproduce the error? For example, fork the ng-packagr repo, then copy the issue-raising code to `integration/samples/*` and then send me an example of the code.

For example, try to add the issue in this sample: https://github.com/dherges/ng-packagr/blob/master/integration/samples/custom/src/baz/baz.component.less

**Comment by riccardomariani** [comment]
Hi @dherges,
I reproduced the error and it's caused by empty less files. I don't know if the problem also affects other style formats. Anyway you can reproduce the problem simply removing everything from  https://github.com/dherges/ng-packagr/blob/master/integration/samples/custom/src/baz/baz.component.less

**Comment by dherges** [comment]
@riccardomariani thanks for reporting. Fix will be in next release!
