### ISSUE TITLE
Requesting alternate ng-packagr configuration capabilities

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#167]
## Type of Issue

- [x] Feature Request

## Description

I would like to be able to configure ng-packagr without the need for an extra `ng-package.json` file. Specifically, I'd like to reuse an existing file such as `tsconfig.json` and/or `package.json`.  As more and more tooling packages get added, a repo becomes polluted with large amounts of config files that make it harder to onboard new developers. Ideally, I'd like new developers not have to know about tooling so they can focus on implementing new business logic.

**Comment by dherges** [comment]
Yes, why not have multiple configuration locations.

1. `ng-package.json`
2. `package.json` with `ngPackage: {}` section
3. `tsconfig.json` with `ngPackage: {}` section

**Comment by DavidParks8** [comment]
Implemented and merged.
