### ISSUE TITLE
Unused Dependencies in generated package.json

### ISSUE THREAD

**Issue by epaillous** [dherges/ng-packagr#170]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

I want to create a library containing several reusable components. My library uses ng-packagr as a dev dependency. It also uses Material as dependency, for demo purposes. But these dependencies are not needed in my finale package. The problem is that the package.json generated in the dist folder is exactly the same as the one in my library.

#### Expected Behaviour

I was thinking the dependencies in section 'dependencies' of generated package.json are only the one effectively use by elements present in public_api.ts

#### Version Information

```
ng-packagr: v1.3.0
node: v7.10.1
@angular: v4.1.3
rxjs: 5.4.2
zone.js: 0.8.14
```

**Comment by dherges** [comment]
Hi @epaillous,

unfortunately not.

Right now, ng-packagr copies the `package.json` file and [only adds the `es2015`, `module`, `main`, `typings` properties](https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-packagr.ts#L52) to it.

You can either try to remove the `devDependencies` and `dependencies` from the generated `package.json` in a separate step (after running ng-packagr) or you can use a separate `package.json` file for your library (e.g. as in the [ng-packaged my-lib](https://github.com/dherges/ng-packaged/tree/master/my-lib)].

**Comment by epaillous** [comment]
🎉  Thanks ! I will use a separate package.json.
