### ISSUE TITLE
Does not build with Material beta.12

### ISSUE THREAD

**Issue by nmrichards** [dherges/ng-packagr#172]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
This could be a material beta.12 issue but wanted to make sure I submitted it here just in case it's not. When I run ng-packagr using with material beta.12, I get a build error, ENOENT: no such file or directory, open `.../node_modules/@angular/packages/material/...`. I can't find where it's trying to grab this `@angular/packages` from. I'm only importing one module from the material library but if I use beta.11, I don't get the build error. So I'm almost certain it's a material issue. If it is, feel free to close this one. 

The material issue can be tracked here if anyone is interested. [#7681](https://github.com/angular/material2/issues/7681).

#### How To Reproduce

1.  Start a new project using cli. `ng new material-test`
2. Update dependencies to use `@angular/material 2.0.0-beta.12` and all peer dependencies. 
3. Add ng-packagr  to dev dependencies, all necessary files for ng-packagr (public_api & ng-package.json) and run `npm install`. 
4. Import any material module into main app module
5. run `ng-packagr -p ng-package.json`. 

OR

1. Checkout https://github.com/nmrichards/material-issue-project
2. run `npm install`
3. run `npm run packagr`

#### Expected Behaviour

It builds with no errors.

#### Version Information

```
ng-packagr: v1.3.0
node: v8.6.0
@angular: v4.4.4
material: 2.0.0-beta.12
```
<img width="2182" alt="screenshot 2017-10-10 07 48 10" src="https://user-images.githubusercontent.com/16486521/31386173-e2590f94-ad93-11e7-94e2-e32cd3008ed1.png">

**Comment by matt328** [comment]
I'm seeing the same thing, I suspect it is an issue with material beta.12 itself, probably an issue with an incorrect ```//# sourceMappingURL=...``` somewhere.

**Comment by wallace41290** [comment]
I am experiencing the same problems as @nmrichards and @matt328 . Looking forward to any insight to resolve this issue.

**Comment by matt328** [comment]
Is there any way to configure ng-packagr to avoid esm5 packaging as a temporary workaround?

**Comment by matt328** [comment]
It appears `@angular/material` needs to be added to 'externals' in rollup's config.  [This comment](https://github.com/angular/material2/issues/7681#issuecomment-335482131) shows a workaround for now.

**Comment by dherges** [comment]
Please check #129 for an explanation how to handle external dependencies. There are a few libraries supported by default. `@angular/material` is not on the list.
