### ISSUE TITLE
Angular package included multiples times

### ISSUE THREAD

**Issue by bokzor** [dherges/ng-packagr#175]
## Type of Issue
I'm not sure if I can qualified that as an issue but angular libs can be included severals times.

LibA dependencies : angular/http, angular/common
LibB dependencies : angular/http, angular/browser

The application using both of the libs will have twice the angular/http lib.

So the package size can quickly be a problem. 

Almost 7mo for my application :-/
```
[ x] Bug Report
[ ] Feature Request
```

**Comment by about-code** [comment]
The [rollup config used internally by ng-packagr](https://github.com/dherges/ng-packagr/blob/3f07ec15c3b4d63bc753bc94a87bd2eaef4ef5bf/src/lib/conf/rollup.globals.ts#L1) lists the angular packages in the `globals` section which [according to rollup-docs](https://rollupjs.org/#command-line-flags) means they should be treated like `externals` which in turn should make rollup not to include them at all in the final bundle.

So actually, none of the angular libs should be included in the result produced by *ng-packagr*. Libraries should add angular packages to their (peer-)dependencies instead. How exactly are you packaging LibA and LibB?

**Comment by about-code** [comment]
ng-packagr [lists the angular packages](https://github.com/dherges/ng-packagr/blob/3f07ec15c3b4d63bc753bc94a87bd2eaef4ef5bf/src/lib/conf/rollup.globals.ts#L1) and [adds them to the `externals` section](https://github.com/dherges/ng-packagr/blob/3f07ec15c3b4d63bc753bc94a87bd2eaef4ef5bf/src/lib/conf/rollup.globals.ts#L1) of its rollup config which [according to rollup-docs](https://rollupjs.org/#command-line-flags) means they should not be included by rollup in the final bundle.

So actually, none of the angular libs should be included in the result produced by *ng-packagr*. Libraries should add angular packages to their (peer-)dependencies instead. How exactly are you packaging LibA and LibB?

**Comment by bokzor** [comment]
Good to know. 
I'm using ng-packagr. I'm gonna to investigate this problem so...

**Comment by elliotleelewis** [comment]
Anyone get any further with this? I am trying not to bundle `ngx-bootstrap` as part of the compiled output and adding:

```
"externals": {
    "ngx-bootstrap": "ngx-bootstrap"
}
```

to the lib section of the `ng-package.json` file doesn't fix it...
