### ISSUE TITLE
Unable to compile due to unable to find node_modules folder

### ISSUE THREAD

**Issue by jonyeezs** [dherges/ng-packagr#177]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

I have a global variable that has its own typings found in `node_modules/@types/google.analytics`.

```
[debug] ngc C:\Dev\ng\gsf.google-analytics\.ng_build/ts/tsconfig.lib.json, { basePath: C:\Dev\ng\gsf.google-analytics\.ng_build/ts })

BUILD ERROR
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:22:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:32:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:33:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:34:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:45:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:60:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:65:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:75:9: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:88:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:95:5: Cannot find name 'ga'.
Error: Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:22:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:32:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:33:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:34:13: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:45:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:60:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:65:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:75:9: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:88:5: Cannot find name 'ga'.
Error at C:/Dev/ng/gsf.google-analytics/.ng_build/ts/src/app/services/google-analytics.service.ts:95:5: Cannot find name 'ga'.
    at new UserError (C:\Dev\ng\gsf.google-analytics\node_modules\@angular\tsc-wrapped\src\tsc.js:27:28)
    at check (C:\Dev\ng\gsf.google-analytics\node_modules\@angular\tsc-wrapped\src\tsc.js:93:15)
    at Tsc.typeCheck (C:\Dev\ng\gsf.google-analytics\node_modules\@angular\tsc-wrapped\src\tsc.js:173:9)
    at C:\Dev\ng\gsf.google-analytics\node_modules\@angular\tsc-wrapped\src\main.js:122:23
```

FYI: it works with command `ng build`. The app that uses ng builds imports the module directly.

#### How To Reproduce

This is my folder structure
```
\ node_modules
|
\ src
|    |
|    \ app
|        | 
|        \ services
|             |
|             \ module.ts
|
\ ng-package.json
\ public_api.ts
\ package.json
```

public_api.ts
```
export * from './src/app/services/google-analytics.module';
```

ng-package.json
```
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "public_api.ts"
    }
  }
```

#### Expected Behaviour

Expect it to find the `ga` declarations and tsc should build it successfully.

#### Version Information

```
ng-packagr: v1.4.0
node: v7.10.0
@angular: v4.4.4
rxjs: v5.4.3
zone.js: v0.8.18
@angular/cli: v1.4.5
typescript: v2.3.3
```

_please include any version information that might be relevant, e.g. other third-party libraries_

#### Additional Information

included only the relevant parts

package.json 
```json
"devDependencies": {
 "@types/google.analytics": "0.0.35",
}
```

tsconfig.json
```json
"compilerOptions": {
  "typeRoots": [
      "node_modules/@types"
    ],
}
```
Used in a service
```javascript
// not needed for explicit import of ga as typeRoot contains declaration
ga('send', 'pageview', this.location.path(true));
```

**Comment by jonyeezs** [comment]
i believe the problem is in `.ng_build/ts/tsconfig.lib.json`

when i removed the typeRoots because of

>By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

it compiled correctly for me and now i have my files in the dist folder.

I'm wondering why this isn't an issue for everyone else?

What is wrong with my setup?

**Comment by BenjaminDobler** [comment]
I have exactly the same issue. I use @types/node cause i use fs and process in my lib code.
It fails when running normally but when i remove typeRoots from the tsconfig.ngc.json file it works.

**Comment by DavidParks8** [comment]
@jonyeezs, can you show the exact change you made and in which file when you said "removed the typeRoots"?

**Comment by BenjaminDobler** [comment]
@DavidParks8 Not sure where he did it but i removed them in node_modules/ng-packagr/lib/conf/tsconfig.ngc.json and then it started working.

**Comment by jonyeezs** [comment]
>can you show the exact change you made and in which file 

@DavidParks8 sorry left out that info. And the file i changed is the one mentioned by @BenjaminDobler `node_modules/ng-packagr/lib/conf/tsconfig.ngc.json`.

I assumed that was the file copied for the generated `tsconfig.lib.json`. And sure enough it reflected that.

**Comment by jonyeezs** [comment]
>can you show the exact change you made and in which file 

@DavidParks8 sorry left out that info. And the file i changed is the one mentioned by @BenjaminDobler `node_modules/ng-packagr/lib/conf/tsconfig.ngc.json`.

I assumed that was the file copied for the generated `tsconfig.lib.json`. And sure enough it reflected that.

**Comment by dherges** [comment]
Can you check and give feedback whether the issue still persists with 1.5.0-rc.0?

**Comment by jonyeezs** [comment]
still the same issue.

What changes should have fixed this?

**Comment by jonyeezs** [comment]
@BenjaminDobler is it working for you now?

**Comment by dherges** [comment]
@jonyeezs @BenjaminDobler Ah, now I understand. Can you point to t a documentation where it says what `@types` packages are visible by defualt? You quoted something in the above comments... where can I find that? Is the `typeRoots` really superfluous?

**Comment by BenjaminDobler** [comment]
The strange thing is that it`s working for me now with or without the typeRoots. Not sure what else i changed.
For the visibility it says in the tsconfig doc:

> @types, typeRoots and types
> 
> By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.
> 
> If typeRoots is specified, only packages under typeRoots will be  included

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by dherges** [comment]
Ok. I can think of cases (monorepos, yarn workspaces, lerna) where this could be an issue, say:

```json
|- node_modules/@types
|- subfolder
   |- node_modules/@types
   |- angular-lib-source
      |- node_modules/@types
```

It could happen here that duplicate typings are found on the path. By setting `typeRoots` this is prevennted because only the specified `@types` folders is considered.

**Comment by DavidParks8** [comment]
https://github.com/palantir/blueprint is an example of a lerna mono repo that does not set type-roots, but works properly. I don't think it will be an issue.

**Comment by aitboudad** [comment]
I have got the same issue, and it's work if I changetypeRoots in [tsconfig.ngc.json#L23-L25](https://github.com/dherges/ng-packagr/blob/master/src/lib/conf/tsconfig.ngc.json#L23-L25) into
```ts
    "typeRoots": [
      "../../node_modules/@types"
    ],
```
