### ISSUE TITLE
Packaging error after adding dependencies for Angular Material

### ISSUE THREAD

**Issue by cathy02** [dherges/ng-packagr#181]
## Type of Issue
Packaging error
```
[ x] Bug Report
[ ] Feature Request
```

## Description
1. Using Angular CLI to create a new project.
2. Add a new module/component (e.g. navbar).
3. "ng-packagr -p ng-package.json" works fine.
4. Add Angular Material packages: 
                 `npm install --save @angular/material @angular/cdk
`
5. Import a material module (e.g. MatToolbarModule) to the new module (navbar).
6. "ng-packagr -p ng-package.json" gives the following error

> nav-component@0.0.0 packagr C:\work\GitRepos\nav-component
> ng-packagr -p ng-package.json

Building Angular library

BUILD ERROR
ENOENT: no such file or directory, open 'C:\work\GitRepos\nav-component\node_modules\@angular\packages\material\esm5\form-field\error.js.map'
Error: ENOENT: no such file or directory, open 'C:\work\GitRepos\nav-component\node_modules\@angular\packages\material\esm5\form-field\error.js.map'

#### How To Reproduce

See the Description

#### Expected Behaviour

Packaging successfully

#### Version Information

```
ng-packagr: v1.4.1
node: v8.5.0
@angular: v4.2.4
rxjs: 5.4.2
zone.js: 0.8.14
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by bjornalm** [comment]
I get the same error, only it is complaining about not finding a different file in my case: node_modules/@angular/packages/material/esm5/autocomplete/autocomplete.js.map

**Comment by cathy02** [comment]
bjornalm,

Yes, the suggestion from @matt328 worked for me as well. Thanks very much.

**Comment by matheuscaldasrj** [comment]
Thanks a lot @bjornalm , I was looking for a solution for a long time ;)

**Comment by nchetbani** [comment]
@cathy02 @matt328´s suggestion don’t work for me
Can you please give me more details about how you are implemented thé suggestion ?
Thank you in advance
