### ISSUE TITLE
Issue with nested modules

### ISSUE THREAD

**Issue by thinhnguyenhm** [dherges/ng-packagr#186]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I follow the tutorial (https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d) to implement on my project, and I used 'ng-packagr' to build some modules for re-used. But I get error logs here:

D:\Repositories\project\angular-demo>npm run servering

> angular-demo-app@0.0.1 preservering D:\Repositories\project\angular-demo
> ng build --dev --aot=false && ngc && cpy node_modules/@angular/service-worker/bundles/worker-basic.min.js dist/

Date: 2017-10-16T09:16:54.869Z
Hash: 8b11d712e5f7f93b941d
Time: 15934ms
chunk {about.module} about.module.chunk.js, about.module.chunk.js.map () 7.04 kB {main}  [rendered]
chunk {contact.us.module} contact.us.module.chunk.js, contact.us.module.chunk.js.map () 6.64 kB {main}  [rendered]
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 77.5 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 185 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 977 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.13 MB [initial] [rendered]

> angular-demo-app@0.0.1 servering D:\Repositories\project\angular-demo
> ts-node src/server.ts

D:\Repositories\project\angular-demo\dist\ngfactory\node_modules\angular-demo-home\angular-demo-home.ngfactory.ts:9
import * as i0 from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Repositories\project\angular-demo\node_modules\ts-node\src\index.ts:400:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Repositories\project\angular-demo\dist\ngfactory\src\app\app.server.module.ngfactory.ts:12:1)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "servering"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-demo-app@0.0.1 servering: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-demo-app@0.0.1 servering script 'ts-node src/server.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-demo-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node src/server.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-demo-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-demo-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Repositories\project\angular-demo\npm-debug.log

D:\Repositories\project\angular-demo>

# With the same source and config, I build for not support server side render ('ng serve') and it work well
#### How To Reproduce

- I have angular-core repository, I use ng-package to build to angular-core module( use for common module, and re-used able)
- I have angular-demo-home repository and in package.json I pull angular-core module to re-used some component,  I use ng-package to build to angular-demo-home module

So I have 2 libs module: angular-core and angular-demo-home

The last action:
I setup project angular-demo to used angular-core and angular-demo-home, with router /home in angular-demo I open HomeComponent of angular-demo-home so I get the error above
#### Expected Behaviour

Please help me to resolve it 

#### Version Information

```
ng-packagr: v1.3.0
node: v6.10.0
@angular: v4.4.4
rxjs: 5.4.2
zone.js: 0.8.12
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by DavidParks8** [comment]
Can you please provide a repo to help us troubleshoot?
