### ISSUE TITLE
Unable to link an external library

### ISSUE THREAD

**Issue by epaillous** [dherges/ng-packagr#187]
## Type of Issue

- [x] Bug Report
- [ ] Feature Request

## Description

I would like to add 'ng-inline-svg' as dependency of my package. Here is my configuration : 

```
\ node_modules
|
\ lib
|    |
|    \ package.json
|    \ public_api.ts
|    \ src
|        | 
|        \ modules
\ src
|    |
|    \ app
|
\ ng-package.json
\ package.json
```

Here is my ng-package.json :  
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "lib",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "ng-inline-svg": "ng-inline-svg",
      "ng-inline-svg/index": "ng-inline-svg"
    }
  }
}
```

Here is my lib/package.json (the main package.json is the one for my demo app of my package)

```
{
  "name": "my-design",
  "version": "0.0.0",
  "license": "MIT",
  "private": false,
  "peerDependencies": {
    "@angular/core": "^4.1.3",
    "@angular/common": "^4.1.3",
    "ng-inline-svg": "^3.2.1"
  }
}
```

I can export correctly my package (npm run packagr works, and also npm pack), but if I try to use this package (my-design) in another app (Main_Project), I get this error :  

```
ERROR in ./node_modules/my-design/my-design/my-design.es5.js
Module not found: Error: Can't resolve 'ng-inline-svg/index' in '/Users/pailloue/Sources/Main_Project/node_modules/my-design/my-design'
```

I tried to put the ng-package.json inside my lib directory, but I have the same result.

#### Version Information

```
ng-packagr: v1.3.0
node: v7.10.1
@angular: v4.1.3
rxjs: 5.4.2
zone.js: 0.8.14
```

**Comment by DavidParks8** [comment]
Please update to angular 4.4.5 and see if the issue still exists. It might be related to [this](https://github.com/angular/angular/pull/19579).

**Comment by dherges** [comment]
Should the error persist, see #101 - it seems like the same root cause where an `/index` is appended to the import paths during compilation with `ngc`.

**Comment by dherges** [comment]
Hi @epaillous,

I see you have added the second externals entry for the `/index`. I would need a repro (maybe a GitHub project) to look at it.

Can you check and tell whether upgrading to angular 4.4.5 solves the issue for you?
