### ISSUE TITLE
Secondary entrypoints: package.json contains backslash on windows

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#191]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Building a secondary entrypoint on a windows machine. Creates `package.json` for secondary:

```json
{
  "main": "..\\../bundles/components-lib\\alert.umd.js",
  "module": "..\\../@orbis-u/components/lib\\alert.es5.js",
  "es2015": "..\\../@orbis-u/components/lib\\alert.js",
  "typings": "alert.d.ts",
  "metadata": "alert.metadata.json",
  "name": "@orbis-u/components/lib\\alert"
}
```

#### How To Reproduce

Build on windows machine.

#### Expected Behaviour

Should contain forward slashes only (both for pathes and package name)

#### Version Information

```
ng-packagr: v1.5.0-rc.0
node: v8.4.0
```

**Comment by dherges** [comment]
@DavidParks8  FYI

**Comment by DavidParks8** [comment]
This should be fixable by using path.posix everywhere. I’ll fix it after work and make a PR today.

**Comment by dherges** [comment]
No worry! Take your time!
