### ISSUE TITLE
Externals

### ISSUE THREAD

**Issue by KoLogicDev** [dherges/ng-packagr#192]
## Type of Issue

```
[x] Bug Report
[] Feature Request
```

## Description

Hi guys, thanks for awesome tool! I'm trying to build my own library on top of [devextreme-angular](https://github.com/DevExpress/devextreme-angular). In its turn it depends on  [devextreme](https://github.com/DevExpress/devextreme), jQuery and JSzip. After simply addition these packages to peerDependencies  I've got huge module with all 3 packages inlined. I've read a few issues that seemed similar and add following records to the externals section:

        "jquery": "jQuery", 
        "jszip": "JSZip",
        "devextreme": "DevExtreme"

 After that jQuery and JSzip have disappeared but DevExtreme is still there (and I don't understand why) and devextreme-angular of course too (this is second part of my question: I can't find its module name). 
It'll be great if you will make it clear, I really appreciate any help you can provide 

P.S. DevExtreme team have [some docs](https://github.com/DevExpress/devextreme-angular/blob/master/docs/using-rollup.md) about Rollup usage which I already follow (I use long paths in my imports) and it doesn't seem have any affect.

#### How To Reproduce

Just add jQuery, JSzip, DevExtreme and devextreme-angular to your lib as peerDependencies.

#### Expected Behaviour

Flat modules with only my code.

#### Version Information

```
ng-packagr: v1.4.1
node: v8.4.0
@angular: v4.4.5
rxjs: "5.4.3"
zone.js: "0.8.14"
devextreme-angular: "17.1.7",
devextreme: "17.1.17",
jquery: "3.2.1",
jszip: "3.1.4"
```

**Comment by dherges** [comment]
It's the symbol on the global scope. You can find it by looking into the dist javascript files of a lirary, e.g.:

https://github.com/dherges/ng-packagr/issues/135#issuecomment-332730342

Also...
- https://github.com/dherges/ng-packagr/issues/85#issuecomment-321256775
- https://github.com/dherges/ng-packagr/issues/163#issuecomment-335567457
-
