### ISSUE TITLE
ng-packagr -p not picking my custom typings

### ISSUE THREAD

**Issue by x1c0** [dherges/ng-packagr#193]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm working on a project where unfortunately there are some events polluting the window object.. nobody is proud of that here but that's what we got 🙈 

When running angular-cli -> ng build, the angular-cli is able to compile a specific ts file that contains a call to window.specialEvent but when running ng-packagr -p we get:
Property 'specialEvent' does not exist on type 'Window'.
I have a local file window.d.ts that contains:
```
declare global {
  export interface Window {
    specialEvent(eventName: string, data: any): boolean;
  }
}

```
this is our tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

#### Expected Behaviour

Angular library is build with success 😎 

#### Version Information

```
ng-packagr: ^1.3.0
node: v6.9.1
@angular/cli: 1.4.5,
@angular: ^4.2.4
rxjs: ^5.4.2,
zone.js: ^0.8.14
```
ps. thanks in advance for your support and thanks for this great project!

**Comment by dherges** [comment]
Hi @x1c0,

thanks for reporting.

My recommendation is to either use typings from `node_modules/@types/<*>` or reference a custom `*.d.ts` file by a [triple slash refertence](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html). The latter is a proven solution for working with custom (proprietary / legacy) libs - maybe, you even need the `d.ts` file by hand - at least it works well with at least one proprietary lib that I use.

**Comment by dherges** [comment]
Labelled as "documentation" so that others can find it more easier for help.

If you have another suggestion / idea how custom typings should handled, let me know!

**Comment by x1c0** [comment]
Hi @dherges,

Thank you for your reply! 

I just added now `/// <reference path="../../typings/window.d.ts" />` to one of the files that uses the window object and it works like a charm 😄 Thank you!

I'm not sure how this could be "better" handled.. I also tried to add to `tsconfig.json` on the `typeRoots` property array the path to my custom typing but it didn't work. Are you considering this file when you are compiling? maybe there is a way to pick the custom types from there? 

ps. please feel free to close this issue if you feel like 🤓

**Comment by dherges** [comment]
No, the `tsconfig.json` for `ngc` is auto-generated as Angular Package Format requires some special values in that config file to work properly. 

There have been questions on configuration in the past, but it's been a deliberate choice to hide some / the most of the internal tools configuration. From the very start of the project, this was [one of the primary goals and design choices](https://github.com/dherges/ng-packagr/blob/master/DESIGN.md#configuration-and-customization): take away the burden to configure everything.

**Comment by dherges** [comment]
Ah, the design doc probably needs some updates / re-phrasing in the mean time!

**Comment by dherges** [comment]
Also changed the title so that *fingers crossed* it's easier to find.

**Comment by dlcooper** [comment]
I know this issue is closed but I hope someone sees this:

My library defines some.service.ts which has a reference:

	/// <reference path="../typings/jquery/cometd.d.ts" />
	
when compiled, the reference becomes: 

	/// <reference path="../../../../src/typings/jquery/cometd.d.ts" />

When I import and use that service in an app project and run it --aot I get the following error:

	ERROR in node_modules/mu-library/services/some.service.d.ts(1,22): error TS6053: File 'C:/workspace/src/someTypeDef.d.ts' not found.

Can anyone help me get this to work?

`
@angular: 5.2.0
@angular/cli: 1.5.4
ng-packagr@2.0.0-rc.11
`

thx

**Comment by mark-at-tusksoft** [comment]
Stumbled across this from a google search.
Just to clarify, once you have created the typings file (i.e. `projects/lib-project/src/typings.d.ts`)
Be sure to add it to the types array in `projects/lib-project/tsconfig.lib.ts`
```{
  "compilerOptions": {
    "types": [
      "./src/typings"
    ],
  }
}```

This worked for me; now VSCode recognizes the namespaces referenced in typings.d.ts and the tsconfig.lib "types" addition helps ng-packagr find the custom typings file.

**Comment by Qarun-Qadir-Bissoondial** [comment]
@mark-at-tusksoft It seems that doesn't work for me, but I'm not sure if it's because I'm using secondary entry points
