### ISSUE TITLE
TypeScript definition of service missing

### ISSUE THREAD

**Issue by bjornalm** [dherges/ng-packagr#194]
## Type of Issue
```
[x ] Bug Report
[ ] Feature Request
```

## Description
I'd like my library to export a service, but the service doesn't seem get a TypeScript definition when my library is packaged with ng-packagr so the TypeScript checker is complaining in the IDE.

#### How To Reproduce

1. Create a library (myLib) that has a module (MyMod) that provides a service (MyService)
2. Export MyService explicitly by putting it in public.api.ts. 
3. Then have a consuming application import MyMod from myLib. 
4. Now try to import MyService to a component using:
import { MyService } from 'myLib';

This actually works since it has been exported, but TypeScript complains (in the IDE) that the module has no exported member with that name.

#### Expected Behaviour

I would expect that MyService is added to myLib.d.ts, rstor-ui-library.metadata.json or wherever ot is needed just like regular components are.

#### Version Information

```
ng-packagr: v1.4.1
node: v8.6.0
@angular: v4.4.5
rxjs:
zone.js:
```

**Comment by dherges** [comment]
Hi @bjornalm,

thanks for reporting. Is the service exported by the entry file of the library? It can also be exported transitively, but it needs to be on the "public surface".

If yes, can you provide a repro, e.g. a GitHub repo?

**Comment by MGD4375** [comment]
Hi @dherges ,

I'm experiencing the same issue. I'm experimenting with ng-packagr for the first time so apologies if there's some documentation I'm missing. 

I can send you a bitbucket repo you like, and some of the key files are below. It appears that the Angular import is working fine, but the typescript import of the ToastService is failing.

Thanks for your time.

Library:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DropDownComponent } from './drop-down/drop-down.component';
import { DropDownOptionComponent } from './drop-down-option/drop-down-option.component';
import { FormsModule } from '@angular/forms';
import { ToastNotificationsComponent } from './toast-notifications/toast-notifications.component';
import { ToastService } from './toast-notifications/toast.service';

@NgModule({
  imports: [
    CommonModule,
    FormsModule
  ],
  declarations: [
    DropDownComponent,
    DropDownOptionComponent,
    ToastNotificationsComponent
  ],
  exports: [
    DropDownComponent,
    DropDownOptionComponent,
    ToastNotificationsComponent
  ],
  providers: []
})
export class MuiCoreModule {
  public static forRoot() {
    return {
      ngModule: MuiCoreModule,
      providers: [ToastService]
    };
  }
}
```

Consumption:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';

import { AppComponent } from './app.component';
import { FormsModule } from '@angular/forms';
import { MuiCoreModule } from 'mui-core';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    MuiCoreModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Component in the consuming project:
```
import { Component } from '@angular/core';
import { ToastService } from 'mui-core/src/mui-core/toast-notifications/toast.service';
@Component({
  selector: 'mp-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'mp';

  constructor(private toasts: ToastService) { }

  selectedOption: any;
  options = [
    { name: 'Option 1', value: 1 },
    { name: 'Option 2', value: 2 },
    { name: 'Option 3', value: 3 }
  ];

}

```

**Comment by deanpeterson** [comment]
@dherges, I am having the same issue as @MGD4375. Is there something wrong with his implementation, because when I try to import a service into a component that uses my ng-packaged service, I still get "has no exported member" error at run time.

**Comment by deanpeterson** [comment]
Nevermind. I found the solution here: https://codewithstyle.info/creating-angular-npm-packages-with-ng-packagr/

Once I added an index.ts file the service could be imported just like a module from the package.

**Comment by shaungrady** [comment]
@deanpeterson I'm facing this same issue. Where did you add an index.ts? Can you be a little more specific about your solution? Thanks!

**Comment by danielmhair** [comment]
I'm having the same issue. @deanpeterson I assume you mean that instead of exporting a folder like this:
```
import * from './src/module1';
import * from './src/module2';
```
You changed it to this?
```
import * from './src/module1/index';
import * from './src/module2/index';
```

If so, I'm still facing this issue when I added the index.ts file to the exports.
