### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by lexzhukov** [dherges/ng-packagr#2]
Hi, David

I have some questions for you:
- How can I extend the rollup globals for 3rd-parties libraries?
- How can I setup ng-packagr for several libraries in one solution?

Thanks, 
Alex

**Comment by dherges** [comment]
Hi @lexzhukov,

> How can I extend the rollup globals for 3rd-parties libraries?

It's not yet implemented, to me, it should be possible to [pass a custom `rollup-config.js`](https://github.com/dherges/ng-packagr/blob/master/DESIGN.md#rollup-config) in the JSON config. If you like, just open a PR for that! Or add more rollup globals to completely support RxJS by default.

> How can I setup ng-packagr for several libraries in one solution?

You can pass as a CLI argument `ng-packagr -p .ng-packagr.json` (very much like `tsc -p tsconfig.json`) so you can create multiple JSON configs and run it for each of your config files.

Does that help you?

Cheers!
David

**Comment by lexzhukov** [comment]
@dherges yes, it helped me. Thanks!
