### ISSUE TITLE
service ot found

### ISSUE THREAD

**Issue by ovione** [dherges/ng-packagr#203]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

Web pack can not compile

#### How To Reproduce

I have a module with a component and a service provided.
When I do a npm start is works fine but when
I install it in another project it says 
'Web pack can not compile'.

This is the configuration of my project:
           header.module
                       header.component
                       my-service.service

header.component uses my-service.service
#### Expected Behaviour

It works with only the component in the module but when I add the service as provided inside the module it seems that it can not find that service when I install it in another project.
I tried puting in public_api.ts
    export * from './src/app/modules/header/header.module';
    export * from './src/app/services/my-service.service';

This works and I can access the header.component and my-service.service independently but 
from the moment the header.component uses the my-service.service it doesn't work anymore.

#### Version Information

```
ng-packagr: ^1.5.0-rc.0

@angular/cli: 1.2.7
node: 7.9.0
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.7
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6

```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by DavidParks8** [comment]
Can you please provide a repro so we can help troubleshoot?

**Comment by ovione** [comment]
hi David

thanks for your quick answer.
I posted my question just before leaving my workplace today.
Then when I arrived home I decided to try it again from scratch based on the example in 
https://github.com/dherges/ng-packaged.

**Now is working very well and I'm very happy.**

I think the reason why it didn't work before with my example at my workplace was because
in my public_api.ts I was only exporting:
export * from './src/app/modules/header/header.module';
export * from './src/app/services/my-service.service'; 

and I think I had to export my component as well.

but on monday when I go back to my workplace I will compare my working example with the not working example and I will let you know why it didin' work.

cheers
O

**Comment by DavidParks8** [comment]
Sounds good!

**Comment by ovione** [comment]
hi
in my public_api.ts I included the component as well and now the full file is 

```
export * from './src/app/modules/header/header.module';
export * from './src/app/modules/header/header.component';
export * from './src/app/services/my-service.service';
```

this works fine and I can see my app when I do an npm start.
I have no errors

**But I still have a problem**
when I build the client that uses the library for **aot** with the npm script:

> "build.aot": "ng build --aot",

 I get the follwing error:

```
ERROR in Can't resolve all parameters for HeaderComponent in C:/wksp/componentgeneration/componentclient/node_modules/@my/lib/lib.d.ts: (?).

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\wksp\componentgeneration\componentclient\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```
As I comented before in my library the **HeaderComponent** uses **MyServiceService**

```
import { Component, OnInit } from '@angular/core';

import { MyServiceService } from '../../services';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  messageFromService: string;

  constructor(private myServiceService: MyServiceService) { }

  ngOnInit() {
    this.messageFromService = this.myServiceService.sayHi();
    //  this.messageFromService = 'without service';
  }

}
```
In aot it can't find the MyServiceService.

Maybe I should add somewhere an option. But I don't know which.
I will investigate but If you have the solution that would be great :)

**Comment by ovione** [comment]
hi David

its working if I put it in the context  of a https://github.com/dherges/ng-packaged
thanks

I need to create libraries but I don't know what to use.
I don't know if I should use ng-packagr but I saw the video that you linked of
Packaging Angular - Jason Aden at ng-conf 2017 

Then I heard that angular-cli could be doing the same.

So I'm a bit in the dark and I don't know which option to choose if I have to go forward.
I also don't know what are the main differences between options.
I also would like to choose a stable option that will stay because I need to create libraries at work.

Maybe you could enlight me a bit about it or suggest me some links.

thanks
O

**Comment by dherges** [comment]
Hi,

in Jason's video, he explains the Angular Package Format. It describes different (let's call them) "artefacts" that should be contained in a npm package for piublishing to the npm reg.

You can do this by hand. There are other starters and seed that create configuration files (and you can edit all the configurations if you wish to). The idea of ng-packagr is a little bit different: you give it an "entry file", the `public_api.ts`. Think if this similar to the `main.ts` of a regular ANgular app. From that entry file all the components, services, and so on... if the library are exported. Then, ng-packagr (kind of) _compiles_ that entry file and all the sources it references and creates the artefacts for publishing.
