### ISSUE TITLE
(Documentation) secondary package structure

### ISSUE THREAD

**Issue by Tallyb** [dherges/ng-packagr#207]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

_please describe the error that you encountered_
The documentation for secondary package shows the sub package (testing) under source, while it seems that it actually needs to be directly under the package. This is how the angular modules are built.

**Comment by DavidParks8** [comment]
Perhaps we need to make the documentation more clear. The folder structure assumes that `src` is the root of the package, thus making `testing` directly under the root.

**Comment by Tallyb** [comment]
see PR #209

**Comment by dherges** [comment]
Also, I changed the wording on the folder structure and tried to make it more clear where the secondary entry points are located from a node module perspective. See 9bb8b94

Do you think that makes it more clear and better or more confusing?

**Comment by Tallyb** [comment]
Thank you! It clarifies it a bit more. 
I am still puzzled by: 
> The module id of a secondary entry directs the module loader to a sub-directory by the secondary's name. 
Any chance you can enhance the explanation of how this is used, if at all? (I can open another issue if this is beyond the scope of this one).

**Comment by dherges** [comment]
Hm. The term “module id” is wrong in this place. What it’s trying to say is in the following sentence in the readme: the name in package.json is the same as the import path in typescript and is the same as the sub-directory in node_modules. How do you understand the explanation? Or how would you phrase the sentence?


Cheers, David

**Comment by Tallyb** [comment]
I have read it again and again, and I am not sure what are the correct wording to describe this. I am not yet familiar with sub packages. The one missing clarification is probably explaining that the module Id is the "main" entry in package.json. 
Closing for now.

**Comment by dherges** [comment]
I found a good explanation in teh [Angular Package Format doc](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit):

> This is an example of `@angular/core/testing/package.json` that simply redirects `@angular/core/testing` imports to the appropriate bundle, flat module, or typings.
