### ISSUE TITLE
ng-packagr exports markdown files from all folders within a library

### ISSUE THREAD

**Issue by paesku** [dherges/ng-packagr#214]
For documenting my library, I'm using [compodoc](https://compodoc.github.io/website/) which allows to add additional markdown files (https://compodoc.github.io/website/guides/tips-and-tricks.html) to describe a component.

My libraries folder structure looks like this:
```
└── my-exported-component/
    ├── my-exported.component.ts
    ├── my-exported.component.spec.ts
    ├── my-exported.component.scss
    ├── my-exported.component.html
    ├── my-exported.module.ts
    └── my-exported.component.md
└── my-not-exported-component/
    ├── my-not-exported.component.ts
    ├── my-not-exported.component.spec.ts
    ├── my-not-exported.component.scss
    ├── my-not-exported.component.html
    ├── my-not-exported.module.ts
    └── my-not-exported.component.md
├── package.json
└── index.ts
```

```typescript
// index.ts
export * from './my-exported-component/my-exported.module';
```

When I build with ng-packagr : 
```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "src/my-lib/lib",
  "dest": "dist/",
  "lib": {
    "entryFile": "index.ts"
  }
}
```

it creates the `dist` folder like this:

```
└── dist/
    ├── my-exported-component/
         ├── my-exported.component.ts
         ├── my-exported.module.ts
        └── my-exported.component.md
    ├── my-not-exported-component/
        └── my-not-exported.component.md
    ├── bundles/
    ├── package.json
    ├── etc..
```

It seems as ng-packagr copies all markdown files from all folders although I did not explicitly register these modules in my index.ts file. Is there a way to exclude them?

**Comment by DavidParks8** [comment]
Not currently (without deleting them after build). This could potentially be exposed as a configurable minmatch path (in a new feature) if there is demand for it. @dherges has the final say in that matter.

**Comment by dherges** [comment]
Hmpf. Have to check. I'd say that only top-level `README.md` and `LICENSE` file should be copied.

**Comment by dherges** [comment]
Related code is here:

https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/package.ts#L234-L235

Before the secondary entrypoints feature, it was the following:

https://github.com/dherges/ng-packagr/blob/cc0657520a2ad021d08f6b0fd2077ebb361074f2/src/lib/ng-packagr.ts#L50-L52

**Comment by comradesharf** [comment]
Due to this
https://github.com/dherges/ng-packagr/blob/9de75241aba6bcf511d88a465e8ffbc5bf59b03c/src/lib/steps/package.ts#L234
if I have a *node_modules*  directory in my source path, it will copy all the markdown files.
<img width="413" alt="copied markdown from node_modules" src="https://user-images.githubusercontent.com/1421734/31987531-b20b036c-b99e-11e7-916d-fe13d193782b.png">

**Comment by comradesharf** [comment]
I suggest doing `${ngPkg.sourcePath}/*.md` instead of `${ngPkg.sourcePath}/**/*.md` will be better

**Comment by dherges** [comment]
With the [initial design doc](https://github.com/dherges/ng-packagr/blob/master/DESIGN.md#build-artefacts), the intetion was to just copy one `README.md` file. I'd like to keep it that way for now.

**Comment by x1c0** [comment]
Hi @dherges 

I'm facing the same issue like @comradesharf where on my dist folder I have all the node_modules README.md files, there is no way of excluding node_modules folder from the dist build?

As far as you wrote above, you should like to keep it like that?

> A README.md and LICENSE file for the library. These files should be located next to the package.json (and can be copied "as is" / static assets).

I understand that you want to include the readme files, but also the ones from node_modules?

Thank you!

**Comment by comradesharf** [comment]
Hi @x1c0,

You can use version 1.4.1 `npm install ng-packagr@1.4.1` instead of the newer version.
There's [pull request](https://github.com/dherges/ng-packagr/pull/215) merged to fixed this but still not released yet.

**Comment by x1c0** [comment]
Hi @comradesharf,

Thanks for your reply, I'm using 1.5.0-rc1  because we had an issue with external libraries being included.. 

I just wanted to make sure that I was not doing something wrong, ATM I'm just running rimraf on that folder and it's ok for now 😉 

I'll wait for the release then.

Thanks guys!
