### ISSUE TITLE
problem with momentjs

### ISSUE THREAD

**Issue by ovione** [dherges/ng-packagr#217]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

I have a build error when I include momentjs.

```
Cannot call a namespace ('moment')
```

I check the other articles about momentjs but couldn't make it work.
Maybe I'm missing something

#### How To Reproduce
I have used the https://github.com/dherges/ng-packaged.

In my package.json I have installed momentjs:
```
"moment": "^2.19.1",
```

In my ng-package.json I have:
```
  "externals": {
      "moment": "moment"
    }
```
In my my-lib/package.json I put the peerDependencies like:
```
{
  "name": "@moblibs/my-lib",
  "version": "1.0.0",
  "repository": "https://github.com/dherges/ng-packaged.git",
  "author": "david <david@spektrakel.de>",
  "license": "MIT",
  "private": true,
  "peerDependencies": {
    "@angular/core": "^4.1.2",
    "@angular/common": "^4.1.2",
    "moment": "^2.19.1"
  }
}
```

In my component I import it like:

```
import * as moment from 'moment';
```

When I build my my-lib I have the following error

```
BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
    at error (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:8390:3)
    at Node.bind (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:6419:17)
    at eachChild.child (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:5819:34)
    at keys.forEach.key (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:5847:5)
    at Array.forEach (native)
    at Node.eachChild (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:5840:13)
    at Node.bind (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:5819:8)
    at Node.bind (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:6242:9)
    at eachChild.child (C:\wksp\componentgeneration\ng-packaged\node_modules\rollup\dist\rollup.js:5819:34)

```

#### Expected Behaviour

To be able to build my library without error with momentjs.

#### Version Information

```
@angular/cli: 1.4.9
node: 7.9.0
os: win32 x64
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.5.3
```

_please include any version information that might be relevant, e.g. other third-party libraries_
"moment": "^2.19.1",

**Comment by ovione** [comment]
I made it work modifying the import in my library component FooComponent 
from
`import * as moment from 'moment';`

to

`
import * as momentImported from 'moment';
const moment = momentImported;
`

I read that in [https://stackoverflow.com/questions/39519823/using-rollup-for-angular-2s-aot-compiler-and-importing-moment-js](url)

With that said now I'm able to generate the lib, install it into my project, build my project for prod and aot enabled and start it and test it in a browse.

Of course it works without giving any errors but is this the bes way ?

thanks
O

**Comment by dherges** [comment]
This is the way for moment.js

Please see #163

**Comment by ovione** [comment]
yes but if I wollows that article it is said that to use moment in code the import should be:
`import ... from 'moment';`

but this should be 
`import * as momentImported from 'moment';` and then

`const moment = momentImported;`

Otherwise rollup doesn't work.
>

**Comment by samuel-gallet** [comment]
I agree with @ovione.
If you don't use the 
`
import * as momentImported from 'moment';
const moment = momentImported;
`
You get the `Cannot call a namespace ('moment')` Error

**Comment by Nevergonnachange** [comment]
Why is this issue closed? I am having the same issue. And adding the 

```
"lib": {
"externals": {
      "moment": "moment"
    }
}
```

Does not help. I am still having the problem.

When using
import * as moment from 'moment';
I get the following

```
BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
```

The other import possiblities give me errors aswell:

import moment from 'moment'

`time-line/node_modules/moment/moment"' has no default export`

import * as momentImported from 'moment'; const moment = momentImported;

`Cannot find module 'momentImported'`

Id appreciate any help. Thanks very much.

**Comment by beradrian** [comment]
I'm still having this issue and as @Nevergonnachange said above, I also tried everything.

**Comment by ranglang** [comment]
any way to deal with it ?

**Comment by matheo** [comment]
@ranglang the namespace fix worked for me, replacing the import  of moment like:
```
import * as momentNs from 'moment';
const moment = momentNs;
```
and sometimes I was using the type `moment.Moment;` and I had to replace it with `momentNs.Moment` and it worked. Do not forget about the "externals" setup, that got renamed to  `umdModuleIds`, mine looks like:
```
  "ngPackage": {
    "dest": "./dist",
    "lib": {
      "entryFile": "./src/datepicker/index.ts",
      "umdModuleIds": {
        "@angular/cdk": "ng.cdk",
        "@angular/material": "ng.material",
        "lodash": "_",
        "moment": "moment",
        "moment-timezone": "moment-timezone"
      }
  }
```

**Comment by jakubjosef** [comment]
I have the same problem with using of lodash (_). I tried all solutions found across the internet.
but only this worked `import * as lodashImported from 'lodash'; const _ = lodashImported;`.

No changes in files (adding globals, externals, umdModuleIds) to ng-package.json) helped.
With this solution you also dont have to do any other change in any file. 
So externals setup is not necessary - @matheo is not completely right.

I will be glad to find better solution because this is kinda ugly. :(

**Comment by matheo** [comment]
I've moved to ES6 imports like
`import { findIndex } from 'lodash';`
and probably I'm not using the external alias anymore.

**Comment by gabrielalan** [comment]
So no one is going to fix this problem seriously between `ng-packagr` contributors?

**Comment by etiennecrb** [comment]
@matheo The problem with your solution is that you are importing the whole lodash library, no tree shaking!

**Comment by yglin** [comment]
Same problem here and solved with @matheo 's solution, THANX~

typescript@2.9.2
ng-packagr@4.7.0
@angular/cli@6.2.9
moment@2.24.0

**Comment by Arikael** [comment]
the same issue also happens with deepmerge

**Comment by newmanw** [comment]
Similar problem for me as well.  I am running into a issue with providing the moment as a bundledDependency.

```
import * as momentNs from 'moment';
const moment = momentNs;
```

```
  "ngPackage": {
    "dest": "./dist",
    "lib": {
      "entryFile": "./src/datepicker/index.ts",
      "umdModuleIds": {
        "moment": "moment"
      }
  }
```

Library builds fine, but when trying to use the component in another project I get a runtime error accessing the moment() constructor.

```
  ngOnInit() {
    this.now = moment().format('LLLL');
  }
```

With error: 

> moment$1 is not a function

The library umd.js ends up looking like this:

```
var moment$1 = momentNs;
var now = moment$1().format('LLLL');
```
