### ISSUE TITLE
Unable to npm pack scoped package 

### ISSUE THREAD

**Issue by cogitaria-admin** [dherges/ng-packagr#218]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Running ng-packagr then npm pack in dist folder fails if the package.json name is **scoped**:

```
"name": "@foo/bar"
```

The npm pack generates this error message: 

```404 Not Found: @foo/bar@latest```

Tried ```npm pack @foo/bar``` but same result. 

#### How To Reproduce

See descriptions

#### Expected Behaviour

Running ```npm pack``` works with scoped package name.

#### Version Information

```
 "ng-packagr": "^1.5.0-rc.1",

```

**Comment by DavidParks8** [comment]
Can you please provide a repro?

**Comment by DavidParks8** [comment]
Indeed that is the issue as seen [here](https://github.com/npm/npm/issues/18328). Rolling back to npm 5.3 should fix the problem.

**Comment by dherges** [comment]
Please see npm's project page / documentation / issue tracker as  the error you describe is from `npm pack`

**Comment by cogitaria-admin** [comment]
Thanks for investigating this and for the workaround!
