### ISSUE TITLE
Angular team wants people not to use tsc-wrapped

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#219]
Taken directly from the [@angular/tsc-wrapped build repo's readme](https://github.com/angular/tsc-wrapped-builds/blob/master/README.md): "This package is an internal dependency used by angular/compiler-cli. Please use that instead."

I've tested it and it works the same without direct use of tsc-wrapped. 

I propose ng-packagr be changed to use angular/compiler-cli.

**Comment by dherges** [comment]
Yes, I don't know whether to classify as bug, feature or refactoring. To be clear and honest: it's super duper extreme low priority. I see no need to change.

**Comment by DavidParks8** [comment]
The output of them seem to be identical, but the angular/compiler-cli is much faster on my machine. This is probably due to it being implemented as a typescript transform. I would say this performance improvement is worth implementing, since the change is so minimal.

**Comment by dherges** [comment]
With v5 support, we will then change :smile:
