### ISSUE TITLE
scripts and css available to angular-cli.json via scripts and styles tag are not packaged in the distribution

### ISSUE THREAD

**Issue by sbibek** [dherges/ng-packagr#220]
## Scripts and styles mentioned in angular-cli.json are not available in the distribution

```
[ ] Bug Report
[ ] Feature Request
```

## Description

My module I am working on depends on the js and css from bootstrap and font-awesome which are included inside angular-cli,json. They don't seem to be packaged with the distribution.

**Comment by dherges** [comment]
Please see #123
