### ISSUE TITLE
When will this support Node 8 / npm 5

### ISSUE THREAD

**Issue by pl4yradam** [dherges/ng-packagr#223]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
When using Node 8 and NPM 5 using the packagr command followed by npm publish fails

#### How To Reproduce

Create any standard NG-CLI project, have the project name something like:

`@something/feature`

Add the ng-package and index ts and correctly map,
Run the ng-packagr command (which generates the dist folder)
The dist folder should then have a folder inside it with @something (followed by the umd)

Try to publish this, we will see an error that the directory is not found, publish is looking for <folder>/something
instead of
<folder>/@something

#### Expected Behaviour

The correct folder to be found at publish.

#### Version Information

```
ng-packagr: v1.x.y
node: v8.x.y
@angular: v4.x.y
NOM: v5.x.y
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by DavidParks8** [comment]
This is not a bug with ng-packagr, but rather a bug with npm itself. https://github.com/npm/npm/issues/18328
Rolling back to npm 5.3 should fix the problem.

**Comment by pl4yradam** [comment]
@DavidParks8 thanks for the information!

**Comment by DavidParks8** [comment]
No problem.
