### ISSUE TITLE
3rd party causing conflict - ng2-validation

### ISSUE THREAD

**Issue by pl4yradam** [dherges/ng-packagr#224]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

When using, the following package, during the `npm run packagr` command this will cause failure.

`https://www.npmjs.com/package/ng2-validation`

This package has a file called 
libphonenumber-js/metadata.min.json
I have confirmed this file has valid json, jsonlint

Within this dependency there is a file called 

#### How To Reproduce

Install the ng2-formvalidate, run a packgr build
error:

BUILD ERROR
Unexpected token
```
Error: Unexpected token
  /frontend/Libraries/form-validation-library/node_modules/rollup/dist/rollup.js:187:14)
    at Module.error (/frontend/Libraries/form-validation-library/node_modules/rollup/dist/rollup.js:8392:3)
    at tryParse (/frontend/Libraries/form-validation-library/node_modules/rollup/dist/rollup.js:8108:10)
    at new Module (/frontend/Libraries/form-validation-library/node_modules/rollup/dist/rollup.js:8149:15)
    at load.catch.then.then.then.source (frontend/Libraries/form-validation-library/node_modules/rollup/dist/rollup.js:10009:20)
```

#### Expected Behaviour

A successfull build

#### Version Information

```
ng-packagr: v1.x.y
node: v5.x.y
@angular: v4.x.y
npm 3
```

When the build packgr function command is ran, is it nessecary to include the node_modules folder or can this be ignored by a flag? Other packages I have developed without packagr have not needed to build a node_module folder, also, this doesnt get distributed on publish.

**Comment by DavidParks8** [comment]
If you are on windows, please change your package.json script to include `"packagr": "SET DEBUG=true && ng-packagr -p ng-package.json"`, run it, then paste the output.

**Comment by pl4yradam** [comment]
Unfortunately I'm on MAC any assistance on debug for that?

**Comment by DavidParks8** [comment]
Sorry, I don't have a mac to test commands on, but the idea is that you temporarily set the DEBUG environment variable to true. If you provide a clone-ready reproduction of the issue, it would also be helpful.

**Comment by pl4yradam** [comment]
Hi David, ill make a clone ready reproduction as unfortunately I cant seem to set debug for you
