### ISSUE TITLE
Doesn't work with scoped packages (@scope/package-name)

### ISSUE THREAD

**Issue by avatsaev** [dherges/ng-packagr#226]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Using scoped packages with names like `@avatsaev/my-lib` doesn't structure the artifacts correctly, so the final result can't be packaged.

#### How To Reproduce

Initialize a project with a scoped name in package.json

`"name": "@scope-name/package-name"`

compile with ng-packagr

go to the resulting folder and pack the lib

`npm pack`

resulting error:

```
(node:25409) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 
ENOENT: no such file or directory, stat './dist/lib/@scope-name/package-name.es5.js'
(node:25409) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>



```

**Comment by dherges** [comment]
Hi,

see #225 #223 #218

**Comment by avatsaev** [comment]
Excellent, thank you for the fast response

**Comment by wgwine** [comment]
Figured out a workaround for this, in case anyone needing it can't update NPM anytime soon. Just move the files from the scoped folder to the parent before running npm pack.

`"ng-packagr -p ng-package.json && cd dist/@scopename && move * ../ && cd ../  && npm pack && cd ../"`
