### ISSUE TITLE
Can't use ~ in less file to reference file in node_modules

### ISSUE THREAD

**Issue by trashhead** [dherges/ng-packagr#227]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

When having a less file with ~-character in import, ie: 
@stilguide-path: '~module/src';
@import '@{stilguide-path}/less/variabler.less';

It cannot resolve the path.

#### How To Reproduce

I guess adding a less-file with an import that references a module in node_modules but instead of using ..\..\..\..\node_modules\module\src\less\variables.less

it should be: ~module\src\less\variables.less

#### Expected Behaviour

BUILD ERROR
'~module/src/less/variabler.less' wasn't found. Tried - C:\Proj\git\my-module\src\app\modules\stuff\~module\src\less\variabler.less,~module\src\less\variabler.
less
undefined

#### Version Information

```
ng-packagr: ^1.5.0-rc.1
node: v6.11.4
@angular: v4.2.4
rxjs:
zone.js:
```

**Comment by dherges** [comment]
HI @trashhead,

the "~" syntax for resolve relative to `node_modules` is only implemented for scss and was inspired by [webpack's sass-loader](https://github.com/webpack-contrib/sass-loader#imports)

**Comment by wwarby** [comment]
The "~" syntax works for LESS files when running `ng build` or `ng build --prod` though. Would be really nice if ng-packagr supported it too.
