### ISSUE TITLE
Unable to access services in consuming application

### ISSUE THREAD

**Issue by mockuniverse** [dherges/ng-packagr#232]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

I am packaging a module whose forRoot looks like this:

`forRoot() { return { ngModule: MyModule, providers: [MyService]  }  }`

So, there's no providers property on the @NgModule declaration as we are using forRoot.  Either way (with or without forRoot) how is the consuming application supposed to access MyService?

I assumed adding this to application code would work, but MyService is not exported:

`import { MyService } from 'MyModule`

#### How To Reproduce

Package a module with a service and try use it from an application that uses that module. 

What am I missing?

#### Expected Behaviour

The services in the providers (forRoot or otherwise) should be available so it can compile. 

#### Version Information

```
ng-packagr: v1.x.y
node: v8.x.y
@angular: v4.x.y
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by DavidParks8** [comment]
`MyService` must also by exported in your library entry file. Doing so should enable import statements in consuming code. Take a look at [this `public-api.ts` file from material2](https://github.com/angular/material2/blob/master/src/lib/form-field/public-api.ts). It exports much more than just a module.

**Comment by mockuniverse** [comment]
Excellent and thanks for being so responsive!
