### ISSUE TITLE
How to properly add CSS files into a bundle?

### ISSUE THREAD

**Issue by piotrkorlaga** [dherges/ng-packagr#233]
## Type of Issue

```
[X] Question
```

## Description
Hi all,

I've started to use  "ng-packagr" and I enjoy it a lot! :)

I have only small issue and I'd like to kindly ask you for advice.

I've created "core lib" for my projects and I want to put my global styles (*.less) into this lib. I did it by linking styles in .angular-cli.json. These styles are properly generated and appears in dist directory when I use "ng build" but I cannot figure out how to add them to a bundle while using "ng-packagr"

Any advice will be more than welcome

**Comment by DavidParks8** [comment]
ng-packagr only bundles styles that are referenced by a component in a typescript decorator. For external or global less styles, I would recommend using [the official less package](http://lesscss.org/) to compile your styles to css in your dist folder.

**Comment by piotrkorlaga** [comment]
@DavidParks8 thanks for a tip. I will go this way.
