### ISSUE TITLE
Error: ENOENT: no such file or directory, chmod '...\dist\node_modules\fileset\test\fixtures\foo.md'

### ISSUE THREAD

**Issue by rojasjandro89** [dherges/ng-packagr#234]
## Type of Issue

```
[x ] Need Help | Possible bug report
```

## Description

When I run it I get the following response:

> frosted-glass@0.0.0 packagr C:\Users\jandro\Desktop\Projects\FrostedGlassUI
> ng-packagr -p ng-package.json

>Building Angular library
>Generating bundle for frosted-glass

>BUILD ERROR
>ENOENT: no such file or directory, chmod 'C:\Users\jandro\Desktop\Projects\FrostedGlassUI\dist\node_modules\fileset\test\fixtures\foo.md'
>Error: ENOENT: no such file or directory, chmod 'C:\Users\jandro\Desktop\Projects\FrostedGlassUI\dist\node_modules\fileset\test\fixtures\foo.md'

>npm ERR! code ELIFECYCLE
>npm ERR! errno 111
>npm ERR! frosted-glass@0.0.0 packagr: `ng-packagr -p ng-package.json`
>npm ERR! Exit status 111
>npm ERR!
>npm ERR! Failed at the frosted-glass@0.0.0 packagr script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\jandro\AppData\Roaming\npm-cache\_logs\

According to this error, it can't find foo.md file but every time I got the error I go to the location and the file in question DOES exist, I don't know what could be happening here.
This is the log file:
[2017-10-31T12_42_27_962Z-debug.log](https://github.com/dherges/ng-packagr/files/1430836/2017-10-31T12_42_27_962Z-debug.log)

#### Version Information

node v8.1.3

This is my package.json

{
  "name": "frosted-glass",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "packagr": "ng-packagr -p ng-package.json"
  },
  "private": false,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^1.5.0-rc.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

I'm stuck here, any help will be greatly appreciated.

**Comment by rojasjandro89** [comment]
Nevermind, I created a new angular project, moved the module files and it worked this time. I wonder what was causing this weird behavior but anyway...it works now.  I guess I'm closing this for now.

**Comment by loicsalou** [comment]
I'm facing the exact same issue. Sometimes with fileset just like you sometimes with glob-watcher:

```
BUILD ERROR
ENOENT: no such file or directory, chmod 'C:\tools\Workspace-AngularX\zas-web-components\dist\node_modules\glob-watcher\node_modules\globul
e\test\fixtures\expand\README.md'
Error: ENOENT: no such file or directory, chmod 'C:\tools\Workspace-AngularX\zas-web-components\dist\node_modules\glob-watcher\node_modules
\globule\test\fixtures\expand\README.md
```

I'm not having this every time, and usually cleaning node_modules + reinstalling resolves the issue, or even cleaning dist, but not systematically.
I fear this might be blocking issue when building in CI with Jenkins...

Has anyone an idea of what's going on ? why are we struggling with .md files ?
really strange.

**Comment by loicsalou** [comment]
I may be wrong but my feeling is that empty files are not correctly handled in ng-packagr or one of its dependencies. Both file causing issues during my builds are empty. I wrote "123" in each and tried again ==> it's working.

Temporarily I'll try and search a version of both packages involved (fileset and glob-watcher) which has these files not empty but I doubt I'll find any.
Workaround would be to write something using gulp in these files before building but that's really ugly.

Will try experimentations and open an issue in this repo when I have something to reproduce and a confirmed  @diagnosis.
@dherges as you are in RC, that may be something easy to fix ? just a question ;-)

**Comment by rojasjandro89** [comment]
I know it's not right but I can't say I'm not glad someone else is having the same issue. It is driving me crazy and no one else is having it?! I have to reinstall everything and try until it randomly works...it's really messing with my workflow :/

**Comment by loicsalou** [comment]
So I for sure have found a workaround now. I wrote a simple gulp script that remove these f#@!?@ empty files that make ng-packagr crash.
Rather easy though not satisfying. Simply read which file causes the issue, check it's actually empty (just in case it's not the same issue as I have) then create a gulp file.

I will write an issue in the repo this weekend and provide some similar case juste to help and solve this.
Btw we must hang these developers who create empty readme.md or foo.md ;-)

If you need I can provide an example.
