### ISSUE TITLE
Packaging issue when using Moment.js in Library

### ISSUE THREAD

**Issue by plambhsa** [dherges/ng-packagr#235]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When running ng-packagr and trying to include moment, I get the following error:
```
BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
```

#### How To Reproduce

Create a component/pipe that needs moment, and import it. In a normal Angular app, you would use it by doing this: `import * as moment from 'moment';`, but that doesn't fly when packaging the library. I changed the tsconfig.json to `allowSyntheticDefaultImports` but the same error occurs.

#### Expected Behaviour

The package should be packaged up just fine with ng-packagr, including if it has moment included.

#### Version Information

```
ng-packagr: v1.5.0-rc.1
node: v8.4.0
@angular: v4.4.6
rxjs: 5.5.2
zone.js: 0.8.18
```

The moment library I'm using is 2.19.1. I also tried using moment-es6 at version 1.0.0.

**Comment by KyleMcNutt** [comment]
@plambhsa Try taking a look at this two issues, and see if they resolve your problem:
https://github.com/dherges/ng-packagr/issues/163
https://github.com/dherges/ng-packagr/issues/217

**Comment by dherges** [comment]
Hi @plambhsa, yes, can you please check the other issues if they solve your situation? Should there still be issues/questions, please comment and re-open!
