### ISSUE TITLE
scoped packages

### ISSUE THREAD

**Issue by iwhp** [dherges/ng-packagr#245]
## Type of Issue
```
[x] Bug Report
[ ] Feature Request
```
## Description
running `npm run packagr` for a scoped package (e.g. `@test/test` will produce a folder called `@test` under `dist`.

Running `npm pack` or `npm publish` then throw errors, `no such file or directory`.

#### How To Reproduce

In `package.json` name your package `"name": "@test/test"`
Then run `npm run packagr`.
Under `dist` a folder called `@test` is created.

#### Expected Behaviour

The folder should probably just be called `test`, without `@`.

#### Version Information

```
ng-packagr: v1.5.0-rc.1
node: v8.8.1
@angular: v5.0.0
rxjs: v5.5.2
zone.js: v0.8.14
```

**Comment by DavidParks8** [comment]
This is a duplicate of #218

**Comment by iwhp** [comment]
As described in #218, npm v5.3.0 works fine.
The bug should be fixed as documented in https://github.com/npm/npm/pull/19033
