### ISSUE TITLE
ng 5

### ISSUE THREAD

**Issue by zpydee** [dherges/ng-packagr#246]
Hi,

I'm about to get into the meat of breaking my ng app into libraries using your library and also need to upgrade to ng5 in parallel Naturally, they question of compatibility arises. Can you give any indication of what one can expect and if not compatible, when you plan to upgrade your library?

many thanks.
Dave

**Comment by sollenne** [comment]
@zpydee , I'm not the author, but I'm doing the same thing. angular 5 is nothing more than a version number change. If you look at the angular release schedule, the '5' is a major release based on the date only. This is working for me at the moment.

**Comment by Sibiraj-S** [comment]
I too tried with Angular5, SFSG. Everything works just fine...  😄

**Comment by zpydee** [comment]
@sollenne @Sibiraj-S thanks for your feedback. naturally, i'd prefer to upgrade my monolith before splitting it up.

**Comment by dherges** [comment]
Hi all,

in general, ng-packagr will move to angular v5 support ... let's say "soon" ... like in next couple of weeks or so.
