### ISSUE TITLE
RxJS: lettable operators

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#247]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Need to check / verify whether RxJS "lettable operators" do work by default.

![2017-11-03 10_31_56-version 5 0 0 of angular now available angular blog](https://user-images.githubusercontent.com/901354/32367419-5211a9b2-c082-11e7-99b7-cf56d4852723.png)

https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

#### How To Reproduce

see above

#### Expected Behaviour

see above, lettable operators should work ootb

#### Version Information

```
ng-packagr: v1.5.0-rc.x
```

**Comment by ocombe** [comment]
I wanted to use ng-packagr for ngx-translate, and I was a bit worried when I saw that the UMD module was 127kb minified, so I checked with source map explorer and I can tell you that it bundles the rxjs operators :(
![screenshot-2017-11-23 dist bundles core umd min js - source map explorer](https://user-images.githubusercontent.com/265378/33162958-69d3c99a-d02c-11e7-9183-36d09393d59c.png)

Any idea what I could try to remove them?
