### ISSUE TITLE
[Question] Where can I put my library's .spec.ts and .e2e-spec.ts files?

### ISSUE THREAD

**Issue by Ks89** [dherges/ng-packagr#248]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I have some .spec.ts files to test my library, but I don't know where to put these files in my repo (equals to ng-packaged) to run karma in the right way. I want to execute my lib's tests and measure test coverage with different reporters.

For e2e tests it seems easier, because I can put all my .e2e.ts into /e2e and run they with the angular-cli app.

thank u

**Comment by dherges** [comment]
Hi @Ks89,

please the two demo projects, ng-packaged and nx-packaged, as well as Nicolas Le Blanc medium story. Karma tests are included there.

**Comment by dherges** [comment]
Just put them next to the components like you would do with Angular CLI:

```
foo
  |- foo.component.ts
  |- foo.component.spec.ts
```

**Comment by Ks89** [comment]
@dherges 
Hi, I saw ng-packaged (I also based my project using this as starter) but there aren't example tests into ./my-lib.

I cloned ng-packaed and I am able to build it and run ng serve, but when I try to run "yarn test" or "npm test" I get this error:

```
ERROR in ./src/app/app.component.spec.ts
Module not found: Error: Can't resolve '@my/lib' in '/Users/ks89/git/ng-packaged/src/app'
 @ ./src/app/app.component.spec.ts 4:12-30
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '@my/lib' in '/Users/ks89/git/ng-packaged/src/app'
 @ ./src/app/app.component.ts 13:12-30
 @ ./src/app/app.component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
```

Also, in angular-cli.json there are two "apps" with the same root and outDir, but with different names. Is it correct? I don't understand the purpose.

PS: which project do you suggest as starter project to build a library?  ng-packaged or nx-packaged (with Nrwl Nx)?

Thanks.
