### ISSUE TITLE
[Question] How can I export a component?

### ISSUE THREAD

**Issue by yonigo** [dherges/ng-packagr#249]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I would like to reference an exported component using ts import, but I receive a "can't resolve..." error.  

#### How To Reproduce

1.Create a module that exports a component. 
2. Add reference in public_api.ts: (export * from './src/app/myModule/components/myComponent.component'; )
3. pack using ng-packagr and publish
4. Use the component in another app:
anotherApp-routing.module.ta
import {myComponent} from 'my-module'...

**Comment by dherges** [comment]
Hi,

can you please take a look at the demo projects, ng-packaged and nx-packaged, as well as Nicolas Le Blanc medium story? I think it's very well explained there!
