### ISSUE TITLE
Consider including scope name in moduleName

### ISSUE THREAD

**Issue by JoostK** [dherges/ng-packagr#251]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Currently, the moduleName of a library is set to the package's name without the scope name. I would like to see the possibility/default to include the scope name in the moduleName, as a package name such as `core` is meaningless without scope name and will likely cause conflicts.

I can whip up a PR if you feel this may be useful. I'm not quite sure if including the scope name by default is warranted as it would be a breaking change, although I feel like it is a more sensible default. What is your thought on how to go about this?

**Comment by dherges** [comment]
Hi @JoostK,

yes, you're right. A good starting point for a PR is the `ngc.ts`:

https://github.com/dherges/ng-packagr/blob/c5c32c5/src/lib/steps/ngc.ts#L14-L15
