### ISSUE TITLE
Use Angular CLI and ng-packagr for local development and CI servers

### ISSUE THREAD

**Issue by jonesmac** [dherges/ng-packagr#252]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Not sure the packagr is actually compatible with the cli in the same repo as described in the readme.  I realize that this issue is related to another repo, but this was the only place to file an issue.  I believe it is related to how the cli resolves modules slightly differently than tsc (at least for modules outside the baseUrl).

#### How To Reproduce

When attempting to use the [repo](https://github.com/dherges/ng-packaged) from the readme, the ng serve command fails with `ERROR in src/app/app.component.ts(3,28): error TS2307: Cannot find module '@my/lib'.
src/app/app.module.ts(7,29): error TS2307: Cannot find module '@my/lib'.`

#### Expected Behaviour

It should be able to resolve lib

#### Version Information

```
  "dependencies": {
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/language-service": "~5.0.0",
    "@types/jasmine": "~2.6.0",
    "@types/node": "~8.0.0",
    "codelyzer": "~4.0.0",
    "cpr": "^3.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "1.5.0",
    "protractor": "~5.2.0",
    "rimraf": "^2.6.1",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "~2.5.2"
  }
```

__Update:__
For anyone else facing this issue, I believe it is being tracked here in the cli project and has been assigned to someone. - https://github.com/angular/angular-cli/issues/8308
Seems it is looking in node_modules to module resolution and ignoring all other path settings and alias' such as those in tsconfig or webpack (according to the issue).

**Comment by deebloo** [comment]
@jonesmac are you using tsconfig paths? if so ng-packagr uses it's own internal tsconfig that has no insight into your projects defined paths. I opened a different issue asking to be allowed to provide your own tsconfig.

**Comment by dherges** [comment]
Hi @jonesmac,

thanks for reporting! The ng-packaged demo needs an update!

My recommended way is to use "ng serve" with a cli config that uses the library sources and another npm/yarn script for building against binaries of library (e.g. on a ci server)

**Comment by dherges** [comment]
Updated the [ng-packaged](https://github.com/dherges/ng-packaged) demo.

I guess the readme over there is now out-of-date. I'd very much appreciate when someone could send a PR for that when she/he tries to get going with the demo....

**Comment by jonesmac** [comment]
@dherges thanks so much for updating the repo!  I pulled it down and verified that it all works locally.  I see the CI config and updated scripts.  Are you looking for a PR that documents how to the new features you recently added or a general rewrite of the README?

**Comment by dherges** [comment]
@jonesmac Exactly! That will be super-cool!

**Comment by PsyGik** [comment]
Did not want to create another ticket since this one already exists. A simple clone of the repo and build is still causing `ERROR in src/app/app.component.ts(3,28): error TS2307: Cannot find module '@my/lib'. src/app/app.module.ts(7,29): error TS2307: Cannot find module '@my/lib'.`

Any workarounds?
