### ISSUE TITLE
LICENCE is not copied

### ISSUE THREAD

**Issue by Sibiraj-S** [dherges/ng-packagr#253]
## Type of Issue

```
[ x ] Bug Report
[ ] Feature Request
```

## Description

The LICENCE file isn't copied. Was that intentional?

#### Version Information

```
ng-packagr: v1.5.0
node: v8.9
```

**Comment by dherges** [comment]
No, it should be copied. Strange. I have projects where the LICENSE file is copied. Silly question: do you have a repro like a GitHub repo?

**Comment by Sibiraj-S** [comment]
No. Sorry My bad. There was a typo in my file. Just looked closely 😅
