### ISSUE TITLE
Publish pre-release versions to npm with next tag

### ISSUE THREAD

**Issue by Sibiraj-S** [dherges/ng-packagr#254]
Last time when I tried to install `ng-packagr` with `npm` it installed the `release candidate` version but It should install the latest final version not `alpha, beta or rc` version.

So, unreleased version can be published using `beta tag`. 😄

**Comment by dherges** [comment]
Yes, definetely!

Do you have a good solution for automated publishing from circle CI?

https://github.com/dherges/ng-packagr/blob/a4174977d7c3009faf480377d695d456b4358e69/.circleci/config.yml#L30-L35

**Comment by dherges** [comment]
Is `npm publish --tag next` ok? Should keep latest to the v1.x.y and set next to v1.x.y-pre.n

**Comment by Sibiraj-S** [comment]
>Do you have a good solution for automated publishing from circle CI?

I think `semantic-release` would be a better solution for publishing from `circle-ci(or any other CI-CD.services)`. Have you seen that?

**Comment by Sibiraj-S** [comment]
> Is npm publish --tag next ok? 

 A-Ok.

**Comment by dherges** [comment]
Written a wonderful regex which seems to match :smile: 

```bash
[[ v1.0.0-rc.0 =~ v([0-9]{1,1})\.([0-9]{1,1})\.([0-9]{1,1})-([a-zA-Z]+)\.*.* ]] && echo ${BASH_REMATCH[4]}
```

tested on https://www.regexpal.com/

**Comment by dherges** [comment]
If [standard-version auto-generates publishConfig](https://github.com/conventional-changelog/standard-version/issues/146#issuecomment-343486322), I'd prefer that!

**Comment by Sibiraj-S** [comment]
cool . 😃
