### ISSUE TITLE
[DRAFT] Add ability to override tsconfig

### ISSUE THREAD

**Issue by deebloo** [dherges/ng-packagr#256]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I know that the idea of ng-packagr is to remove as much config as possible from the user but there are cases where being able to manage the tsconfig used by ng-packagr would be very useful, for example adding paths or alternate/additional typeroots. There could be an additional and optional flag to point to the desired tsconfig.

It can cause some difficult to troubleshoot issues when you need to use one config to test your library and another unseen one is used to build.

```
ng-packagr: v1.5.0
node: v8.6.0
@angular: v5.0.0
rxjs: 5.2.2
zone.js: latest
```

Thanks for the awesome work! I might be able to help with a PR if it is something @dherges thinks it is a valuable usecase

**Comment by dherges** [comment]
Hi @deebloo,

I label this as "enhancement" for now.

Certain compiler options, e.g. the es "target" and "module" for tsc or "skipTemplateCodegen" for ngc, would be overridden during build. With the current idea of "lib.entryFile", the "files: []" need to be overridden. In current implementation it would mean to merge tsconfig files.

For angular v5, we need to switch to `@angular/compiler-cli` (from tsc-wrapped) ... we could pass a user's tsconfig and override values by passing cli options to ngc.

Opinions and discussion wanted :grimacing:

To the girls and guys using ng-packagr, can you describe what your use case/motivation is for overriding the tsconfig?

**Comment by jerousseau** [comment]
Hi,

I think I need this feature too, I use ng-packagr with NX Workspace.
I have two libs in the workspace and the second lib reference the first, if I want to build the second lib I need to add the first lib into the "paths" of the tsconfig.

**Comment by dherges** [comment]
Good point.

Coming from java android territory, this is a build graph. Compile library A to binary first, then compile B linking to binaries of A. 

The tsconfig approach is compiling B while linking to sources (“library”) of A.

My workaround is to publish binaries of A (= copy or symlink dist folder) to node_modules directory, then build B, then unpublish A from node_modules. 

I’d like to hear more opinions on this. I guess the angular core repo is doing something similar by setting tsconfig paths pointing to dist folders?!?



Cheers, David

**Comment by deebloo** [comment]
@dherges so that is what I do now. I build one package and then package the ones that depend on it. This mean I have to build packages one a a time and they have to be built in the correct order. allowing custom tsconfigs would mean faster builds for repos with multiple module. Besides the mono repo use case it would be nice to have the same tsconfig for both building and for demos. I do agree that the angular specific config stuff shouldn't be overridable, we could throw a warning if a user tries to do this

**Comment by tomwanzek** [comment]
For starters, thanks for all the great work on `ng-packr` 💯 

To expand a little on the use case question, clearly one major factor are the already described dependencies between multiple libraries and the app(s). Another part of this puzzle are libraries which contain shared theming support, similar to Angular Material. Arguably not an uncommon scenario.

Other than the manual linking/publishing of these "theming" libraries with appropriate copy scripts for the styling files not captured by the default build scripts, I have not yet found "tooling" support covering this aspect. 

With all the apparent emphasis on e.g. `path` mappings in `tsconfig.json`, this more comprehensive approach seems to be elusive at this point i.p. during development time. I ran into this limitation as well when experimenting with the `nx` monorepos.

Hope this comment is not too tangential. Bit of a wide angle lens on the use case, I suppose.

**Comment by DavidParks8** [comment]
This is very much related to my https://github.com/dherges/ng-packagr/issues/162#issuecomment-335665479. I would like to reiterate my proposal here and see if people agree.  Essentially, I propose we add another config property to allow the specification of an override tsconfig:
```json
{
  "tsconfig": "./../tsconfig.app.json"
}
```
This property would have to be clearly documented such that everyone is aware of what can, and can not be overridden in the `tsconfig.json` file.

**Comment by JoostK** [comment]
I also have use-cases for overriding certain tsconfig options, ie I need to use `downlevelIteration` and compile using `es2016` libs instead of `es2015` that is the default. Furthermore, being able to modify the paths mapping would avoid the need to symlink dist folders of dependent builds.

**Comment by kuhnroyal** [comment]
I am currently going with this:
```
"build:lib/foo": "copyfiles -u 2 lib/foo/tsconfig.ngc.json node_modules/ng-packagr/lib/conf && ng-packagr -p lib/foo/ng-package.json",
```

**Comment by davidenke** [comment]
This affects #269, since the cli now creates a tsconfig.json with compiler options `lib: "es2017"` by default.

**Comment by alan-agius4** [comment]
Really keen into having this feature.for various reasons such as paths, unusedImports and other settings.

**Comment by DavidParks8** [comment]
@dherges, would now be an appropriate time to implement this? I don't want to push a PR without the go ahead.

**Comment by gund** [comment]
+1 for this feature.

My use-case: do not want TS to generate helper's in the output and instead import them from `tslib`.
So want to set this options:
```json
{
  "compilerOptions": {
    "noEmitHelpers": true,
    "importHelpers": true,
  }
}
```

**Comment by MartinSvarrer** [comment]
Also would like to add my support for this feature. My use-case is that I would like to control some of the settings for improving the code quality where TSLint is not sufficient, like strictNullChecks, noImplicitAny, noUnusedLocals etc.

**Comment by dherges** [comment]
Let's pretend ng-packagr gives you two choices of using it:
- for the _"quick starters"_, drop in a package.json and you're up and running
- for the _"rampant runaways"_ who are in for the long haul and need/want/like to deep dive, a programmatic API where you're able to _'scriptfigure'_ a build with `js` / `ts` (© / ® 2018 on the term "scriptfigure")

An example of what it could look like:

```ts
import { ngPackagr } from 'ng-packagr';

ngPackagr()
  .project('/usr/local/foo/bar/package.json')
  .withAdditionalStuff(/* ... */)
  .andCustomStylesheetProcessor(
    styles => styles.filter(f => f.ext === '.less').map(/* ..*/)
  )
  .andTsConfig(/* ... */)
  .andStaticAssets(assets =>
     assets.from('here/**/*.bmp').to('there')
  )
  .build();
```

What do you think about it that tsconfig customization is part of just such a programmatic API?

An example of what it could like is scripted in #470 

I'd like to hear what you think about i!

**Comment by alan-agius4** [comment]
I like the idea of having an API quite a lot,
As long as there is good documentation and the API is fluent and clean to
use.

I saw the example of the future usage with DI, I am not sure to be honest
if it would be the easiest and cleanest way for the API consumers. Maybe
cause I have never seen any API with DI used in Node, and really never
found a good turning point why I should and need to use DI in Node itself.

To overrite a single property in tsconfig I don’t think I’d want all the
boilerplating to set up a provider and stuff needed for the DI.

But I am interested in seeing what others think 😁

**Comment by DavidParks8** [comment]
The most important thing we must consider is making this feature as easy as possible to consume. As far as programmatic apis go, the fluent pattern is a good one that people find easy to use. That being said, we need to ask ourselves whether that is the "easiest" we can make it. The most common way people configure ng-packagr today is by using declarative json configuration. Personally, I think it is important that we continue to utilize that method because it will be the most familiar and thus initially consumable by the largest group of people.

Still, the fluent api is a fantastic idea, and I think it should be explored as a separate feature.

**Comment by paulsouche** [comment]
Hi,

Can't wait for this ! Could you please provide an example ?

Thank you anyway for the great job

**Comment by dherges** [comment]
Hi @paulsouche,

the rc-12 is published.

Can you build a sophisticated example how you'd like to use it?

**Comment by alan-agius4** [comment]
If i may ask, I’d very much like to know how can i specify
angularCompilerComptions, paths and ts compiler options such as baseUrl,
strickNull check etc...

The most important for me and people using mono repos and npm link is paths
and baseUrl.

**Comment by dherges** [comment]
Minimal usage example:

```ts
const customTsConfig: TsConfig = /* ... */;

ngPackagr()
    .withProviders([
      provideProject(opts.project)
    ])
    .withTsConfig(customTsConfig)
    .build();
```

You'll like to have a `.forProject(path: string)` alias for sure. And then also a `withTsConfig(value: string | TsConfig)` signature that either reads tsconfig from a file or takes it from the object, will be good for your side?

**Comment by alan-agius4** [comment]
That would be so awesome \m/

**Comment by jonathanbarton** [comment]
please add this to the readme :)

**Comment by villecoder** [comment]
@dherges 
How do you use the API?  I don't see a sample in the repository.  What tool are you using to execute the sample code?

**Comment by noelmace** [comment]
Trying to solve this issue (https://github.com/dherges/ng-packagr/issues/256#issuecomment-343417335) in [packagr-for-nx](https://github.com/noelmace/packagr-for-nx) by following @dherges comment https://github.com/dherges/ng-packagr/issues/256#issuecomment-360601173, I still get the following error : 

```
Building Angular Package
Building entry point '@foo/testing'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
libs/testing/src/rest.ts(3,34): error TS2307: Cannot find module '@foo/core'.

Error: libs/testing/src/rest.ts(3,34): error TS2307: Cannot find module '@foo/core'.

    at Object.<anonymous> (D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ngc\compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:37:60)
    at Generator.next (<anonymous>)
    at D:\git\perso\packagr-for-nx\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```
and I also ran into another (new) issue (https://github.com/dherges/ng-packagr/issues/589#issuecomment-376877211).

See https://github.com/noelmace/packagr-for-nx/commit/63ca240e9030011c318d31564342db05dc1f4310#diff-01994488c699366e7146092d8327cadaR27

**Comment by noelmace** [comment]
@villecoder look at https://github.com/dherges/ng-packagr/blob/v2.4.1/src/lib/ng-v5/packagr.ts for more infos about the programmatic API
About the tool, you'll simply have to write your own nodejs script.

**Comment by allenhwkim** [comment]
can't use cli for this purpose?

**Comment by allenhwkim** [comment]
Tried tsconfig.json with `path`, but did not work with API.

**Comment by Babeetlebum** [comment]
I am using the cli and setting up the programmatic API for this feature seems like a lot of hassle. I wish I could add a `ngPackage.lib.tsconfig` option in my package.json to override a few tsconfig options

My use case is working in a monorepo, I updated a package which added types to an unrelated library, the types got hoisted and are now included in (and failing) the compilation of my lib. To solve this I would like to specify the `compilerOptions.types` option in the tsconfig.json of ng-packagr

In the meantime I'm glad I have a working alternative; thanks for your work !
