### ISSUE TITLE
@ngx-translate

### ISSUE THREAD

**Issue by ovione** [dherges/ng-packagr#259]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description

In one of my librarires I use @ngx-translate
`
    "@ngx-translate/core": "7.1.0",
    "@ngx-translate/http-loader": "1.0.1"
`

I pack the library with **ng-packagr** and all goes well  but when I include it in my client application that has **ngx-translate** configured then I can't get the translations from inside my library.

The translations are in the client that is an angular-cli app and are in the assets/i18n/en.json | fr.json.

In my library I include the **@ngx-translate TranslateModule** like:

`
import {TranslateModule} from '@ngx-translate/core';
...
@NgModule({
  imports: [
      ...
      TranslateModule
`

I know in some way the library should pick up the TranslateModule that is configured in the client and pick the i18n json files and find the keys.

#### Expected Behaviour

The library should be able to translate keys like  {{'validation.required' | translate }} in one of its htmls and 
'validation.required' should be defined in the client of the library in the assets/i18n/en.json | fr.json files.

When I use it in submodule of my client I caan see the translations but not in a packed library.

If I find the answer I will update this post.

cheers
O

#### Version Information

```
@angular/cli: 1.2.7
node: 7.9.0
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.7
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
Hi, do you have a repro for the issue? Maybe a GitHub repo to checkout and reproduce the error?

**Comment by ovione** [comment]
I will try to make an example tomorrow.

thanks

**Comment by ovione** [comment]
hello thanks for waiting

I created a repo at [pack the translate as a lib](https://github.com/ovione/packagerwithtranslate)
you can clone it and there is a Readme explaining the problem.

But basically everything runs fine but when I pack it as a tarball it can't find the **TranslateService** from the ngr-translate framework.

If someone could give me some hints that would be very welcome.


thanks
O
PS: let me know if you need an extra information

**Comment by ovione** [comment]
did you manage to take a look, because maybe for some reason its not possible.
It would be nice if I could package it and that each client provide translation files.
So different clients that use the library could internationalize it for different languages depending on the client requirements.
But as you can see from my repo this is not possible.
Or maybe I'm missing someting.


cheers
O

**Comment by dherges** [comment]
Please check your `lib.externals`, see #129

**Comment by ovione** [comment]
hi @dherges 

yes the answer in #129 about ngx-translate worked
Like you mentioned I did include in
lib.externals the libraries 

```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "externals": {
      "@ngx-translate/core": "ngx-translate-core",
      "@ngx-translate/core/index": "ngx-translate-core"
     }
  }
}
```
and now I can find my first traslation **but** when I change the language I don't see the change.
Its stays in initial language.
Maybe you have an idea.
That would be the last thing that I need I guess.

thanks
:)

**Comment by dherges** [comment]
Sorry, this is best asked at StackOverflow or if it's an issue, at the ngx-translate repo.
