### ISSUE TITLE
Inline images from scss

### ISSUE THREAD

**Issue by mitsoe** [dherges/ng-packagr#263]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

When using background-image pointing to an url in a component that is exported the scss is not inlined. This results in not being able to find the image when including the component in a different project.

#### Expected Behaviour

The images are inlined (or a different way to show them) in a consumer module.

#### Version Information

```
ng-packagr: v1.4.1
node: v8.x.y
@angular: v4.2.4
rxjs:5.4.2
zone.js:0.8.14
```

**Comment by dherges** [comment]
A pull request for that would be welcome!

It should support a syntax so that I - as a developer - can decide whether to embed the resource with a `data:` or whether to retain the original url.
