### ISSUE TITLE
[Angular 5] `ng serve` works; `ng build -prod` gives ERROR in Error:[…] add a @NgModule annotation

### ISSUE THREAD

**Issue by SamuelMarks** [dherges/ng-packagr#266]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Upgraded to Angular 5 then my [ng-gauge](https://github.com/glaucoma-australia/ng-gauge) component stopped working. So I started using ng-packagr; which made `ng serve`—and my application—work perfectly. Unfortunately `ng build -prod` doesn't work anymore. I've also tried adding the `--preserve-symlinks` argument.

#### How To Reproduce

Add [ng-gauge](https://github.com/glaucoma-australia/ng-gauge) to your dependencies, use it somewhere, now the error is reproduced.

#### Expected Behaviour

`ng build -prod` should produce compiled minified distribution files like it did with Angular 4.

#### Version Information

```
ng-packagr: v1.5.0
node: v8.9.0
@angular: v5.0.1
rxjs: 5.5.2
zone.js: 0.8.18
```

**Comment by dherges** [comment]
Hi, thanks for your report.

I consider this an angular 5 migration task. Is that right?

There will be changes and a new version for angular 5 .... “soon” like next week or in two weeks time. I’m asking to be patient for that. 

Do you have a GitHub repo or similar with the sources? I am also trying to understand what is not working ... 
- is the library no longer compiling with ng@5 peerDeps?
- can the library be compiled, but the binaries no more be imported into an ng cli app in version5?
- can binaries with ng@4 peerDeps not be imported into ng cli app with version 5?

Cheers, David

**Comment by SamuelMarks** [comment]
Dropped you a demo:
https://github.com/SamuelMarks/ng-gauge-demo

Angular 4 I didn't need ng-packagr; I just had the .ts files included and it all worked fine. Upgrading to Angular 5 that stopped working, someone suggested ng-packagr so that's where I am.

**Comment by dherges** [comment]
Can you check whether the issue persists with the [1.6.0-rc.0](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#160-rc0-2017-11-10)?

**Comment by SamuelMarks** [comment]
Exact same error in 1.6.0-rc.0 (just tried).

**Comment by fourctv** [comment]
I came to ng-packagr for the same reasons. Using angular 5.0.3  and it builds the library and publishes it fine.
Where I'm having problems is on the app side, where I use my library. It builds fine for testing, `ng build`, but I cannot build for production `ng build --prod --aot`, I get loads of errors stating it cannot find components in my library!

Library is at: https://github.com/fourctv/JS44D

The library build shows the following warnings:
```
Building Angular library
Generating bundle for js44d
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
'default' is not exported by 'node_modules/rxjs/add/operator/toPromise.js'
Compiling to FESM5
Compiling to UMD
Minifying UMD bundle
Converting duplicated definition of variable id to assignment [0:3967,33]
Dropping duplicated definition of variable trial [0:4968,16]
Dropping duplicated definition of variable iterator$$2 [0:10891,16]
Side effects in initialization of unused variable _trailingValue [0:23651,53]
Side effects in initialization of unused variable _hasTrailingValue [0:23651,89]
Side effects in initialization of unused variable _trailing [0:23651,131]
Converting duplicated definition of variable i to assignment [0:25525,17]
Side effects in initialization of unused variable document$1 [0:2338,4]
Side effects in initialization of unused variable location [0:2339,4]
Side effects in initialization of unused variable gc [0:2340,4]
Side effects in initialization of unused variable performance [0:2341,4]
Side effects in initialization of unused variable Event [0:2342,4]
Side effects in initialization of unused variable MouseEvent [0:2343,4]
Side effects in initialization of unused variable KeyboardEvent [0:2344,4]
Side effects in initialization of unused variable EventTarget [0:2345,4]
Side effects in initialization of unused variable History [0:2346,4]
Side effects in initialization of unused variable Location [0:2347,4]
Side effects in initialization of unused variable EventListener [0:2348,4]
Side effects in initialization of unused variable rxSubscriber_1 [0:5114,4]
Side effects in initialization of unused variable rxSubscriber_2 [0:5115,4]
Side effects in initialization of unused variable observable_1 [0:5422,4]
Side effects in initialization of unused variable observable_2 [0:5423,4]
Side effects in initialization of unused variable observable_3 [0:5424,4]
Side effects in initialization of unused variable iterator_1 [0:6946,4]
Side effects in initialization of unused variable iterator_2 [0:6947,4]
Side effects in initialization of unused variable iterator_3 [0:6948,4]
Side effects in initialization of unused variable RefCountSubscriber [0:19575,4]
Side effects in initialization of unused variable throttle_2$2 [0:23679,4]
Side effects in initialization of unused variable throttle_3$1 [0:23680,4]
Side effects in initialization of unused variable TestScheduler$1 [0:25938,4]
Side effects in initialization of unused variable animationFrame_1 [0:26314,4]
Side effects in initialization of unused variable throttle$3 [0:26315,4]
Side effects in initialization of unused variable Symbol [0:26329,4]
Remapping source maps
Copying staged files
Writing package metadata
Built Angular bundle for js44d
Built Angular library from /js44D, written to /js44D/dist
```

And when I use it in my app, and try `ng build --prod`, I get something like this:
```
      looking for modules in /Best Flex/BestClientesJS/src
        using description file: /Best Flex/BestClientesJS/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Best Flex/BestClientesJS/package.json (relative path: ./src)
          using description file: /Best Flex/BestClientesJS/package.json (relative path: ./src/js44d/src/js44D/index)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Best Flex/BestClientesJS/src/js44d/src/js44D/index doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Best Flex/BestClientesJS/src/js44d/src/js44D/index.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Best Flex/BestClientesJS/src/js44d/src/js44D/index.js doesn't exist
            as directory
              /Best Flex/BestClientesJS/src/js44d/src/js44D/index doesn't exist
```
_repeated a ton of times_


**FYI**, `ng serve` or `ng build` work fine and produce perfect builds! oh, and the library also works fine in NativeScript.

**Versions**:
```
ng-packagr: v1.6.0
node: v8.9.1
@angular: v5.0.3
rxjs: 5.5.2
zone.js: 0.8.18
typescript: 2.6.1
```

**Comment by azizantoun** [comment]
Facing the exact same issue as @fourctv when trying to use --prod which is mandatory in order to have smaller files. 

Any suggestion?

**Comment by fourctv** [comment]
@azizantoun I managed to solve it here by modifying `public_api.ts`. In my previous version I had it simply import `index.ts` files in my folders. I replaced those references by directly exporting my components and services, and got rid of all the `index.ts` files.

So, my `public_api.ts` now looks like this:
```
export { fourDModule } from './src/fourD.module';
export { JS44DModule } from './src/js44D.module';
export { ModalModule } from './src/modal.module';

export { FourDInterface, FourDQuery, MD5 } from './src/js44D/JSFourDInterface';
export { FourDModel } from './src/js44D/JSFourDModel';
export { FourDCollection } from './src/js44D/JSFourDCollection';
export { QueryBand, CustomButtonBarDirective, QueryBandDirective } from './src/containers/queryBand';
export { AdvancedQueryComponent } from './src/containers/advancedQuery';
export { RecordList } from './src/containers/recordList';
export { RecordEditWindow } from './src/containers/recordEditWindow';
export { Tabs, Tab } from './src/containers/tabs';
export { WebAppContainer } from './src/containers/webAppContainer';
export { FourDDropDown } from './src/controls/fourDDropDown';
export { QuickFindInput } from './src/controls/quickFindInput';
export { DataGrid } from './src/dataGrid/dataGrid';
export { LoginCmp } from './src/login/login';
export { ListSelectorDialog } from './src/dialogs/listSelectorDialog';

export { ICustomModal } from './src/angular2-modal/models/ICustomModal';
export { ICustomModalComponent } from './src/angular2-modal/models/ICustomModalComponent';
export { ModalConfig } from './src/angular2-modal/models/ModalConfig';
export { ModalDialogInstance } from './src/angular2-modal/models/ModalDialogInstance';
export { Modal } from './src/angular2-modal/providers/Modal';
export { OKOnlyModal, OKOnlyContent } from './src/angular2-modal/commonModals/okOnlyModal';
export { YesNoModal, YesNoModalContent } from './src/angular2-modal/commonModals/yesNoModal';
```

And that is the only file exporting my components in my module.

hth
julio

**Comment by dhakehurst** [comment]
I managed to fix simmilar issue with an npm upgrade,
angular 5.1.0
rxjs 5.5.5
typscript 2.6.2

etc

**Comment by SamuelMarks** [comment]
Still doesn't work. Just tried with:
`npm` 5.5.1
`node` 8.9.3
`@angular/cli` 1.6.1
`@angular/*` 5.1.1
`ng-packagr` 1.6.0

**Comment by mhdSid** [comment]
When using **ng-packagr** to publish a repository, the repo's root directory shouldn't contain any **dist/** directory, which means that all the final` js,umd,es5.js` files should exist on the root directory of the published repository.
Suppose you have a repository named **myRepo**, then the final hierarchy should be similar to this:
```
---myRepo
---------myRepo.js
---------myRepo.es5.js
---------bundles/
---------src/ (contains definition files for components, services, etc)
```

When using **myRepo** in any other project, that is the case here, all the imports should be similar to this:
```
import {myService} from 'myRepo'
import {myModule} from 'myRepo'
```
