### ISSUE TITLE
Problem in a multiple library repo: can't inter-depend on each other

### ISSUE THREAD

**Issue by crowmagnumb** [dherges/ng-packagr#275]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If I create a repo made of two libraries for which one depends on the other I can't figure out how to package the one that depends on the other. I get the error shown below.

#### How To Reproduce

I have a repo setup [here](https://github.com/animalus/au-ng). The libraries are in the packages folder. Note that ng-date-utils depends on ng-utils. But I get this error trying to package ng-date-utils.

```
cuervomovil:au-ng ken$ node_modules/.bin/ng-packagr -p packages/ng-date-utils/ng-package.json
Building Angular library
Generating bundle for @animalus/ng-date-utils
Cleaning bundle build directory
Processing assets
Running ngc

BUILD ERROR
Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/src/dateUtils.service.ts:10:27: Cannot find module '../../ng-utils/public_api'.
Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/src/module.ts:4:23: Cannot find module '../../ng-utils/public_api'.
Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/ng-date-utils.ts:7:45: Cannot find module '../ng-utils/public_api'.
Error: Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/src/dateUtils.service.ts:10:27: Cannot find module '../../ng-utils/public_api'.
Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/src/module.ts:4:23: Cannot find module '../../ng-utils/public_api'.
Error at /Users/ken/dev/animalus/au-ng/packages/ng-date-utils/.ng_pkg_build/@animalus-ng-date-utils/ts/ng-date-utils.ts:7:45: Cannot find module '../ng-utils/public_api'.
    at new UserError (/Users/ken/dev/animalus/au-ng/node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/src/tsc.js:27:28)
    at check (/Users/ken/dev/animalus/au-ng/node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/src/tsc.js:93:15)
    at Tsc.typeCheck (/Users/ken/dev/animalus/au-ng/node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/src/tsc.js:173:9)
    at /Users/ken/dev/animalus/au-ng/node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/src/main.js:122:23
    at <anonymous>
```

#### Expected Behaviour

_please describe what behaviour or result you expected_

#### Version Information

```
ng-packagr: v1.x.y
node: v8.x.y
@angular: v4.x.y
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by deebloo** [comment]
@crowmagnumb you need to use npm link or yarn link. you also need to make sure to package them in the correct order. so for example.
```
ng-packagr -p packages/lib-a
npm link packages/lib-a/dist
ng-packagr -p packages/lib-b
```

**Comment by crowmagnumb** [comment]
Thank you! It doesn't work exactly like that. I had to do both parts of the linking process. In your nomenclature...

```
cd packages/lib-a/dist
yarn link
cd ../../..
yarn link lib-a
```
...which for my repo was solved with the following scripts in the package.json...

```
    "build:utils": "ng-packagr -p packages/ng-utils/package.json && cd packages/ng-utils && yarn link && cd ../.. && yarn link @animalus/ng-utils",
    "build:date-utils": "ng-packagr -p packages/ng-date-utils/package.json",
    "build": "yarn run build:utils && yarn run build:date-utils"
```

I also found out the hard way (in that it took me a while to find out why it wasn't working) that you can't mix ```npm link``` and ```yarn link``` commands as they use different global directories to store the links in!

Thanks!

**Comment by crowmagnumb** [comment]
This is back to not working again with updated code. :( The repo linked to above fails on the building of the dependent repo with the following message ...

```
Cannot find module '@animalus/ng-utils'.
```

Any help would be greatly appreciated as this is critical to me going forward with this library system.  :)

**Comment by crowmagnumb** [comment]
OK, my bad. Sorry. You know how you set up automation, then come to rely on it, and then not really pay attention to it because well it's all automated right? Well, I just did that. I had automated the linking of the package after building, but then I later moved the location of where the package gets built to but did not update the linking code. So it kept linking to the old place and I didn't notice. Sorry, this still works. Closing again....

**Comment by dherges** [comment]
These kinda happens!

**Comment by eromano** [comment]
Hi guys is possible avoid the use of link? 

i find out a plugin for rollup that could avoid this thing:

https://www.npmjs.com/package/rollup-plugin-paths

but I am not sure if there is a way to include plugin in ng-packagr

**Comment by mezoistvan** [comment]
This can be achieved without linking the packages, as described in https://github.com/dherges/ng-packagr/issues/256

**Comment by benjamincharity** [comment]
@mezoistvan are there any examples of this new functionality in use? I can't seem to find any.. I am trying to accomplish the same type of structure as Angular Material:

```typescript
// Can import everything from the root:
import { FooModule, BarModule, BazModule } from '@my/lib';

// OR from individual entry points:
// FooModule imports BazModule
import { FooModule } from '@my/lib/foo';
// BarModule imports FooModule & BazModule
import { BarModule } from '@my/lib/bar';
```

The issue I'm having is during the build, modules can't be found. When `BarModule` imports other entrypoints, do I use relative paths (`./../foo/module.ts`) or 'library' paths (`@my/lib/foo`)?

**Comment by brunano21** [comment]
@mezoistvan can you adjust the link? I'm not finding an example...how can we avoid to use `npm link`?
@dherges any documentation on this?

**Comment by mezoistvan** [comment]
Using the programmatic API, we are able to package the libraries in order, and during the packaging we are able to use the already packaged libraries. Something like:

```
await ngPackagr()
    .project('/usr/local/lib-1/package.json')
    .withTsConfig(customTsConfig)
    .build();

await ngPackagr()
    .project('/usr/local/lib-2-that-depends-on-lib-1/package.json')
    .withTsConfig(customTsConfig)
    .build();
```

**Comment by brunano21** [comment]
@mezoistvan where should I put the snippet you show here?

**Comment by abbazabacto** [comment]
@mezoistvan awesome that the API opens up the possibility for dependencies for a multi-library repo.

How would this work for **Secondary Entry Points**, it seems like an overkill to have to suddenly add a full `package.json` for each entry point. NPM also doesn't allow the name property to be like `@angular/material/button`.

Would be great if we can make **Secondary Entry Points** depend on each other. If there is already a way, would love to know how I could achieve this...

Thanks in advance!

**Comment by crowmagnumb** [comment]
@fetis This issue is closed. It works fine now.

**Comment by fetis** [comment]
@crowmagnumb I have this issue with new Angular v6. Shall I create the new one?

**Comment by crowmagnumb** [comment]
I suppose. Do you have a repo that recreates it?
