### ISSUE TITLE
Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by crowmagnumb** [dherges/ng-packagr#276]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If I package a library using ng_packagr and try to use it in another project I get the following.

```
client  WARNING in ./node_modules/@animalus/ng-utils/@animalus/ng-utils.es5.js
client  Module not found: Error: Can't resolve './locale' in '/Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/@animalus'
client  resolve './locale' in '/Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/@animalus'
client    using description file: /Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/package.json (relative path: ./@animalus)
client      Field 'browser' doesn't contain a valid alias configuration
client    after using description file: /Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/package.json (relative path: ./@animalus)
client      using description file: /Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/package.json (relative path: ./@animalus/locale)
client        as directory
client          /Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/@animalus/locale doesn't exist
client  [/Users/ken/dev/animalus/idservices/whaleid-server/client/node_modules/@animalus/ng-utils/@animalus/locale]
client   @ ./node_modules/@animalus/ng-utils/@animalus/ng-utils.es5.js 1693:12-46
client   @ ./src/app/app.module.ts
client   @ ./src/main.ts
client   @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

#### How To Reproduce

I have a repo [here](https://github.com/animalus/au-ng) that after building to ```dist/ng-utils``` I try to add it to another project using yarn such that my ```package.json``` contains the line ...

```"@animalus/ng-utils": "file:../../../au-ng/dist/ng-utils",```

... which seems to work fine as all IDE happy with imported code. But when running ```ng serve``` I get the above.

#### Expected Behaviour

_please describe what behaviour or result you expected_

#### Version Information

```
ng-packagr: v1.x.y
node: v8.x.y
@angular: v4.x.y
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by crowmagnumb** [comment]
I also noticed, and this might be related, that the rxjs library (Observable, Subscription, etc.) is getting sucked into the final bundle making the bundle 850K.

Sorry, I also didn't fill out the above versioning since I included the repo but here that info is...

ng-packager: 1.5.0
node: v8.2.1
@angular: v5.0.1
rxjs: v5.5.2
zone.js: v0.8.18

**Comment by crowmagnumb** [comment]
I found my issue. I was importing rxjs stuff like this...

```
import {ReplaySubject, Subscription} from 'rxjs';
```

... instead of ...

```
import {ReplaySubject} from 'rxjs/ReplaySubject';
import {Subscription} from 'rxjs/Subscription';
```

...and the globals are not set up to ignore just 'rxjs' but rather all of the sub bits. Writing it the latter way works.

**Comment by dherges** [comment]
Hi @crowmagnumb,

cool you figured it out!

The `import ... from 'rxjs'` isn't really recommended afaik. Because of that it's being left out of the default rollup config. There could/should be a warning ... may codelyzer / tslint have a rule for that?!?
