### ISSUE TITLE
Feature parity to angular-cli: `stylePreprocessorOptions.includePaths`

### ISSUE THREAD

**Issue by ClemensSchneider** [dherges/ng-packagr#282]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

First let me say a big thank you for your work!

Angular-cli allows to add include-paths for the style-preprocessor in use:

```
      "stylePreprocessorOptions": {
        "includePaths": [
          "styles"
        ]
      },
```

In the scss / less files, you don't have to provide the complete relative path to an import.

#### How To Reproduce

Add the includePath to angular-cli.json and add an import to a file in your styles-folder without specifying the complete relative path.

#### Expected Behaviour

As angular-cli itself resolves the import correctly, ng-packagr should do it, too.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.7.0
@angular: v5.0.0
```

**Comment by dherges** [comment]
Hi @ClemensSchneider,

sounds like a good idea!

Let's please wait for #279 and then further discuss how this can be included.

**Comment by michieldejong** [comment]
+1, I need this as well :-)

**Comment by mrunal-patel** [comment]
+1, I would love to see this resolved :) Have to use workaround for the issue right now.

**Comment by falkop** [comment]
This feature would be great:)
@mrunal-patel :  I assume that the "workaround" is using the fullpath to the imported file?

**Comment by mwootendev** [comment]
I too had to workaround this issue. Using relative paths works, but there are a lot of SCSS files to update. I was able to update assets.js and add `includePaths: ['my/path/to/scss']` to the `renderSass` call parameters in `renderPreProcessor`. Obviously this was a hard-coded workaround for this case, but it would be fairly simple to add an option in ng-package.json that could be used to populate that field. Maybe a `"sassIncludePaths"` property under the `"lib"` element?

It looks like #279 is now closed. Can this be worked?

**Comment by dherges** [comment]
Hi all,

a feature option for scss (see #494) is now implemented. Thanks to @mwootendev!

Cross-checking the CLI's implementation: it passes the custom paths to all three preprocessor (scss, stylus, less) [1] [2] [3]


[1]: https://github.com/angular/angular-cli/blob/7352bcbcabe976b82b651fbd4b251fbbfebe2ba4/packages/%40angular/cli/models/webpack-configs/styles.ts#L172

[2]: https://github.com/angular/angular-cli/blob/7352bcbcabe976b82b651fbd4b251fbbfebe2ba4/packages/%40angular/cli/models/webpack-configs/styles.ts#L189

[3]: https://github.com/angular/angular-cli/blob/7352bcbcabe976b82b651fbd4b251fbbfebe2ba4/packages/%40angular/cli/models/webpack-configs/styles.ts#L145-L147

A generified solution looks like a good idea to me! For the moment, I'd say that mimicking `lib.stylePreprocessorOptions.includePaths` in `ngPackage` is the way to go! Should one of you come across with a PR, it'll be feature-parity with the CLI.

Other ideas or thoughts?

**Comment by picheli20** [comment]
@dherges it will be good to add it on the `ng-package.json` as well, only only on `ngPackage`

Here we've the `src/scss` folder that I includes on `.angular-ci.json` (angular`"includePaths": ["./scss"]`) and the scss files are including just `@import 'variables';`.

Basically I get a error while building the packaged cause of the path `File to import not found or unreadable: variables.`

**Comment by picheli20** [comment]
I'm getting a error while trying to include:
```
```

**Comment by picheli20** [comment]
@dherges really nice feature!
But I think it could get the default configuration dynamically from `.angular-cli.json`, since without that the project will not build.

**Comment by mlc-mlapis** [comment]
@picheli20 ... it is not directly joined with CLI, `ng-packagr` has to work as a standalone tool.

**Comment by mrunal-patel** [comment]
Thank you @dherges for providing the fix for this issue. It works perfectly now !

**Comment by satjai1** [comment]
Is this available for less files?

**Comment by alan-agius4** [comment]
Yes
