### ISSUE TITLE
How to prevent inlining Stylesheets?

### ISSUE THREAD

**Issue by F1oyd** [dherges/ng-packagr#283]
## Type of Issue

```
[ ] Bug Report
[*] Feature Request
```

## Description

Is there any beautiful way to avoid inlining css styles during build?

#### Version Information

```
ng-packagr: v1.5.1
```

**Comment by dherges** [comment]
No. There isn't any. Neither a beautiful nor a ugly way. Not inling a component's `stylesUrl` is contrary to [Angular Package Format])https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit)

> Component libraries are typically implemented using stylesheets and html templates stored in separate files. While it's not required, we suggest that component authors inline the templates and stylesheets into their FESM files as well as *.metadata.json files by replacing the stylesheetUrls and templateUrl with stylesheets and template metadata properties respectively. This simplifies consumption of the components by application developers.

**Comment by guilhermevrs** [comment]
Hi @dherges 
I understand your point, but while reading the APF again, it's clearly stated that it's not required. It's a suggestion.
Why not leaving that to the library's author to decide? The inlining could even be the default, but an option to disable it.
