### ISSUE TITLE
Metadata for angular services injected into component constructor are getting not resolved(metadata is not generated for those params).

### ISSUE THREAD

**Issue by Sudheer-Reddy** [dherges/ng-packagr#286]
## Type of Issue

```
[Bug] - Metadata for services injected as constructor params are not generated.
```

## Description
I've created a service say 'UtilService' and declared as providers: [UtilService] in my module decorator. Later point of time i was using the service in my component constructor function as
```
constructor(private _utils: UtilService) {}
```
This works fine when i build and run my app. But when i generate a umd file using ng-packagr. I'm getting a error `Can't resolve all parameters of X component`

#### How To Reproduce
1. Create a Angular4 injectable service X service.
2. Declare it in providers array for X Module.
3. Create a component X Component with service injected in constructor as shown above.
![screen shot 2017-11-16 at 10 09 47 am](https://user-images.githubusercontent.com/11575352/32874141-596eae2e-cab6-11e7-86d8-9a64f23b8160.png)

4. Now run ng-packagr, runs fine and generates umd bundle.

But when we use that umd file in some other app which uses X module and its components. It throws an error.

So i went ahead and analyzed the generated umd file. This is what the metadata generated for the constructor param
![screen shot 2017-11-16 at 10 23 24 am](https://user-images.githubusercontent.com/11575352/32874433-360186e4-cab8-11e7-98cd-a7a5f5d5c505.png)

But if we see the angular generated file using ng build. It also contains one more metadata _param as shown below.
![screen shot 2017-11-16 at 10 21 59 am](https://user-images.githubusercontent.com/11575352/32874442-4d4ed892-cab8-11e7-9de8-05887e12967d.png)

So i thought that it might be something to do with Inject, which we won't do and follow the shorthand way that is private _util: UtilService which angular will take care of injecting the service as well as creating a private property on the component. So i've used the long way that is
@Inject(UtilService) private _util: UtilService. 

Then only it worked. 
![screen shot 2017-11-16 at 10 31 05 am](https://user-images.githubusercontent.com/11575352/32874589-49e151c0-cab9-11e7-8078-2dcf1bbebcd9.png)

Can we fix this because writing @Inject for one service is ok, but if may come to the scenario where we inject so many service, for which writing @Inject will look clumsy. 

#### Version Information

```
ng-packagr: 1.6.0-rc.0
node: v6.9.4
@angular: v5.0
```

**Comment by dherges** [comment]
Ah, yes. We've seen similar stuff in other projects a few days ago ... Please check your TypeScript version! Which `tsc` version do you use in your project? For Angular v4 it should be a 2.3.x, for Angular v5 a 2.4.x

Can you please upgrade to `ng-packagr@1.6.0` and then `node_modules/.bin/tsc --version`?

**Comment by Sudheer-Reddy** [comment]
Updated `ng-packagr` to `1.6.0`. Now the way of umd code generation has changed, and no longer throws error. Thanq :)
