### ISSUE TITLE
Change output location

### ISSUE THREAD

**Issue by dhakehurst** [dherges/ng-packagr#287]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

I want to be able to change the default output location of 'dist'.
to '../../../build/dist'

#### Expected Behaviour

I would expect something in the ng-package.json file,
or that it is picked up from the .angular-cli.json file.

#### Version Information

```
ng-packagr: latest
node: latest
@angular: latest
```

**Comment by JoostK** [comment]
There is a `"dest"` option you can specify in your ng-package.json file, see [the JSON schema](https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json)
