### ISSUE TITLE
missing loader support

### ISSUE THREAD

**Issue by JanEggers** [dherges/ng-packagr#289]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

i use the following code to load localization:

```
let translationsDe = require(`raw-loader!../translations/ui.de.xlf`);
```

if i ng build the xliff is included in the generated app but if i npm run packagr it is not included in the bundle.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.7.0
@angular: v5.0.0
rxjs: 5.4.2
zone.js: 0.8.14
```

**Comment by JanEggers** [comment]
tried another syntax:

import translationsDe from 'raw-loader!./../translations/template.de.xlf';

again ng build works, packagr does not:

error message is: cannot find module raw-loader!./../translations/template.de.xlf

**Comment by deebloo** [comment]
ng-packagr does not use webpack so no you won’t be able to use any webpack loaders

**Comment by JanEggers** [comment]
why? i thought it uses ngc and that uses webpack? the big feature of this lib was described as take your angular cli project and make a npm package from it.

**Comment by dherges** [comment]
No. ngc and webpack are two independent tools. The cli uses webpack and - afaik - invokes ngc thru a loader.

Cheers, David

**Comment by deebloo** [comment]
yup david is correct. the CLI uses webpack under the hood but it isn't exposed.

**Comment by JanEggers** [comment]
oki the i have to come up with something else to load stuff

**Comment by deebloo** [comment]
good luck!

**Comment by zakhenry** [comment]
@JanEggers / @deebloo is there any known workarounds for this? I have the same issue - using `require()` & raw loader with angular cli, but ng-packagr doesn't work.

For context I am loading GLSL shaders for webgl, and need to assign them to the webgl framework I am using.

Normally this looks like
```ts
import * as stockFragmentShader from 'raw-loader!./stock.frag';
import * as stockVertexShader from 'raw-loader!./stock.vert';

// omitted for brevity

    Effect.ShadersStore['StockPixelShader'] = stockFragmentShader as any;
    Effect.ShadersStore['StockVertexShader'] = stockVertexShader as any;
```

**Comment by zakhenry** [comment]
raised #514 to continue the conversation

**Comment by kiranjholla** [comment]
@JanEggers Have you found any way to load stuff while using ng-packagr?

I am trying to deploy an Angular library which makes use of the `worker-loader` loader to load a script that would be run in a web-worker. However, given the lack of support for loaders, this fails build.

Is there another way to run web-workers from an Angular library? I am already aware of the possibility of running the entire Angular app in a worker, but that is not what I am looking for.
