### ISSUE TITLE
'deflate' is not exported by node_modules\pako\dist\pako_deflate.js

### ISSUE THREAD

**Issue by skorunka** [dherges/ng-packagr#301]
## Type of Issue

```
[x] Support Request
```

## Description

After running `npm run packagr` I get this error

```
PS C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter> npm run packagr

> eyc.control.grid-filter@2.0.0 packagr C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter
> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for eyc.control.grid-filter
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15

BUILD ERROR
'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
Error: 'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
    at error (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:16526:3)
    at Module.trace (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:16623:10)
    at ModuleScope.findVariable (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:13965:22)
    at Node._bindVariableIfMissing (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:12626:31)
    at Node.bindNode (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:12621:8)
    at Node.bind (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:11005:8)
    at eachChild.child (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:11024:34)
    at keys.forEach.key (C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\rollup\dist\rollup.js:11041:5)
    at Array.forEach (<anonymous>)
```

#### Version Information

```
ng-packagr: v1.6.0
node: v8.7.0
@angular: v5.0.2
rxjs: 5.5.2
zone.js: 0.8.18
```

_please include any version information that might be relevant, e.g. other third-party libraries_

Is it a problem with `pako` package?

Thank you.

**Comment by skorunka** [comment]
When I run `ngc -p tsconfig.json` as npm script, it works. I get output in `dist` folder.

**Comment by DavidParks8** [comment]
That makes sense because the compilation failed after ngc was already done. The step `Compiling to FESM15` actually is rollup trying to compile to es2015 flat modules. Since pako uses `module.exports`, my guess would be that you need to include the correct rollup external for it. 

My first try for an external configuration would be:
```json
{
  "lib": {
    "externals": {
      "node_modules/pako/dist/pako_deflate.js": "pako"
    }
  }
}
```

**Comment by skorunka** [comment]
@DavidParks8 Thank you for reply. I'm sorry, but I'm quite new to this npm world, where (in which file) should I pus the above snippet? Thank you.

**Comment by skorunka** [comment]
This is how the library I have in `peerDependencies` is using pako deflate: 
```
import { deflate as pakoDeflate } from 'pako/dist/pako_deflate';

export var deflate = pakoDeflate;

export function supportsDeflate() {
    return true;
}
```

**Comment by skorunka** [comment]
Same problem reported here https://github.com/telerik/kendo-angular/issues/748
Anyways, updating `externals` did not help to me. I trie:
- `"node_modules/pako/dist/pako_deflate.js": "deflate"`
- `"node_modules/pako/dist/pako_deflate.js": ["deflate"]`
- `"node_modules/pako/dist/pako_deflate.js": "pako"`
- with `node_module` or without it

**Comment by DavidParks8** [comment]
You've put the setting in the correct location. Now that I see your import path, I'd like you to try it again, but this time, use `"pako/dist/pako_deflate": "pako"`. Tell me if it works.

**Comment by DavidParks8** [comment]
You also might need to change your import to be:

```ts
import * as pakoImport from 'pako/dist/pako_deflate';
// note that I'm specifically not using "pako" as the import alias

export const deflate = pakoImport.deflate;
```

**Comment by skorunka** [comment]
Hi, I cannot change imports, it is 3th party library (@progress/kendo-drawing), which is using `pako`.
Anyways, this `"pako/dist/pako_deflate": "pako"` helped and now I don't get that error, but:

The `Compiling to FESM15` takes very long time to run and it ends with this error:

```
Compiling to FESM15

<--- Last few GCs --->

[1436:00000160DA6DD9E0]   228426 ms: Mark-sweep 1409.7 (1568.1) -> 1409.7 (1568.1) MB, 1675.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001C084FA5E71 <JSObject>
    1: decode(aka decode) [C:\Projects\EYC\SDK\Eyc.Sdk.Ui\eyc.control.grid-filter\node_modules\sorcery\dist\sorcery.cjs.js:~99] [pc=000002E429654104](this=00000002AE302311 <undefined>,mappings=000000667C74A339 <String[477]: AAAA,eAAe,SAAS,oBAAoB,CAAC,MAAM,EAAE,EAAE,EAAE,EAAE,EAAE,MAAM,EAAE;IACjEA,GAAG,CAAC,QAAQ,GAAG,CAAC,CAAC;IACjBA,GAAG,CAAC,QAAQ,GAAG,CAAC,CAAC;;IAEjB,IAAI,MAAM,EAAE;QACR,QAAQ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! eyc.control.grid-filter@2.0.0 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the eyc.control.grid-filter@2.0.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skoru\AppData\Roaming\npm-cache\_logs\2017-11-22T19_15_35_250Z-debug.log
```
There is a `.ng_pkg_build` folder:
![image](https://user-images.githubusercontent.com/218913/33145931-23b9f578-cfba-11e7-89c2-2d9e6e35c311.png)

I just wonder, why it does not only contains the content from `lib` folder, where the library code is. I probably might have something to do with the above problem. Thank you very much!

**Comment by skorunka** [comment]
./index.ts:
`export * from './src/lib/gridFilter/';`

./src/lib/gridFilter/index.ts:
```
export * from './gridFilter.module';

export * from './components/gridColumnFilter.component';
export * from './components/gridFilter.component';

export * from './models/';

export * from './services/gridFilterApi.service';

export * from './productsHierarchy/';
export * from './storesHierarchy/';
```

**Comment by fourctv** [comment]
I have a very similar situation in my module, but in my case I'm using `base64.js`, and the message I get is:
` 'encode' is not exported by 'node_modules/base64.js'`.
In `base64.js` the function `encode` is declared as `var encode = function...`.

The resulting bundle code ends up being `_undefined_(value)`...

The code where I use it in my module looks something like this:
```
import * as base64 from 'base-64';
...
let foo = base64.encode('bar');
```

The resulting bundle code ends up being:
```
var foo = undefined('bar');
```

Is there a property, configuration, I can set in `ng-package.json` to deal with that kind of situation?

FYI, `ngc` works fine, I can build and publish my library fine, except it does not work if I try to AOT my app.

**Comment by skorunka** [comment]
@fourctv What helped to me was to edit `ng-package.json` and add external library mapping:
```
{
	"$schema": "./node_modules/ng-packagr/ng-package.schema.json",
	"lib": {
		"entryFile": "index.ts",
		"externals": {
			"pako/dist/pako_deflate": "pako" // <-- MAPPING
		}
	}
}
```

You need to figure out the mapping `key` and `value`...

**Comment by DavidParks8** [comment]
You'll need the proper externals config to deal with base-64. That should be `"base-64": "base64"`.

**Comment by DavidParks8** [comment]
I would recommend making the third party library that uses pako an external instead of pako itself. The idea being: anything external to your code that is used directly by your code should not be bundled with it. Instead, such a library should be configured as an external, and added as a peerDependency in your library package.json.

**Comment by DavidParks8** [comment]
The last time I saw the sorcery error, it had to do with a bug in the source maps of the library I was trying to reference. You might be out of luck with that one. Can you provide a git repo to help troubleshoot?

**Comment by dherges** [comment]
Hi, from looking at their `dist` stuff on the github repo: they register everything with `pako` on the global scope ...

... https://github.com/nodeca/pako/blob/master/dist/pako_deflate.js
... https://github.com/nodeca/pako/blob/master/dist/pako.js
... https://github.com/nodeca/pako/blob/master/dist/pako_inflate.js


So your config should, in theory, be:

```ts
import { stuff }  from `pako/foo/bar`
import { stuff }  from `pako/bla/blubb`
```

```
   "pako/foo/bar": "pako"
   "pako/bla/blubb": "pako"
```

**Comment by seanrowe** [comment]
I'm having this issue

`{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "name": "@instec/sm-lib-shared-fe",
    "version": "0.0.13",
    "ngPackage": {
        "lib": {
            "entryFile": "public_api.ts",
            "externals": {
                "pako/dist/pako_deflate": "pako"
            }
        }
    }
}
`

> BUILD ERROR
'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
Error: 'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
    at error (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:16526:3)
    at Module.trace (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:16623:10)
    at ModuleScope.findVariable (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:13965:22)
    at Node._bindVariableIfMissing (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:12626:31)
    at Node.bindNode (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:12621:8)
    at Node.bind (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:11005:8)
    at eachChild.child (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:11024:34)
    at keys.forEach.key (D:\smlibsharedfe\sm-lib-shared-fe\node_modules\rollup\dist\rollup.js:11041:5)
    at Array.forEach (<anonymous>)

**Comment by Kalemstorm94** [comment]
Hello @skorunka. How did you resolve the `Compiling to FESM15` time? This is my ng-package.json: 

`{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "pako/dist/pako_deflate": "pako"
    }
  }
}`. I don't understand what have you done to get it work...

**Comment by skorunka** [comment]
@Kalemstorm94 Hi, actually adding that mapping helped: `"pako/dist/pako_deflate": "pako"`

**Comment by Kalemstorm94** [comment]
After I add the mapping, it remains in `Compiling to FESM15` a long time and them it says  ```
Compiling to FESM15

<--- Last few GCs ---> 
ERROR....
```

**Comment by skorunka** [comment]
@Kalemstorm94 Try `ng-packarg` v2, maybe it helps?

**Comment by Kalemstorm94** [comment]
Thank you, but still the same problem. I've solved this by changing the library creation method. I've followed this tutorial and everything worked perfectly.

**Comment by dherges** [comment]
Hi all,

if the issue still persists in v2, please make a separate issue. The `lib.externals` is dropped in v2 and the questions regarding the UMD module ids of pako seem to be answered. That said, bundling to FESM in v2 will treat dependencies as external by default and `lib.umdModuleIds` ist just be used to generate a correct UMD module.
