### ISSUE TITLE
Directives not properly transpiled

### ISSUE THREAD

**Issue by Eufix** [dherges/ng-packagr#302]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Directives in transpiled angular library do not work in host application.

#### How To Reproduce

I have created showcase project that reproduce this issue:
https://github.com/Eufix/ng2-school

ng2-lib is the library project and ng2-app is host application that depends on ng2-lib.

When directives are tested directly in ng2-lib project they work as expected, but when created library is
included in host application hg2-app, the throw errors:

- attribute directive:
```
ERROR Error: StaticInjectorError[ElementRef]: 
  StaticInjectorError[ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at NgModuleRef_.get (core.js:11806)
    at resolveDep (core.js:12302)
```
- structural directive
```
ERROR Error: StaticInjectorError[TemplateRef]: 
  StaticInjectorError[TemplateRef]: 
    NullInjectorError: No provider for TemplateRef!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at NgModuleRef_.get (core.js:11806)
    at resolveDep (core.js:12302)
```

#### Expected Behaviour

Both directives should not thow error when used and behave same as in ng2-lib testbed application.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.8.1
@angular: v5.0.2
rxjs: v5.5.2
zone.js: v0.8.18
```

**Comment by dherges** [comment]
Hi @Eufix,

can you check in the generated `*.js` "binaries" (the `dist` folder produced by ng-packagr`) to the repo as well?

If I see right, you use `ng-packagr@1.6.0` in an Angular v5 project with `typescript@2.4.2` .... this could be troublesome combo. Can you try `ng-packagr@next` (2.0.0-rc.x) as it's intended for Angular v5 projects.

**Comment by dherges** [comment]
Oh, and thinks for putting the repro up! It's a good issue report! :smiley:

**Comment by Eufix** [comment]
Hi @dherges ,

I made a switch to v2.0.0-rc.2 but the problem still persists :(
Generated files (dist folder) is now in repo as well.

I also tried with typescript v2.6.1 and still no luck.

**Comment by dherges** [comment]
Hi @Eufix ,

the error is reproducible in the integrationt ests of ng-packagr by running `ng serve` in the Angular CLI consumer app.

If you can figure out what is causing the Angular DI to throw the `StaticInjectionError`, it's going to help!

**Comment by dherges** [comment]
When I came across the error, I remember that it was due to symlinks.

Solution is to include `--preserve-symlinks` options.

**Comment by vapits** [comment]
@dherges I downloaded the example above, added an ngIf or and ngFor in the project and simple `--preserve-symlinks` doesn't work. There are several open issues regarding this matter and Angular 5. Is the reason clear to you? 

If you use ANY angular relate element in the template of the component, the app is builded correctly but the app you are going to include the library is breaking.
