### ISSUE TITLE
The external HTML & Sass are not inlined

### ISSUE THREAD

**Issue by MatthiasSkopek** [dherges/ng-packagr#303]
## Description

I have an Angular V5 App and I used ng-packagr, but the Sass and Html files are not inlined. 
I worked for 3 days now to get it working.

#### How To Reproduce

I follow this article https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e, but it won't work.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.9.1
@angular: v5.0.2
rxjs: v5.5.2
zone.js: v0.8.18
```

**Comment by doenikoe** [comment]
@MatthiasSkopek : I'm following the same article and I didn't found any words there that saying _make your css or sass inline_. If you want to have your style inline then maybe you can use **style** attribute in your template. ie: ```<div style="width: 100%"></div>```

**Comment by MatthiasSkopek** [comment]
<img width="903" alt="screen shot 2017-11-22 at 15 33 04" src="https://user-images.githubusercontent.com/17468883/33132718-b14bc558-cf9a-11e7-9cfb-91472f39ef3b.png">

I write an library like Material and I need the styling in an sass file...

**Comment by DavidParks8** [comment]
The only scss files that are inlined are those which are directly referenced by components. Global scss files are not handled by ng-packagr. To make a theme file like material2, use https://github.com/SimplrJS/scss-bundle and copy to dist after ng-packagr has run.

**Comment by eromano** [comment]
@MatthiasSkopek in Alfresco we are using ng-packagr as well and we solved this problem as @DavidParks8  says with scss bundle :  

https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/config/bundle-scss-new.js

You can even use it in gulp

**Comment by dherges** [comment]
Please see #273 #233#216 #123

**Comment by MatthiasSkopek** [comment]
I don't talk about the global styles... it's about the inlined styles. My component looks like that before. 
`import { Component, OnInit, Input, ContentChildren, QueryList } from '@angular/core';
import { TuModalCarouselPageDirective } from './tu-modal-carousel-page.directive';

@Component({
  selector: 'tu-modal',
  templateUrl: './tu-modal.component.html',
  styleUrls: ['./tu-modal.component.sass']
})
export class TuModalComponent{
  @Input() isModalOpen: boolean = false;
  @Input() isFullScreen: boolean = false;

  @ContentChildren(TuModalCarouselPageDirective) public pages: QueryList<TuModalCarouselPageDirective>;

  currentPage = 0;

  ngAfterViewInit(){
    console.log('isFullScreen', this.isFullScreen);
  }

  toggleModal() {
    this.isModalOpen = !this.isModalOpen;
  }
  nextPage(){
    if(this.isFullScreen){
      if(this.currentPage+1 < this.pages.toArray().length)
        this.currentPage++;
    }
  }
  prevPage(){
    if(this.isFullScreen){
      if(this.currentPage-1 >= 0)
        this.currentPage--;
    }
  }

}`

And After
`export declare class TuModalComponent {
    isModalOpen: boolean;
    isFullScreen: boolean;
    pages: QueryList<TuModalCarouselPageDirective>;
    currentPage: number;
    ngAfterViewInit(): void;
    toggleModal(): void;
    nextPage(): void;
    prevPage(): void;
}`

It looks like the css and the html are not inlined after run ng-packagr?

**Comment by DavidParks8** [comment]
It looks like you are looking in the .d.ts file. Look in the .js file in the output and you should see everything properly inlined.

**Comment by MatthiasSkopek** [comment]
I don't have a .js file for every component only .umd.js & js.map .es5.js

**Comment by vapits** [comment]
Same here, module is created and exported but HTML and CSS of the component are missing from any .js file. Anyone solved it?

**Comment by coolmate** [comment]
Run into same issue that the ng-packagr not automatically inlining the templates html and styles files. Interestingly, Angular 6 is fine with this. Not sure how to fix it in Angular 5.
