### ISSUE TITLE
Exported variable 'x' has or is using name 'y' from external module 'z' but cannot be named.

### ISSUE THREAD

**Issue by fxck** [dherges/ng-packagr#305]
If you import `Foo` somewhere, and `Foo` is internally using `Bar`, you have to import `Bar` as well, which basically negates all benefits of type inference, you have to write all types everywhere (https://github.com/Microsoft/TypeScript/issues/9944).. from what I understood from that issue, you can get around this by disabling `declaration` in `compilerOptions` (which is what angular-cli does by default I think).. could this be made configurable in ng-packagr? It's currently set to `true`.

@dherges

**Comment by dherges** [comment]
Hi @fxck,

short answer: no.

```
--declaration-d | boolean | false | Generates corresponding .d.ts file.
```

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by fxck** [comment]
@dherges I don't think it's a duplicate, also I'm not entirely sure what you do you mean 

```
--declaration-d | boolean | false | Generates corresponding .d.ts file.
```
is it something you can pass down to `ng-packagr`?

Let me try to explain the problem once more, in my lib I import

```
import { createFeatureSelector } from '@ngrx/store';
```

as `createFeatureSelector` is the only thing I need, but internally, `createFeatureSelector` uses `MemoizedSelector`, so I get an error

> packages/dialog/src/dialog.selector.ts(6,14): error TS4023: Exported variable 'getDialogSlice' has or is using name 'MemoizedSelector' from external module "/Users/fxck/www/vshlibs/node_modules/@ngrx/store/src/selector" but cannot be named.

which can be fixed by 

```
import { createFeatureSelector, MemoizedSelector } from '@ngrx/store';
```

but I DO NOT actually use `MemoizedSelector`..

**Comment by mlc-mlapis** [comment]
@fxck ... but it is not specific for `ng-packagr`. The same effects happens just in pure Angular app ... when compiling to AOT mode. Form exapmple with `Observable` from rxjs, .... and others.

**Comment by fxck** [comment]
Could be, that's why I linked to that typescript issue https://github.com/Microsoft/TypeScript/issues/9944

But it doesn't doesn't happen when you try to use `createSelector` in a standard app, aot or not.

**Comment by fxck** [comment]
This one is related https://github.com/dherges/ng-packagr/issues/542
