### ISSUE TITLE
How to provide angular core injection tokens

### ISSUE THREAD

**Issue by hamedbaatour** [dherges/ng-packagr#308]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[X] Documentation
```

## Description

**No provider for InjectionToken Platform ID!** when I run `ng serve`

![image](https://user-images.githubusercontent.com/5658460/33165939-8873fa6a-d049-11e7-9c78-a9e93487308e.png)

#### How To Reproduce

_**1. import platfrom id injection token:**_
`import { PLATFORM_ID } from '@angular/core'`

**_2. inject it in the constructor of a service & console log it:_**
```
constructor(@Inject(PLATFORM_ID) private platformId) {
console.log(platformId);
}
```

#### Expected Behaviour

platformId get's printed to the console without a dependency error.

#### Version Information

ng-packagr: ^2.0.0-rc.2 and ^1.6.0 gives the same error

![image](https://user-images.githubusercontent.com/5658460/33166199-72a056a6-d04a-11e7-9f8d-a214d31b0207.png)

**Comment by hamedbaatour** [comment]
have to close this as it turns out to be happening only when you use `npm link` during development. have to push a new version to npm every few minutes now to test the lib but at least it everything works now.

**Comment by hamedbaatour** [comment]
have to close this as it turns out to be happening only when you use `npm link` during development. have to push a new version to npm every few minutes now to test the lib but at least it everything works now.

**Comment by codemile** [comment]
I also ran into this error, and don't understand it. Why would linking of a library have any side effects on providers for a project. Especially providers from `@angular/core`?

Publishing just to get around the error is not an acceptable work around. What I don't understand is the nature of the problem. I've been debugging the `core.js` trying to figure out why this is happening, but so far no luck.

**Comment by Terrafire123** [comment]
Anyone find a solution, other than rebuilding the library every time you want to run your code?
