### ISSUE TITLE
date-fns startOfDay is not exported by node_modules\date-fns\index.js

### ISSUE THREAD

**Issue by bm-software** [dherges/ng-packagr#310]
## Type of Issue

```
[*] Bug Report
[ ] Feature Request
```

## Description

When I run `ng-packagr -p ng-package.json` the packagr return the following error while compiling FESM15:

    BUILD ERROR
    'startOfDay' is not exported by node_modules\date-fns\index.js
    Error: 'startOfDay' is not exported by node_modules\date-fns\index.js
    at error (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:16413:3)
    at Module.trace (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:16510:10)
    at ModuleScope.findVariable (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:14000:22)
    at Scope.findVariable (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:11568:33)
    at FunctionScope.findVariable (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:11568:33)
    at Scope.findVariable (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:11568:33)
    at Node._bindVariableIfMissing (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:12651:31)
    at Node.bindNode (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:12646:8)
    at Node.bind (C:\Users\Michele\Desktop\angular-calendar-scheduler\node_modules\rollup\dist\rollup.js:10991:8)

#### How To Reproduce

Run `ng-packagr -p ng-package.json` with date-fns module as dependencies of some component.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.7.0
@angular: v5
rxjs: v5.5.2
zone.js: v0.8.14
```

date-fns: v1.29.0

**Comment by DavidParks8** [comment]
This means you are missing a rollup external for whatever package contains `startOfDay`.

**Comment by bm-software** [comment]
@DavidParks8 How should I configure that?

**Comment by morphatic** [comment]
I had a similar error. See ["[name] is not exported by [module]"](https://github.com/rollup/rollup/wiki/Troubleshooting) heading in the rollup wiki, and the fix which is [custom named exports](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports). I just found the answer but haven't figured out how to implement the solution, yet. I'll post back when I figure it out.

**Comment by bm-software** [comment]
@morphatic Thank you, I'll wait for your solution. Meanwhile I've tried many possible solutions but non of them has worked

**Comment by MatissJanis** [comment]
Any progress with this? Couple of people are experiencing the same issue in this repository: https://github.com/zenkkor/ngx-credit-cards/issues/6

**Comment by alan-agius4** [comment]
Most likely you are missing `date-fns` from the external list, Can you confirm that you added the below?

```json
{
    "lib": {x
    "externals": {
          "date-fns": "dateFns"
    },
  }
}
```

**Comment by morphatic** [comment]
For most of this I followed [the structure in the ng-packaged example repo](https://github.com/dherges/ng-packaged). However, I found that it didn't work out-of-the-box on my system. I had to make the modifications to the structure described below. You can see [my full project setup in this repo](https://github.com/morphatic/charts-testing). I'm using the latest versions:

* I'm using `ng-packagr@2.0.0-rc.5`
* My angular project install is as follows

```
Angular CLI: 1.5.5
Node: 8.0.0
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.40
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1
```

There were several keys to getting this all to work. First, the folder structure:

```
project-root/
├── my-new-package-root/       # in my case 'morphatic-charts'
│   ├── src/                   # the actual source for your custom package
│   ├── ng-package.json        # config that tells ng-packagr what to do
│   ├── package.json           # things you want in the package.json for your custom package, i.e. morphatic-charts
│   └── public_api.ts          # makes sure .d.ts files get created for all exports
│     
├── src/                       # the angular code for the enclosing project
│   ├── tsconfig.app.json      # tells the test app where to find the custom package code
│   ├── tsconfig.packages.json # tells test app where the compiled custom package lives
│   ├── tsconfig.spec.json     # how to compile/find test files
│   └── ... other normal angular files (app/, assets/, index.html, etd.) ...
├── package.json               # see modification to the build:lib script below
└── ... other normal angular root files ...
```

The root `package.json` file needed to have the `scripts.build:lib` script modified as follows:

```
  "scripts": {
    "build:lib": "ng-packagr -p my-new-package-root/ng-package.json",
  },
```

The key to the main problem in this thread was `ng-package.json`. Mine contained the following:

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "my-new-package-root",
  "dest": "../dist/my-new-package",
  "workingDirectory": ".ng_build",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "d3kit": "d3Kit" # <-- this is the configuration part that was causing the compile error!
    }
  }
}
```

I found it challenging to figure out exactly which two values to place in the `externals` object. The explanation that helped the most as [this one](https://github.com/dherges/ng-packagr/issues/135#issuecomment-332730342). However, all of the posts linked to in [this post](https://github.com/dherges/ng-packagr/issues/129) are in some way supposed to help address this issue.

**Comment by bm-software** [comment]
@alan-agius4 I've tried to add your condiguration to my `ng-packagr.json` file but the problem persists.

**Comment by morphatic** [comment]
@bm-software is there a public repo where we can take a look at your code? @alan-agius4 suggestion is probably the correct one, but there could be another typo or misconfiguration that's causing the problem. In particular, what does the `scripts.build:lib` command in your root `package.json` look like? Is your config file named `ng-package.json` or `ng-packagr.json`? Does the `scripts.build:lib` command point to the actual location of this file? It took me a while to get all of my paths configured correctly.

**Comment by bm-software** [comment]
@morphatic yes, take a look [here](https://github.com/bm-software/angular-calendar-scheduler). Thank you very much :)

**Comment by dherges** [comment]
```json
{
  "scripts": {
    "packagr": "ng-packagr -p ng-package.json",
  }
}
```

Looks like a [typo](https://github.com/bm-software/angular-calendar-scheduler/blob/master/package.json) for [ng-packagr.json](https://github.com/bm-software/angular-calendar-scheduler/blob/master/ng-packagr.json)
