### ISSUE TITLE
[PR WELCOME] Dynamic rollup configuration // print descriptive error messages

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#312]
## Type of Issue

```
[x] Feature Request
```

## Description

Many people seem to have the same issue with various libraries: they don't have correct rollup externals.

#### How To Reproduce

Look at #310, #301, #85, #119, #108, #142, #230, #163, etc... 

#### Expected Behaviour

I suspect that a lot of these issues can be avoided by printing a more helpful error message.

#### Version Information

```
ng-packagr: v2.x.y
node: v8.x.y
@angular: v4.x.y
rxjs:
zone.js:
```

**Comment by alan-agius4** [comment]
Question, why not have externals in rollup be a function like the below so that all node modules are treated  as externals 

‘’’
externals: (path) => path.indexOf(“node_modules”) !== -1;
‘’’

**Comment by matheo** [comment]
I got a "descriptive" error message but I wonder what can I do about it.
```
$ node_modules/.bin/ng-packagr
Building Angular library
Generating bundle for @coachcare/common
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
'http' is imported by node_modules/axios/lib/adapters/http.js, but could not be resolved – treating it as an external dependency
'https' is imported by node_modules/axios/lib/adapters/http.js, but could not be resolved – treating it as an external dependency
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'url' is imported by node_modules/follow-redirects/index.js, but could not be resolved – treating it as an external dependency
preferring built-in module 'assert' over local alternative at '/cli-project/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'assert' over local alternative at '/cli-project/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'assert' is imported by node_modules/follow-redirects/index.js, but could not be resolved – treating it as an external dependency
'http' is imported by node_modules/follow-redirects/index.js, but could not be resolved – treating it as an external dependency
'https' is imported by node_modules/follow-redirects/index.js, but could not be resolved – treating it as an external dependency
'stream' is imported by node_modules/follow-redirects/index.js, but could not be resolved – treating it as an external dependency
'tty' is imported by node_modules/follow-redirects/node_modules/debug/src/node.js, but could not be resolved – treating it as an external dependency
preferring built-in module 'util' over local alternative at '/cli-project/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at '/cli-project/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'util' is imported by node_modules/follow-redirects/node_modules/debug/src/node.js, but could not be resolved – treating it as an external dependency
'os' is imported by node_modules/supports-color/index.js, but could not be resolved – treating it as an external dependency
'os' is imported by commonjs-external:os, but could not be resolved – treating it as an external dependency
'tty' is imported by commonjs-external:tty, but could not be resolved – treating it as an external dependency
preferring built-in module 'util' over local alternative at '/cli-project/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at '/cli-project/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'util' over local alternative at '/cli-project/node_modules/util/util.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'util' is imported by commonjs-external:util, but could not be resolved – treating it as an external dependency
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'url' is imported by commonjs-external:url, but could not be resolved – treating it as an external dependency
preferring built-in module 'assert' over local alternative at '/cli-project/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'assert' over local alternative at '/cli-project/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'assert' over local alternative at '/cli-project/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'assert' is imported by commonjs-external:assert, but could not be resolved – treating it as an external dependency
'http' is imported by commonjs-external:http, but could not be resolved – treating it as an external dependency
'https' is imported by commonjs-external:https, but could not be resolved – treating it as an external dependency
'stream' is imported by commonjs-external:stream, but could not be resolved – treating it as an external dependency
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'url' over local alternative at '/cli-project/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'url' is imported by node_modules/axios/lib/adapters/http.js, but could not be resolved – treating it as an external dependency
'zlib' is imported by node_modules/axios/lib/adapters/http.js, but could not be resolved – treating it as an external dependency

BUILD ERROR
Unexpected token
Error: Unexpected token
    at error (/cli-project/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/cli-project/node_modules/rollup/dist/rollup.js:16526:3)
    at tryParse (/cli-project/node_modules/rollup/dist/rollup.js:16220:10)
    at new Module (/cli-project/node_modules/rollup/dist/rollup.js:16264:15)
    at load.catch.then.then.then.source (/cli-project/node_modules/rollup/dist/rollup.js:18189:20)

error Command failed with exit code 111.
```
@dherges in this case I need to setup Rollup globals?
can I do it from the ng-package.json?

**Comment by oliveti** [comment]
Hi @matheo, how did you include `globals()` in lib.externals ?

**Comment by dherges** [comment]
@alan-agius4 Only saw your comment now. Looks good in theory .... will UMD bundles continue to work? What about the large list of rxjs mappings?

**Comment by matheo** [comment]
@oliveti I found that any library requiring globals should be handled as `external`, so I moved to out all my dependencies requiring global stuff and voilá, `ng-packagr` can work take those libraries from the angular/cli project's `package.json` and compile the Angular related stuff only.

So, I didn't declare my library `my-api` as external, and it requires `axios` and a lot of external stuff. If `ng-packgr` tries to include it in my Angular Components bundle, it cannot because the third party dependencies are not met. It ran fine when I declared `my-lib` and external, and any other requiring external libraries that are not in my project.

**Comment by dherges** [comment]
On a broader discussion: what if... we analyze the TypeScript imports (AST traversal) and set up the rollup configuration to just what your library source code needs?

![2017-12-05 16_37_27-typescript ast viewer](https://user-images.githubusercontent.com/901354/33615508-a016ff24-d9da-11e7-9db6-e3852afcae45.png)


Regarding rxjs in specific: rxjs is moving to top-level imports ... but it's still likely that users are running different versions of rxjs and use different import syntax'es.

- https://twitter.com/BenLesh/status/936474134292209664
- https://github.com/ReactiveX/rxjs/pull/3145
- https://github.com/ReactiveX/rxjs/pull/2882

**Comment by dherges** [comment]
@matheo @oliveti Can you please open a separate issue for your specific problem? It's good if we can keep this issue here on concept and ideas for the bundle flattening / rollup

**Comment by alan-agius4** [comment]
@dherges UMD should continue to work, the only thing that you'd need to include `tslib` cause of the `ImportHelpers` flag.

I am not quite sure how it will play with `RxJs` to be honest,

**Comment by dherges** [comment]
@alan-agius4 Can you verify that? Do not speculate here. For UMD, we need a mapping from the module ID (the "path" written in the `import ... from '<path>'` statement) to the UMD module ID (the "global-scoped object" at runtime)

UMD:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('@angular/cdk/overlay'), require('@angular/cdk/portal'), require('rxjs/observable/range'), require('rxjs/operators'), require('rxjs/Observable'), require('rxjs/operator/map'), require('rxjs/add/operator/map'), require('rxjs/add/observable/of'), require('rxjs/symbol/observable')) :
	typeof define === 'function' && define.amd ? define(['exports', '@angular/core', '@angular/cdk/overlay', '@angular/cdk/portal', 'rxjs/observable/range', 'rxjs/operators', 'rxjs/Observable', 'rxjs/operator/map', 'rxjs/add/operator/map', 'rxjs/add/observable/of', 'rxjs/symbol/observable'], factory) :
	(factory((global.sample = global.sample || {}, global.sample.externals = {}),global.ng.core,global.ng.cdk.overlay,global.ng.cdk.portal,global.Rx.Observable,global.Rx.Observable.prototype,global.Rx,global.Rx.Observable.prototype,global.Rx.Observable.prototype,global.Rx.Observable,global.Rx.Symbol));
}(this, (function (exports,core,overlay,portal,range,operators,Observable,map$1,map$3,of,observable) {
```

**Comment by alan-agius4** [comment]
@dherges, sorry for speculating So I did some tests and while rollup does try to provide default values for globals when you don't specify it, For RxJs and angular it' won't work one reason being is the scope.

So in order to make it work properly with `Umd` you's still need to provide the `globals` for instances that rollup cannot "guess".

So you'd still need to do something like;
```js
external: x => x.indexOf("node_modules") > -1,
```
```js
globals:  (x: string) => {
      let regMatch;
      if (regMatch = /^\@angular\/(.+)/.exec(x)) {
        return `ng.${regMatch[1]}`.replace("/", ".")
      }

      if (/^rxjs\/[^/]+$/.test(x)) {
        return "Rx";
      }

      if ( /^rxjs\/(add\/)?observable\/[^/]+$/.test(x)) {
        return "Rx.Observable";
      }

      if ( /^rxjs\/(add\/)?scheduler\/[^/]+$/.test(x)) {
        return "Rx.Scheduler";
      }

      if (/^rxjs\/(add\/)?operator\/[^/]+$/.test(x)) {
        return "Rx.Observable.prototype";
      }

      return undefined;

    },
```

**Comment by dherges** [comment]
@alan-agius4 Looks good to me! Let's implement dynamic rollup configuration like you suggested. Before returning an `undefined` value, it should print a warning message.

Maybe like: `Library "@your/stuff" depends on "@foo/bar".  Please consider to add "@foo/bar" to the "lib.externals" section of your package file!`

A pull request here is welcome!

**Comment by alan-agius4** [comment]
Just a small note when rollup tries to guess the name of an external, it will print out a warning telling you so, so it might be a bit redundant adding an addition warning, that said ofc we can customuze the message if you prefer that format.

**Comment by dherges** [comment]
Hm. Obviously, `lib.externals` was driven by rollup's `external` and `global` settings. So that's what it was in the past.

Now, let's switch perspective to the present. If I, as an author or maintainer of a library, write a library depending on a third-party – `import { ... } from '@foo/bar';` in TypeScript code – , then I'd like to treat the third-party as a `peerDependency: { "@foo/bar": "..." }` and thus a rollup `external` – in almost every case.

There is one exception that I found and that we use in an _enterprisy_ case: I, as a maintainer, have _legacy_ javascript code that I'd like to embed in the bundles of my library. Why? The _legacy_ may not be on a npm registry, it may be monkey-patched, … that sort of _enterprisy_ things.

Why do we keep writing `external` when external is the 9-out-of-10 use case? Why don't we write `embedded` for things we'd like to embed and treat everything else as `external` by default?

**Comment by alan-agius4** [comment]
Agreed I like it and sounds good to me, than maybe we should name external
to externalNames? As in some cases for UMD you’d need to pass the names
since rollup won’t be able to guess correctly for some libraries.


What do you think?
