### ISSUE TITLE
Angular package format has changed

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#319]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Angular package format (link from readme) now shows package format version 5. Ng-Packagr should be updated to reflect this new format.

#### Version Information

```
ng-packagr: v2.0.0-rc.3
@angular: v5.x.y
```

**Comment by DavidParks8** [comment]
I'm willing to implement this. @dherges should I go ahead before, or after #279?

**Comment by alan-agius4** [comment]
#322

**Comment by dherges** [comment]
Hi @alan-agius4 @DavidParks8 ,

what has changed beside the folder names for "esm5", "esm2015"?

Metadata JSON files carry a version flag. It has been increased from "version: 3" to "version: 4" by bumping `ngc` to Angular v5.

Are there more changes?

**Comment by DavidParks8** [comment]
It seems that es5 files no longer have .es5.js and are just .js inside the es5 folder. That’s another change I see.

**Comment by alan-agius4** [comment]
Ah yeah totally forgot about that. I doesn't have it any more. It's by the
new specs.
