### ISSUE TITLE
Using @ in package name

### ISSUE THREAD

**Issue by pl4yradam** [dherges/ng-packagr#321]
## Type of Issue

```
[ x ] Bug Report
[ ] Feature Request
```

## Description

When writing a package that contains an @ symbol, causes the project to not be publishable
Packge name: @something/something

#### How To Reproduce

Create a new package, with a name of @something/something, then go through npm run packagr, when the /dist folder is made you will notice the folder will have @something in it

When you try to do npm publish, the es5 file cannot be found (the path is looking for /something not /@something. 

#### Expected Behaviour

The correct file to be used.

_please describe what behaviour or result you expected_

#### Version Information

```
ng-packagr: v1.6.y
node: v9.x.y
@angular: v5.x.y
rxjs:
zone.js:
```

To fix, I have just removed the @ symbol from the dist folder

**Comment by dherges** [comment]
Hi @pl4yradam,

what npm version do you have?

It sounds very much like  npm/npm#19222

**Comment by dherges** [comment]
The issue will be circumvented by #319 and #322 as Package Format 5 drops the "@org" folder names
