### ISSUE TITLE
[Style] Add linter / code formatter

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#327]
It's not a feature per see, but I think adding `ts-lint` to the library will be beneficial in order to keep the same coding standards and guidelines throughout.

Also might be good to include the following two flags in the tsConfig, 
```
noUnusedParameters
noUnusedImports
```

https://www.typescriptlang.org/docs/handbook/compiler-options.html

What do to think @dherges ?

I can happily add them and add ts-lint if you'd like it.

**Comment by dherges** [comment]
Hi,

I am open to adding prettier for code formatting. I guess it should enforce the formatting as a commit hook for the moment.

**Comment by dherges** [comment]
See https://prettier.io/docs/en/precommit.html

**Comment by deebloo** [comment]
If you do add strict compiler options you may also need to do a major increment since it would break some folks builds

**Comment by dherges** [comment]
Ok, so that's where prettier for formatting the source code in `src` is fine imo. Beyond that, I wouldn't go further.

**Comment by deebloo** [comment]
Ah I misunderstood the PR. My bad!

**Comment by dherges** [comment]
See 1f1ce1859fbbb2e0c6ff2e08a7d265c2c6efbf56
