### ISSUE TITLE
Configuration inheritance with extends

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#329]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description
I have a mono repo with a lot of angular project, and I want to share the `ng-package.json` configuration among them, similar to the `tsconfig.json`

I'd like to have support for configuration inheritance with `extends`

**Comment by dherges** [comment]
Relates to #190: `ng-package.js` to read dynamic configuration
