### ISSUE TITLE
Angular5: StaticInjectorError // Solution: `--preserve-symlinks`

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#335]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Several `StaticInjectionError` being reported.

- [x] #299 
- [x] #302 
- [x] #304

#### How To Reproduce

Reproducible in the Angular CLI consumer in the integration tests:

```bash
$ cd integration/consumers/ng-cli
$ ng serve
```

(`ng build` in the CI tests work fine though!)

![2017-11-29 11_44_56-consumerngcli](https://user-images.githubusercontent.com/901354/33371501-3a610b86-d4fb-11e7-964c-766e87c237f0.png)

#### Expected Behaviour

_needs investigation_

#### Version Information

```
ng-packagr: next
node: v8.9.0
@angular: v5.0.1
typescript: 2.4.2
```

**Comment by dherges** [comment]
Current status: what exactly causes the error? Investigation needed.

**Comment by dherges** [comment]
Enabling `preserveSymlinks` in the `integration/consumers/ng-cli` app vanishes the error on Mac OS.

See a1fbbe0f2501d5ba81f81af621fe2faf10813998

**Comment by rmedaer** [comment]
Hi @dherges 
I still have the issue if I inject anything in my Injectable class from my library.

Example (working well):
```typescript
import { Injectable } from '@angular/core';
@Injectable()
export class MyLibraryService {
  constructor() {}
}
```

The same injecting `Injector`:
```typescript
import { Injector, Injectable } from '@angular/core';
@Injectable()
export class MyLibraryService {
  constructor(private injector: Injector) {}
}
```
returns:
```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: StaticInjectorError[Injector]: 
  StaticInjectorError[Injector]: 
    NullInjectorError: No provider for Injector!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10585)
    at _createClass (core.js:10622)
    at _createProviderInstance$1 (core.js:10596)
```

**Comment by filipesilva** [comment]
@igorminar @chuckjaz do you know what these errors mean?

**Comment by IgorMinar** [comment]
This is odd. I don't know why this would be happening.

Can someone setup a repo with a reproduction and open an issue on angular/angular and reference this issue? thanks!

**Comment by admosity** [comment]
Seems related to angular/angular#20598

**Comment by IgorMinar** [comment]
could you create a minimal reproduction without ng-packagr and file an issue against angular again? #20598 was closed because there are too many variables and it looked like the problem was outside of angular.

**Comment by SaturnTeam** [comment]
For Angular v5, please use the 2.0.0 release candidates of ng-packagr

**Comment by ronnyek** [comment]
I was getting this but saying ChangeDetectorRef (which seemed erroneous). I tried fiddling with a lot, ultimately deciding to try to 2.0.0 rc (2.0.0-rc.11), and this did not resolve my problems.

I'm not 100% sure its related.
```
ERROR Error: StaticInjectorError[ChangeDetectorRef]: 
  StaticInjectorError[ChangeDetectorRef]: 
    NullInjectorError: No provider for ChangeDetectorRef!
    at _NullInjector.get (webpack-internal:///../../../core/esm5/core.js:1190)
    at resolveToken (webpack-internal:///../../../core/esm5/core.js:1478)
    at tryResolveToken (webpack-internal:///../../../core/esm5/core.js:1420)
    at StaticInjector.get (webpack-internal:///../../../core/esm5/core.js:1291)
    at resolveToken (webpack-internal:///../../../core/esm5/core.js:1478)
    at tryResolveToken (webpack-internal:///../../../core/esm5/core.js:1420)
    at StaticInjector.get (webpack-internal:///../../../core/esm5/core.js:1291)
    at resolveNgModuleDep (webpack-internal:///../../../core/esm5/core.js:11075)
    at NgModuleRef_.get (webpack-internal:///../../../core/esm5/core.js:12307)
    at resolveDep (webpack-internal:///../../../core/esm5/core.js:12805)
```

**Comment by ronnyek** [comment]
I spoke too soon... looks like this is a preserveSymlinks thing because I was testing the inclusion of my lib into a new dummy test app. This helps in debugging, but is this preserveSymlinks thing only a problem because of the npm link? (Should I be able to move forward and expcet my library to be installed into a new app from npm and just work?)

**Comment by aryanisml** [comment]
Still facing the issue **Uncaught (in promise): Error: StaticInjectorError** Any solution on it.

Using Angular cli 1.5.4 and Angular 5.0.0 
Created the service library which contained the httpclient.post() call in my consume app added the service library package using npm.

On run time when we run the application it throw the error 
Uncaught (in promise): Error: StaticInjectorError
No provider for httpclient 

If I tested the service library code without consuming in any application it work as expected.
when we consumed in any application and run that application it throw the run time error

Also try preserveSymlinks in angular.cli.json file in consumer application however no success still the error present run time.
"defaults": {
    "styleExt": "css",
    "build": {
      "preserveSymlinks": true
    },
    "component": {}
  }

**Comment by samuel44ase** [comment]
> I spoke too soon... looks like this is a preserveSymlinks thing helps, because I was testing the inclusion of my lib into a new dummy test app. This helps in debugging, but is this preserveSymlinks thing only a problem because of the npm link? (Should I be able to move forward and expcet my library to be installed into a new app from npm and just work?)

i tried a lot to solve this problem finally i just use this method:
first : npm install ng-packagr
then : run npm install 
so this solve my problem i hop it will help u to try

**Comment by Ni55aN** [comment]
`preserveSymlinks` doesn't solve the problem for me
