### ISSUE TITLE
Include assets in the package (images,...)

### ISSUE THREAD

**Issue by oliveti** [dherges/ng-packagr#336]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description

I'm currently building a shared library and it seems there is no way to include custom assets with ng-packagr. Would it be possible to have this feature built in or do we have to use an external tool for this ?

#### Expected Behaviour

Possibility to specify patterns for assets to include.

#### Version Information

```
ng-packagr: v2.0.0
```

Thank you very much for this already awesome lib !

**Comment by alan-agius4** [comment]
See https://github.com/dherges/ng-packagr/issues/273

**Comment by oliveti** [comment]
Hi, 
Thank you for you answer. That's the way I implemented it right now but it is not so optimal in watch mode.
My watch task is : `"build:watch": "watch \"npm run packagr && npm run assets-copy\" src/app -c -x --ignoreDotFiles"

With this configuration, if the lib is linked. The main app will be built twice (once on packager and once on assets-copy). 

But ok, I can live with that.

**Comment by dherges** [comment]
Let's say: "in a future release, you can hook into the build pipeline"

**Comment by ronnyek** [comment]
If this just worked like angular-cli.json asset configuration where it could just take /somelib/assets/* and copy that to the output of that lib's assets folder that would be delightful
