### ISSUE TITLE
Component selectors are sometimes changed during compilation

### ISSUE THREAD

**Issue by DavidParks8** [dherges/ng-packagr#340]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Sometimes, component selectors in source code end up different that component selectors in compiled library code. I suspect this has something to do with the typescript transforms.

#### How To Reproduce

Clone master as of https://github.com/dherges/ng-packagr/commit/a1fbbe0f2501d5ba81f81af621fe2faf10813998 

yarn install

yarn build

yarn integration:samples

Take a look at the source code of `./integration/samples/custom/src/baz/baz.component.ts` and notice that its selector is `custom-baz`. Then take a look at `./integration/samples/custom/dist/esm2015/sample-custom.js` and you will see that `BazComponent` now has `baz` as its selector. The selector is changed in the same way for esm5 and umd bundles. Not all components had their selectors changed from what they were in typescript.

#### Expected Behaviour

Component selector should remain the same as in the typescript sources.

#### Version Information

```
ng-packagr: v2.x.y
node: v8.x.y
@angular: v5.x.y
```

**Comment by dherges** [comment]
Hi, can you reproduce the error by (deliberately) failing one of the integration tests?

**Comment by DavidParks8** [comment]
I cannot reliably fail a test. On one of my computers it succeeds, on another it fails. I found that it passes on both when you set `tsConfig.options.generateCodeForLibraries = true;`. I added a test to make sure it continues to work.
