### ISSUE TITLE
Expose Node API

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#341]
## Type of Issue

```
[] Bug Report
[X] Feature Request
```

## Description
I am currently using lerna as a mono repo, and rather than installing `ng-packagr` in every project, I have a global task that executes within in library. 

In order to use ng-packagr, I'll have to spawn the command like so;

``` ts
import { spawnSync } from "child_process";
import { normalize } from "path";

spawnSync(normalize("../../node_modules/.bin/ng-packagr"), {
	stdio: "inherit",
	shell: true
});
```

However, it would be nice to expose your API even if just the `createNgPackage` method.

So i can change my implementation to something like

```ts
import { createNgPackage } from "ng-packagr";
createNgPackage();
```

I am willing to do a PR myself if you accept the proposal.

**Comment by dherges** [comment]
Ok, just add a `main` to the `package.json` and open a PR! That should do it!
