### ISSUE TITLE
[PR WELCOME] Language level support for library authors

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#354]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Current Behaviour: language level is tied to [es2015](https://github.com/dherges/ng-packagr/blob/master/src/lib/conf/tsconfig.ngc.json#L23-L26)

Desired use case is es2016 / es2017 language level support for authors writing library code with es2016 features.

#### Expected Behaviour

Usage: `ngPackage.lib.languageLevel = "es2017"`

Internal / implementation detail: `tsconfig compilerOptions.lib = [ /*..*/ es2017 /*..*/ ]`

#### Version Information

```
ng-packagr: v2.0.0-rc.x
```

**Comment by dherges** [comment]
See #162

**Comment by e-cloud** [comment]
it seems simple to update the version number. But obviously it's not. otherwise @dherges will already do it.

should we add more configuration into the `ng-package.json`?

**Comment by dherges** [comment]
Closed by #486
