### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by andreasonny83** [dherges/ng-packagr#357]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] General Request
```

## Description

It would be great to have a release note for each new version of the package to help developers understanding what's going on in the different versions.
It would be good to highlight bug fixes, new features and breaking changes in there to help developers get the most of this great tool.

Thank you

**Comment by dherges** [comment]
Is the [changelog](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md) sufficient?

**Comment by andreasonny83** [comment]
If that is updated on each version release, then yes but honestly I find having all the information in the same place as a better solution. But that should be up to you.
