### ISSUE TITLE
Change Export Values

### ISSUE THREAD

**Issue by tuckerjt07** [dherges/ng-packagr#360]
Is there a way to configure the export values of services and components when packaging a module?

I am getting a ```xxx as ɵy``` pattern and would like to be able to export the service by name so that it can be more easily imported?

**Comment by deebloo** [comment]
@tuckerjt07 anything that you want to be importable from the packaged needs to be exported from your public_api.ts file. From there you can ```export { MyService } from './src/my.service.ts'```

**Comment by tuckerjt07** [comment]
@deeblo Thanks
