### ISSUE TITLE
Unable to export/import Services

### ISSUE THREAD

**Issue by tezine** [dherges/ng-packagr#366]
## Type of Issue
```
[X ] Bug Report
[ ] Feature Request
```

## Description
Hi, 
I'm unable to export a Service from a library called MyLib and import it after packaged in an app called TestMyLib. 
MyLib has a service called MyService. Whenever I try to inject it into app.component.ts constructor in TestMyLib, I get the following error:

`ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'MyLib/src/lib/modules/tezine/codes/MyService' in 'R:\Projetos\Labs\TestMyLib\src\app'
resolve 'MyLib/src/lib/modules/tezine/codes/MyService' in 'R:\Projetos\Labs\TestMyLib\src\app'
  Parsed request is a module
.....`

#### How To Reproduce

1) Create a service in MyLib: 
```
import {Injectable} from "@angular/core";
@Injectable()
export class MyService{
   public name:string='testing'
}
```

2) Export the module and service in public_api.ts
```
export * from './src/lib/modules/tezine/mylib.module'
export { MyService} from './src/lib/modules/tezine/codes/MyService'
```

3) Run `ng-packagr -p ng-package.json` and `npm pack .`

4) Import the library in TestMyLib

5) Add MyService as provider in TestMyLib. (it was also a provider in MyLib)

#### Expected Behaviour
The service should be imported successfully without errors. 
PS: **I'm able to import components from MyLib, only services are not working**. 
I already tried to run ng serve using --preserve-symlinks without success. 
#### Version Information
```
ng-packagr: v1.6.0
node: v8.x.y
@angular: v5.0.0
rxjs:5.5.2
zone.js:0.8.14
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by Itrulia** [comment]
Is the service provided in a module?

**Comment by tezine** [comment]
Hi @Itrulia , yes. The Service is provided in mylib.module.ts. 
I also added as a provider in TestMyLib: 
```
  providers: [
     MyService
  ],
```
I removed MyService from providers in TestMyLib and everthing worked! 
Thanks for the help.

**Comment by changhuixu** [comment]
Why needt o remove MyService from providers???

**Comment by Itrulia** [comment]
You don't need to. But if the tests are also being compiled for AoT it will fail because it detects it being provided twice (which it shouldn't).

That's atleast my guess what happened.
