### ISSUE TITLE
[BUG] ngc/tsc errors when encountering `ts.NodeFlags.Synthesized` nodes during emit phase

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#369]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

```bash
$ ../../node_modules/.bin/ng-packagr
Building Angular Package
Building from sources for entry point '@org/components'
Cleaning build directory
Extracting templateUrl and styleUrls
Processing assets
Inlining templateUrl and styleUrls
Compiling with ngc

BUILD ERROR
Error: TypeError: Cannot read property 'push' of undefined
    at getOrCreateEmitNode (/* ..*/ /node_modules/typescript/lib/typescript.js:14102:63)
```` 

#### How To Reproduce

See vmware/clarity#1751

#### Expected Behaviour

_please describe what behaviour or result you expected_

#### Version Information

```
ng-packagr: 2.0.0-rc.5
@angular/*: 5.0.1
typescript: 2.4.2
node: 9.2.0
yarn: 1.3.2
```

**Comment by dherges** [comment]
Help wanted! I need a repro in the [`integration/samples`](integration/samples)

At clarity, [`button-group.ts`](https://github.com/vmware/clarity/blob/master/src/clarity-angular/button/button-group/button-group.ts) runs into this.

**Comment by silberjan** [comment]
@dherges can you give us a hint how to find out which file causes the error? we have the same stack trace at our project.

**Comment by dherges** [comment]
Put a `console.log(sourceFile.path)` at `node_modules/typescript/lib/typescript.js:14102:63` ... or [better debugging with VSCode launchers](https://code.visualstudio.com/docs/editor/debugging)

**Comment by dherges** [comment]
`ts.SourceFile` fails the `ts.isParseTreeNode()` check, thus `node.emitNode = {}` is returned and `annotatedNodes` is empty.

https://github.com/Microsoft/TypeScript/blob/18a7c3fb533a99898ecf6a1ebf2bc7e17e574fa0/src/compiler/utilities.ts#L4108-L4110

```ts
    /**
     * Gets a value indicating whether a node originated in the parse tree.
     *
     * @param node The node to test.
     */
    export function isParseTreeNode(node: Node): boolean {
        return (node.flags & NodeFlags.Synthesized) === 0;
    }
```

**Comment by dherges** [comment]
In the integration test:

```
isParseTreeNode  265
isParseTreeNode  71
sourceFile.flags:  0
sourceFile.path:  /home/david/Projects/github/dherges/ng-packagr/integration/samples/material/foo/foo.component.ts
isParseTreeNode  265
isParseTreeNode  71
sourceFile.flags:  0
sourceFile.path:  /home/david/Projects/github/dherges/ng-packagr/integration/samples/material/foo/foo.component.ts
isParseTreeNode  265
isParseTreeNode  265
isParseTreeNode  265
```

In the failing project(s):

```
isParseTreeNode... 71
sourceFile.flags:  8
sourceFile.path:  /home/david/Projects/agfa/org/proprietary/packages/components/lib/alert/alert.component.ts
returning emit node  {}
```

So it's running into a `ts.SourceFile` with [`ts.NodeFlags.Synthesized`](https://github.com/Microsoft/TypeScript/blob/49a48ffd4d7ed76fa4033752d1d55a1ad31ab18a/lib/typescript.d.ts#L395)

**Comment by dherges** [comment]
Is tsickle part of the solution or part of the problem?

https://github.com/angular/tsickle/blob/master/src/transformer_util.ts#L94-L103

**Comment by emoralesb05** [comment]
I'm trying to use this in my repo and i found that the line that is throwing this error is when you `re-export` something..

e.g.

index.ts
```
export * from './module/my-submodule';
```

**Comment by dherges** [comment]
Current Update:

- ngc (and/or tsc) choke on synthesized nodes during emit phase
- ng-packagr misses to run tsickle because `emitCallback` is unset (see below)
- tsickle chokes on synthesized nodes, too
- current idea: replace source text of synthesized `ts.SourceFile` after inlining, create a fresh AST before running ngc.


---

`ts.SourceFile` replacer for decorator property assignments:

```
declare let node: ts.Node; // of kind PropertyAssigment

sourceFileOf = (node) => {
  while(node.parent) {
    node = node.parent;
  }
  return node;
}

sourceFileOf(node).getFullText()
  .substring(0, node.original.getStart())
  .concat(node.name.text)
  .concat(": `")
  .concat(node.initializer.text)
  .concat("`,")
  .concat(sourceFileOf(node).getFullText().substring(node.original.getEnd() + 1))
```

Source file creator:
```ts
declare let source: string;

ts.createSourceFile(
  'test.ts', source, ts.ScriptTarget.ES2015, true, ts.ScriptKind.TS
)
```

---

- SyntaxKind Reference: https://github.com/Microsoft/TypeScript/blob/v2.5.3/lib/typescript.d.ts#L62
- TypeScript compiler factory: https://github.com/Microsoft/TypeScript/blob/v2.5.3/src/compiler/factory.ts
- tsickle source code `Rewriter`: https://github.com/angular/tsickle/blob/a575eaaa79286381baffd3f65ca638ad7b59fd2f/src/rewriter.ts#L124-L129
- ngc `createEmitCallback()`: https://github.com/angular/angular/blob/24bf3e2a251634811096b939e61d63297934579e/packages/compiler-cli/src/main.ts#L41-L62

**Comment by dherges** [comment]
Current solution: write synthesized source files during typescript transformation. In later stages of the build, "fresh" `ts.SourceFile` are created containing the "synthesized source text"

https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/ngc.ts#L138-L165
