### ISSUE TITLE
Make it possible to keep temp files for debugging purposes when pipe fails

### ISSUE THREAD

**Issue by silberjan** [dherges/ng-packagr#370]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

To investigate issues that occur on running the pipe, it would be cool to have a flag in the cli that prevents the temp files from being deleted on fail. 

From time to time i get errors like this:
```
BUILD ERROR
Unexpected token (15076:4) in <workspace>\.ng_pkg_build\<name>\esm5\client.js
...
```

However i cannot look into the file that is causing the error because it already got deleted.

**Comment by silberjan** [comment]
Investigating the file led me to the solution on this one: https://github.com/dherges/ng-packagr/issues/367  

Was kinda hard to get the file though.

**Comment by dherges** [comment]
Yes, good point.

Why not have a `build` directory like gradle? with sub-folders for the npm `dist` folder and the intermediate `temp` files. Or keep the `ng_build` directory after packaging.

**Comment by DavidParks8** [comment]
This probably should be configurable if allowed. Many people don't want a bunch of intermediate files on their machines.

**Comment by dherges** [comment]
In current version (2.0.0-rc.8), the working directory is no longer pruned when the pipeline fails.

https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-packagr.ts#L55-L57

Whether a `build` directory should be "visible" is a separate discussion. Gradle does it. On the Java world, it's common to have class files and jars and ears and aar or apk files written to disk ... let's discuss this elsewhere :earth_africa:
