### ISSUE TITLE
TypeScript helpers are inlined in FESM5 and FESM2015 package

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#371]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Following the new RC and this PR #338. Ng Packagr now supports typescript helpers. however these are are being inlined inside the FES5 modules, and not external like https://github.com/angular/common-builds/blob/master/esm5/common.js#L7, 

Also, I noticed that tslib, is not marked as `peerDependency` nor `devDependency` in your package.json. Thus, ng-packagr is working because any `Angular` package has `tslib` as dependency.
https://github.com/angular/common-builds/blob/master/package.json#L12

#### How To Reproduce
Run `npm t` in ng-packagr or build a normal library

#### Expected Behaviour
tslib is only inlined for UMD bundles
tslib is added as a dependency in `package.json`
tslib is set as an external in FESM5

#### Version Information
```
ng-packagr: 2.0.0-rc.5 
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by unlight** [comment]
Why tslib are embeded in UMD bundle?
Is it possible to make tslib external for UMD also?

**Comment by alan-agius4** [comment]
That’s following the APF specs.

One of the reasons is that users shouldn’t care if a library is built with
TypeScript or not.
