### ISSUE TITLE
Cannot use Array.prototype.includes()

### ISSUE THREAD

**Issue by darkbasic** [dherges/ng-packagr#381]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If I use `Array.prototype.includes()` in my library I get errors with `ng-packagr`. `ng serve` works flawlessly.

#### How To Reproduce

Just use `Array.prototype.includes()` into your library. You can use this one if you want to mimic my very same environment: https://github.com/darkbasic/ngx-selectable-list/tree/packagr

#### Expected Behaviour

Should be able to use `Array.prototype.includes()`.

#### Version Information

```
ng-packagr: ^2.0.0-rc.5
@angular/*: ^5.0.0
typescript: ~2.4.2
rxjs: ^5.5.2
node: 9.2.0
npm/yarn: 5.6.0
```

https://github.com/darkbasic/ngx-selectable-list/blob/packagr/package.json

**Comment by dherges** [comment]
Hi @darkbasic,

do you like to open a PR for #354?
