### ISSUE TITLE
Cannot package basic angular 5 app

### ISSUE THREAD

**Issue by brinzi** [dherges/ng-packagr#403]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I have a simple Module that exports a components with a "Hello World".
I cannot package the module.

Getting 

```BUILD ERROR
ENOENT: no such file or directory, open 'D:\MyNpm\module_template_new\bi-module-ms\node_modules\packages\common\esm5\src\location\platform_location.js.map'
Error: ENOENT: no such file or directory, open 'D:\MyNpm\module_template_new\bi-module-ms\node_modules\packages\common\esm5\src\location\platform_location.js.map
```

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.2
node: 8.9.1
npm/yarn: x.y.z
```
ng-package.json
```
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "public_api.ts"
    }
}
```

**Comment by deebloo** [comment]
@brinzi can you post your code? and can you veryify that all of your node_modules are installed correctly? also if there are still issues try updating to 2.0.0-rc.* and see if that solves it

**Comment by brinzi** [comment]
Updating to 2.0.0-rc solved the issue. Thanks!

**Comment by deebloo** [comment]
@brinzi awesome! glad to help.
