### ISSUE TITLE
Version.js.map file not available in external file, is this required externally?

### ISSUE THREAD

**Issue by tydanielson** [dherges/ng-packagr#405]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I'm running into an error where when I'm trying to use an external package, in this case angular/flex-layout I get an error that it doesn't have a version.js.map file

`@angular/flex-layout/packages/flex-layout/esm5/version.js.map`

Is this a standard file that's required or is angular in the right now to include it?

#### How To Reproduce

Build with a module that imports `@angular/flex-layout`

#### Expected Behaviour

Build to complete successfully

#### Version Information

```
ng-packagr:1.6.0
@angular/5.1.0
typescript:2.6.2 <- I know, but everything compiles fine as long as I don't use new features
rxjs: N/A
node: 8+
npm: 5.4.2, yarn: 1.2.1
```

**Comment by dherges** [comment]
Hi @tydanielson,

what version of `@angular/flex-layout` are you using?

Can you post a repro (e.g. on a public GitHub repo)?

Most likely one of the source files references the source map file (`*.js.map`) and so the build breaks when trying to generate source maps for your lib.

**Comment by Salimlou** [comment]
Hi @dherges @tydanielson,

I had the same problem with flex-layout.
for me the problem was that i didn't specify flex-layout as an external.

Hope it helps :)!

**Comment by jonbk** [comment]
Hi Salimlou,

What are you meaning by "specify flex-layout as an external".

Can you copy/paste exactly what to do ?

Thanks.

**Comment by jonbk** [comment]
Ok find it : 

`{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@angular/flex-layout": "ng.flex-layout"
    }
  }
}`

Thanks anyway !

**Comment by Salimlou** [comment]
Exactly! 

And sorry for late response :)!

**Comment by tydanielson** [comment]
@jonbk That worked for me thanks!... I was wondering how you knew to add `ng.flex-layout` as the external for `@angular/flex-layout`? Is there a good place to look for documentation on that?

**Comment by tydanielson** [comment]
Please checkout the repo below.  I noticed that adding the external did help some, but not for all the other utils that flex uses and the error would change depending on which one it seemed to hit first.

https://github.com/tydanielson/packagr-test
`npm install`
`npm run build-pkg`

**Comment by tydanielson** [comment]
@dherges Do you have a minute to look at the errors I'm getting in the repo I created?  Maybe I'm missing something obvious that you could point out.  Is the problem actually with how flex-layout is being packaged?

**Comment by dherges** [comment]
Transcript:

```bash
$ git clone https://github.com/tydanielson/packagr-test.git
$ yarn install
$ yarn build-pkg
yarn run v1.3.2
$ ng-packagr -p ng-package.json
Building Angular library
Generating bundle for @bpf/core-ui
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15

BUILD ERROR
ENOENT: no such file or directory, open '/Users/David/Projects/github/dherges/ng-packagr/foo/packagr-test/node_modules/@angular/flex-layout/packages/flex-layout/esm5/version.js.map'
Error: ENOENT: no such file or directory, open '/Users/David/Projects/github/dherges/ng-packagr/foo/packagr-test/node_modules/@angular/flex-layout/packages/flex-layout/esm5/version.js.map'

error Command failed with exit code 111.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The source map file doesn't exist at that location.

**Comment by tydanielson** [comment]
That makes sense, but `flex-layout` is an external component to my stuff... so I can't change it.  Would this be a problem with flex-layout or with the packagr not being able to handle it?

**Comment by dherges** [comment]
More likely flex-layout than ng-packagr.
