### ISSUE TITLE
unclear relationship between `src` and `lib.entryFile` in ng-package.json

### ISSUE THREAD

**Issue by e-cloud** [dherges/ng-packagr#411]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
as described in the title, in the older version(like 1.6.0), the `lib.entryFile` is relative to `src`, now there is no relation. So it can't find the target entry file now if i don't update the entryFile.

#### How To Reproduce
Not needed

#### Expected Behavior
It cloud stay the current behavior, but we should state out the issue, it's not mentioned in breaking changes

#### Version Information

```
ng-packagr: 2.0.0-rc.6
@angular/*: 5.1.1
typescript: 2.5.3
node: 8.9.0
npm/yarn: 1.3.2
```

**Comment by dherges** [comment]
Hi @e-cloud,

yes, it wasn't mentioned in the changelog for rc6. It hopefully is in [rc7 changelog](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#breaking-changes) more clarified.

The reason for `src` has been that ng-packagr used to regex/copy files for resource inlining. In the 2.x version, it's going to replace that with the typescript transformations API and thus there is no more need for globbing file patterns like `<src>/**/*.ts`.

The `src` property is eventually going to be dropped.

**Comment by dherges** [comment]
Fixed / adressed in rc8
