### ISSUE TITLE
es2016+ features not supported in tsconfig.ngc.json

### ISSUE THREAD

**Issue by e-cloud** [dherges/ng-packagr#412]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
in tsconfig.ngc.json, it hardcoded with
```
"lib": [
      "dom",
      "es2015"
]
```
which will not support es2016+ features

#### How To Reproduce
not needed

#### Expected Behaviour
allow user to use whatever es version they want to support.

#### Version Information

```
ng-packagr: 2.0.0-rc.6
@angular/*: 5.1.0
typescript: 2.5.3
```

**Comment by Lexanius** [comment]
+1

**Comment by dherges** [comment]
See #354: A Pull Request is Welcome! :checkered_flag:
