### ISSUE TITLE
Typescript warning but build error

### ISSUE THREAD

**Issue by bokzor** [dherges/ng-packagr#413]
## Type of Issue
Build error
```
[x ] Bug Report
[ ] Feature Request
```

## Description

A typescript warning is turned in build error.

#### How To Reproduce
Add comment as : 

/**
 * Returns the value at this numeric index.
 * @param {string} row array of values
 * @param index numeric index
 * @returns or '' if invalid index
 */

#### Version Information

```
ng-packagr: 2.0.0.rc-6

```

warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part

**Comment by Lexanius** [comment]
See: #311

**Comment by dherges** [comment]
This is [tsickle](https://github.com/angular/tsickle/blob/d24b139b71a3f86bf25d6eecf4d4dcdad3b379e4/src/jsdoc.ts#L170-L178)

**Comment by bokzor** [comment]
Ok. Thanks

**Comment by Ks89** [comment]
Exactly the same issue.
It happens when you use ng-packagr 2.0.0-rc and [typdoc](https://github.com/TypeStrong/typedoc) together.

For instance with this doc:
```
/**
   * Method .... do here
   * @param {string} paramname doc here
   */
   setBlaBlaBla(paramname: string) { ... }
```

I get this error:
```
warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
```

@dherges do you think that angular team will release a fix for this or do you have an idea how to use typedoc without to break the build?

Thank u.

**Comment by matheo** [comment]
I don't have `typedoc` on my project and still get an error but with the `@return` annotation...
Refs https://github.com/dherges/ng-packagr/issues/485
I had to disable the warnings on my fork with this suggestion:
https://github.com/dherges/ng-packagr/issues/311#issuecomment-351449412

**Comment by guillermotti** [comment]
I'm facing the same issue, there is any solution to avoid all warnings in order to package successfully?

Thank you in advance.

**Comment by changhuixu** [comment]
@Ks89 @guillermotti 
Just change the line in your code 
```typescript
* @param {string} paramname doc here
```
to be
```typescript
* @param  paramname doc here
```

You don't need to specify "{string}" in Typescript JsDoc.

**Comment by igcarun07** [comment]
@changhuixu thanks it works fine

**Comment by Korigoth** [comment]
We have a pretty big lib and we doesn't want to do it everywhere... is it possible to get an other solution to get ng-packgr >=2.0.0 to work with {type} ?

**Comment by melgish** [comment]
An irritating error.  Same happens with @private which we were using to prevent typedoc from exposing internals.

**Comment by Korigoth** [comment]
it's closed so the owner doesn't get alerted by this ?

It seem's that he doesn't really want to get around this problem, so we are waiting on Angular6 - Bazel packager. 

We really liked to work with ng-packagr but there is no way that we will remove all the comments in our code. If the owner could help us  to get around the problem, we could help the community because we think that many persons use "Document This" pluggin for VsCode.

**Comment by DenisVuyka** [comment]
@dherges What is the way to fix the problem then? The only way I get this "tsickle" is by using `ng-packagr`.

**Comment by METACEO** [comment]
I'm wondering if there is a way we can provide a `tsickle` config (that `ng-packagr` uses) that ignores these warnings. Like @Korigoth, I'm working with a well-documented library with hundreds of inline JsDoc comments and I would prefer not to remove any of them.

**Comment by jscharett** [comment]
@dherges Per [#863](https://github.com/angular/tsickle/issues/863), it would seem that this is not an issue with [tickle](https://github.com/angular/tsickle) rather whatever is calling tickle.  Can tickle warnings be ignored on your end?

**Comment by matheusdavidson** [comment]
My solution, in angular 7, was change my ```tsconfig.lib.json``` config, 

from this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": true
    ...
    ...
}
```
to this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": false
    ...
    ...
}
```
