### ISSUE TITLE
[ng-packaged] package.json has wrong context

### ISSUE THREAD

**Issue by alc86** [dherges/ng-packagr#415]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_for bugs: The packagr takes the wrong package.json and so the generated package is invalid.

#### How To Reproduce

_for bugs: clone the demo project ng-packaged from github and build the library. Please review the package.json at the dist/my-lib folder. There you can see that the ng-packagr uses the root package.json and not the package.json from the my-lib folder. And so the package can not be installed with npm.

generated package.json:
{
  "name": "ng-packaged",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:app": "cpr dist/my-lib src/@my/lib && ng build --app packages && rimraf src/@my",
    "build:lib": "ng-packagr",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "dependencies": {
    "@angular/common": "~5.1.0",
    "@angular/compiler": "~5.1.0",
    "@angular/core": "~5.1.0",
    "@angular/forms": "~5.1.0",
    "@angular/http": "~5.1.0",
    "@angular/platform-browser": "~5.1.0",
    "@angular/platform-browser-dynamic": "~5.1.0",
    "@angular/router": "~5.1.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular-devkit/schematics": "^0.0.41",
    "@angular/cli": "~1.6.0",
    "@angular/compiler-cli": "~5.1.0",
    "@angular/language-service": "~5.1.0",
    "@types/jasmine": "~2.8.0",
    "@types/node": "~8.5.0",
    "codelyzer": "~4.0.0",
    "cpr": "^3.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "2.0.0-rc.6",
    "protractor": "~5.2.0",
    "rimraf": "^2.6.1",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "tsickle": "^0.25.5",
    "typescript": "~2.5.3"
  },
  "main": "bundles/ng-packaged.umd.js",
  "module": "esm5/ng-packaged.js",
  "es2015": "esm2015/ng-packaged.js",
  "typings": "ng-packaged.d.ts",
  "metadata": "ng-packaged.metadata.json"
}

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ng-packaged" under a packagenpm ERR! also called "ng-packaged". Did you name your project the same
npm ERR! as the dependency you're installing?npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

#### Expected Behaviour

_for bugs: Valid package.json.

{
  "name": "@my/lib",
  "version": "1.0.0-alpha.0",
  "repository": "https://github.com/dherges/ng-packaged.git",
  "author": "david <david@spektrakel.de>",
  "license": "MIT",
  "private": true,
  "peerDependencies": {
    "@angular/core": "^4.1.2",
    "@angular/common": "^4.1.2"
  },
  "main": "bundles/ng-packaged.umd.js",
  "module": "esm5/ng-packaged.js",
  "es2015": "esm2015/ng-packaged.js",
  "typings": "ng-packaged.d.ts",
  "metadata": "ng-packaged.metadata.json"
}

#### Version Information

```
ng-packagr: 2.0.0-rc.6
@angular/*: ~5.1.0
typescript: ~2.5.3
rxjs: ^5.4.2
node: v8.2.1
npm: 5.6.0
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
ng-packaged demo should be updated: [move ng-package.json to my-lib folder](https://github.com/dherges/ng-packaged/blob/master/ng-package.json)

Relates to #411 and #416

**Comment by alc86** [comment]
I have moved the ng-package.json now the generated package.json is OK.
