### ISSUE TITLE
[v1] [Feature Request] Exclude specific files and folders from bundle

### ISSUE THREAD

**Issue by JimiC** [dherges/ng-packagr#417]
## Type of Issue

```
[x] Feature Request
```

## Description

_for features: Exclude specific files and folders from bundle_

I've been facing a project structure case similar to #313, except in my case I wanted to exclude a `test` folder. I'm aware of the proposed way @ https://github.com/dherges/ng-packagr/issues/313#issuecomment-347825201 to structure a project to integrate unit testing but unfortunately, it doesn't comply with what I'm trying to achieve.

After looking at the source code I figured that this feature could be achieved with a trivial code modification and adding another configuration property to the `ng-packagr` schema.

I'm more than willing to provide a PR for this feature.
What I'd like to know though before proceeding is:
1. Are you willing to accept such a PR?
2. If so, which version should this be targeting, `1.x` or `2.x`?

**Comment by JimiC** [comment]
A working code for `v1.x` can be @ https://github.com/JimiC/ng-packagr/tree/exclude_folders_files_v1

**Comment by JimiC** [comment]
For `v2` this looks like it's supported due to passing the `entryFile` value to the `Typescript` API, which resolves the files to be included automatically and correctly.

**Comment by JimiC** [comment]
@dherges I don't know if this has any meaning to be added to `v1`. What's the timeframe for releasing `v2`?

**Comment by dherges** [comment]
Hi @JimiC,

there's no "contracted" timeframe. When it's ready and as of now #443 is blocking a 2.0.0. You'd still be able to install the 2.x verison with `npm install ng-packagr@next`

**Comment by JimiC** [comment]
So, is `v1` still actively developed? Should I submit a PR for this request?

**Comment by dherges** [comment]
I will not maintain v1 any further as it's just intended for Angular 4 and the community is progressing to Angular 5. A PR is welcome! Please add a test for the changes!

**Comment by dherges** [comment]
I mean: if possible to reproduce the initial issue in the integration tests, it will also help for v2!

**Comment by JimiC** [comment]
Well, `v2` doesn't need any additional coding as it supports this request by using the `TS` compiler API, but I'll what I can do to add a test case for this.

**Comment by dherges** [comment]
Ah ya, got it. There's a `. ts` file iunder the source folder which isn't included in the TypeScript source files. Nevertheless, when we place an `.ts` file with broken code in one of the integration tests ... in v1, this will break the build. in v2, it will not break. is that the original issue?

**Comment by JimiC** [comment]
Sort of. In my case, the entire `test` folder gets included in the bundle in `v1`, something that is unwanted. In `v2` because `files` of `tsconfig` gets dynamically populated the correct behavior is achieved.

**Comment by dherges** [comment]
Try to break a build by such a way. That's a good test case.

**Comment by JimiC** [comment]
The build isn't actually breaking but the produced distro contains files and folders that shouldn't be distributed with said library thus forcing to write excess code to delete them.

**Comment by JimiC** [comment]
Closing issue as obsolete.
