### ISSUE TITLE
[Bug] the third library formatstring

### ISSUE THREAD

**Issue by PxSonny** [dherges/ng-packagr#421]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am using in one of my pipe in my lib the javascript tool: https://github.com/unlight/formatstring
Been trying to define it in the `lib.externals` in my ng-package.json but no luck I always get a `BUILD ERROR Cannot find module 'formatstring'`. I tried all these:
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
		"formatstring": "formatstring"
		"formatstring/index": "formatstring"
		"formatstring": "formatstring/index"
    }
  }
}
```

Would I be better to use https://github.com/unlight/angular2-pipe-formatstring ? Or try to create an es6 wrapper like https://github.com/Agamnentzar/moment-es6 ? 

I am bit confused on what's the best process here. 

#### How To Reproduce

Install the tool: `npm i formatstring --save`

Use it somewhere by doing: ` import * as formatstring from 'formatstring';`

#### Expected Behaviour

ng-packagr should create my lib module and my components

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 4.0.0
typescript: 2.3.3
rxjs: 5.1.0
node: 6.11.0
```

**Comment by PxSonny** [comment]
I found a workaround by actually using the code from another lib into my pipe: 
https://github.com/sindresorhus/pupa

But I would still be interested to known what would be the proper way to deal with such lib like formatstring.

**Comment by dherges** [comment]
Hi @PxSonny,

see #129 for a general explanation.

The `lib.externals` is also going to change in 2.x

**Comment by PxSonny** [comment]
Thanks though, went through this thread already without luck. 
Any ETA for the final 2.0 release?
