### ISSUE TITLE
Static assets referenced by CSS

### ISSUE THREAD

**Issue by PxSonny** [dherges/ng-packagr#422]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I made a lib using ng-packagr and in my lib I use https://github.com/lipis/flag-icon-css to display some flags easily. Though when I publish my lib and then use in a demo application, the flags doesn't get loaded properly. I get 404 error on the flags that tried to be loaded. 
Example of flag being loaded: http://localhost:4200/flags/4x3/fr.svg

#### How To Reproduce

Add the lib into your project
`npm i flag-css-icon --save`

Then in one of your component link with the stylesheet from the package:
```
@Component({
  selector: 'something',
  templateUrl: './something.component.html',
  styleUrls: [
	'../node_modules/flag-icon-css/css/flag-icon.min.css', // depending where your component is compared to the node_modules folder
	'./something.component.css'
  ]
})
```

Display some flags in your component:
```
<span class="flag-icon flag-icon-gr"></span>
<span class="flag-icon flag-icon-gr flag-icon-squared"></span>
```

Then build your lib and use it in a project to see if yes or not your component displays flags

#### Expected Behaviour

The flags should display properly in any app using my lib. 

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 4.0.0
```

**Comment by dherges** [comment]
In the 2.x version, there'll be an option to embed images via postcss.

https://github.com/dherges/ng-packagr#how-to-embed-assets-in-css
