### ISSUE TITLE
Include commonjs module in the bundle

### ISSUE THREAD

**Issue by rmeshksar** [dherges/ng-packagr#423]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description
Hi,
I have a commonjs module JavaScript file in the project and I would like this to be included in the final bundle.
What is the best way to do that?

Thanks.

**Comment by denver-HJS** [comment]
@rmeshksar I think that's handled by the default output of the tool. Try importing the generated .js files located in `/dist/esm5` & `/dist/esm2015` after running the packagr command.

**Comment by denver-HJS** [comment]
@rmeshksar - have you tried importing the commonjs module into your main app module definition?

**Comment by rmeshksar** [comment]
Yes, I did. It works only if the module is installed via npm or better to say if it is inside node_modules folder.
I think it is the default settings for the rollup-commonjs-plugin and I don't think there is any way to override it in ng-packagr.
As a workaround I can write a script to copy that module to node_modules folder and in this case when it is imported in my typescript file, rollup with pick it up and adds it to the bundle.

**Comment by alan-agius4** [comment]
This will be made easier to do in V2 RC 8

https://github.com/dherges/ng-packagr/pull/395#issuecomment-352844171

**Comment by rojasjandro89** [comment]
Why was this story closed? Is there a way of overriding the rollup configuration? This situation is much less unusual than you would expect. I'm having the exact same issue with a project I'm working on. I need to include certain dependencies in the bundle. I'm surprised this limitation exists in a library packaging tool.
