### ISSUE TITLE
Setup to detect local compilation and intra-packages

### ISSUE THREAD

**Issue by matheo** [dherges/ng-packagr#432]
## Type of Issue

```
[x] Question
[ ] Feature Request
```

## Description

Please, you'are more knowledgeable than me about typescript config, I need tour help with one simple setup that I'm unable to run. I have one repo with an `angular/cli` project to compile and test my lib with `ng-packagr`. The folder structure is:
```
- repo
 |- cli-project
 | |- my-lib
 | | |-api
 | | | |-package.json
 | | |-package.json
 | |- src
 | |  |- tsconfig.app.json
 | |- tsconfig.json
 |- dist
```

My compiled app is successfully bundled into the `/dist` folder, and I want the `cli-project` to use the compiled library in that folder. I've tried many setups but no luck, I successfully build the library with:
```
{
  "extends": "../tsconfig.json",
  "angularCompilerOptions": {
    "paths": {
      "@org/common": [ "../my-lib/index.ts" ],
      "@org/common/api": [ "../my-lib/api/index.ts" ],
      "@org/common/shared": [ "../my-lib/shared/index.ts" ]
    }
  },
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [],
    "paths": {
      "@org/common": [ "../my-lib/index.ts" ],
      "@org/common/api": [ "../my-lib/api/index.ts" ],
      "@org/common/shared": [ "../my-lib/shared/index.ts" ]
    }
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```
I've tried the bundled path in the `angular/cli` tsconfig.json:
```
   "paths": {
      "@org/common": [ "../dist" ]
    }
```

What I need to detect them on `ng serve`?
Thanks for your time @dherges

**Comment by dherges** [comment]
See [nx-packaged](https://github.com/dherges/nx-packaged) demo, relevant [`tsconfig.packages.json`](https://github.com/dherges/nx-packaged/blob/master/tsconfig.packages.json#L8-L10) and [`.angular-cli.json`](https://github.com/dherges/nx-packaged/blob/master/.angular-cli.json#L32-L44)
