### ISSUE TITLE
ENOENT no such file in node_modules is missing package name in path

### ISSUE THREAD

**Issue by mpicard** [dherges/ng-packagr#437]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

```
BUILD ERROR
ENOENT: no such file or directory, open '/home/martin/repos/bugreport/node_modules/src/core/networkStatus.ts'
Error: ENOENT: no such file or directory, open '/home/martin/repos/bugreport/node_modules/src/core/networkStatus.ts'
```

#### How To Reproduce

clone https://github.com/mpicard/ng-packagr-bug
run `yarn && yarn build`

#### Expected Behaviour

expect ng-packagr to resolve this external module from node_modules properly. You can see the path specificed is `node_modules/src/core/networkStatus.ts'` but should be `node_modules/apollo-client/src/core/networkStatus.ts'`

#### Version Information

```
ng-packagr: 2.0.0-rc.7
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.2
node: 8.9.3
npm/yarn: 1.3.2
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by mpicard** [comment]
Fixed using ng-package.json lib.external properly

**Comment by Harmonickey** [comment]
@mpicard what exactly does your lib.external look like for the fix?  I am encountering the same issue.
