### ISSUE TITLE
Configuration option for stand-alone maintainable repo

### ISSUE THREAD

**Issue by inorganik** [dherges/ng-packagr#440]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

If I understand correctly, ng-packagr assumes one use-case, where you want to publish an npm module from some component you made that is part of a whole angular app. 

The issue with this is, it's not maintainable by anyone else except yourself. Meaning, since the source files are not included in dist, no one else can submit a PR and improve my component. 

I can go ahead and package the source files in the level above `dist` (and include `dist`), but now I have 2 duplicate package.json files, and only the one in `dist` has the correct path for `main`, plus a duplicate README. I'll need to tell my contributors to manually delete those, after they run `yarn build` and before they make a PR.

Can we get an option like `"stand-alone": true` which would not dupe all those assets? 
It would also be great to have `"name"` so that it doesn't use the name in my root package.json. 

Thank you!

**Update**

For now I did this under "scripts". Still would be nice not to have to though.
```
"build": "ng-packagr && rm dist/package.json && rm dist/README.md"
```

**Comment by deebloo** [comment]
Hey so while you would only publish the fiat folder to npm you would keep all of the source code on github or something if you want it to be open source.

**Comment by dherges** [comment]
This is by design. The `dist` binaries should be distribution-ready. See [Design Doc on Build Artefacts](https://github.com/dherges/ng-packagr/blob/master/docs/DESIGN.md#build-artefacts)

**Comment by inorganik** [comment]
@dherges Don't you think everyone would benefit more from a component you distribute via npm/open source if others could improve upon it? All of my repos have improved immeasurably from contributions. 

@deebloo Thanks for the suggestion but I have never seen an npm module that is distributed separately from the github repo, they're always mirrors. That's the purpose of the `dist` folder; it keeps minified/modularized code separate from the unminified editable code.

**Comment by deebloo** [comment]
@inorganik a lot of npm packages are distributed that way. Angular itself is an example

**Comment by inorganik** [comment]
@deebloo Fair enough. Still, framework vs component

**Comment by deebloo** [comment]
@inorganik angular material then. sorry I am not trying to pick, just trying to point out that there are examples

**Comment by inorganik** [comment]
@deebloo ok ok, I stand corrected. :) Still, one package for contributing and distributing is convenient.

**Comment by dherges** [comment]
I don't know what I think. Right now, the convention is that the distributables are written to a dedicated `dist` folder. I don't consider the distributables to be sources. No one is capable of reading or understanding the _binary_ js files.

Maybe one time, a _pipeline_ will be exposed through the public API of ng-packagr and you will be able to register steps that will be run before or after a default build step or maybe you even replace/overwrite a build step. Up until then, `ng-packagr && do-thing && do-other-thing` is a proven pipeline customiation 😄

**Comment by inorganik** [comment]
I think you misunderstood me. In other repos of mine, such as [countUp.js](https://github.com/inorganik/CountUp.js), and many other repos such as [Twitter Bootstrap](https://github.com/twbs/bootstrap), they are structured like this:
```
Repo
 |
 +-- myComponent.js
 +-- package.json
 +-- README.md
 |    
 +-- dist
      |  
      +-- myComponent.min.js
```
So, dist is still _only_ for distributables, but the root holds editable files and other miscellany. The advantage is: developers can customize the component to be exactly how they want it, and repackage it themselves, or they can make PRs to improve what's published on npm.

`npm install` will put the entire repo in the `node_modules` folder, but only what's in dist is included in your bundle.

With ng-packagr, it's expecting you to only publish what's in the dist folder to npm. So in effect it is not by default truly open source. If you want it to be open source, you have to make a separate repo for it (as you pointed out), with separate package.json and README files.

My feature request was to simply omit the duplicate package.json and README files in the build step given a certain build option, to facilitate the creation of an open-source component and maintain only one package.

**Comment by dherges** [comment]
Hm, maybe we're talking past each other.

Imo, `package.json` is a _binary_ artefact. There's `main` and `module` and `typings` properties. The values need to point to the generated _binary_ js artefacts. Btw, what happens when setting `dest: "."` to the directory of the source `package.json`? Is the `package.json` overwritten?
