### ISSUE TITLE
External still rquired

### ISSUE THREAD

**Issue by yonigo** [dherges/ng-packagr#442]
## Type of Issue

```
[ x ] Bug Report
[ ] Feature Request
```

## Description
I still need to add primeng to "lib.externals" even though it is a peerDependency and im using latest ng-packagr version.

I get : 
BUILD ERROR
'GrowlModule' is not exported by node_modules\primeng\primeng.js 

adding "primeng/primeng": "primeng" to lib.externals solves the issue.

#### How To Reproduce

Create an angular-cli app using @angular/cli@5.1.2
Install primeng as peerDepndency
Import Growl in app.component
try to pack using latest ng-packgr version.

#### Expected Behaviour

ng-packagr should create the package.

#### Version Information

```
ng-packagr: 2.0.0-rc.7
@angular/*: 5.1.2
typescript: 2.4.2
rxjs: 5.5.6
node: 6.9.5
npm/yarn: 1.3.2
prineng: 5.0.2
```

**Comment by dherges** [comment]
Fixed in rc8

**Comment by yonigo** [comment]
@dherges  When is rc8 released?

**Comment by dherges** [comment]
"soon" 🎁
