### ISSUE TITLE
Backwards compatibility: Support Angular 4 and Angular 5

### ISSUE THREAD

**Issue by kreuzerk** [dherges/ng-packagr#451]
## Type of Issue

```
[x ] Question
```

## Description

I want to package a library with ng-packagr and angular/cli to support Angular 4.x and Angular5.x as well. As I have read ng-packagr is using the compiler-cli internally. Of course the compiler-cli version depends on your local library setup. When I package my library using Angular 5 only Angular 5 apps can consume it while Angular 4.x apps get compile errors. If I package my library using Angular 4, only Angular 4 apps can use it and Angular 5 apps get errors.

I wanted to ask if there is a way to package my library in a way to support both versions or if I need to package and provide my library twice. Once with angular 4 and once with angular 5?

**Comment by Procaseycash** [comment]
Facing the same issue..

**Comment by ovione** [comment]
did you guys found a solution for this problems
I would like to do the same

**Comment by dherges** [comment]
Hi all,

how is your development workflow? I'd reco to have branches in the source code repo for dedicate version support (if at all, you are doing a dual v4/v5-compat support).

Why?

Say your npm package is `@foo/bar`.

- Have `@foo/bar@1.x.y` ("legacy") for Angular v4. You have sources on a branch `support/ng-v4` with dependencies and peer dependencies and test set up (and so on) for Angular v4. You want to build and test your library against Angular v4 API (so make sure it works for your consumers who are sticking with v4, as well). Use `ng-packagr@1` on that branch.
- Have `@foo/bar@2.x.y` ("latest"/"next") for Angular v5. You have sources on `master` branch with dependencies and peer dependencies and so on and on for Angular v5. You want to build and test your library against Angular v5 API to allow you using new features and new APIs. Use `ng-packagr@2` on that branch.

**Comment by dherges** [comment]
I close the issue and leave that as the recommended development workflow. I cannot see to implement a kind-of "allow packaging v4 and v5 with same version of ng-packagr"-feature.
