### ISSUE TITLE
Does adding unused components increase the bundle size?

### ISSUE THREAD

**Issue by MurhafSousli** [dherges/ng-packagr#457]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

Hi, I have a couple of components that act as templates to display data.
I include them in a folder with the package, they are not used or imported in the library's module, but they will be passed by the user and load at runtime using `ComponentFactoryResolver`.
So the user is supposed to import the ones he wants to use like:
```ts
@NgModule({
  declarations: [
    SlideImageComponent,
    SlideVideoComponent,
    SlideThumbnailComponent
  ],
  entryComponents: [
    SlideImageComponent,
    SlideVideoComponent,
    SlideThumbnailComponent
  ]
})
```

The question is would `ng-packagr` add them into the bundle even if they are not imported in the library's module, or they will be compiled and ready for use?

Thanks

**Comment by dherges** [comment]
Hi @MurhafSousli,

in the situtation you describe, these will be included in the library's bundle(s) since they are part of the public API surface.

In an application's build (importing the library into an app), they may be tree-shaken by the app's build process in case they are unused.
