### ISSUE TITLE
Build Error: X is not exported by X in third-party plugin

### ISSUE THREAD

**Issue by bluecaret** [dherges/ng-packagr#461]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am attempting to package my Angular components with ng-packagr and the first few went great until I tried to package a component that uses [text-mask-core](https://github.com/text-mask/text-mask/tree/master/core). 

I can use the component just fine in a build of the app, but when running packagr I get a build error that says:

```
BUILD ERROR
'createTextMaskInputElement' is not exported by node_modules\text-mask-core\dist\textMaskCore.js
Error: 'createTextMaskInputElement' is not exported by node_modules\text-mask-core\dist\textMaskCore.js
    at error (C:\altsawebui\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\altsawebui\node_modules\rollup\dist\rollup.js:16526:3)
    at Module.trace (C:\altsawebui\node_modules\rollup\dist\rollup.js:16623:10)
    at ModuleScope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:13965:22)
    at Scope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
    at FunctionScope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
    at Scope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
    at Node._bindVariableIfMissing (C:\altsawebui\node_modules\rollup\dist\rollup.js:12626:31)
    at Node.bindNode (C:\altsawebui\node_modules\rollup\dist\rollup.js:12621:8)
    at Node.bind (C:\altsawebui\node_modules\rollup\dist\rollup.js:11005:8)
```

The strange thing is that my use of `createTextMaskInputElement` works fine in my app so I'm not sure why packagr is complaining about this.

My import of this looks like this:

```
import { createTextMaskInputElement } from 'text-mask-core/dist/textMaskCore';
```

ng-pacakage.json:

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "dist-package",
  "ngPackage": {
    "lib": {
      "entryFile": "public_api.ts"
    }
  }
}
```

public_api.ts (the text-mask-core plugin is included within the date-picker.component exported below)

```
export * from './src/app/modules/quick-help/quick-help.component';
export * from './src/app/modules/animations/animations';
export * from './src/app/modules/toast/toast.component';
export * from './src/app/modules/toast/toast.service';
export * from './src/app/modules/details-panel/details-panel.component';
export * from './src/app/modules/details-panel/details-panel.service';
export * from './src/app/modules/modal/modal.component';
export * from './src/app/modules/modal/modal.service';
export * from './src/app/modules/multiselect/multiselect.component';
export * from './src/app/modules/multiselect/multiselect-filter.pipe';
export * from './src/app/modules/multiselect/reference-filter.pipe';
export * from './src/app/modules/loading/loading.component';
export * from './src/app/modules/validation-message/validation-message.component';
export * from './src/app/modules/date-picker/date-picker.component';
```

And the error occurs when I run the following NPM script.

```
"package:build": "ng-packagr -p ng-package.json && node_modules\\.bin\\mkdirp dist-package/scss/webui && node_modules\\.bin\\mkdirp dist-package/assets/webui && cp -r src/scss/webui dist-package/scss && cp -r src/assets/webui dist-package/assets",
```

Forgive me if I missed something obvious, I'm new to Angular and creating NPM packages so I might not understand fully how to do this.

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.1.2
typescript: 2.4.1
rxjs: 5.5.6
node: 8.2.1
npm: 5.3.0
angular2-text-mask: 8.0.4
text-mask-addons: 3.7.1
```

**Comment by AaronJin2013** [comment]
I have this problem, too.
mark

**Comment by ronnyek** [comment]
I'm also running into this attempting to import NgxDatatableModule from @swimlane/ngx-datatable

**Comment by ronnyek** [comment]
so... just so everyone knows... this is he answer to the problem at least for me:
https://github.com/dherges/ng-packagr/issues/142#issuecomment-337111535

Effectively need to add externals object to the lib config in ng-package.json, which rollup will take and do the right hting with. I needed to add
`"externals": {
      "@swimlane/ngx-datatable": "ngxDatatable"
    }`

**Comment by mlc-mlapis** [comment]
@ronnyek ... and as I know it is related to Rollup and ... `ngxDatatable` has to be `flattenModuleId` used in UMD version of `@swimlane/ngx-datatable`.

When used MD `"@angular/material": "ng.material"` and for CDK `"@angular/cdk": "ng.cdk"`.

**Comment by AaronJin2013** [comment]
@ronnyek 
you are right, the problem is solve by #142

**Comment by bluecaret** [comment]
I've tried to add the externals line but am still getting the same error.

ng-package.json:

    {
      "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
      "dest": "dist-package",
      "ngPackage": {
        "lib": {
          "entryFile": "public_api.ts",
          "externals": { "text-mask-core/dist/textMaskCore": "createTextMaskInputElement" }
        }
      }
    }

error:

    BUILD ERROR
    'createTextMaskInputElement' is not exported by node_modules\text-mask-core\dist\textMaskCore.js
    Error: 'createTextMaskInputElement' is not exported by node_modules\text-mask-core\dist\textMaskCore.js
        at error (C:\altsawebui\node_modules\rollup\dist\rollup.js:185:14)
        at Module.error (C:\altsawebui\node_modules\rollup\dist\rollup.js:16526:3)
        at Module.trace (C:\altsawebui\node_modules\rollup\dist\rollup.js:16623:10)
        at ModuleScope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:13965:22)
        at Scope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
        at FunctionScope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
        at Scope.findVariable (C:\altsawebui\node_modules\rollup\dist\rollup.js:11543:33)
        at Node._bindVariableIfMissing (C:\altsawebui\node_modules\rollup\dist\rollup.js:12626:31)
        at Node.bindNode (C:\altsawebui\node_modules\rollup\dist\rollup.js:12621:8)
        at Node.bind (C:\altsawebui\node_modules\rollup\dist\rollup.js:11005:8)

**Comment by dherges** [comment]
Is that an issue of `text-mask-core`?

QUestions:
- what is the UMD module ID of `text-mask-core`?
- how do you import `text-mask-core` in TypeScript source?

**Comment by bluecaret** [comment]
@dherges I import text-mask-core into the module and component with:

```
import { TextMaskModule } from 'angular2-text-mask';
import createAutoCorrectedDatePipe from 'text-mask-addons/dist/createAutoCorrectedDatePipe';
```

I'm sorry I don't entirely know what UMD means. We use webpack to build if that helps. Text-mask is a third party plugin so I don't have any control over how it works.

Thank you.

**Comment by dherges** [comment]
There's an explanation of UMD module ids in #129
