### ISSUE TITLE
ng-packagr failed to create source files in dist/src when there is a import busyModule statement in the module file

### ISSUE THREAD

**Issue by andrew5277** [dherges/ng-packagr#466]
[x] Bug Report
[ ] Feature Request

Description
We are using angular2-busy package in our project. Here is an example code of our module file.

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ListSearchComponent } from './list-search.component';
import { BusyModule, BusyConfig } from 'angular2-busy';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [ListSearchComponent]
})
export class ListSearchModule { }

the line of code import { BusyModule, BusyConfig } from 'angular2-busy', caused "ng-packagr -p ng-package.json" command failed to create source files in dist/src folder.

An example project is here: https://github.com/andrew5277/ng-packagr
steps to reproduce:
1. open NgApp1 solution
2. run pack in Task Runner Explorer
3. check dist/src folder, and it's empty 
4. comment out import { BusyModule, BusyConfig } from 'angular2-busy'; and run pack again,
expect to find dist/src/app/modules/list-search/list-search.module.ts and list-search.component.ts

ng-packagr: 1.6.0
@angular/*: 5.1.0
typescript: 2.4.2
rxjs: x.y.z
node: 6.9.2
npm:5.2.0

**Comment by Arikael** [comment]
there is now angular-busy2, a fork of angular2-busy which works with angular 5 and ng-packagr.
Might wanna try it (I tested it and it works on my side)

**Comment by andrew5277** [comment]
Thanks Arikael. angular-busy2 works.

**Comment by dherges** [comment]
I'll close this as there seems to be more activity or the issue was out of ng-packagr's scope.
