### ISSUE TITLE
[v1] Error on compiling FESM15

### ISSUE THREAD

**Issue by elsticky** [dherges/ng-packagr#477]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

_for bugs: please describe the error that you encountered_

The error is the following:

> Building Angular library
> Generating bundle for nlie-json-editor
> Cleaning bundle build directory
> Processing assets
> Running ngc
> Compiling to FESM15
> preferring built-in module 'url' over local alternative at '/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> preferring built-in module 'url' over local alternative at '/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> 'url' is imported by node_modules/ajv/lib/compile/resolve.js, but could not be resolved – treating it as an external dependency
> preferring built-in module 'url' over local alternative at '/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> preferring built-in module 'url' over local alternative at '/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> preferring built-in module 'url' over local alternative at '/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
> 'url' is imported by commonjs-external:url, but could not be resolved – treating it as an external dependency
> 
>
> BUILD ERROR
> Unexpected token
> Error: Unexpected token
>     at error (/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/rollup/dist/rollup.js:185:14)
>     at Module.error (/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/rollup/dist/rollup.js:16526:3)
>     at tryParse (/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/rollup/dist/rollup.js:16220:10)
>     at new Module (/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/rollup/dist/rollup.js:16264:15)
>     at load.catch.then.then.then.source (/home/nlie/dev/ts-gui/nlie-json-editor/node_modules/rollup/dist/rollup.js:18189:20)
>     at <anonymous>
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 111
> npm ERR! nlie-json-editor@0.0.0 packagr: `ng-packagr -p ng-package.json`
> npm ERR! Exit status 111
> npm ERR! 
> npm ERR! Failed at the nlie-json-editor@0.0.0 packagr script.
> 

_for features: please describe your use case_

#### How To Reproduce

I just did a build of my project and I have the following package.json contents:

```
{
  "name": "nlie-json-editor",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "packagr": "ng-packagr -p ng-package.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.0",
    "@angular/common": "^5.1.0",
    "@angular/compiler": "^5.1.0",
    "@angular/core": "^5.1.0",
    "@angular/forms": "^5.1.0",
    "@angular/http": "^5.1.0",
    "@angular/platform-browser": "^5.1.0",
    "@angular/platform-browser-dynamic": "^5.1.0",
    "@angular/router": "^5.1.0",
    "@types/jsoneditor": "^5.5.2",
    "core-js": "^2.4.1",
    "jsoneditor": "^5.13.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.1",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.1.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^1.6.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.4.1"
  }
}

```

_for bugs: please include instructions how to reproduce_

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_for bugs: please describe what behaviour or result you expected_

_for features: do you have a first draft or an idea how to implement?_

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.1.3
typescript: 2.6.2
rxjs: x.y.z
node: 8.9.1
npm/yarn: 5.5.1 (npm)
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dallastjames** [comment]
I just ran into this same issue tonight with this exact error message. For me, this issue was very similar to the one found [here](https://github.com/angular/material2/issues/7681) regarding bundling Angular Material into a library with ng-packagr. The package in question for me however was the ng2-validation npm library that I was trying to package as part of a larger component. Doing the following is what fixed this error for me (and it should hopefully fix your error by extrapolating it to whatever package is causing your issue.

(top level `ng-package.json` file)
```
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
        "entryFile": "public_api.ts",
        "externals": {
            "ng2-validation": "ng2-validation"
        }
    }
}
```

Sadly, I can't explain why adding the `externals` fields works like this, possibly the packgr maintainer could, but for me it just worked to add that to the json file. Hopefully it helps!

**Comment by elsticky** [comment]
This worked for me too! Thanks! I was using 'jsoneditor' and added it to the externals. Now is packages it fine :)

**Comment by 4996wsu** [comment]
Would be great to get a bit of explanation why this works. Or if there is a "better" way to do it.

**Comment by mlc-mlapis** [comment]
@4996wsu ... simply `externals` are not then included to the package.

**Comment by dherges** [comment]
Hi all,

an explanation and collection of q&a's for `lib.externals` is in #129.

The behaviour of external dependencies is going to change in v2. Library dependencies will be external by default. The `lib.externals` property is consequently going to be dropped.

In v2, the behaviour is _"kind of"_ reversed. If you were embedding dependencies into a library bundle, you will migrate your ngPackage description and explicitly state the embedded dependencies in [`lib.embedded`](https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json#L35-L41). Everything else will be external, and thus omitted from the bundle. For UMD bundles, the module ids will be resolved from [`lib.umdModuleIds`](https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json#L42-L46).

I'll close this issue as "question answered" then, ok?
