### ISSUE TITLE
change dist folder

### ISSUE THREAD

**Issue by molikh** [dherges/ng-packagr#481]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description
Is there anyway to set dist to another place?
I have a template app that I create my components in it and then build that components into individual  libraries to use in other apps.
so if i could specify each library to a separate dist would be great.

thanks for great work 💯

**Comment by dherges** [comment]
https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json#L11-L15
