### ISSUE TITLE
wrong inlining for html templates files that have encoding UTF-8 with BOM

### ISSUE THREAD

**Issue by ahmedGomaa90** [dherges/ng-packagr#487]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

when inlining any html file saved with **UTF-8 with BOM** encoding results in inserting `\uFEFF` in the beginning of the template property string value in the component decorator, which leads the browser to insert new line break after any component selector in the DOM.

#### How To Reproduce

* save any component template file in UTF-8 with BOM encoding.
* run ng packagr for this component
* check the ES5 & UMD packages, the result string is something like this:
` template: "\uFEFF<p>\n  simple works!\n</p>\n",`

#### Expected Behaviour

I think the inlining step should handle such a thing as webpack loader "raw-loader" doesn't result something like this.

#### Version Information

```
ng-packagr: 2.0.0-rc.10
@angular/*: 5.0.0
typescript: 2.4.2
node: 8.0.0
npm: 5.0.0
```

**Comment by dherges** [comment]
Hi @ahmedGomaa90,

guess we should add [strip-bom](https://github.com/sindresorhus/strip-bom)
