### ISSUE TITLE
lib.externals being ignored

### ISSUE THREAD

**Issue by drew-moore** [dherges/ng-packagr#49]
The description of the  [lib.externals](https://github.com/dherges/ng-packagr/blob/master/lib/ng-package.schema.json#L40) entry in the package schema led me to believe I could list additional  key/value pairs and have them included in the externals passed to rollup.

This didn't work, so I looked into the code and - unless I'm missing something - the lib.externals entry is not being referenced anywhere at all, so my inputs there are being ignored.  

If this is intentional, the entry should be removed from the package schema - but FWIW I hope it isn't, as I can't use this (otherwise great!) tool to build the app I'm working on unless I can include some of its third-party libs (in particular, angularfire2 and firebase) as rollup externals. 

I threw together a quick implementation that's working for my app [here](https://github.com/drew-moore/ng-packagr/commit/2bc2c5e8683293ee187e67257be60310de84762f) - I'd be happy to clean it up and submit a pull request if you'd like me to.

**Comment by drew-moore** [comment]
(In particular, I'd remove the use of object spread [here](https://github.com/drew-moore/ng-packagr/blob/2bc2c5e8683293ee187e67257be60310de84762f/lib/steps/rollup.ts#L166) unless you already require TS 2.1+ (which it doesn't appear you do), and add unit tests)

**Comment by dherges** [comment]
Hi @drew-moore, yes, it's just not implemented until now. A PR is very welcome! 👍 

I'd like to stick with the newest TypeScript version.

For tests, adding an usage example to one of the `integration/sample_*` packages would be fine! For now, tests are meant to be integration tests and assert that certain files / folder structures are generated by a build.
