### ISSUE TITLE
Unexpected token < in JSON at position 9071

### ISSUE THREAD

**Issue by walakoala** [dherges/ng-packagr#499]
## Type of Issue
Install package error

```
Unexpected token < in JSON at position 9071
```

```
[x] Bug Report
[ ] Feature Request
```
## Description
When installing the package it gives a compile error. I tried even the example (https://github.com/dherges/ng-packaged) and it doesn't work.

#### How To Reproduce
Create your own package and try to install it following the steps in the doc.

#### Expected Behaviour
No errors on install

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.2.0
typescript: 5.6.0
rxjs: 5.5.6
node: 9.4.0
npm/yarn: 5.6.0
```

**Comment by sumigoma** [comment]
@walakoala can you repro in a plunkr or a stackblitz?

**Comment by walakoala** [comment]
Well it's kinda hard to do that. I just followed the article on https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e. The packaging of the module seems to work until I import it into another project. I tried to install it from local and from the npm repository and it's the same issue.
