### ISSUE TITLE
Build error when using ramda for ng-packagr 1.6.0 and angular 4.4.6

### ISSUE THREAD

**Issue by veentoo** [dherges/ng-packagr#500]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm trying to package my lib that uses ramda and get the error
>'pipe' is not exported by node_modules/ramda/index.js

But it works with angular ~5.x and ng-packagr v2.x in ng-packaged app

#### How To Reproduce
See reproduction on ng-packaged app for ng-packagr 1.6.0 and angular 4.4.6:
https://github.com/veentoo/ng-packaged/commit/be19ea5b3669f4bf04e6be768a4eae305baffe86

with `"externals": { "ramda": "R" }`:
https://github.com/veentoo/ng-packaged/commit/a32ec3dd794d4bdc5380a081d3df92418269a498

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 4.4.6
typescript: 2.6.2
rxjs: 5.5.6
node: 8.4.0
npm: 5.4.2
ramda: 0.24.1
```

**Comment by dherges** [comment]
Hi @veentoo,

is it a v1 issue then?

I am going to not actively maintain v1.
