### ISSUE TITLE
Comments with backticks in component styles breaking build

### ISSUE THREAD

**Issue by petersandor** [dherges/ng-packagr#503]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Component with Sass styles containing backticks break builds.

```
/* Some comment `something` etc. */
```

Backticks are interpreted as and end of string in `@Component({..., styles: [``]})`, so it expects a comma since the string continues. This is the resulting error:

<img width="879" alt="screen shot 2018-01-17 at 19 47 53" src="https://user-images.githubusercontent.com/3933866/35060635-574bcab6-fbbf-11e7-85ba-1e972a7c2ab3.png">

#### How To Reproduce

Add a comment with some backticks into a component Sass stylesheet. 

For example the error from the screenshot above can be reproduced by cloning this repository, installing all dependencies and adding a comment like the one mentioned above into this file: 
- [integration/samples/embed-assets/src/angular.component.scss](https://github.com/dherges/ng-packagr/blob/master/integration/samples/embed-assets/src/angular.component.scss)

And then run `yarn test`.

Also works when such a comment is in another scss file which is imported.

#### Expected Behaviour
Backticks should be escaped? Or comments could be discarded with [postcss-discard-comments](https://github.com/ben-eb/postcss-discard-comments) plugin.

#### Version Information

```
ng-packagr: 2.0.0-rc.11
@angular/*: 5.2.0
typescript: 2.6.2
rxjs: 5.5.6
node: 8.9.4
npm/yarn: 5.6.0/1.3.2
```

**Comment by dherges** [comment]
@petersandor FYI rc-12 is out

**Comment by petersandor** [comment]
I just found out, that if you remove `"cssUrl": "inline"` from package configuration, the test setup mentioned in this issue will fail again.

Reason is that the `postcss-discard-comment` is used only when `cssUrl` option is set. 
https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/assets.ts#L87-L93

I'll create a PR with a fix for this.

**Comment by petersandor** [comment]
There is another problem with whitespace being removed from those processed styles, some tests are failing because of it:

<img width="712" alt="screen shot 2018-01-26 at 12 49 38" src="https://user-images.githubusercontent.com/3933866/35438593-6d245996-0297-11e8-87b1-5f1c5e79c53e.png">

There is an issue opened https://github.com/ben-eb/postcss-discard-comments/issues/44 

@dherges would you be ok with adjusting those tests to not expect whitespace so this wouldn't be a problem?

**Comment by dherges** [comment]
Does stripping the whitespace cause a different rendering behaviour in the browser?

If no, it's safe to remove.
