### ISSUE TITLE
Ng-Packagr doesn't export the NgModules in subfolders

### ISSUE THREAD

**Issue by matheo** [dherges/ng-packagr#518]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Is this behaviour by design?

#### How To Reproduce

Try to package a library with NgModules in some subfolders.
It only packages the NgModules on the root folder.

#### Expected Behaviour

All the existing NgModules to be packages except if there's a secondary entrypoint.

#### Version Information

```
ng-packagr: 2.0.0-rc.10
@angular/*: 5.1.3
typescript: all tested
rxjs: 5.5.6
node: 6.11.5
yarn: 1.3.2
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by JoostK** [comment]
Do you export the modules in subfolders all the way to public_api.ts? If they aren't used internally and are not exported outwards, Rollup may decide not to bundle the code at all.

**Comment by matheo** [comment]
I included them in the `publlic_api.ts` and they were not exported, but if I move them to a `file.ts` in the root folder I get them exported.

**Comment by deebloo** [comment]
@matheo what do you mean they were not exported? can you show us your public_api.ts file and then how you are trying to import your Modules?

**Comment by matheo** [comment]
Yes, here's the history:
At [this point](https://github.com/selvera/npm-datepicker/commit/da9c5ca7a31d16ea2344557bdca320041f90e662), the `NativeAdapterModule` was not present in the dist file. Even with the core/index.ts file being exported in the [public_api.ts](https://github.com/selvera/npm-datepicker/blob/da9c5ca7a31d16ea2344557bdca320041f90e662/src/datepicker/public-api.ts).

I had to [move both exports to the root folder](https://github.com/selvera/npm-datepicker/commit/83082df0dcef73ce1467f4e48f9573b28c565266) to see them in the dist/bundle.

**Comment by dherges** [comment]
```ts
export * from './core';
```

pointing to source file: `./core/index.ts`.

What do you mean by "not present in dist/bundle"? Do you mean that the symbols were not exported in the ESM bundles (`export { .. }`)? Or do you want to say that it is an AoT issue (information missing in `*.metadata.json`)?

**Comment by dolanmiu** [comment]
I am having a similar issue, users have to do this, which is so un-intuitive:

```ts
import { ColorOutput } from 'ng-color/shared/color-utility/color-output';
```

rather than straight up:

```
import { ColorOutput } from 'ng-color';

```

**Comment by deebloo** [comment]
@dolanmiu can you shared your public_api file?

**Comment by matheo** [comment]
@dolanmiu check how do you include your barrels
I found that `ngc` doesn't go through `export * from `./core'`, it requires `export * from `./core/index'`

**Comment by dolanmiu** [comment]
I will give this a try
