### ISSUE TITLE
Turning aliasing of components off

### ISSUE THREAD

**Issue by MuhammadTaha** [dherges/ng-packagr#520]
How to turning component aliasing off ? I want to use the component with its real name.
```
[ ] Bug Report
[*] Feature Request
```

```
ng-packagr: 1.6.0
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.2
node: 8.9.1
npm/yarn: 5.6.0
```

**Comment by mlc-mlapis** [comment]
@MuhammadTaha ... what is it `component aliasing`?

**Comment by MuhammadTaha** [comment]
when I package my modules, it aliased it as ` export {  DialogComponent as ɵa }; ` . How can it be just be like `export {  ListViewComponent };`

**Comment by mlc-mlapis** [comment]
@MuhammadTaha ... are you using `v2.0.0-rc.11` or `v1.6.0`?

**Comment by MuhammadTaha** [comment]
v1.6.0

**Comment by mlc-mlapis** [comment]
@MuhammadTaha  ... `DialogComponent` is your own component or from external lib ... any simple reproduction code?

**Comment by MuhammadTaha** [comment]
It is my own component. 
my `public_api.ts` contains `export {MyModule} from './src/app/modules/my.module';`
and my MyModule  is exporting my Dialog component.

`my.module.ts`
``````
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogComponent }   from './dialog/dialog.component';

@NgModule({
    imports: [ CommonModule ],
    exports: [  DialogComponent ],
    declarations: [ DialogComponent ]
})
export class MyModule {}
``````

`ng-package.json` contains:

```````
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts"
  }
}
```````

**Comment by mlc-mlapis** [comment]
@MuhammadTaha ... try to also export the component in your module file ...

```
...
import { DialogComponent }   from './dialog/dialog.component';
export * from './dialog/dialog.component';
...
```
I also suppose that you have `src` directory for source files of your package, so ..
```
{
	"$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
	"src": ".",
	"dest": "dist",
	"workingDirectory": ".ng_build",
	"lib": {
		"entryFile": "./src/public_api.ts"
	}
}
```

**Comment by MuhammadTaha** [comment]
It didnt worked. I am still getting that ` export { MyModule, DialogComponent as ɵa };` in `mylibrary.js` file in `dist` folder

**Comment by MuhammadTaha** [comment]
Yes, this worked. Thanks alot. 

This is weird since I am exporting this component from my.module even then I have to explicitly export it in public_api.ts which should be the case.

**Comment by mlc-mlapis** [comment]
@MuhammadTaha ... when https://github.com/dherges/ng-packagr/issues/520#issuecomment-359390810 I use also `export * from './demo.module';` in my `public_api.ts` so it should be equivalent ... at least works for me.

**Comment by MuhammadTaha** [comment]
I now tried using ` export { DialogComponent } from './src/app/modules/dialog/dialog.component';
` in just public_api.ts . Its working like that too.
`my.module`  right now:
``````
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogComponent }   from './dialog/dialog.component';

@NgModule({
    imports: [ CommonModule ],
    exports: [  dialogComponent], //well since I have added my component here, it should work like that
                                  // without explicitly adding to public_api
    declarations: [ dialogComponent ]
})
export class MyModule {}
``````
and public_api
``````
export {MyModule} from './src/app/modules/my.module';
export { DialogComponent } from './src/app/modules/dialog/dialog.component';
``````

**Comment by MuhammadTaha** [comment]
Thanks alot . I am closing this issue.
