### ISSUE TITLE
Error Cannot find the models or Data Entity in service

### ISSUE THREAD

**Issue by aryanisml** [dherges/ng-packagr#521]
## Type of Issue
Error Cannot find the models or Data Entity

## Description
Added the model like sampleapp.model.ts class it contained only name property which initated in constructor. Created simple method in SampleappService .ts and return the new SampleApp('Hello World');
While Running the npm run packagr it give the error Cannot find the module ....
If i removed the return new SampleApp('Hello world') and return simple string then it will start working and creating the package 

#### How To Reproduce
sampleapp.model.ts
export class SampleApp{
    public _name:string;

    constructor(name:string){
       this._name=name;
    }
    
}

sampleapp.service.ts
import { Injectable } from '@angular/core';
import { SampleApp } from "app/sampleapp/sampleapp.model";

@Injectable()
export class SampleappService {

  constructor() { }

  getSampleData(){
   return new SampleApp('Hello World');
  }

}

Public_api.ts

export * from './src/app/sampleapp/sampleapp.model';
export * from './src/app/sampleapp/sampleapp.service';

SampleAppModule.ts

import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import {SampleappComponent} from './sampleapp.component'

 //import { SampleappService } from "app/sampleapp/sampleapp.service";

@NgModule({
  imports: [
    CommonModule
  ],
  exports:[],
  declarations: [SampleappComponent]
})
export class SampleappModule { 
/*
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: SampleappModule,
      providers: [
        SampleappService
      ]
    };
  }

*/
}

**Comment by deebloo** [comment]
@aryanisml i see that you are using an absolute import for your model.

```TS 
import { SampleappService } from "app/sampleapp/sampleapp.service";
import { SampleApp } from "app/sampleapp/sampleapp.model";
```

can you try using relative imports and see if that fixes it?

**Comment by aryanisml** [comment]
Yes i try the relative import for model its working now,
import {SampleApp} from "../sampleapp/sampleapp.model";

**Comment by deebloo** [comment]
@aryanisml awesome! If that solved your issue will you close this issue?
