### ISSUE TITLE
Build Error:  media query expression

### ISSUE THREAD

**Issue by aharris** [dherges/ng-packagr#53]
BUILD ERROR
media query expression must begin with '('
Error: media query expression must begin with '('
    at options.error (/Users/aharris/Projects/Royal/excalibur/node_modules/node-sass/lib/index.js:291:26)

ng-package.json:
`
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts"
  }
}
`

**Comment by dherges** [comment]
@aharris can you give a little bit more info how to reproduce?

**Comment by dherges** [comment]
Closing this issue as no reproduction given.
