### ISSUE TITLE
unexpected token error in rollup when executing npm run packagr

### ISSUE THREAD

**Issue by ak4wrapp** [dherges/ng-packagr#532]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

_for bugs: please describe the error that you encountered_
npm run packagr throws unexpected token error

> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for @wmclientonline/mso-auth
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15

BUILD ERROR
Unexpected token
Error: Unexpected token
    at error (C:\Test\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Test\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:16526:3)
    at tryParse (C:\Test\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:16220:10)
    at new Module (C:\Test\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:16264:15)
    at load.catch.then.then.then.source (C:\Test\node_modules\ng-packagr\node_modules\rollup\dist\rollup.js:18189:20)

_for features: please describe your use case_

#### How To Reproduce

_for bugs: please include instructions how to reproduce_

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_for bugs: please describe what behaviour or result you expected_

_for features: do you have a first draft or an idea how to implement?_

#### Version Information

```
ng-packagr: 2.0.0-rc.11
@angular/*: 5.1.2
typescript: 2.6.2
rxjs: 6.0.0-alpha.2
node: 9.4.0
npm/yarn: yarn: v0.24.6
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by ak4wrapp** [comment]
ng-packagr: 2.0.0-rc.11
@angular/*: 5.1.2
typescript: 2.6.2
rxjs: 6.0.0-alpha.2
node: 9.4.0
npm/yarn: yarn: v0.24.6

**Comment by deebloo** [comment]
@ak4wrapp it will be difficult to help you until you fill out the entire issue template

**Comment by ak4wrapp** [comment]
Thanks I updated it now

**Comment by dherges** [comment]
Hi, please provide a reproduction.

**Comment by garrett-vangilder** [comment]
Hey I'm actually running into this same issue. Able to reproduce with the following versions: 

```
    "@angular/core": "~5.2.3",
    "@angular/cli": "^1.6.7",
    "ng-packagr": "^1.6.0",
    "tslint": "~5.9.1"
```
