### ISSUE TITLE
styleUrls cannot be packaged and generates error

### ISSUE THREAD

**Issue by michieldejong** [dherges/ng-packagr#538]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
styleUrls in Angular components are not able to be packaged, generates an error.

#### How To Reproduce
I have Angular components which include styleUrls. When packing it cannot inline those sass files. The Angular CLI does manages this correctly. The previous version of ng-packagr I used was fine (version 1.6.0). I upgraded to 2.0.0-rc.11 because I needed the sassIncludePaths functionality.

If I leave the style references out of the component everything compiles fine. 

The error:
```
BUILD ERROR
Cannot inline stylesheet path-to-component/searchbox.component.scss
Error: Cannot inline stylesheet path-to-component/searchbox.component.scss
at Object.<anonymous> (/node_modules/ng-packagr/lib/steps/assets.js:87:31)
    at throw (native)
    at rejected (/node_modules/ng-packagr/lib/steps/assets.js:5:65)
```

Code referencing the styles in the two components: 

```
@Component({
  selector: 'iba-infobarista',
  templateUrl: './infobarista.component.html',
  styleUrls: ['../../../scss/infobarista.scss']
})
```

```
@Component({
  selector: 'iba-searchbox',
  templateUrl: './searchbox.component.html',
  styleUrls: ['./searchbox.component.scss']
})
```

I have tried different paths to the components, including an absolute path to the files. Doesn't work...

#### Expected Behaviour

_for bugs: Should work as in version 1.6.0 which I used before.

#### Version Information

```
ng-packagr: 2.0.0-rc.11
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.5
node: 6.9.5
yarn: 1.3.2
```

**Comment by dherges** [comment]
Hi @michieldejong,

can you give access to a repro?

**Comment by michieldejong** [comment]
@dherges Unfortunately not, its a corporate project. I'll look if I can make a small test project in a separate repo.

**Comment by michieldejong** [comment]
Ok after debugging a bit, it seems to be related to something I do in the sass files. I import another sass file from the node_modules directory: 

`@import "~portal-styling/scss/portal-styling-essentials-beta";`

This somehow breaks it.

**Comment by michieldejong** [comment]
I managed to solve it. In the imported css files I had comments with /* */, for some reason it breaks because of that. I changed those comments all to // and that works. Im guessing it has to do with the parser reading line by line and can't deal with the text that is multiline and in between /* */.

**Comment by vapits** [comment]
Good to know. Then this can be closed? ;)

**Comment by michieldejong** [comment]
Yep!
