### ISSUE TITLE
 TypeError: program.name(...).option is not a function

### ISSUE THREAD

**Issue by Ts-alan** [dherges/ng-packagr#539]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description

TypeError: program.name(...).option is not a function

#### How To Reproduce
I write 'npm run packagr' and get issue

#### Version Information

```
ng-packagr: ^1.6.0
@angular/*:^4.0.0
typescript:~2.0.0
rxjs:^5.2.0
node: last
npm/yarn: last
```

**Comment by dherges** [comment]
Hi @Ts-alan,

can you give access to a repro?

**Comment by deebloo** [comment]
@Ts-alan is is hard to help you with your issue without more information

**Comment by Ts-alan** [comment]
Sorry.A solved problem.it was necessary to update angular ,cli, typescript
