### ISSUE TITLE
ng-packagr not working with angular project having ngrx module in it

### ISSUE THREAD

**Issue by roopkt** [dherges/ng-packagr#542]
## Type of Issue
sample app [ngrx-with-ng-packgr.zip](https://github.com/ngrx/platform/files/1666552/ngrx-with-ng-packgr.zip)
```
[x ] Bug Report
[ ] Feature Request
```

## Description
ngrx project is not working with ng-packagr
 trying to run ng-packagr on angular project with ngrx modules.

#### How To Reproduce
install the app which is in the zip file and then run 
```
npm i
ng-packagr 
```

Below is the error that you see:
```

PS Z:\rupesh\rnd\angular\ngrx-with-ng-packgr\my-app> ng-packagr
Building Angular library
Generating bundle for my-app
Cleaning bundle build directory
Processing assets
Running ngc

BUILD ERROR
Error at Z:/rupesh/rnd/angular/ngrx-with-ng-packgr/my-app/.ng_pkg_build/my-app/ts/src/app/app.component.ts:34:14: Exported variable 'getProductState' has or is using name 'MemoizedSelector' from external module "Z:/rupesh/rnd/angular/ngrx-with-ng-packgr/my-app/node_modules/@ngrx/store/src/selector" but cannot be named.
Error: Error at Z:/rupesh/rnd/angular/ngrx-with-ng-packgr/my-app/.ng_pkg_build/my-app/ts/src/app/app.component.ts:34:14: Exported variable 'getProductState' has or is using name 'MemoizedSelector' from external module "Z:/rupesh/rnd/angular/ngrx-with-ng-packgr/my-app/node_modules/@ngrx/store/src/selector" but cannot
be named.
    at new UserError (C:\Users\rtiwari\AppData\Roaming\npm\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\tsc.js:27:28)
    at check (C:\Users\rtiwari\AppData\Roaming\npm\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\tsc.js:93:15)
    at Tsc.typeCheck (C:\Users\rtiwari\AppData\Roaming\npm\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\tsc.js:173:9)
    at C:\Users\rtiwari\AppData\Roaming\npm\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\main.js:122:23
    at <anonymous>
```

_for bugs: please include instructions how to reproduce_

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour
IT should compile the project with ngrx and create package
_for bugs: please describe what behaviour or result you expected_

_for features: do you have a first draft or an idea how to implement?_

#### Version Information

```
ng-packagr: ^1.6.0
@angular/*: ^5.2.0
typescript: ~2.5.3
rxjs: ^5.5.6
node: 8.9.4
npm:5.6.0
ngrx: 5.0.1
```

_please include any version information that might be relevant, e.g. other third-party libraries_
I also created this issue in https://github.com/ngrx/platform/issues/754

Added sample app in github to review
https://github.com/roopkt/angular-ngrx-using-ng-packagr

**Comment by deebloo** [comment]
@roopkt this is an error thrown by the compiler. "MemoizedSelector" is the the return signature of getProductState but when angular attempts to compile your code it can't find it. To fix it import MemoizedSelector from @ngrx/store and set your variable to it.

```
export const getProductState: MemoizedSelector<any, any> = createFeatureSelector<any('products');
```

**Comment by AaronJin2013** [comment]
@roopkt 
When I encounter this kind of problem, I will try to solve it in the following way.
open the file 'ng-package.json', add 'externals'
`
      "@ngrx":"@ngrx",
      "@ngrx/store":"@ngrx/store",
      "@ngrx/store-devtools":"@ngrx/store-devtools",
      "@ngrx/effects":"@ngrx/effects",
`
Most third-party libraries can be solved by this method.

**Comment by roopkt** [comment]
@AaronJin2013  Thanks for replying I tried the way you explained however it is still not compiling and same error is coming. Here is my source code shared https://github.com/roopkt/angular-ngrx-using-ng-packagr/blob/master/ng-package.json can you please download my source code run` npm install` and try it out.

**Comment by roopkt** [comment]
Hi @deebloo Thank you very much the way you explained it solved the problem now I can compile my app. Here is the sample https://github.com/roopkt/angular-ngrx-using-ng-packagr/blob/Fixing-Error/src/app/app.component.ts

However , this is tough every where I use third party do I have to explicitly mention the type ?

**Comment by deebloo** [comment]
@roopkt awesome I am glad it is working. it will depend on the library if you have to do this or not, but at least you know how to fix the error.

**Comment by AaronJin2013** [comment]
Hi @roopkt , I download you source code and run it, you may try this way to your code:
add this code to your app.component.ts
```
import { MemoizedSelector } from '@ngrx/store/src/selector';

```
this error because 
`using name 'MemoizedSelector' from external module "/Users/aaronjin/github/angular-ngrx-using-ng-packagr/node_modules/@ngrx/store/src/selector" but cannot be named.`
so, you need According to declaration it.
good lucky

**Comment by roopkt** [comment]
Thanks @AaronJin2013 exactly that is the way it is working Thanks to @deebloo to give me workaround.
