### ISSUE TITLE
[v1] StaticInjectionError: Package breaks after compiling project with --prod

### ISSUE THREAD

**Issue by tommueller** [dherges/ng-packagr#570]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

In my package created with `ng-packagr` I have a `GlobalErrorHandler`, which injects `@angular/material`s SnackBar-component to show an error notification. Running the package itself works fine. Using the package in a parent application also works fine, but if I build the parent application with `ng build --prod` the build version breaks as soon as the `GlobalErrorHandler` gets triggered with the following error:
```
Uncaught Error: StaticInjectorError(ct)[t]: 
  StaticInjectorError(Platform: core)[t]: 
    NullInjectorError: No provider for t!
```
which refers to this line of code:
```
var /** @type {?} */ snackBar = this.injector.get(MatSnackBar);
```

Even though both the package and the parent import the `MatSnackBarModule`.

#### How To Reproduce

I created a repository with a test-case here: https://github.com/tommueller/angular-di-fail-testcase
The package folder contains an `angular cli` project bundled with `ng-packagr` and the parent consumes this package.

#### Expected Behaviour

The code should work fine, as it does in dev-mode.

I am not 100% sure if this is a `ng-packagr` issue, or `@angular/material` or even `@angular/cli` ... But this here was my first assumption. If you think it originates from somewhere else, let me know and I will open an issue over there with reference to here.

#### Version Information

```
ng-packagr: 1.6.0
Angular CLI: 1.5.0
Node: 8.9.4
OS: linux x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.1
@angular/cli: 1.5.0
@angular/material: 5.1.1
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by dherges** [comment]
Hi @tommueller,

thanks for putting up the repro. I am going to look at it in the next days!

**Comment by vapits** [comment]
Same gos for everything else `ngiF`, `routerModule` etc etc. It's not usable with `-prod` and also with `-aot` (symlinks is not a fix).

**Comment by dherges** [comment]
Transcript:

```bash
$ cd package
$ npm install
$ npm run packagr
$ cd ../parent
$ npm install
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for ng-packagr-error-test
```

Did you do a `npm link` in the `package/dist` directory? If yes, that may be the source of the issue as it will install the `dependencies` (incl. angular) to `package/dist/node_modules`.

Still, I didn't get that to run. 
```bash
$ cd package/dist
$ npm link
$ cd ../../parent
$ npm install
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for ng-packagr-error-test
```

How to reproduce?

**Comment by dKab** [comment]
I used ng-packagr today to build [nb-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap), 
 that I use in my angular-cli project. But when I navigate to the page which imports a component from ng-bootstrap I get the same error StaticInjectionError blah blah blah no provider for ...

**Comment by tommueller** [comment]
@dherges did you manage to get the repro working? or should I create a better example? this is becoming a big problem in our development, so I'd be happy to help to fix it soon.

**Comment by dherges** [comment]
Hi @tommueller, I don't have time to maintain v1. If the issue is solved in v2, you're best off by migrating to v2 or provide a PR for v1 or customize your build set up (w/o ng-packagr).

**Comment by joerossetter** [comment]
i'm seeing the same issue locally when using `ng serve --prod` and `ng serve --aot`. works fine with just `ng serve`.

my demo repo contains just a simple library and demo application. the library basically just imports `MatExpansionModule` and adds some text. the demo application is built on the cli, and it just imports the library and displays the component on the page.

if i cut and paste my library component into my demo application template (and don't use the library) then everything works as expected.

i can publish it if that's helpful.

**Comment by benelliott** [comment]
@joerossetter Did you try setting `defaults.build.preserveSymlinks` to `true` in the `.angular-cli.json` of your demo repo (not the library)?

**Comment by tommueller** [comment]
@dherges I think the issue is gone with v2 actually. I will close this for now because I assume this is solved in v2, if I run into this issue again I will reopen this issue here.

Cheers, Tom
