### ISSUE TITLE
Question: Bundle size is 1MB?

### ISSUE THREAD

**Issue by timhwang21** [dherges/ng-packagr#575]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

If this is not the proper platform for questions, please let me know.

I am using `ng-packagr` with the Angular CLI to publish a component. However, when examining the bundled file, it is **1MB in size!** It seems like peer dependencies are being included in the bundle (specifically, React).

I feel I must be doing something wrong. My package has a single dependency (one lodash function), and everything else is a peer dependency.

* [Link to repo](https://github.com/timhwang21/react-to-angular)
* [Bundle](https://github.com/timhwang21/react-to-angular/blob/dist/dist/bundles/react-to-angular.umd.js)

Additionally, another issue (probably with the same root cause) is that my exported bundle does not correctly acceess imports, while they do in local development. I see related issues involving `lodash` and `moment`, but the solutions described there don't seem to solve my issue. Specifically, when bundling I get the following errors:

```
'render' is not exported by 'node_modules/react-dom/index.js'
'createElement' is not exported by 'node_modules/react/index.js'
```

I get these errors despite adding this to my config:

```
    "umdModuleIds": {
      "react": "React",
      "react-dom": "ReactDOM"
    },
```

#### How To Reproduce

```bash
git clone https://github.com/timhwang21/react-to-angular
cd react-to-angular
yarn install
yarn packagr
du -k dist/bundles/react-to-angular.umd.js
# 992
```

#### Expected Behaviour

When doing a traditional prod build with the Angular CLI, the output is about 200kb.

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.2.2
typescript: 2.5.3
rxjs: 5.5.6
node: 9.2.0
yarn: 1.2.1
```

**Comment by timhwang21** [comment]
So, it seems that I fixed this by adding the following to my `ng-package.json` config:

```
    "externals": {
      "react": "react",
      "react-dom": "react-dom"
    }
```

Is this the "correct" way to handle this? And if so, should the README include this? Thanks!

**Comment by dherges** [comment]
Hi @timhwang21,

there's some confusion about v1 that uses `lib.externals` and v2 which dropped `lib.externals` and split that into two `lib.embedded` and `lib.umdModuleIds`. Also in v2, dependencies are external by default.

**Comment by timhwang21** [comment]
Thanks for the quick response!

Do you think the readme can benefit from a note that it's for v2? Given that a "default" install of the library gives 1.6. Cheers!

**Comment by dherges** [comment]
I just want the v2 final rather sooner than later! 😄

**Comment by dherges** [comment]
But let's keep the issue as documentation also for people migrating from v1 to v2.
