### ISSUE TITLE
No name was provided for external module 'rxjs/util/TimeoutError' in options.globals – guessing 'TimeoutError$1'

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#579]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

No name was provided for external module 'rxjs/util/TimeoutError' in options.globals – guessing 'TimeoutError$1'

#### How To Reproduce

use `import { TimeoutError } from "rxjs/util/TimeoutError";`

#### Expected Behaviour
no warnings.

#### Version Information

```
ng-packagr: 2.0.0-rc.11

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by brunano21** [comment]
I have the same error but with other libraries, specifically with ng-bootstrap, ng2-cookies, ngx-translate and lodash-es.

This is my ng-packagr.json:
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "./src/public_api.ts",
    "externals": {
      "Cookie": "./node_modules/ng2-cookies/cookie.js",
      "@ngx-translate/core": "ngx-translate-core",
      "@ngx-translate/core/index": "ngx-translate-core"
    }
  }
}

```
and this is the `ng-packagr` output:
```
Building Angular Package
Building from sources for entry point 'myLib'
Cleaning build directory
Extracting templateUrl and styleUrls
Processing assets
Inlining templateUrl and styleUrls
Compiling with ngc
Writing flat bundle files
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
No name was provided for external module '@ngx-translate/core' in options.globals – guessing 'core$1'
No name was provided for external module 'ng2-cookies/cookie' in options.globals – guessing 'cookie'
No name was provided for external module 'lodash-es' in options.globals – guessing 'lodashEs'
No name was provided for external module '@ng-bootstrap/ng-bootstrap' in options.globals – guessing 'ngBootstrap'
Minifying UMD bundle
Remapping source maps
Copying staged files
Writing package metadata
Built myLib
Built Angular Package!
   - from: c:\Projects\myLib
   - to:   c:\Projects\myLib\dist
```

#### Version Information
```
ng-packagr: 2.0.0-rc12
@angular/*: 5.2.1
typescript: 2.4.2
rxjs: 5.5.2
node: 8.9.4
npm: 5.6.0
```

**Comment by alan-agius4** [comment]
For that you need to specify umdModuleIds

Have a look at the readme how to do that.

**Comment by brunano21** [comment]
@alan-agius4 
Can you make an example, please?

**Comment by alan-agius4** [comment]
Full description here
https://github.com/dherges/ng-packagr/blob/master/README.md

Example:

  {

"lib": {

    "umdModuleIds": {
      "lodash" : "_",
      "date-fns" : "DateFns",
    }
  }
}

**Comment by org-slashlib** [comment]
@alan-agius4
... I still can't figure out the way UMD module ids are resolved

When packaging "@org.slashlib/ng-services-i18n" with a peer dependency of "@org.slashlib/ng-services-core", this will result in <package>.umd.js:

(factory((global.org = global.org || {}, global.org.slashlib = global.org.slashlib || {}, global.org.slashlib['ng-services-i18n'] = {}),global.ng.core,global.ngServicesCore));

Same package scope => different result?

the following ng-package.json:
"umdModuleIds": {
      "@org.slashlib/ng-services-core": "@org.slashlib/ng-services-core"
 }
results in:
(factory((global.org = global.org || {}, global.org.slashlib = global.org.slashlib || {}, global.org.slashlib['ng-services-i18n'] = {}),global.ng.core,global['@org']['slashlib/ng-services-core']));

finally, this did the trick:
"umdModuleIds": {
      "@org.slashlib/ng-services-core": "org.slashlib.ng-services-core"
 }
Although this works, I would not have expected this.

It looks like package.json::name(s) and peer dependency package names are resolved in different ways?

**Comment by NicolasErices** [comment]
fix it by adding this umdModuleIds line to the ng-package.json

{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/webkit",
  "lib": {
    "entryFile": "src/public-api.ts",
    "umdModuleIds": {
      "ng-lottie": "ng-lottie"
    }
  },
  "whitelistedNonPeerDependencies": [
    "ng-lottie"
  ]
}

**Comment by sozakir** [comment]
https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers

for people seeing this thread
