### ISSUE TITLE
[v2] [migration] Can't find public_api.ts error after update ng-packagr-2.0.0

### ISSUE THREAD

**Issue by bozoh** [dherges/ng-packagr#591]
## Type of Issue
Can't find public_api.ts after update ng-packagr-2.0.0
```
[x] Bug Report
[ ] Feature Request
```

## Description

I have a project which libs source code is not in the default src folder (angular-cli), so my ng-package.json have this configuration
```javascript
{  
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json", 
  "src": "ng-br-tools",  
  "dest": "dist/ng-br-tools",  
  "workingDirectory": ".ng_build",  
  "lib": {  
    "entryFile": "src/public_api.ts"  
  }  
}
```

There is a `src` option set, but when i run ng-packagr it's seems to ignore it and tries to find public_api.ts in the default src folder,  but it's in  ng-br-tool/src folder.  
In the previous version it's uses `src` option to find the public_api.ts file.

#### How To Reproduce

- create a new project 
- create a folder call  foo/src
- put public_api.ts in it
- install  ng-packagr previous version
- add this ng-package.json configuration files
```javascript
{  
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json", 
  "src": "foo",  
  "dest": "dist/bar",  
  "workingDirectory": ".ng_build",  
  "lib": {  
    "entryFile": "src/public_api.ts"  
  }  
}
```
- run ng-packagr
- update to ng-packagr-2.0.0
- run ng-packagr again

#### Version Information

```
ng-packagr: 2.0.0
@angular/*: 1.6.6
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by deebloo** [comment]
@bozoh you listed your angular-cli version but not your actual angular version

**Comment by dherges** [comment]
Look the [migration notes](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#200-2018-02-05)

`src: "ng-br-tools"` has no effect any more.
