### ISSUE TITLE
How to create debug bundle?

### ISSUE THREAD

**Issue by hemalgondaliya** [dherges/ng-packagr#592]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description
I am trying to use my application as library for the other application, for that purpose i want to prepare the bundle which I can debug!

Currently in my debug mode  i can see the Modulename.ngfactory.js file.

I dont find any good solution.

#### Version Information

```
ng-packagr: 2.0.0
@angular: 5.1.3
typescript: 2.5.3
node: 8.9.4
npm: 5.6.0
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
Do you want to do something like:

```ts
export const DEBUG_TOKEN = new InjectionToken<boolean>('debug-token');

@NgModule({ .. })
export class ComponentModule {

  public static forDebugging(): ModuleWithProviders {
    providers: [ { provide: DEBUG_TOKEN, useValue: true } ],
    ngModule: ComponentModule
  }
}
```

Another option is to set a debugging flag like:

```ts
export let myLibraryInDebugMode: boolean = false;

export function enableLibraryDebugMode() {
  myLibraryInDebugMode = true;
}
```
