### ISSUE TITLE
Exported Typings file has services exports obfuscated

### ISSUE THREAD

**Issue by Kamalen** [dherges/ng-packagr#599]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

Final typings file (.d.ts) have autodetected my services and exported them but is renaming them, preventing easy import from client application.

```
export { StompService as ɵch } from './app/common/service/stomp/stomp.service';
export { ToolService as ɵx } from './app/common/service/tool/tool.service';
```

#### How To Reproduce

Use default configuration and export a module

#### Expected Behaviour

`export { StompService } from './app/common/service/stomp/stomp.service';`

## Question

Is there a missing configuration to allow the export as standard name ? Or is the full export of the lot in "public_api.ts" mandatory ?

Thanks for any help

**Comment by deebloo** [comment]
Angulars compiler does this for internal reasons. I'd you want then publically available yes you will have to export them from your public_api file

**Comment by janerikmai** [comment]
> I'd you want then publically available yes you will have to export them from your public_api file

@Kamalen Personally I had to export them in format: 

`export { FirstDirective, SecondDirective, FirstComponent, SecondComponent, FirstService, SecondService } from './app'; `

**after** exporting NgModule.

So wildcard exporting `export * from './app'` did not work as expected for me.

**Comment by Tyler-V** [comment]
Having a similar but possibly unrelated issue, something going on with enums

https://github.com/dherges/ng-packagr/issues/809
