### ISSUE TITLE
Question regarding third party files export

### ISSUE THREAD

**Issue by KedarMarathe1** [dherges/ng-packagr#604]
Question: How do i export third party JS/CSS file along with the final package?
for ex : assets/scripts or assets/css?
and also use them internally within the package

**Comment by dherges** [comment]
Do you like to do something like #336 ?

**Comment by KedarMarathe1** [comment]
Thanks for the help

one more question...
How do i refer the copied files internally within the package?
Can this be handled in the packagr?

**Comment by KedarMarathe1** [comment]
i need to use these external files within the module.
for ex - lets consider an image!
i copy the image file into the package manually.

Now i need to use it internally within the package
but the the image is searched under assets of the host application and not under the package.
Is there a way i can access the files within the package ?

**Comment by dherges** [comment]
I think that's not a concern of ng-packagr, isn't it?

SCSS extensions have support for [imports starting with a `~`](https://github.com/webpack-contrib/sass-loader#imports), e.g. the scss loaders for webpack support it.
