### ISSUE TITLE
Incorrect angular package format implementation

### ISSUE THREAD

**Issue by anjmao** [dherges/ng-packagr#608]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Hi @dherges  
In #600 I registered a bug report saying that bundles file names was changed in v2 and asked why it was needed. Reading from [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) doc  I see that scope is not added to any file name which seems correct and logical. Can you elaborate more that was the problem with previous files naming and is there any chance to fix it or should I fix it in forked repository? Thanks.

## Expected
Do not add npm scope name to any file in the bundle.

#### Version Information

```
ng-packagr: 2.0.0

**Comment by dherges** [comment]
The file name can be set through [`flatModuleFile`](https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json#L30-L34)

Change for UMD module ids is intentional.
