### ISSUE TITLE
[Question] Create library with multiple modules.

### ISSUE THREAD

**Issue by brunano21** [dherges/ng-packagr#609]
Hi,
I would like to create a library (only one repo) which exports multiple modules.
In theory something like:

```
myLib\
    ModuleA
    ModuleB
    ModuleC
```
so then in a separate project, I can use any of them independently, without importing the whole library as

```
import { ModuleA } from '@myLib/moduleA'
```

I do like also the idea how having an app within the same repo, where I can see the modules/components in operation, as for demo purposes

I was looking at ng-packaged project, but I can specify (this was my impression) an entryPoint only, so I cannot as many as I want.

Is Nx the only approach here?

**Comment by deebloo** [comment]
@brunano21 We have a single with multiple modules are work. what we do is we use npm link to make intermodule dependencies possible.

**Comment by brunano21** [comment]
@deebloo can you share your configuration, please?

**Comment by deebloo** [comment]
Let me see if I can share a vanilla repo with the setup

**Comment by brunano21** [comment]
@deebloo I will much appreciate! Have you done also the setup for tests for each module?

**Comment by alan-agius4** [comment]
We have a similar setup at work as well. 

This might also help you out: https://github.com/alan-agius4/ng-mono-repo-starter

**Comment by dherges** [comment]
EH, is it a question for multi libaries or is the question for multiple entry points?

Or are you saying that dependencies from one library on the other? Example: `@foo/one` depends on `@foo/two` (inter-package dependency) or `@foo/one/two` depends on `@foo/two/three` (intra-package deps)?

**Comment by dherges** [comment]
If it's just about multiple libraries / packages, see https://github.com/dherges/nx-packaged

**Comment by brunano21** [comment]
@dherges it's about a library with multiple modules/packages..

@alan-agius4 thanks, I'll take a look!

**Comment by brunano21** [comment]
@dherges let's suppose my libs have some code in common and I would like to move it into its own lib and then import it? How could I achieve that?

**Comment by deebloo** [comment]
hey @brunano21 I haven't had time to get our seed up on github yet. but in theory what you would do is.

```BASH
ng-packagr -p packages/common && npm link packages/common
```

then your other packages would be able to import from common

**Comment by brunano21** [comment]
@deebloo 
@all have you ever experienced wrong path imports into IntelliJ?
Although I have followed step-by-step the whole "guide" I notice that when using IntelliJ auto-import feature, the package is resolved like `../.../my-lib/my.lib.module` instead of `@my/lib`. @dherges any thoughts about that?

**Comment by deebloo** [comment]
@brunano21 this is the repo setup we are currently using at work. https://github.com/deebloo/ng-libs-seed.

As far as auto imports i'm not sure how to handle that

**Comment by dherges** [comment]
Intra-package dependencies (e.g. `@foo/bar/one` depends on `@foo/bar/two`) are currently not supported. Relevant issue is #379 

Inter-package dependencies (e.g. 'foo' depends on 'bar') can be mimicked by publishing 'bar'  to local `node_modules` before building `foo`. It's a workaround. A dedicated issue for that would be great to discuss how it may be added to ng-packagr :-)

**Comment by dherges** [comment]
Experimental support will be added in #685

**Comment by brunano21** [comment]
🥇

**Comment by rojasjandro89** [comment]
I guess ng-packagr is only useful to create a simple library and when I say simple I mean a single bundle with a single module. I still don't understand why the angular team decided to use it as the official packaging tool for libraries. It doesn't give you the option to include specifically dependencies into the final bundle and it has no apparent means to export more than one module...

**Comment by dherges** [comment]
go make it better? 😆 📈

**Comment by alan-agius4** [comment]
Hi @rojasjandro89, I am not quite understanding what you mean by

>  specifically dependencies into the final bundle and it has no apparent means to export more than one module...?
