### ISSUE TITLE
ng-packagr does not export angular interfaces

### ISSUE THREAD

**Issue by luiscontrerasm** [dherges/ng-packagr#613]
## Type of Issue

Either a bug or a feature request

[ ] Bug Report
[X] Feature Request

## Description
Im trying to export an interface to the package in order to can be imported somewhere else.
Im doing this on the public_api.ts file and i get everything exported but the interface.

PUBLIC API
```
export { SearchbarLibModule } from './src/app/searchbar-lib/searchbar-lib.module';
export { SearchbarInterface, SearchbarInterfaceInitialState } from './src/app/store/searchbar.store';
export { searchbarReducer } from './src/app/store/searchbar.reducers';
```

Interface code

```
import { SearchOption, SearchOptionInitialState } from '../shared/searchbar/searchbar.model';
import { FilterOption, FilterOptionInitialState } from '../shared/dialog-modal/filter.model';

interface SearchbarInterface {
  searchInterface: SearchOption;
  filterInterface: FilterOption;
}

const SearchbarInterfaceInitialState: SearchbarInterface = {
  searchInterface: SearchOptionInitialState,
  filterInterface: FilterOptionInitialState
}

export { SearchbarInterface, SearchbarInterfaceInitialState };
```

#### How To Reproduce

Just try to add an interface export in the public api and you will check why is not importing.

#### Expected Behaviour

_for bugs: please describe what behaviour or result you expected_

_for features: do you have a first draft or an idea how to implement?_

#### Version Information

ng-packagr: 1.6.0
@angular/*: 1.3.0
typescript: 2.3.3
rxjs: 5.4.2
node: 8.9.3
npm/yarn: 5.0.0

Im using the https://github.com/angular-redux/store for handling redux in my project.

**Comment by alan-agius4** [comment]
You are trying to export the interface as an object that’s why its not exported.

You should probably change the files contents to;

‘’’ts
import { SearchOption, SearchOptionInitialState } from '../shared/searchbar/searchbar.model';
import { FilterOption, FilterOptionInitialState } from '../shared/dialog-modal/filter.model';

exported interface SearchbarInterface {
  searchInterface: SearchOption;
  filterInterface: FilterOption;
}

export const SearchbarInterfaceInitialState: SearchbarInterface = {
  searchInterface: SearchOptionInitialState,
  filterInterface: FilterOptionInitialState
}
‘’’

**Comment by dherges** [comment]
Hi @luiscontrerasm,

I tried to reproduce your issue but according to the changes in https://github.com/dherges/ng-packagr/commit/251dcfbf8e7e6c05ee821870f9ca0dd17699bdc4 the `export { Foo, Bar }` constructs are working.

**Comment by dherges** [comment]
See here:

![screen shot 2018-02-11 at 18 40 41](https://user-images.githubusercontent.com/901354/36076340-1c09afc2-0f5b-11e8-8979-03ebaa91c303.png)

**Comment by luiscontrerasm** [comment]
@dherges Hello, i already have the interface added to a const and initialize the values. That works fine, what i am not received is the interface.

```
import { SearchOption, SearchOptionInitialState } from '../shared/searchbar/searchbar.model';
import { FilterOption, FilterOptionInitialState } from '../shared/dialog-modal/filter.model';

THIS IS NOT GETTING EXPORTED
interface SearchbarInterface {
  searchInterface: SearchOption;
  filterInterface: FilterOption;
}

THIS IS GETTING EXPORTED
const SearchbarInterfaceInitialState: SearchbarInterface = {
  searchInterface: SearchOptionInitialState,
  filterInterface: FilterOptionInitialState
}

export { SearchbarInterface, SearchbarInterfaceInitialState };
```

Why do i need the interface without initialization ? because i'm working with redux, and i need the interface of this app to added in another one like this:

```
interface AppStoreInterface {
  mainLayoutInterface: MainLayoutInterface;
  authInterface: AuthInterface;
  aclInterface: AclInterface;
  themeInterface: ThemeInterface;
  masterAclInterface: MasterAclInterface;
}

/*
 * Build the initial state of all the app interfaces
 */
const INITIAL_STATE: AppStoreInterface = {
  mainLayoutInterface: MainLayoutInterfaceInitialState,
  authInterface: AuthInterfaceInitialState,
  aclInterface: AclInterfaceInitialState,
  themeInterface: ThemeInterfaceInitialState,
  masterAclInterface: MasterAclInterfaceInitialState
};
```

I need to add to the big interface i build here the search bar interface into the redux store creator

```
export class AppModule {
  /**
   * @param  {NgRedux<AppStoreInterface>} ngRedux  [ For declaring the app interface ]
   * @param  {DevToolsExtension}          devTools [ Browser plugin extension for debuggin redux]
   */
  constructor(
    ngRedux: NgRedux<AppStoreInterface>,
    devTools: DevToolsExtension
  ) {
    // Preparing the plugin
    const storeEnhancers = devTools.isEnabled() ? [devTools.enhancer()] : [];

    // Creating the store
    ngRedux.configureStore(
      rootReducer,
      INITIAL_STATE,
      [],
      storeEnhancers
    );
  }
}
```

So when i try to get the search bar interface from the searbar package folder, is not there.
The reducer is there, but the interface dont.

How can i solve this?
@dherges Thank you for answering.

**Comment by alan-agius4** [comment]
Can you try to export the interface directly? 

Example:

```ts
export interface SearchbarInterface {
}
```

As to be honest I am not sure if Angular Compiler accets your kind of exports.

**Comment by luiscontrerasm** [comment]
@alan-agius4 Hello! i already try that, i dont that is the problem :/

**Comment by alan-agius4** [comment]
I saw that you are using ng-packagr 1.6.0, can you try to update to 2.0.0?

**Comment by luiscontrerasm** [comment]
@alan-agius4 Let me try. I hope this can solve the problem.

**Comment by dherges** [comment]
If it still fails, can you try to reproduce in the code i mentioned above?

**Comment by ukaaa** [comment]
I'm struggling to export interfaces. Can someone please explain how a user of my Angular package can import an interface from it?

I tried putting the following in my `public_api.ts` but without success:
```typescript
export { Tab } from './src/app/tabs/tab';
```

**Comment by Tyler-V** [comment]
Any insight into this? Also curious on how to properly package interfaces / enums so users can import them directly from the npm name space.

**Comment by alan-agius4** [comment]
Can someone do a reproduction of this issue please? Also can you please highlight which versions of dependencies are you using example, are you using `ng-packagr` 2.x.x?

**Comment by inthegarage** [comment]
@alan-agius4 
I see it when I try to export something with interface/enum and then later in the public_api file I then include a module. I think the previous line(s) are being forgotten about or overwitten.

**Comment by hei-pa** [comment]
I have same issue like @ukaaa. Any progress on this?

**Comment by duydnguyen07** [comment]
I think I have found a work around for this. What I have done is to export a dummy service class in the same folder of my interfaces like so:

```
export interface DropdownItemInterface {
  value: string;
  viewValue: string;
}

...

export class MyService {}
```

And then in my `app.module.ts`, I'm exporting the service using the following:

```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { MyService } from './my_interfaces_with_dummy_service.ts'

...

export class CommonLibModule { 
  /** 
   * This code is purposely left here for future use
   */
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: CommonLibModule,
      providers: [MyService]
    };
  }
}
```
This will make ng-packagr generate a .d.ts file of the service.ts file and include/export your interfaces along in it. 

Hope this helps! =)

**Comment by mehrta** [comment]
> I'm struggling to export interfaces. Can someone please explain how a user of my Angular package can import an interface from it?
> 
> I tried putting the following in my `public_api.ts` but without success:
> 
> ```ts
> export { Tab } from './src/app/tabs/tab';
> ```

Export your components, modules, services DIRECTLY, not from index.ts:
**replace:**
export { Tab } from './src/app/tabs/tab';

**with something like this:**
export { TabModule } from './src/app/tabs/tab/tab.module';
