### ISSUE TITLE
Reduce bundle size for components

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#614]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```
#### Decription
Reduce final bundle size for compents.

The main reason of this is that Uglify JS is unable to remove new lines, extra spaces in `css` and new lines can be dropped in html as these don't have any effect.

example
```js
    SkeletonComponent.decorators = [
        { type: core.Component, args: [{
                    selector: "obg-skeleton",
                    template: "<h1>Sample</h1>\n\n<p>some text</p>",
                    styles: [":host {\n  display: block; }\n"]
                },] },
    ];
```

#### How To Behavior
Create a component that uses external HTML and CSS. You will notice a lot of white space and new lines in css and new lines in html. 

#### Expected Behaviour
That css and html is minified.

#### Version Information
```
ng-packagr:2.0.0
```

**Comment by dherges** [comment]
Hi Alan,

for CSS, i think it's a safe change. For the html, I doubt whether it is safe. I think removing whitespace (by default) will result in broken libraries as whitespace has an effect on browser rendering.

Isn't it a better idea to use ngc `preserveWhitespace` option? Imho, I would reccomend to turn on/off `preserveWhitespace` per component as the display behaviour is dependent on the component's HTML template.

Beside, how much is the benefit? Isn't the library code later processed (and optimized?) by an app's build? I know that we're relying on the users (Angular CLI, webpack, whatever) to do some optimizations but as long as it's a common practice I wouldn't like to risk breaking existing builds here.

**Comment by alan-agius4** [comment]
Well, for html i am only removing breaklines which are not removed by
turning ‘preserveWhiteSpaces’ to false, the problem here is that the css
and html are inside the Javascript so pretty much any bundler won’t be able
to optimize that later on, as none of the css/html optimization plugins can
run JS for example.

If you take a look at other libs such as Angular Material you can see that
prior to shipping it, they optimize these as well As you can see for
example there are now new lines anywhere;
https://github.com/angular/material2-builds/blob/master/esm2015/button.js

And they are dopping breaks here;
https://github.com/angular/material2/blob/master/tools/package-tools/inline-resources.ts

Apart from that they have the preserveWhiteSpaces turned off, but I agree
that, that flag can be turned on when creating a component.

**Comment by alan-agius4** [comment]
Just confirmed that `Build Optimizer` doesn't optimize this as well.  This is my final output for styles when building `AOT` and with `Build Optimizer`

```js
styles:["obg-accordion-header[_ngcontent-%COMP%], [obgAccordionHeader][_ngcontent-%COMP%]{\n  display:block;\n  -webkit-transition:-webkit-transform 200ms;\n  transition:-webkit-transform 200ms;\n  transition:transform 200ms;\n  transition:transform 200ms, -webkit-transform 200ms;\n  -ms-touch-action:manipulation;\n      touch-action:manipulation;\n  contain:content;\n  -webkit-transform:translateZ(0);\n          transform:translateZ(0); }\n\nobg-accordion[_ngcontent-%COMP%], obg-accordion-content[_ngcontent-%COMP%]{\n  display:block; }\n\nobg-accordion-content[_ngcontent-%COMP%]{\n  contain:content;\n  -webkit-transform:translateZ(0);\n          transform:translateZ(0);\n  overflow:hidden; }"]
```

**Comment by peterbakonyi05** [comment]
I also noticed this issue, it would be great to minify the generated CSS before adding it to `styles`

**Comment by alan-agius4** [comment]
@dherges, thoughts and way forward?

**Comment by dherges** [comment]
Wll be in next verson, i.e. 2.2.x
