### ISSUE TITLE
Support commonjs dependencies, e.g. class-transformer

### ISSUE THREAD

**Issue by sforner405** [dherges/ng-packagr#62]
We use ng-packagr for packaging a Angular 4 Module. 
Unfortunately it does not work with the import of class-transformer. It states the nodemodule/class-transfomer does not define / export plainclass. 
If we use EmptyObservable from Rxjs the same problem occurs. 
Is there a solution for it?

Thanks.

**Comment by sforner405** [comment]
A link to the class-transfomer project. 
https://github.com/pleerock/class-transformer

**Comment by dherges** [comment]
What exactly is not working?

**Comment by sforner405** [comment]
We get the following error:
`'classToPlain' is not exported by node_modules/class-transformer/index.js
Error: 'classToPlain' is not exported by node_modules/class-transformer/index.js
`

Import in the service is:
`import { classToPlain, plainToClass } from "class-transformer";`

and the ng-package.json :
`{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "src": "src",
    "dest": "dist",
    "workingDirectory": ".ng_build",
    "lib": {
        "entryFile": "app/core/core.module.ts"
    }
}`

**Comment by dherges** [comment]
Can you please provide more context?

Can you run the build with `DEBUG=true` env variable? E.g. in pcakge.json:

```json
  "scripts": {
    "build": "DEBUG=true ng-packagr"
  }
```

Is the issue caused by rollup? If yes, is this an issue with `class-transformer` because it does not support ES2015 modules?

**Comment by sforner405** [comment]
We get the following debug message:

[debug] rimraf /home/project_wizard_ui/dist
[debug] rimraf /home/project_wizard_ui/.ng_build
[debug] processAssets /home/project_wizard_ui/src to /home/project_wizard_ui/.ng_build/ts
[debug] render stylesheet /home/project_wizard_ui/src/app/app.component.css
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/app.component.css
[debug] render stylesheet /home/project_wizard_ui/src/app/project-steps-activation/project-steps-activation.component.scss
[debug] rendering sass for /home/project_wizard_ui/src/app/project-steps-activation/project-steps-activation.component.scss
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/project-steps-activation/project-steps-activation.component.scss
[debug] render stylesheet /home/project_wizard_ui/src/app/project-steps-partner/project-steps-partner.component.scss
[debug] rendering sass for /home/project_wizard_ui/src/app/project-steps-partner/project-steps-partner.component.scss
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/project-steps-partner/project-steps-partner.component.scss
[debug] render stylesheet /home/project_wizard_ui/src/app/project-steps-personaldata/project-steps-personaldata.component.scss
[debug] rendering sass for /home/project_wizard_ui/src/app/project-steps-personaldata/project-steps-personaldata.component.scss
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/project-steps-personaldata/project-steps-personaldata.component.scss
[debug] render stylesheet /home/project_wizard_ui/src/app/project-steps-vehicle/project-steps-vehicle.component.scss
[debug] rendering sass for /home/project_wizard_ui/src/app/project-steps-vehicle/project-steps-vehicle.component.scss
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/project-steps-vehicle/project-steps-vehicle.component.scss
[debug] render stylesheet /home/project_wizard_ui/src/app/spa/spa.component.scss
[debug] rendering sass for /home/project_wizard_ui/src/app/spa/spa.component.scss
[debug] postcss with autoprefixer for /home/project_wizard_ui/src/app/spa/spa.component.scss
[debug] ngc /home/project_wizard_ui/.ng_build/ts/tsconfig.lib.json, { basePath: /home/project_wizard_ui/.ng_build/ts })
[debug] re-mapping sources for /home/project_wizard_ui/.ng_build/ts/wizard_core.js
[debug] rollup /home/project_wizard_ui/.ng_build/ts//wizard_core.js to /home/project_wizard_ui/.ng_build/undefined/project-wizard-core/wizard_core.js (es)

BUILD ERROR
'classToPlain' is not exported by node_modules/class-transformer/index.js
Error: 'classToPlain' is not exported by node_modules/class-transformer/index.js
    at error (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:8306:2)
    at Module.trace (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:8407:9)
    at ModuleScope.findDeclaration (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:7990:22)
    at Scope.findDeclaration (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:5805:39)
    at Node.bind (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:6335:28)
    at /home/project_wizard_ui/node_modules/rollup/dist/rollup.js:5599:50
    at Node.eachChild (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:5613:21)
    at Node.bind (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:5599:7)
    at Node.bind (/home/project_wizard_ui/node_modules/rollup/dist/rollup.js:6353:23)

This is the tsconfig from class_transfomer :

{
    "version": "1.8.0",
    "compilerOptions": {
        "outDir": "build/es5",
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "declaration": true
    },
    "exclude": [
        "build",
        "node_modules"
    ]

**Comment by sforner405** [comment]
So I think commonjs is maybe the problem?
Is there a possibility to map the commonjs to es modules like 
https://github.com/rollup/rollup-plugin-commonjs
?

**Comment by dherges** [comment]
Hm, ok. Would it be possible to reproduce this w/ one of the samples ion the `integration` folder?

From first look, it should be relatively easy to add the plugin to rollup. Just the question is: does it break anything else?

https://github.com/rollup/rollup-plugin-commonjs#usage

https://github.com/rollup/rollup-plugin-node-resolve#using-with-rollup-plugin-commonjs

**Comment by DDeis** [comment]
Hi @sforner405, have you tried to add `"class-transformer/index": "class-transformer"` to `externals` in `ng-package.json` ?

**Comment by sforner405** [comment]
Hi @DDeis ,
unfortunately I ad still no time looking at the problem again, but I will do it this week and give feedback here.

**Comment by dherges** [comment]
Ok. So we have progress here.

A quick recpature of #83: 
 - in a library, we do not want to include the dependency in the generated bundle
 - the dependency should be stated in `peerDependencies`
 - consumers of the library are resposible to add a correct `dependencies` section satisfying peers
 - reason is: a dependency should be included only once in an app's bundle so the library (and thus ng-packagr) *MUST NOT* include it in a bundle; they just need the dependency for compile-time validation.

If you have any uddates on how commonjs supported can be implemented, let me know!

**Comment by ronnyek** [comment]
I think this probably more likely falls under that workign with third party dependencies, but I cant comment there... to be able to reference / wrap ngx-datatable (@swimlane/ngx-datatable) with my prior build configuraiton, I'd reference from libraries package.json as a peerDependency, but also had to add to my rollupconfig

```
plugins: [
    nodeResolve({ modulesOnly: true, jsnext: true, module: true }),
    commonjs({
      include: ['node_modules/rxjs/**', 'node_modules/@swimlane/**']
    })
  ]
```

With ng-packager, it seems like referencing as purely peerDependency, with nothing in externals, kinda works... at least ng-packager successfully compiles... but when trying to use my wrapping component, it is trying to resolve that 3rd party lib in a really wonky way.

I tried both with and without this
```
 "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@swimlane/ngx-datatable/index": "@swimlane/ngx-datatable"
    }
  }
```
 And both situations compile library wise... but consuming I get this error when trying to build test app
```
ERROR in ./dist/design/design.es5.js
Module not found: Error: Can't resolve '@swimlane/ngx-datatable/index' in 'C:\Users\user\Source\Repos\FrontEnd\dist\design\@my'
 @ ./dist/design/@my/design.es5.js 27:0-67
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by dherges** [comment]
@ronnyek Gosh, now I understand!

This is same as #101. Cause is somewhere in [ngc and tsickle](https://github.com/angular/angular/issues/16084#issuecomment-295761766).

I can't really tell why sometimes the app builds still works (there are several app builds that seem to work `@ngx-translate/core/index`...) and why sometimes it does not.

**Comment by ronnyek** [comment]
@dherges is there an existing work around for this? I tried something along the lines of this:
 "@swimlane/ngx-datatable/index": "@swimlane/ngx-datatable",
      "@swimlane/ngx-datatable": "@swimlane/ngx-datatable"

After reading somone suggesting something like that for ngx-translate. Should I just disable annotateForClosureCompiler?

**Comment by dherges** [comment]
Hi @ronnyek,

you cannot disable `annotateForClosureCompiler` as this is setting us automatically set during the build. It is a best practice reco from Json Aden's talk (see project readme).

Please let's discuss this further in #101
