### ISSUE TITLE
AOT Compiling - Not A bug

### ISSUE THREAD

**Issue by AdamKernig** [dherges/ng-packagr#636]
Hi, im trying to look through the docs but unfortunately unable to find how to package in an AOT manor, I am probably missing something or lacking knowledge but if anyone could advise that would be grateful!

Adam

**Comment by deebloo** [comment]
@AdamKernig since ng-packagr uses the angular compiler under the hood everything will be AOT compatible.

**Comment by AdamKernig** [comment]
What im saying is there anything i need to do with ng packagr.

For example on ng build it does jit. On ng build --aot it builds in aot. Is
there anything packagr needs to do to build the aot version

**Comment by deebloo** [comment]
@AdamKernig no. that is what I am trying to say. running ng-packagr builds with the compiler which means it is AOT compatible. No need to do anything else

**Comment by AdamKernig** [comment]
Does packagr by default use AOT apologies if its confusing im just trying
to get a grasp

**Comment by deebloo** [comment]
yes. sorry if I am just trying to explain WHY this is the true. Yes it uses AOT by default

**Comment by AdamKernig** [comment]
That is absolutely wonderful thank you for the help

**Comment by kenperregaux** [comment]
Why then does it not show errors / warnings? If I run ng build --aot, I get an warning, but if I run ng-packagr I do not.

**Comment by deebloo** [comment]
@kenperregaux if that is the case then we are going to need more information about your issue to help. what versions of the cli and ng-packagr are you using. what error are you seeing?

**Comment by kenperregaux** [comment]
Angular CLI: 1.7.0
Node: 9.3.0
Angular: 5.2.5

I have a simple component library that just shows a header like the article by Nikolas LeBlanc. However, just to see if the AOT would show errors like it does with ng build --aot I added a private function that doesn't get called. Our tsconfig is the following.
{
	"compileOnSave": false,
	"compilerOptions": {
		"outDir": "./dist/out-tsc",
		"sourceMap": true,
		"declaration": true,
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"target": "es5",
		"strict": true,
		"noUnusedLocals": true,
		"typeRoots": [
			"node_modules/@types"
		],
		"lib": [
			"es2017",
			"dom"
		]
	}
}

The error that should show up is ...
ERROR in src/app/components/header/header.component.ts(18,10): error TS6133: 'funcname' is declared but never used.

**Comment by deebloo** [comment]
@kenperregaux it is telling you what the error is right there. It is a typescript compiler setting either use "funcname", remove it, or update your compiler settings in your project

**Comment by kenperregaux** [comment]
@deebloo, thanks but I'm not sure I follow. If the error shows up when running ng build --aot (or --prod) and you use AOT what do I have to do different to get it to show up running this?

**Comment by deebloo** [comment]
@kenperregaux you have to use your own tsconfig. I think it is important here to identify exactly what AOT is. AOT mode for angular precompiles all of your templates using a tool called `ngc` which is a drop in replacement for typescript. this means that when the AOT compiler is run it is running the typescript compiler which is why the compiler options in your tsconfig matter. The error you are seeing isn't an error in angular template compilation but a general typescript error because of settings you have in your tsconfig. Those setting you are using in your cli project are not necessarily the setting that ng-packagr is using by default

**Comment by deebloo** [comment]
the api looks something like this.

```TS
ngPackagr()
  .withTsConfig('path/to/tsconfig.json')
  .build()
```

**Comment by kenperregaux** [comment]
Ah, thanks @deebloo.

**Comment by deebloo** [comment]
@kenperregaux no problem I hope it was helpful

**Comment by kenperregaux** [comment]
Sorry last question and it may be stupid...but where do I find all these options?

**Comment by JanEggers** [comment]
I think what @kenperregaux is searching for is a way to generate an aot bundle, (like i do).

I just had a look at the stats of my ng cli app that consumes a npm bundled with packagr. and that lib still references the angular compiler and does not contain any component factories.

but that is what i would expect if it was compiled aith aot

**Comment by AbhilashThomas** [comment]
How can use tsc instead of ngc?
