### ISSUE TITLE
[Question] How to Test lib using ng-packaged

### ISSUE THREAD

**Issue by ankeshdave** [dherges/ng-packagr#638]
## Type of Issue
How to Write unit tests for created Library

## Description
How run unit test with are written as a part of the library folder in `ng-packaged`.

##Error
```
Uncaught Error: Module build failed: Error: <Folder Location>\\<my-lib-root>\\<my-lib>\\src\\my-component\\my-component.component.spec.ts is missing from the TypeScript compilation.
Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

I can seem to run this with the default `Angular-Cli` `ng test` command @dherges

**Comment by dherges** [comment]
Ah, I haven't checked for a lomng time the "ng-packaged" demo. It works well in nx workspace so you want to [have a look at the `test.js` scripts from nx](https://github.com/dherges/nx-packaged/blob/master/test.js)?

**Comment by cmckni3** [comment]
I am running into the same problem. Used the `ng-packaged` demo as an example. Should I switch to using nx?

**Comment by joerossetter** [comment]
i was able to solve a similar issue with tests by downgrading my `jasmine-core` package to `2.9.9`

**Comment by cmckni3** [comment]
I am runnin `jasmine-core` 2.8.0 in my project itself. Looks like `ng-packagr` pulls in `jasmine-core` 2.9.1.

**Comment by cmckni3** [comment]
`jasmine-core` 2.9.9 doesn't exist. 2.9.1 is the latest. Still doesn't work with 2.9.1. I also up

My project: https://github.com/andyperlitch/ngx-super-table
