### ISSUE TITLE
[Question ]Merge ts files from node_modules into dist package.

### ISSUE THREAD

**Issue by miloszsobczak** [dherges/ng-packagr#640]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

I'd like to embed node_modules' ts files into destination package.

#### How To Reproduce
Consider following application architecture:
```
src
----app
--------src
-----------sub-module
-----------------------sub.module.ts
-----------------------sub.component.ts
-----------------------sub.component.scss
-----------main.module.ts
-----------package.json
--------dist
node_modules
----external_ts_module
-----------------------external-component.ts
```

I want to extend my sub.component.ts using external-component.ts:
```
import {
  Component
} from '@angular/core';
import { ExternalComponent } from 'external_ts_module/external-component';

@Component({
  selector: 'sub-component',
  template: '<div>I'm subcomponent inherited from external-component</div>',
  styleUrls: ['./sub.component.scss']
})
export class SubComponent extends ExternalComponent {
}
```
package.json
```
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "name": "MY_PACKAGE",
  "version": "1.0.0",
  "ngPackage": {
    "lib": {
      "entryFile": "main.module.ts"
    }
  },
  "dependencies": {
    "external_ts_module": "1.0.0"
  }
}
```
I this scenario package compiles, but doesn't embedd external_ts_module in order to compile those files as well.

#### Expected Behaviour

Have u any ideas how to accomplish compilation with external ts files?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.1.0
@angular/compiler:     5.2.6
@angular/compiler-cli: 5.2.6
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.6.2
```

**Comment by dherges** [comment]
There are threadsand discussions on other github isuse trackers whether publishing `*.ts` sources in npm packages is a "good idea" or a "bad idea". The most common answer is that it's a bad idea as it has drawbacks and some tools don't even support loading `*.ts` sources from a `node_modules` folder afaik.

**Comment by miloszsobczak** [comment]
thanks @dherges for answering. Yeah, I totally understand common problem with that architecture. There are some prons as well (such as inheritance from *.ts).

So I guess the simplest way to achieve this, would be copying node_modules *.tss into main directory in prebuild time?
