### ISSUE TITLE
Error encountered in metadata generated for exported symbol [Fixed]

### ISSUE THREAD

**Issue by fourctv** [dherges/ng-packagr#641]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

Building my module I got error `Error encountered in metadata generated for exported symbol...` for some of my service classes/components. It affected only those Service classes with static methods/variables.

#### How To Reproduce

Any .ts file in the project that exports a class without metadata, and includes static methods/variables, like many Service classes, generate that error.

#### Expected Behaviour

Prior versions of ng-packagr built fine. It started breaking with the latest versions of ng-packagr and ngc.

## How to FIX it

This issue seems to be related to Angular issue `https://github.com/angular/angular/issues/18867`, which also provides a way to fix that.

All one needs to do is to add '// @dynamic' before the class that declares static methods, as in:
```
// @dynamic
export class SomeClass {
    public static foo() { return 'bar'; } 
}
```

**Hope this helps someone else that encounters the same error.**

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.0.2
@angular/*: 5.2.5
typescript: 2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by fourctv** [comment]
Not really an issue, but an issue fix.

**Comment by dherges** [comment]
https://github.com/angular/angular/issues/18867

**Comment by dherges** [comment]
Hi @fourctv, cool you figured it out! I labelled it as "documentation" so that others can find it! Thank you!

**Comment by volkanokcu** [comment]
Thank you fixed my issue.

**Comment by sharikovvladislav** [comment]
You helped me to fix my issue too.

```
// @dynamic
@NgModule({
  ...
})
export class SomeModule {
```

I had to add dynamic before `@NgModule`
