### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by jogelin** [dherges/ng-packagr#65]
Hello,

Do you planify to manage multiple library in one repo ? It is very useful when you work in a enterprise world ;).

This seed https://github.com/shlomiassaf/angular-library-starter has good ideas about that by using scope, sub library, etc...

**Comment by dherges** [comment]
@jogelin We actually do so w/ our internal projects at my employer. The integration samples in this repo are also like a "monorepo".

The structure basically looks like this:

```
|- packages
   |- a
      |- package.json
      |- ng-package.json
   |- b
      |- package.json
      |- ng-package.json
   |- c
      |- package.json
      |- ng-package.json
|- package.json // <-- shared dependencies and devDepenendencies for sub-projects
```

**Comment by jogelin** [comment]
I think it's a very good structure. But do you planify to manage those libraries in a common way ? I mean having common feature like: 

* Inherit from the parent package.json: during the build, be able to inject in the package.json some properties like author, repo, license, ...
* Be able to manage local version with placeholders like angular team is doing. If a library depends on another local one, the version is injected in the package.json
* Give the possibility to inherit other configurations like tests,
* Some scripts/command to synchronize libraries configurations like doing npm install in each library or synchronize the tsconfig or rollup file file, etc... usually, it is a bootstrap command
* Some scripts/command to be able to execute a command in each library
* The hooks of [angular-library-starter](https://github.com/shlomiassaf/angular-library-starter) is also very useful to interact with configurations and to avoid file multiplication !
* ...

**Comment by dherges** [comment]
> - Inherit from the parent package.json: during the build, be able to inject in the package.json some properties like author, repo, license, ...
> - Be able to manage local version with placeholders like angular team is doing. If a library depends on another local one, the version is injected in the package.json

No. Right now, we do this as a separate build step after the compilation.

> Give the possibility to inherit other configurations like tests,

First, a testing command needs to be implemented with `ng-packagr`.

> - Some scripts/command to synchronize libraries configurations like doing npm install in each library or synchronize the tsconfig or rollup file file, etc... usually, it is a bootstrap command
> - Some scripts/command to be able to execute a command in each library

I see this out-of-scope for `ng-packagr`. I hope for yarn workspaces to give some good tooling for that. Either way, I think this should be handled by another tool - whether that is yarn, or lerna, or builder, or whatever. https://staltz.com/setting-up-a-javascript-monorepo.html

**Comment by dherges** [comment]
Or, [OAO](https://github.com/guigrpa/oao) looks like it does what you mentioned. It runs command per sub-project.

**Comment by dherges** [comment]
@jogelin I also wrote about "publishing workflow" in the [design doc](../blob/master/DESIGN.md#package-definition-and-librarymetadata)

I hope this makes it clear that ng-packagr is a small, focused, opinionated tool.

I'll close this issue ftb. Feel free to re-open in case there are more questions!
