### ISSUE TITLE
Build error with rollup-plugin-commonjs library

### ISSUE THREAD

**Issue by sopretty** [dherges/ng-packagr#657]
## Type of Issue

```
[x] Bug Report
```
## Description

There is a new release on "rollup-plugin-commonjs" library causing some troubles: 
v8.4.0 : https://github.com/rollup/rollup-plugin-commonjs/releases 
```
BUILD ERROR
parse is not a function in /Users/../project/.ng_pkg_build/project/out/project.js
TypeError: parse is not a function in /Users/../project/.ng_pkg_build/project/out/project.js
    at error (/Users/../project/node_modules/rollup/dist/rollup.js:170:15)
    at /Users/../project/node_modules/rollup/dist/rollup.js:17548:17
    at <anonymous>

```
#### How To Reproduce

Create an angular-cli project, install ng-packagr (+ set up files) and run "ng-packagr -p ng-package.json".

#### Version Information

Deps versions

```
ng-packagr: ^2.1.0,
@angular/*: ^5.2.0
typescript: 2.5.3
```
#### Temporary Fix

To fix it temporarily, I added  "rollup-plugin-commonjs": "8.3.0"  in my devDependencies to override the new version.

**Comment by AlejandroMoran** [comment]
@sopretty Having the same issue, your temporary solution works, thanks.

**Comment by bodyasakalo** [comment]
if you are using yarn add this to package.json
`"resolutions": {
    "rollup-plugin-commonjs": "8.3.0"
  }`

**Comment by eromano** [comment]
maybe should be pinned those versions inside the package.json :

```json
   "rollup": "^0.55.0",
    "rollup-plugin-cleanup": "^2.0.0",
    "rollup-plugin-commonjs": "^8.2.1",
    "rollup-plugin-license": "^0.5.0",
```

without wildcard

**Comment by avatsaev** [comment]
Same issue here, couldn't figure out where the problem was coming from.

Let's hope the PR gets merged soon.

**Comment by skaughtx0r** [comment]
Forcing ng-packagr to use rollup 0.56.0 (manually edited the package.json after npm install) also seems to fix this error. Current version of ng-packgr on npm is unusable due to this error.

**Comment by karel88** [comment]
Temporary fix with fixed versions for rollup is working.
