### ISSUE TITLE
environment.ts files being changed to const environements in code.

### ISSUE THREAD

**Issue by nathanhokanson** [dherges/ng-packagr#666]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

By following Nikolas LeBlanc's excellent tutorial I was able to get a package created from a standard angluar-cli project.  However, when I execute the ng-packagr command the resultant js has the environment in it as a const.  This value should be provided by the application consuming the package, rather than the package itself.

Please note that I _am_ including the environments file in the service that I am exporting, so it makes sense that the file is getting written as part of the js, however, I don't believe this should be the case specifically with environments files.

```
import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';

import {environment} from '../environments/environment';
import {Observable} from 'rxjs/Observable';

@Injectable()
export class DemoService {
  constructor(private http: HttpClient) {
  }

  getBaseServices():Observable<Object> {
    return this.http.get(environment.baseServiceUrl);
  }
}

```

#### How To Reproduce

https://github.com/nathanhokanson/ng-packagr-test

Clone the repo, run npm install, ng build and npm run packagr

The dist/esm2015/ng-packagr-test.js contains
```
const environment = {
    production: false,
    baseServiceUrl: 'http://localhost/base_services'
};
```

#### Expected Behaviour

Environment files are provided by apps, not packages.

#### Version Information

```
node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.7
@angular/compiler-cli: 5.2.7
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.5.3
```

**Comment by deebloo** [comment]
If you want to do that in you lib you will have to pass the environment to your module. Ng packagr doesn't know about the environments only your app does.

**Comment by nathanhokanson** [comment]
Yes, I get that now.  I found a new way of doing it with a InjectionToken.  For anyone that wants to see a working package, look at the github repo I listed above.

**Comment by huang12zheng** [comment]
Can you show how to use environment in lib

**Comment by dherges** [comment]
Provide it as [InjectionToken](https://angular.io/api/core/InjectionToken) from app to lib.

```ts
import { ENVIRONMENT_DI_TOKEN } from '@org/lib';

@NgModule({
  providers: [
    {
      provide: ENVIRONMENT_DI_TOKEN,
      useValue: environment
    }
  ]
})
class AppModule {}
```
