### ISSUE TITLE
Need to give names to the AMD modules nested in UMD bundles

### ISSUE THREAD

**Issue by alexeagle** [dherges/ng-packagr#673]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

Currently a package published by ng-packagr uses anonymous AMD modules:
https://unpkg.com/@toxicable/lite-router@0.0.3/bundles/lite-router.umd.js
`typeof define === 'function' && define.amd ? define(['exports', '@angular/core', 'rxjs/ReplaySubject', 'rxjs/BehaviorSubject', '@angular/router', '@angular/common'], factory) :
	(factory((global['lite-router'] = {}),global.ng.core,global.Rx,global.Rx,global.ng.router,global.ng.common));`

the fact that the first argument to `define` is not a string literal is what tells AMD (eg. requirejs) that the module is unnamed.

That means that libraries produced by ng-packagr must *always* be loaded from URI's or the loader must be configured with a map saying what the name of this module is.

Under bazel's `ts_devserver` we use a faster on-the-fly assembly which is basically just `cat`, and this relies on having named AMD modules.

We should get this in before Angular v6.

**Comment by kylecordes** [comment]
I wonder if the name under which the module is registered could just be the package name already in package.json. That way it wouldn't have to be specifically configured, to preserve the remarkable extent to which `ng-packagr` "just works".

**Comment by dherges** [comment]
Solved in #675
