### ISSUE TITLE
Does not seem to compile to proper es5 as the packaged code does not work in Internet Explorer

### ISSUE THREAD

**Issue by DewaldOosthuizen** [dherges/ng-packagr#681]
## Type of Issue

```
[ ] Bug Report
```

## Description

_A bug: Doesn't seem to compile to es5, can't get my app to work in Internet Explorer._

#### How To Reproduce

_A bug: create a CLI project with some decent amount of logic, include all polyfills required by Internet Explorer, package the application and import the application into another application. The app does not seem to work in IE. A syntax error is shown in the console. Starting the packaged app itself with ng serve seems to work just fine with the generated vendor, polyfills, and main bundles. Only when including the code generated by the ng-packagr inside another app seems to cause the issues when starting the application which the packaged app is included. My tsconfig.json file is set to target es5 and module es2015. The dist folder does, however, include a .es5.js generated file and it is referenced in the generated package.json. Yet IE does not work. I hope its just me missing something small, but I have tried various attempts and can't seem to figure this out. Some of my smaller modules containing less logic seem to start up just fine though. Seems like a compile issue. Just not sure related to what piece of code._

_Can you reproduce the error in the integration tests in ng-packagr?_
_I don't think so_

_Is the error you faced in an application importing the library_
_No it's importing the packaged app generated by the library_

#### Expected Behaviour

_A bug: That es5 should be supported by Internet Explorer and should work seeing that my code is set to target es 5 and should be compiled to es5._

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^1.6.0 
also tried with version 2 RC and some packages do not build at all then. With 1.6.0 my angular 5 apps build just fine and work with chrome and other modern browsers.

@angular/*: ^5.1.0

typescript: 2.7.2 
also tried lowering the version to 2.6.2 and 2.5.3

rxjs: ^5.5.2
node: 8.9.4
npm: 5.6.0
```

_Other libraries_
```
    "devDependencies": {
        "@angular/cli": "^1.7.2",
        "@angular/compiler-cli": "^5.1.0",
        "@angular/language-service": "^5.1.0",
        "@team-griffin/install-self-peers": "^1.1.1",
        "@types/jasmine": "~2.8.3",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "angular-polyfills": "^1.0.1",
        "codelyzer": "^4.0.1",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~2.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "mdn-polyfills": "^5.4.0",
        "ng-packagr": "^1.6.0",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.9.1",
        "typescript": "2.7.2"
    },
    "peerDependencies": {
        "@angular/common": "^5.1.0",
        "@angular/compiler": "^5.1.0",
        "@angular/core": "^5.1.0",
        "@angular/forms": "^5.1.0",
        "@angular/platform-browser": "^5.1.0",
        "@angular/platform-browser-dynamic": "^5.1.0",
        "core-js": "^2.4.1",
        "rxjs": "^5.5.2",
        "zone.js": "^0.8.19"
    }
```

**Comment by JoostK** [comment]
Where does the syntax error occur, can you share that bit of code? Without it we can't say much of what could be the culprit.

**Comment by DewaldOosthuizen** [comment]
I don't really know what piece of code causes the problem. Since the package is bundled successfully and only breaks when is imported into another application. When starting the application I have imported in into it immediately breaks on IE and only points to the beginning of either the vendor.js or main.js file. The line that it points to usually starts with 'eval(' and it is usually a really long line. This also happens on some older versions of edge. Latest edge and other modern browsers work fine. I will try and pinpoint code responsible for this and post it here.

**Comment by JoostK** [comment]
@DewaldOosthuizen you're probably looking at the Angular CLI bundles (Webpack) then, I presume, since they use the `eval` trick.  The bundles produced by ng-packagr through Rollup are in fact readable. Your best bet is to look into the UMD bundle, which has been downleveled to ES5.

**Comment by DewaldOosthuizen** [comment]
Got the issue sorted, It's not the ng-packager build that's wrong. Our applications are being pulled in along with the dist folder created by ng-packager. We needed to include some references in out main package.json file of the app and not the one inside the dist folder.

This fixed it for us.

Adding the following to our package.josn:
  "main": "./bundles/nbc-service-country.umd.js",
  "module": "./modules/nbc-service-country.es5.js",
  "es2015": "./modules/nbc-service-country.js",
  "typings": "./nbc-service-country.d.ts",

and then adding this inside the pollyfills:
(window as any).__Zone_enable_cross_context_check = true;       // IE 11 "Can't execute from freed script"
