### ISSUE TITLE
How can I provide access to lib .less files in a published package?

### ISSUE THREAD

**Issue by kroeder** [dherges/ng-packagr#690]
## Type of Issue

```
[ ] Bug Report
[ x ] Feature Request
```

## Description

We developed an UI Framework that contains Angular components as well as standalone *.less files that are exported by a styles.less in the root of the library

What is the best aproach to provide this styles.less file (maybe with the content of all @import style files) when publishing a library with ng-packagr? 

Is this even possible or should I add a custom step in my build process after ng-packagr finished it's build?

**Comment by deebloo** [comment]
@kroeder at the moment you will have to run a script to copy the files after the build is complete.

**Comment by kroeder** [comment]
Thanks!
