### ISSUE TITLE
Angular Package Format (APF) v6.0

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#705]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description
With a new major Angular version comes a new package format. Some details can be found here though it's not fully updated: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx

#### What changes?
An example build with `APF v6.0` can be found here: https://github.com/angular/core-builds

- Ship both `fesm` and `esm`. 
- Several new entry point in `package.json`. 
```json
  "main": "./bundles/core.umd.js",
  "module": "./fesm5/core.js",
  "es2015": "./fesm2015/core.js",
  "esm5": "./esm5/core.js",
  "esm2015": "./esm2015/core.js",
  "fesm5": "./fesm5/core.js",
  "fesm2015": "./fesm2015/core.js",
  "typings": "./core.d.ts"
```
#### What needs to change in `ng-packagr`?
- The biggest issue to switching from v5 to v6 is that `ng-packagr`, uses a lot of rollup plugins, all these features based on rollup will no longer work. 

`Rollup` should purely be used to generate the `FESM` and `UMD` bundles.

- Downleveling should happen on non flattened files and down outside of rollup.
- Add more entry points for bundlers.
- Ship `ESM5` and `ESM2015` (Unflattened)

#### Expected
Align with `APF v6.0`. 

I still need to look into which bundlers use which entry points in `package.json`, From what I know is that `webpack v4` does tree-shaking on non flat modules `ESM`, but for dev-mode it's best to use `FESM` as it's more performant when having many modules.

**Comment by elesueur** [comment]
This may be related or not, but I am wondering how (if possible at all) to try and build a library that will work with multiple versions of Angular. Currently, I have ng-packagr version 2 which is producing a library using the 5.2 compiler-cli which produces AOT metadata with version 4.

The library doesn't work if I try to load it into an Angular 4 app, complaining of a metadata version mismatch.

There is nothing crazy in this library that would actually stop it from working with Angular 4 as far as I can tell, and it would be nice to be able to support Angular 4,5,6 with one version of the library. In fact, if I go into the metadata file and change the version back to 3, it works just fine with Angular 4 AFAICT.

It would be nice if ng-packagr was flexible enough to allow me to target specific lowest version of Angular but allow me to work against a more recent version and warn me if I use features that won't work in the lower targeted versions.

**Comment by alan-agius4** [comment]
That’s not really related as it’s more of Angular that metadata is not backward compatible.

Thus, metadata v4 cannot be used with Angular 4. That said at least for the time being Angular 5 and 6 both use Metadata v4, so they should both can be used togather.

**Comment by alan-agius4** [comment]
This won’t cause any incompatability between different versions of angular.
Packages format changes are more related to bundlers, better tree-shaking
and optimizations in that aspect.

**Comment by dherges** [comment]
@elesueur I disagree. At some point we start using a new API from Angular 6 and that will then break the "old" Angular 4 users. It's not a good-fit solution to support different major Angular versions from the same branch. if an Angular 4 lib continues to work in a newer version, great! The other way (a v6 lib working in v4) is much harder.

**Comment by alan-agius4** [comment]
@dherges, If you need any help with this, I am willing to take this one on me.

**Comment by dherges** [comment]
I had a chat with Hans from the CLI team.

What needs to change in ng-packagr:
- `ngc` to es5, write output to `esm5` folder
- `ngc` to es2015, write output to `esm2015` folder
- contents of `esm5` will be flattened to `fesm5` and `umd`
- contents of `esm2015` will be flattened to `fesm2015``
- get rid of the temporary working folder, because now the individual `.js` files can be included in the `dest` directory. It would just mean to move/delete type definitions (`.d.ts`) and metadata to the proper locations.

**Comment by alan-agius4** [comment]
What I am worried about is `rollup` there is loads of dependencies on it for various plugins, such as license, comments etc.. Should these be removed or it's okay if they will be done only for the FESM output?

**Comment by dherges** [comment]
Bonus: if there was a good solution for flattening type definitions, I'll take it in a blink of an eye!

**Comment by alan-agius4** [comment]
I saw something a couple of days ago. Haven't tried it myself to be honest and I don't know how good or bad it is.

https://medium.com/@paleo.said/how-to-bundle-an-npm-package-with-typescript-and-rollup-f80e0f196189

Also, Angular themselves due some sort of bundle of types in API Guardian, to generate the golden files. That said, it can be a bit unsafe. 

As merging types can cause risk on skipping something etc..

**Comment by dherges** [comment]
I think we have to disable the comments and license processing for a while. It's neither working in the latest rollup version (#620)

**Comment by dherges** [comment]
`fullTemplateTypeCheck`: https://angular.io/guide/aot-compiler#fulltemplatetypecheck

`strictInjectionParameters`: https://angular.io/guide/aot-compiler#strictinjectionparameters

**Comment by alan-agius4** [comment]
Okay, I''ll try to do something related to this, this week. I am assuming you send those 2 links, to enable them :P?

**Comment by alan-agius4** [comment]
So between esm2015 and esm5 your are not seeing it as a downlevel hut rather an ngc recompilation? (Following your comment above)

**Comment by dherges** [comment]
Good point. It can also be just a down-levelling, e.g. with [buble](https://github.com/Rich-Harris/buble), [babel](https://github.com/babel/babel).

There was also a chat about optimising for a dev-mode with file watchers and my initial thought was to make it `ngc --watch --target es5` to only compile the esm5 for dev. But it's yet not clear how tjhat will work (ng-packagr still needs to own the file watchers and run through the preprocessing before running ngc). It will at least need to run the ngc compilation, because the flattened metadata could change. Hm hm...

Let's leave that up for later. It doesn't matter right now whether we do two ngc runs or transpiling. We can change the implementation of that esm5 build step still later.

**Comment by dherges** [comment]
So yes, what I am trying to say: it's an implementation detail
