### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by vapits** [dherges/ng-packagr#708]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When I use the library in an external application I'm getting the following error:
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@vlk/lexicon-ng/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

#### How To Reproduce

I'm only starting the app, nothing special.
I get that need a reproduction but it quite simple, when I do `ng serve` I get the following error:
![image](https://user-images.githubusercontent.com/8594758/37714455-db09a5fe-2d19-11e8-932d-0efb5652b984.png)
 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.2.0
@angular/*: 5.2.9
typescript: 2.4.2 (and 2.6.2)
rxjs: 5.5.2
node: 9.8.0
npm/yarn: 5.6.0
```

**Comment by vapits** [comment]
I figure out that the problem is that on `npm install` . in the application that uses the library I created a `node_modules` folder is created inside my library in parent app `node_modules` folder. And because angular is a different version it imports also parts of angular and therefore I get this message and static injector errors.

Now I'm not sure how to handle this. I moved in my library all the dependencies to the `devDependencies` but I still have the same issue.

**Comment by vapits** [comment]
Solution: 
Actually it was a bad setup. In my project I had an ng-package.json and a package.json, though package.json include dependencies like angular/core etc that had to be excluded from the build package.

So I did remove the ng-package.json and created a second package.json inside my libe folder and point to that second package.json on my build script.

I do believe that a small update on the documentation is needed.

Thanks

**Comment by frot-io** [comment]
I had nearly the same issue, only that my IDE (VS Code) wrongly imported a Component from another Projekt in the same repo: `import { Tooltip } from './../../../../admin-ui/src/app/directives/prime/tooltip/tooltip';` (my project uses Angular 5.2.0, the other 5.1.0)

Although the component "tooltip" have not been used, the error still appeared. Removing the import solved the issue. But getting a more detailed error could have saved me some time.

**Comment by benmed00** [comment]
thanks @vapits that helps me

**Comment by Mathijs003** [comment]
@vapits Can you show us how you did that? I have the same issue

**Comment by samuelnygaard** [comment]
thanks @frot-io, you pointed me in the right direction. I found a way to find which component is resulting in the error, if you build the project with the `--prod` tag, it gives a bit more verbose errors.
```ng build --prod```
