### ISSUE TITLE
Why does the new peerDependency check make sense for development dependencies?

### ISSUE THREAD

**Issue by CarstenLeue** [dherges/ng-packagr#719]
## Type of Issue

```
[x] Question
[ ] Bug Report
[ ] Feature Request
```

## Description

With 2.3.0 the build fails if I have devDependencies that are not whitelisted. Why does this make sense? In the devDependencies I need to list all dependencies that I need for the build and test cycle, that includes e.g. jest or extra tools only required for development. Isn't this the default setup? It adds a lot of churn to have to whitelist each of these dependencies.

**Comment by dherges** [comment]
It's good to go through this discussion.

When I wrote it, I had a set up in mind where you have a root `package.json` (with devDependencies) for the workspace/project and another `package.json` for the library.

There are several issues that could go down misaligned dependencies set-up like the `is not a NgModule` error. They are really hard to track down. These issues usually occure only in the consuming app and sometimes it's possible to reproduce reliably. Thus, I think the build should be more rigid and try to catch those issues early in the build process. Filipe gave an explanation here: https://github.com/dherges/ng-packagr/pull/715#issue-177247845


devDependencies are problematic for locally installed packages. Afaik `npm install path/to/dist` would install devDependencies too.

**Comment by CarstenLeue** [comment]
I see, so it's probably my setup that is not ideal, then. Can you give an example how the suggested split between a root level project and the library project looks like, so you can 
- run testcases for the library and probably also start a local test app as a shell for the library for testing
- build the library using ng-packagr without having to whitelist the dev dependencies

**Comment by dherges** [comment]
I checked `npm install path/to/dist` again:

```bash
$ cat package-lock.json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "folder-with-devDependencies": {
      "version": "file:../path/to/dist"
    }
  }
}
```

```bash
$ ls -al node_modules/
folder-with-devDependencies -> ../../path/to/dist
```

It didn't install the devDependencies listed in the package.json - so it would be fine to not fail the build for devDependencies.

Still symlinking a local package is horribly broken. let's say there is a `path/to/package.json` as workspace directory. Then `path/to/node_modules` [ends up in the module resolution strategy](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) and then module loaders will try to resolve from there which is... broken.

We can't solve that issue with the devDependencies whitelist. So the whitelisting for devDependencies should probably go away.

**Comment by dherges** [comment]
The only reliable way for local packages seems to be `npm install path/to/dist.tgz`

```bash
$ ls -al node_modules/
drwxr-xr-x  @sample
drwxr-xr-x  tslib
coala:foo david$ cat package-lock.json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@sample/comments": {
      "version": "file:../ng-packagr/integration/samples/comments/dist.tgz",
      "integrity": "sha512-xoO7WpXSRUJTo6aso+WH2XU049qFVhNHfiVdoQz/rbRHYIMYO/vH0GNB5V151rboCMQCmm0gGwB9BRn9v7xAOA==",
      "requires": {
        "tslib": "1.9.0"
      }
    },
    "tslib": {
      "version": "1.9.0",
      "resolved": "https://registry.npmjs.org/tslib/-/tslib-1.9.0.tgz",
      "integrity": "sha512-f/qGG2tUkrISBlQZEjEqoZ3B2+npJjIf04H1wuAv9iA8i04Icp+61KRXxFdha22670NJopsZCIjhC3SnjPRKrQ=="
    }
  }
}
```

**Comment by dherges** [comment]
@CarstenLeue AN example is shown in nx-packaged, one of the libs: https://github.com/dherges/nx-packaged/tree/master/libs/one-lib
