### ISSUE TITLE
How to define typescript configuration

### ISSUE THREAD

**Issue by dareksob** [dherges/ng-packagr#722]
## Description
How can I define the tsconfig.json configuration file. They always use a other (ng-packagr\lib\tsconfig) configuration than the project has.

#### How To Reproduce

Use a simple example with ES7 features. 
Example
export function toolArray(list: Array<string>, value: string): boolean {
    return list.include(value);
}

#### Expected Behaviour

error TS2551: Property 'include' does not exist on type 'string[]'. Did you mean 'includes'?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
  "ng-packagr": "^2.4.1",
```

**Comment by dareksob** [comment]
the property languageLevel helps for this problem, but a tsconfig.json file will be better to resolve this

**Comment by alan-agius4** [comment]
In order to use a different tsconfig you’d need to use the ng-packagr API

**Comment by dareksob** [comment]
Sounds good, I found the solution by that. But it isn't documented yet, right?

**Comment by alan-agius4** [comment]
I don’t think there yet. As it’s not yet stable.

**Comment by dareksob** [comment]
ok thanks, I will waiting for
