### ISSUE TITLE
How to disable the creating package of *.tgz

### ISSUE THREAD

**Issue by SerkanSipahi** [dherges/ng-packagr#728]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description
This is a question (not a bug or feature)! 
It is possible to disable the creating package of *.tgz?
I have nothing found about that in https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/compiler: 5.2.9
@angular/compiler-cli: 5.2.9
rollup: 0.55.5
tsickle: 0.27.2
typescript: 2.5.3
```

**Comment by kylecordes** [comment]
It seems very useful to have the .tgz file routinely available. Is there reason it would need to be disabled?

**Comment by SerkanSipahi** [comment]
On my mac it takes too long to create this file (30 seconds)! I would be great when this be configurable over package.schema.json

**Comment by SerkanSipahi** [comment]
It reproducible on each run! (took each time 30 - 40 sek)

**Comment by kylecordes** [comment]
Now that is an interesting result. Creating a tgz should be nearly instant, compared to the effort of all the compilation it took to create the dist files.

**Comment by SerkanSipahi** [comment]
@kylecordes (benchmark test)
```
> ng-packagr | gnomon --medium=1.0 --high=4.0 --ignore-blank --real-time=100

  10.0502s   Building Angular Package
   0.0005s   Building entry point '@honey.glass/matmedia'
   0.0034s   Cleaning build directory
   0.0078s   Rendering Stylesheets
   0.0018s   Rendering Templates
   0.9021s   Compiling TypeScript sources through ngc
   0.0758s   Bundling to FESM15
   0.0780s   Bundling to FESM5
   0.0951s   Bundling to UMD
   0.0967s   Minifying UMD bundle
   0.0011s   Relocating source maps
   1.9747s   Copying staged files
   0.0014s   Writing package metadata
   0.0010s   You enabled keepLifecycleScripts explicitly. The scripts section in package.json will be published to npm.
  44.7387s   Creating package .tgz
   0.7725s   Built @honey.glass/matmedia
   0.0001s   Built Angular Package!
   0.0000s   - from: packages/matmedia
   1.3198s   - to:   packages/matmedia
   1.4298s   - to:  packages/matmedia
             
     Total   60.2324s
```

**Comment by kylecordes** [comment]
I see a few possibilities here:

* Perhaps `ng-packagr` is somehow using the world's worst possible, amazingly slow way of creating a tgz? Seems unlikely, but worth a look.
* Maybe something else is going wrong and you are getting a vastly bloated number of files in your tgz? If you look unpack it, is it reasonable, does it contain just a small number of files typically in "dist"?
* Perhaps the log output of `ng-packagr` as it runs, is incorrectly doing lots of work unrelated to the tgz, under the "creating package" output banner.

Someone more deeply familiar with the internals may know what to make of this... and none of them has stepped into this issue yet.

**Comment by SerkanSipahi** [comment]
[logo]: https://ibb.co/hEE7vS "tgz"

**Comment by SerkanSipahi** [comment]
i found the bottleneck"
```
slow:
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "dest": "./",    // ===> bottleneck when it referenced on it self
  "deleteDestPath": false,
  "whitelistedNonPeerDependencies": ["."],
  "keepLifecycleScripts": true,
  "lib": {
    "entryFile": "./public_api.ts",
    "languageLevel": ["dom", "es2017"]
  }
}
```
fast:
```
slow:
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "dest": "./dest", 
  "deleteDestPath": false,
  "whitelistedNonPeerDependencies": ["."],
  "keepLifecycleScripts": true,
  "lib": {
    "entryFile": "./public_api.ts",
    "languageLevel": ["dom", "es2017"]
  }
}
```

If the reference is referenced to itself (see slow "dest" property), then it takes a long time. But in my case must be exactly the same (dest).

**Comment by kylecordes** [comment]
That is very interesting. I'm not sure if `ng-packagr` really supports this use "officially" or not. It's possible that the answer to this will be, dest needs to be a dedicated directory for output, not used for any other purpose.

Perhaps this item will become a feature request.  Ideally `ng-packagr` should either support `dest: '.'` officially, and produce tested, correct results in about the same time as any other dest; *or* it should not support that setting, and exit immediately with helpful error.

**Comment by SerkanSipahi** [comment]
I think it should be supported :)

**Comment by SerkanSipahi** [comment]
We are working with lerna (monorepo)! In our case we are in need of it :)

**Comment by vtabary** [comment]
Hey all,

I think this topic is not about to remove this behavior but to provide a way to disable it if we do not need it. 

It shouldn't change the actual behavior if nothing is configure to.

So we won't have to manage an unused tgz file, or multiple files if you are using secondary entry points.

In our project, we have to remove or exclude these files before publishing. It's not a big deal, but if we do not need it, it shouldn't be created.

**Comment by tommck** [comment]
Yeah.. what's the point in creating this tgz file?

**Comment by daimoonis** [comment]
Hello, i would also like to know what is the reason for this? 

I think that ng-packagr should not create tgz file by default as it does now. Possibly it may be configurable, but anyway, anyone can pack generated code by himself right? I'm using version 2.2.0 because it was not implemented there yet. Personally i do take generated code (all files in folder) and push that into "release" git repository, i do not want to work with one tgz file.

**Comment by TwanoO67** [comment]
Can we use this tgz file to directly "npm publish" ? if so, how ?
At the moment I only use somethings like "cd dist; npm publish" to get my package online.
So I don't understand the need of the tgz file neither...

**Comment by tommck** [comment]
@TwanoO67 yes, I believe you could do "npm publish dist.tgz" if you wanted to

**Comment by SerkanSipahi** [comment]
@tommck really?

**Comment by tommck** [comment]
@SerkanSipahi Yeah..

From https://docs.npmjs.com/cli/publish

```npm publish [<tarball>|<folder>] ...```

**Comment by alan-agius4** [comment]
This feature has been dropped in ng-packagr V3 RC.0
