### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by MurhafSousli** [dherges/ng-packagr#747]
## Type of Issue

```
[ x ] Question
```

## Description

Can **ng-packagr** be used to target Angular 6 now? if yes, What are the migration steps?

Thanks!

**Comment by SaturnTeam** [comment]
I tried a week ago. it isn't working.

**Comment by AdamKernig** [comment]
I would be interested in this two as all of the modules I have made use this and I would like to be on 6. 

HOWEVER
Angular 6 is still in RC phase, it would not be wise to look at enhancing the package untill the release is done.

**Comment by dherges** [comment]
Yes, it can be used with v6.

**Comment by isastangarlin** [comment]
Not working for me

**Comment by AdamKernig** [comment]
Its baked in to ng6 use that
