### ISSUE TITLE
ENOENT: no such file or directory, open .... (but that can not be!!)(please help)

### ISSUE THREAD

**Issue by SerkanSipahi** [dherges/ng-packagr#752]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
I run into the same issues (see related issues)! But something is really strange! Until yesterday everything worked well but today not. I have changed nothing (no versions updates, etc). That's really frustrating (i tried it on 2 different work stations).  Cant do anything since this morning :( 

ng-packagr does not manage to move (`my matmedia files, not some externals, see below header description "which should be packaged"`) the corresponding files into the `out` folder during the build process! 

When i run `./node_ modules/.bin/ng-packagr` i get follow error (see below).

Run command:
```
$ node_modules/.bin/ng-packagr
Building Angular Package
Building entry point '@honey.glass/matmedia'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle

BUILD ERROR
ENOENT: no such file or directory, open 'test.honey.glass/.ng_pkg_build/honey.glass-matmedia/out/matmedia.directive.config.ts'
Error: ENOENT: no such file or directory, open 'est.honey.glass/.ng_pkg_build/honey.glass-matmedia/out/matmedia.directive.config.ts'
```

#### It seems like it would be a general problem (related issues)
https://github.com/dherges/ng-packagr/issues/590 (im not using v1, but v2 and the same error)
https://github.com/dherges/ng-packagr/issues/166 (same issue but something with externals)
https://github.com/dherges/ng-packagr/issues/81 (same issue)
https://github.com/dherges/ng-packagr/issues/694 (the workaround did not work!)
https://github.com/dherges/ng-packagr/issues/174 (suggestion to downgrade, but i cant downgrade)
https://github.com/dherges/ng-packagr/issues/434 (umdModuleIds: what does that do? do i really need it)

Folder which should be packaged:
```
.
├── LICENSE.md
├── README.md
├── dummy.component.ts
├── matmedia.directive.config.ts
├── matmedia.directive.interface.ts
├── matmedia.directive.spec.ts
├── matmedia.directive.ts
├── matmedia.module.ts
├── ng-package.json
├── package.json
├── public_api.ts
└── tslint.json
```

After Error:
```
.
├── LICENSE.md
├── README.md
├── dummy.component.ts
├── matmedia.directive.config.ts
├── matmedia.directive.interface.ts
├── matmedia.directive.spec.ts
├── matmedia.directive.ts
├── matmedia.module.ts
├── ng-package.json
├── ng_pkg_build
│   └── honey.glass-matmedia
│       ├── out
│       │   ├── honey.glass-matmedia.d.ts
│       │   ├── honey.glass-matmedia.js
│       │   ├── honey.glass-matmedia.js.map
│       │   ├── honey.glass-matmedia.metadata.json
│       │   ├── matmedia.directive.config.d.ts
│       │   ├── matmedia.directive.config.js
│       │   ├── matmedia.directive.config.js.map
│       │   ├── matmedia.directive.d.ts
│       │   ├── matmedia.directive.interface.d.ts
│       │   ├── matmedia.directive.interface.js
│       │   ├── matmedia.directive.interface.js.map
│       │   ├── matmedia.directive.js
│       │   ├── matmedia.directive.js.map
│       │   ├── matmedia.module.d.ts
│       │   ├── matmedia.module.js
│       │   ├── matmedia.module.js.map
│       │   ├── public_api.d.ts
│       │   ├── public_api.js
│       │   └── public_api.js.map
│       └── stage
│           ├── bundles
│           │   ├── honey.glass-matmedia.umd.js
│           │   ├── honey.glass-matmedia.umd.js.map
│           │   ├── honey.glass-matmedia.umd.min.js
│           │   └── honey.glass-matmedia.umd.min.js.map
│           ├── esm2015
│           │   ├── honey.glass-matmedia.js
│           │   └── honey.glass-matmedia.js.map
│           └── esm5
│               ├── honey.glass-matmedia.js
│               └── honey.glass-matmedia.js.map
├── package-lock.json
├── package.json
├── public_api.ts
└── tslint.json
```

#### How To Reproduce
*can someone tell me if he gets the same problem with my repo*
```
git clone https://github.com/SerkanSipahi/test.honey.glass.git
cd test.honey.glass
npm install
./node_modules/.bin/ng-packagr
```

#### Expected Behaviour
build a package

#### Version Information
```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.1
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.5.3
```
node --version `v8.9.4`

**Comment by sebastianscatularo** [comment]
Same issue here, yesterday worked, but today not. I tried with different versions without success.

**Comment by SerkanSipahi** [comment]
@sebastianscatularo My guess is that some version dependencies have changed and it comes to this error. As I said, the bug could be reproduced on two macs.  I am now totally annoyed that I did not maintain package-lock.json. Now its very difficult to find any changes. 

Do you have package-lock.json?

**Comment by sebastianscatularo** [comment]
Here is the yarn.lock that works and the other one that doesn't 

https://gist.github.com/sebastianscatularo/afb25a78c41a11bd30ef836ac765068c

**Comment by sebastianscatularo** [comment]
I can confirm it could be an issue at dependency level, I copied yarn.lock from a project that works to another one that doesn't, deleted the node_modules and reinstall it, and the issue disappears

**Comment by SerkanSipahi** [comment]
Good news its works now, i have made a quick test!
For a `Single Source of Truth` i removed all the `~^` symbols from the package.json inside of `node_modules/ng-packagr/package.json`! The question is which dependency broke it?:

Because of thats issues/problems i never use in my projects `~^` symbols in the package.json! I do it manuelly by my self with some helper tools. This more safe! Especially with popular projects you should be careful.

can anyone confirm my quick test?

```
...
...
  "dependencies": {
    "@ngtools/json-schema": "1.1.0",
    "autoprefixer": "7.1.1",
    "browserslist": "2.1.5",
    "chalk": "2.3.1",
    "commander": "2.12.0",
    "cpx": "1.5.0",
    "fs-extra": "5.0.0",
    "glob": "7.1.2",
    "injection-js": "2.2.1",
    "less": "2.7.2",
    "node-sass": "4.5.3",
    "node-sass-tilde-importer": "1.0.0",
    "postcss": "6.0.2",
    "postcss-clean": "1.1.0",
    "postcss-url": "7.3.0",
    "read-pkg-up": "3.0.0",
    "rimraf": "2.6.1",
    "rollup": "0.55.0",
    "rollup-plugin-cleanup": "2.0.0",
    "rollup-plugin-commonjs": "8.3.0",
    "rollup-plugin-license": "0.6.0",
    "rollup-plugin-node-resolve": "3.0.0",
    "rxjs": "5.5.0",
    "sorcery": "0.10.0",
    "strip-bom": "3.0.0",
    "stylus": "0.54.5",
    "tar": "4.4.1",
    "uglify-js": "3.0.7",
    "update-notifier": "2.3.0"
  },
....
....
```

**Comment by SerkanSipahi** [comment]
i belive one of them should be:
```
 chalk                        ^2.3.1  →   ^2.3.2 
 commander                   ^2.12.0  →  ^2.15.1 
 node-sass                    ^4.5.3  →   ^4.8.3 
 node-sass-tilde-importer     ^1.0.0  →   ^1.0.2 
 postcss                      ^6.0.2  →  ^6.0.21 
 postcss-url                  ^7.3.0  →   ^7.3.2 
 rimraf                       ^2.6.1  →   ^2.6.2 
 rollup-plugin-node-resolve   ^3.0.0  →   ^3.3.0 
 rxjs                         ^5.5.0  →   ^5.5.8 
 uglify-js                    ^3.0.7  →  ^3.3.20 
 update-notifier              ^2.3.0  →   ^2.4.0 
```

**Comment by beeman** [comment]
@SerkanSipahi I can confirm that your test works! 

I faced the same issues. Setting ng-packagr's deps to your list and running it against a linked local build made it work.

**Comment by sellmic** [comment]
I have a similar problem, in my case the culprit seems to be uglify-js, when I replace it with a project that works (from yesterday) it works.

Broken version 3.3.20
Working version 3.3.18

**Comment by SerkanSipahi** [comment]
@sellmic i can confirm it! uglify-js is broking the build. Until v3.3.18 everything works fine! >= 3.3.19 is broken!

**Comment by sellmic** [comment]
Any ideas on possible workarounds? I know this way of loading patches and updates (that are supposedly not incompatible) is common with npm, but this is an example of it having really bad unintended consequences!

**Comment by beeman** [comment]
@sellmic I think the only way to prevent these kind of things from breaking is by using npm or yarn lock-files.

That should get the same dependency tree over and over again.

**Comment by SerkanSipahi** [comment]
I think uglify-js should enable `includeSources`or we should set it by default!

**Comment by SerkanSipahi** [comment]
@beeman we have the same issues with the `*-lock.json`files! We found a way how we get the `single source of truth`! We omit all the symbols `˜^`from the package.json. As i described above we use `npm-check-updates` checking and updating our libs!

**Comment by zixia** [comment]
Ah! How unlucky I am!

I just start using the ng-packagr today, and waste 3 hours to debug this issue!

After I set the `includeSources` to `true`, this issue gone.

Thanks, @SerkanSipahi! I'd like to suggest you make a PR for this fix.

**Comment by pulsejet** [comment]
Just in case anyone is looking for a quick fix, add `"uglify-js": "3.3.18"` to your `devDependencies`

**Comment by SerkanSipahi** [comment]
@zixia yes i will do it! to setting the prop to true is also suggested from @alexlamsl see https://github.com/mishoo/UglifyJS2/issues/3063

**Comment by SerkanSipahi** [comment]
@alan-agius4 thank you for the PR!

**Comment by sellmic** [comment]
Thanks for the quick fix! This was killing all our builds!

Not to be pedantic, but I'm wondering ... is there a unit/integration test that can be added to detect these earlier? Not sure how this project is setup with Jenkins CI builds doing that type of thing ...

**Comment by qwertoyo** [comment]
Got the same issue, only on the build agent, with version 2.2.0

Solved upgrading to 2.4.4

**Comment by ChamNouki** [comment]
Hi every one, excuse me but I use ng-packagr@2.4.4 and I still have this issue with a different file not found each time I execute the ng-packagr command.

Is there any specific action to do to solve this problem ?

**Comment by beeman** [comment]
@ChamNouki try removing any npm/yarn lockfiles from you project, remove node_modules, upgrade ng-packagr to the latest version (`npm install @ng-packagr@latest`) an run `npm install`. That should most likely fix the issue.

**Comment by ChamNouki** [comment]
Version 2.4.4 seems to be the latest. Anyway I (re)do what you suggest but still have the issue :'(

**Comment by sumitramteke** [comment]
What about for angular 4^, ng-packgar about 1.6 do not support older angular ?

**Comment by YassinHussein** [comment]
just close the terminal and then run `npm start` again ... that work for me

**Comment by iAbhinav** [comment]
Updating from 2.0.0 to 2.4.4 resolved the issue for me
