### ISSUE TITLE
File not found under .ng_pkg_build

### ISSUE THREAD

**Issue by mrunal-patel** [dherges/ng-packagr#753]
## Type of Issue
ng-packagr -p ng-package.json command fails with the following error:

Building Angular Package
Building entry point 'service'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle

BUILD ERROR
ENOENT: no such file or directory, open '*/.ng_pkg_build/service/out/service.ts'
Error: ENOENT: no such file or directory, open '*/.ng_pkg_build/service/out/service.ts'
```
[ ] Bug Report
[ ] Feature Request
```

## Description
ng-packagr version used is 2.4.1. I even downgraded the version to 2.0.0 and I still see the same error. 

ng-packagr was not throwing any such errors as of yesterday. In fact, if i build my projects without doing the latest install of ng-packagr, then it works fine. But as soon as i remove the cached version of ng-packagr from node_modules folder, and do 'npm install' and then try to package my projects, I see this error.

#### Version  @Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/*: 5.2.1
typescript: 2.4.2
rxjs: 5.5.6
node: 8.9.2
npm: 5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by SerkanSipahi** [comment]
related bug, please see: https://github.com/dherges/ng-packagr/issues/752

**Comment by sellmic** [comment]
Yup, this is the same thing as https://github.com/dherges/ng-packagr/issues/752

I put a comment there, but it sounds like uglify-js 3.3.20 breaks ng-packagr (3.3.18 works)

**Comment by SerkanSipahi** [comment]
@sellmic please close this issue here, thanks.

**Comment by mrunal-patel** [comment]
Thank you @sellmic for the update. I'll close the issue here.
