### ISSUE TITLE
`node_modules/popper.js/src/utils/debounce.js not found` while build on ng-packagr

### ISSUE THREAD

**Issue by daituzhang** [dherges/ng-packagr#763]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm using popper.js in an angular app and it was built correct until I try ng-packagr

```
BUILD ERROR
ENOENT: no such file or directory, open '/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/popper.js/src/utils/debounce.js'
Error: ENOENT: no such file or directory, open '/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/popper.js/src/utils/debounce.js'
```

There's no `src` folder in `popper.js`, I'm not sure why `ng-packagr` would looking for that folder.

I've asked on `popper.js` on github and their reply is that the build pipeline shouldn't need to compile Popper.js from source and the npm package doesn't include the source. I guess the question is that how can I avoid popper.js from compiling from source while build?

#### How To Reproduce
I was importing popper.js as
`import Popper from 'popper.js';`
and run `ng-packagr`

#### Expected Behaviour
Open the files in `/Users/vfd049/workspaces/dealer/ui-components-angular-lib/node_modules/popper.js/dist/` instead
and Package successfully

#### Version Information
```
ng-packagr: 1.7.0
angular: 5.2.9
typescript: 2.4.2
rxjs: 5.5.8
node: v7.75 
npm: 4.1.2
popper: 1.14.3
```
Thank you!!

**Comment by daituzhang** [comment]
Fixed by updating version.
Thank you

**Comment by thelegendofdeep** [comment]
what did you update and to what version?
