### ISSUE TITLE
Function calls are not supported in decorators: does not work with ag-grid

### ISSUE THREAD

**Issue by crowmagnumb** [dherges/ng-packagr#765]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

In trying to package up an Angular library that uses [ag-grid](https://www.ag-grid.com/) I get the following

```
BUILD ERROR
Error during template compile of 'TestModule'
  Function calls are not supported in decorators but 'AgGridModule' was called.
```

TestModule code looks like

```
import { NgModule } from "@angular/core";

import { AgGridModule } from "ag-grid-angular/main";

import { MyGridComponent } from "./myGrid/myGrid";

@NgModule({
    imports: [AgGridModule.withComponents([MyGridComponent])],
    declarations: [MyGridComponent],
    exports: [MyGridComponent]
})
export class TestModule {}
```

because this is the required way for AgGrid to register components. But angular-cli compiles it just fine.

#### How To Reproduce

[Here is a repo](https://github.com/crowmagnumb/ng-packagr-issue) that reproduces the problem and shows that the same code behaves fine using angular-cli to compile.

#### Expected Behaviour

Successful compilation

#### Version Information

```
ng-packagr: 2.4.2
@angular/*: 6.0.0-rc.0
typescript: 2.7.2
rxjs: 5.6.0-forward-compat.3
node: v8.2.1
yarn: 1.3.2
```

**Comment by dherges** [comment]
Realtes to:
 - #778 
 - #767

**Comment by crowmagnumb** [comment]
The ```// @dynamic``` trick of case [#778](https://github.com/dherges/ng-packagr/issues/767) does not work here.

**Comment by alan-agius4** [comment]
Please check this angular issue, https://github.com/angular/angular/issues/23609

**Comment by crowmagnumb** [comment]
Further development here had suggested that this might be fixed. Sorry it took me so long to verify that. But indeed this now works with the following versioning...

```
rxjs: ^6.0.0
rxjs-compat: ^6.0.0
@angular/*: 6.0.0
@angular/cli: ^1.7.3
ng-packagr: 3.0.1
```

My ag-grid versioning remained unchanged at ...
```
ag-grid: ^17.0.0
ag-grid-angular: ^17.0.0
```
