### ISSUE TITLE
Switch to ngc `enableResourceInlining`

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#770]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Switch to `enableResourceInlining` by ngc.

#### How To Reproduce / Expected Behaviour

See https://github.com/angular/angular/commit/b5be18f4059dc09ee9a3eb22ebd0b1485262e8fa

Remove workarounds for string-replacements of source texts (synthesized source files and compiler host).

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0
@angular/*: 6.x
```

**Comment by alan-agius4** [comment]
This would be awesome 😎

**Comment by alan-agius4** [comment]
What's the plan for this? How to handle `sass`, `stylus` and `less` files as AFAIK this only works for `CSS` and `HTML`?
