### ISSUE TITLE
Angular 6: provide UMD module id defaults for `rxjs`

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#781]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

In Angular v6, code bases need to be migrated from rxjs 5.5 to version 6 of rxjs. rxjs will be released in a 5.x compat version and a 6.x

https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/edit#

#### How To Reproduce

Current behaviour:

```ts
import { Observable, of } from 'rxjs';
```

```bash
No name was provided for external module '<...>' in options.globals – guessing 'rxjs'
```

#### Expected Behaviour

- Build success w/o warnings
- Verify whether umd module ids are stable from 5.5 to 6
- Verify we provide default umd module ids for rxjs v6

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.0-rc.1
@angular/compiler:     6.0.0-rc.5
@angular/compiler-cli: 6.0.0-rc.5
rollup:                0.57.1
tsickle:               0.27.5
typescript:            2.7.2
```

**Comment by matheo** [comment]
Nice to see this update with Angular 6, thanks @dherges!

**Comment by alan-agius4** [comment]
From what I am seeing there is a single UMD module ID for `rxjs v6`, which is `rxjs`
