### ISSUE TITLE
rollup does not find index.ts files in folders when ./<folder> is imported/exported

### ISSUE THREAD

**Issue by ghost81** [dherges/ng-packagr#784]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
I have a project with following structure
```
src
|----- modules
|        |----- index.ts
|        |----- module_1
|        |        |----- index.ts
|        |        |----- component_1.ts
|        |        |---- ........
|        |        |----- component_n.ts
|        |----- ............
|        |----- module_n
|                 |----- index.ts
|                 |----- component_1.ts
|                 |---- ........
|                 |----- component_n.ts
|----- public_api.ts
```
public_api.ts:
`export * from ./modules`

index.ts in each module:
```
export Component1 from ./component_1;
..........
export ComponentN from ./component_n
```
index.ts in modules:
```
export * from ./module_1;
export * from ./module_2;
..........
export * from ./module_n;
```

When I try to build i get the following error:

> BUILD ERROR
> Could not resolve './modules' from dist/esm5/public_api.js
> Error: Could not resolve './modules' from dist/esm5/public_api.js
>    at error (/<path_to_project folder>/node_modules/rollup/dist/rollup.js:224:15)
>    at /<path_to_project folder>/node_modules/rollup/dist/rollup.js:19454:25
>    at <anonymous>

if i change the content of public_api.ts to:
`export * from ./modules/index`

then the error is:

> BUILD ERROR
> Could not resolve './module_1' from dist/esm5/public_api.js
> Error: Could not resolve './module_1' from dist/esm5/public_api.js
>    at error (/<path_to_project folder>/node_modules/rollup/dist/rollup.js:224:15)
>    at /<path_to_project folder>/node_modules/rollup/dist/rollup.js:19454:25
>    at <anonymous>

#### Expected Behaviour

rollup to find index.ts files in the folders and to build successfully.
I tried to integrate **_rollup-plugin-local-resolve_** with no success

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.0-rc.2
@angular/compiler:     6.0.0-rc.5
@angular/compiler-cli: 6.0.0-rc.5
rollup:                0.57.1
tsickle:               0.27.5
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
Can you please provide a sample repo?

**Comment by ghost81** [comment]
https://github.com/ghost81/ng-packagr-test

**Comment by alan-agius4** [comment]
I had a quick look at this, the issue seems to be related to TypeScript downleveling, as when downleveling happens TypeScript is not resolving using the node strategy. 

In order for you to work around this issue in the mean time, I'd suggest you reference the barrel files ex: `/index`

Another option is that we change a bit the implementation of the downleveling to https://github.com/dherges/ng-packagr/issues/785
