### ISSUE TITLE
Inline sourcemaps vs external sourcemaps in esm5 and esm2015 APF6

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#785]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
At the moment in  RC 1 of `ng-package` V3. We are shipping the sourcemaps as external files in `esm5` and `esm2015` folder, Angular shipped these as inlined. https://unpkg.com/@angular/common@6.0.0-rc.5/esm5/

From what I understand this is to speed up the build time of the application to reduce the amount of required file resolutions. Though I'd like to know if there are more reason for this, mainly from @IgorMinar as I think he was the master mind behind this :)

Shall we go with the same approach?

What will bring?
 - Instead of downleveling `TS`, from esm2015 to esm5 `NGC` will be used.
 - No need to re-wire sourcemaps for esm5 and esm2015.

//cc @filipesilva

**Comment by filipesilva** [comment]
I personally am not aware of any benefit to either approach (internal or external sourcemaps).

**Comment by alan-agius4** [comment]
The only thing I can think and based on the code is that for large projects it’s more efficient to use inline since webpack will have less file to resolve and read.

Basically, for `FESM` you have a single `js` file with a single `map` which is super fast to resolve. But for `ESM` you can potentially have `100s` of `js` files. which when sourcemaps are not inlined you would have that amount `x2` IO operations as webpack would have to resolve and do IO operations for both the `js` and `map` files. Rather than parsing a single file and get the code and sourcemap it will have to parse a file, resolve and read the sourcemap, which in large projects will slow down the build quite a lot.

This I think is also something similar why some people choose to flatten their `scss` files into a single one. (Similar to Angular Material 2)

As in general less IO operations is equal to faster builds.

In addition seeing the APF document (https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#), it looks like for `webpack 4` using `FESM` is something interim until a size problem is resolved.

> As of webpack v4 the flattening of ES modules optimization should not be necessary for webpack users, and in fact theoretically we should be able to get better code-splitting without flattening of modules in webpack, but in practice we still see size regressions when using unflattened modules as input for webpack v4. This is why "module" and "es2015" package.json entries still point to fesm files. We are investigating this issue and expect that we'll switch the "module" and "es2015" package.json entry-points to unflattened files when the size regression issue is resolved.

So I think `inline` vs `embedded` sourcemaps will have an impact on build speed sooner or later, maybe not on small projects, but for large once will.
