### ISSUE TITLE
[BUG] Max depth is not creating enough buckets

### ISSUE THREAD

**Issue by Chris3773** [dherges/ng-packagr#793]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

In the class [DepthBuilder](https://github.com/dherges/ng-packagr/blob/cfcf3f901f9d513dbcb0da987715599c95fb2138/src/lib/brocc/depth.ts#L96) the buckets created are one bucket short from the max depth causing the build to fail with entry points depending on more then 1 other entry point.

```
Depth 0 Max Depth: 2 Node: ng://@scope/name Bucket Length: 2
Depth 0 Max Depth: 2 Node: ng://@scope/name/ep1 Bucket Length: 2
Depth 1 Max Depth: 2 Node: ng://@scope/name/ep2 Bucket Length: 2
Depth 2 Max Depth: 2 Node: ng://@scope/name/ep3 Bucket Length: 2
```

#### How To Reproduce

Create a project with at least 3 entry points with 1 of the entry depending on the other 2 entry points. You will get the error `Cannot read property 'push' of undefined`

#### Version Information

```
ng-packagr: 3.0.0-rc.2 
```

**Comment by dherges** [comment]
Hi @Chris3773, how can I reproduce? THe following is working: https://github.com/dherges/ng-packagr/pull/817/files#diff-aad51d62ff957777286c418709a5398f

**Comment by Chris3773** [comment]
I moved my sub modules around and now it builds just fine. 

I'm not sure how I had more buckets then max depth.

**Comment by JoostK** [comment]
I had the same issue and looked into it a bit. I haven't figured out the exact minimum working reproduction scenario but looked into the code a bit and found that a parent is only revisited (re-queued) when it wasn't seen before:

https://github.com/dherges/ng-packagr/blob/cfcf3f901f9d513dbcb0da987715599c95fb2138/src/lib/brocc/depth.ts#L82-L83

```typescript
        if (!nodeDepths.has(parent.token)) {
          // Push the dependency to the queue and track its depth
          nodeQueue.push(parent);
          nodeDepths.set(parent.token, currentDepth);
        }
```

We may fix the issue by simply always enqueueing the node:

```typescript
        nodeQueue.push(parent);

        if (!nodeDepths.has(parent.token)) {
          nodeDepths.set(parent.token, currentDepth);
        }
```

Somehow however this seems sub-optimal to me as we now recursively revisit nodes that may happen over-and-over again. It may just be that we'd only need to derive `maxDepth` differently, or something else completely even perhaps. I will look into this some more in the coming days and see if I can write a testcase for reproduction together with a fix.

**Comment by georgiee** [comment]
This bugged me for a while together with secondary points referencing back the main entry.
Today I got a fix together with a PR https://github.com/dherges/ng-packagr/pull/845

The max depth is calculated correctly but the bucket array is not capable of holding it when you reach an element that requires the actual max depth.

You have to create another feature C in the samples  and import feature A + B in order to get a entry point at the max depth. I easily reproduced the error from my project.

The fix is easy: Make the bucket array one slot larger.

```
const buckets: Token[][] = new Array<Token[]>(maxDepth + 1);
```
