### ISSUE TITLE
undocumented breaking change in v3 : ng-packagr doesn't generate a tarball anymore

### ISSUE THREAD

**Issue by noelmace** [dherges/ng-packagr#802]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] documentation
```
(A feature request could be hadded to angular/devkit).

## Description

When building a library, ng-packagr doesn't generate any tarball anymore.

The expected behaviour was added by @filipesilva #715
See https://github.com/dherges/ng-packagr/commit/94bc915#diff-2e14a1a49f5dcec2e1af74d135633651R38

These regression was introduced by @alan-agius4 #738.
See https://github.com/dherges/ng-packagr/commit/4e6c4f4bb21869c69f084560af3fa75531e4d07f#diff-2e14a1a49f5dcec2e1af74d135633651L133

But the breaking change wasn't mentionned in https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#breaking-changes.

#### How To Reproduce

The associated test (https://github.com/dherges/ng-packagr/commit/94bc91513767e965778df299862b7d28428a2491#diff-7590c1f6c6a53411a7569652cab76e3cR28) was removed (https://github.com/dherges/ng-packagr/commit/4e6c4f4bb21869c69f084560af3fa75531e4d07f#diff-7590c1f6c6a53411a7569652cab76e3cL27).

#### Expected Behaviour

As we could see in #738 discussion, the drop of the tarball generation seems to make sence (https://github.com/dherges/ng-packagr/pull/738#issuecomment-379457152).

So, we'll need to : 
1. document this breaking change, especially how the tarball should be generated (with npm pack)
2. make the associated evolution in ``@angular-devkit/build-ng-packagr``

#### Version Information

```
ng-packagr:            3.0.0-rc.2
@angular/compiler:     5.2.10
@angular/compiler-cli: 5.2.10
rollup:                0.57.1
tsickle:               0.26.0
typescript:            2.6.2
```

**Comment by noelmace** [comment]
As I need this quickly, I may do the associated PRs today :smile:

**Comment by alan-agius4** [comment]
Apologies for this regression.

To generate the tarball, you need to do so manually by running the `npm pack` command in the `dist` folder of the library

**Comment by alan-agius4** [comment]
Just some takeouts though why it's part of the current build. 

At the moment a lot of users have `postbuild` scripts in order to do some transformation in the bundle, example bundle scss files, add some other files.  Generating a `tarball` from `ng-packagr` after the build steps would be invalid. (This is actually one of the problems with the initial approach https://github.com/dherges/ng-packagr/pull/715#issuecomment-378901242)
