### ISSUE TITLE
[Question]: Multiple entry files for ngPackage configuration

### ISSUE THREAD

**Issue by beynya** [dherges/ng-packagr#808]
## Description

Run into the situation, when I need additional entry file or file that will be compiled separately but will be included in the final output. 

Because of the way of compiling FESM module (if i'm right), I need to export everything from `index.ts`, like literally everything. But I need one file, that will not be included and exported separately. 

Example:
```libs/
    - lib-A
        - folder-A
        - folder-B
        - special-file.ts
        - index.ts
```
So `index.ts` has exports from `folder-A` and `folder-B`, and I need this `special-file.ts` to be compiled and provided by this `lib-A` and I'm totally okay to add this file like:
`import { somethingSpecial } from 'lib-A/special-file'`

I know there are some workarounds, like writing additional gulp script for compiling this file and placing it into the `dist` folder of the lib, but I would like to know if there any other options.

Any suggestions?

**Comment by dherges** [comment]
No, this is not supported. You may want to use miltipe [entry points](https://github.com/dherges/ng-packagr#secondary-entry-points). Each entry point has exactly one entry file by design.
