### ISSUE TITLE
Create a tutorial - please!

### ISSUE THREAD

**Issue by piernik** [dherges/ng-packagr#84]
I'm trying to use Your tool to build some modules - without good results:/

Can You please provide a tutorial that contains:
- creating project using `angular-cli`
- creating simplest module to export
- installing `ng-packagr`
- creating config files
- running `npm run publish` command

I, and many more users, would be very grateful

**Comment by dherges** [comment]
Can you take a look at [ng-packaged](https://github.com/dherges/ng-packaged)?

**Comment by piernik** [comment]
@dherges thanks for example. After brief looking. There is no `public_api.ts` file in example. How come?

**Comment by dherges** [comment]
Here are further resources:

Building an Angular 4 Component Library with the Angular CLI and ng-packagr, Nikolas LeBlanc

https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e
