### ISSUE TITLE
Allow option to build in root, not dist/

### ISSUE THREAD

**Issue by johnmcase** [dherges/ng-packagr#859]
## Type of Issue

```
[X] Feature Request
```

## Description

Currently ng-packagr always produces packages in a dist/ folder underneath the root of the project.  I propose providing an option to create the output directly in the root.

**My use case:**
I am building a monorepo of several angular components, and am using [lerna](https://github.com/lerna/lerna) to manage the build for the monorepo.  By default, lerna does not have the ability to publish out of the dist folder, and they will not implement that because building to a dist folder does not follow established npm best practices.  See:  lerna/lerna#91 lerna/lerna#901 lerna/lerna#1282

In the discussion of lerna/lerna#1282 I learned that the dist folder is really an anti-pattern in npm.  It causes `npm link` to a module using ng-packagr to fail because the root folder will be linked, not the dist folder.  I'm worried this is going to become a real problem for my project once I start to have dependencies between packages within my monorepo.

From what I can tell, it shouldn't be that difficult to implement this.  The package.json that is produced in the dist folder doesn't really have to be any different than the one in the project root with the exception of a few additional properties: (main, module, es2015, metadata, typings, etc.)

Ideally, I would love to see this change also backported to 1.x and 2.x because of #814

**Comment by jensbodal** [comment]
Have you tried setting the `dest` in your `ng-package.json` ?

**Comment by dherges** [comment]
1. Try setting the `dest` to the root directory.
2. It's an anti-pattern in npm to not have made the `dist` folder layout a pattern. Gradle writes output to the `build` directory, maven writes it to `target` and others do similar. Lerna should update their code for managing and linking dependencies. They should not use `npm link` at all, as it is flawed either way.

**Comment by dherges** [comment]
It's by the way not going to work by design as it would override the `package.json`.

I'm staying baffled at what is the right and wrong way and strongly believe that anyone should be allowed to find and go their way. Generating the distribution-ready `package.json` is a key benefit and is not going to go away.
