### ISSUE TITLE
feature: acknowledge tsconfig paths

### ISSUE THREAD

**Issue by deebloo** [dherges/ng-packagr#86]
What I would like to do is have multiple packages in the same repo. So far everything works well EXCEPT, I have one package that depends on another I have the paths defined in the tsconfig so that I can use the correct module name during development and testing.

```JSON
{
   ...
   "baseUrl": "./",
    "paths": {
      "@livesafe/common": [
        "./src/app/common/public_api.ts"
      ],
      "@livesafe/dialog": [
        "./src/app/dialog/public_api.ts"
      ]
    }
}
```

Everything works great for dev but falls over when trying to generate the bundle for @livesafe/dialog I get the following error.

<img width="1013" alt="screen shot 2017-07-31 at 8 29 21 am 1" src="https://user-images.githubusercontent.com/6563621/28777753-6ddc76ca-75ca-11e7-909d-bbc374262431.png">

Looking through the code I couldn't find a way to configure paths for the ngc step of the build.

**Comment by deebloo** [comment]
wait a minute maybe this already exists.

**Comment by deebloo** [comment]
the more I did I think this is a tsconfig issue not a rollup issue. Ill close this till i figure out exactly where my problem lies

**Comment by dherges** [comment]
@deebloo This is an enhancement to ng-packagr. Currently there is no solution for your use case.

Difficulty here is: linking to local builds introduces a build-order dependency, i.e., `@livesafe/common` needs to be built first before `@livesafe/core` is built. I don't know how exactly the [angular](https://github.com/angular/angular) packages solve that. I think it would require to map the `paths` to the build artefacts (not the TypeScript sources).

**Comment by deebloo** [comment]
@dherges hmmmm. ok. for now I will just stick with one packagable module and will manage the dependency between the two differently. I played around with the default AOT config and did get the module not found error to go away but ran into other issues. Ill look into it some more. If I come across a solution are you open to a PR?

**Comment by dherges** [comment]
@deebloo Yes, PRs are always welcome! 🍻 

You got me thinking. There might be a workaround w/ symlinks which you can give a try:

```
packages
  |- bar
  |   |- package.json
  |   |- node_modules
  |   |    |- foo # symlink to '../../foo/dist'
  |   |- dist
  |- foo
      |- package.json
      |- dist
```

**Comment by deebloo** [comment]
hmmmmmm that is a good idea actually. I cant think of why that wouldn't work

**Comment by deebloo** [comment]
@dherges so this totally works with npm link without even bothering with tsconfig paths. Perhaps there isn't a need for a code change but maybe some documentation on how to make it work?
```
packages
  |- bar
  |   |- package.json
  |   |- dist // run npm link here
  |- foo
      |- package.json
      |- dist // bar package now available here
```

**Comment by deebloo** [comment]
@dherges I am going to close this issue. Through more testing I can manage everything with npm link and I don't think this project would need to do anything else. cheers

**Comment by JoostK** [comment]
I have the same request, which I am currently solving using `yarn link` in `@my/lib`'s dist directory and then using `yarn link @my/lib` in the dependent package to make the internal dependency available there as well.

In a shell script, this looks something like:

```sh
yarn build:lib || exit

pushd dist/lib
yarn link
popd

pushd packages/dependent
yarn link @my/lib
popd

yarn build:dependent || exit
```

This does get a bit hairy once you start to have multiple packages with multiple reoccurring dependencies.

In the Angular build process, there is indeed [an ordered list of packages](https://github.com/angular/angular/blob/f96142cd7cdb87866fe4b2b07c0ffddbb74ff907/build.sh#L11-L26) which are built sequentially, such that the dist packages can be used by other packages. In their `tsconfig-build.json` file of each package they have [a path listing of all their dependencies](https://github.com/angular/angular/blob/f96142cd7cdb87866fe4b2b07c0ffddbb74ff907/packages/animations/tsconfig-build.json#L7-L9).

@dherges what do you think of allowing to configure all internal dependencies, something like this:

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/dependent",
  "dependencies": {
    "@my/lib": "../../dist/lib"
  }
}
```

We might also be able to automatically determine the dist path of the dependency by pointing to the source directory instead, that would be a bit user friendlier I suppose. I'm currently unsure about how this would work out given that `baseUrl` is currently `""` (is this on purpose?) but I can try if this works, if you think this may be something appropriate for ng-packagr.

**Comment by juristr** [comment]
Is there any progress on this issue? I have a similar scenario, like having nx workspace with multiple libs, where there is one "core" lib and two others which depend on "core".

**Comment by dherges** [comment]
@juristr In 2.3.0, you'll be able to have dependencies between entry point like material does with `@angular/cdk/collection` <- `@angular/cdk/table`. It would be a little radical to publish a lot of libraries in just one npm package. You will have one npm package for the whole nx workspace and each lib will be an entry point / sub-package.

With the new feature we have the fundamentals to make local "dependencies" or "dependsOnPackage" work. It just needs to be implemented to have multiple packages in the build and to set up the build graph in the proper order.

The current workaround for package dependencies like `@angular/common` -> `@angular/forms` is to have hand-written build scripts, build common first, then copy/symlink the dist folder to node_modules, and build forms.

**Comment by juristr** [comment]
> In 2.3.0, you'll be able to have dependencies between entry point like material does with @angular/cdk/collection <- @angular/cdk/table. It would be a little radical to publish a lot of libraries in just one npm package. You will have one npm package for the whole nx workspace and each lib will be an entry point / sub-package.

@dherges is that feature already baked in in `2.4.1`? If so do you have any docs I could look at. I'm currently about to setup some demo libs for tutorials and stuff. thx 👍

**Comment by dherges** [comment]
@juristr Yes, in the [secondary example](https://github.com/dherges/ng-packagr/tree/master/integration/samples/secondary)

File layout:

```
|- package.json (primary, @foo/bar)
|- sub
    |- package.json (secondary, @foo/bar/sub)
|- testing
    |- package.json (secondary, @foo/bar/testing)
```

In ts code, use the [module ids](https://github.com/dherges/ng-packagr/blob/master/integration/samples/secondary/feature-a/feature-a.ts#L1) (not relative paths):

```ts
import { SHARED_FEATURE } from '@sample/secondary/shared';
```

**Comment by juristr** [comment]
@dherges alright, thx for the quick answer.

I've been looking at the secondary example and that covers creating a single NPM package with multiple entry points, very much like Angular material does 👍 

But what about more of a scenario like the Angular build itself. I have such a scenario over at [ngx-formly](https://github.com/formly-js/ngx-formly/tree/master/src), where we have

- @ngx-formly/core
- @ngx-formly/bootstrap _(depends on @ngx-formly/core)_
- @ngx-formly/material _(depends on @ngx-formly/core)_

All of them have the same version but get distributed via separate NPM packages as people usually choose either bootstrap or material. Right now it's covered with a [patch that gets applied to ng-packagr, setting the tsConfig path as a workaround.](https://github.com/formly-js/ngx-formly/blob/master/.config/ng-packagr.patch)

Is such a scenario already covered?

**Comment by dherges** [comment]
No, not yet. There's two sides of it:

1. improving the programmatic API for better tsconfig customization (it's a mess, there's a default tsconfig, an entry point tsconfig, and a build-time tsconfig). What users want is to configre the entry point tsconfig. Right you, the API only allows to configure the default.
2. multi-package builds: something like `dependsOn: [ "path/to/other/package.json" ]` that will build the dependee package first and then build the dependent.

**Comment by deanpeterson** [comment]
I have a similar problem. Following a suggestion for making environment variables reusable, I added the following to the tsconfig:
`"compilerOptions": {
   .
   .
   .
    "paths": {
      "@env/*": ["environments/*"]
    }
  },`

That is so I can use something like:
`import { environment } from "@env/environment";`
Rather than a relative path to the evironment.ts file that exists outside the modules base folder I will be packaging up. Of course when I go to run npm run build:lib to execute ng-packagr I get the error that @env module does not exist. I am having a little trouble deciphering some of the suggestions above. Is there an approach that will work to fix this problem? I would like to use environment variables in place of hard coding values that will change based on the application my npm package is running in. I thought I had a solution with @env/environment but ng-packagr will not allow it.
