### ISSUE TITLE
Packaging fails after upgrading to Angular 6 | Issue related to Custom Pipes & some other unidentified problem

### ISSUE THREAD

**Issue by ledicjp** [dherges/ng-packagr#874]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I recently upgraded my app to Angular 6.0.1 and now ng-packagr doesn't build anymore.
```
src\app\mycomponent\my.component.ts.MyComponent.html(XXX,YY): : Expected 2 arguments, but got 1.
...

at Object.<anonymous> (C:\...\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\...\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\...\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\...\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:44:32)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

#### How To Reproduce

Wherever I'm using a custom pipe, e.g. `<div>{{ someVariable | myCustomPipe }}</div>` I get strange errors like the following one. When I remove the pipe the error disappears.
```
src\app\mycomponent\my.component.ts.MyComponent.html(XXX,YY): : Expected 2 arguments, but got 1.
```

_Of course I also tried with ng-packagr versions 2.4.X but then I get this kind of error:
https://github.com/dherges/ng-packagr/issues/767#issuecomment-385199831_

#### Expected Behaviour

I would at least like to know about some way to ignore these kinds of errors because `ng build --prod` works completely fine for me, even after the migration to Angular 6. I don't see a reason for ngc being more strict than `ng build --prod`.

#### Version Information

```
ng-packagr: 3.0.0-rc.5
@angular/*: 6.0.1
typescript: >=2.7.0 <2.8.0
rxjs: 6.1.0
rxjs-compat: ^6.0.0-rc.0
node: 8.11.1
npm: 5.8.0
```

**Comment by alan-agius4** [comment]
Can you please create a small reproduction?

**Comment by ledicjp** [comment]
After hours and hours I found out that it was my own fault, I'm sorry.
My custom pipe's transform function expected the args parameter, but I didn't provide one, because it's supposed to be optional.


##### changed:
`transform(value, args: string[])`

##### to:
`transform(value, args?: string[])`

Possibly the shortest fix ever... 😃
