### ISSUE TITLE
Better indication of where warnings happen

### ISSUE THREAD

**Issue by pfeigl** [dherges/ng-packagr#882]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

While running a build using ng-packagr different warnings can come up. Here is some examples:

```
Dropping unreachable code [0:1066,8]
Declarations in unreachable code! [0:1066,8]
Dropping unreachable code [0:1172,16]
Declarations in unreachable code! [0:1172,16]
Side effects in initialization of unused variable Vi [0:3321,37]
```

#### How To Reproduce
Just write some code which triggers some of those warnings and build it

#### Expected Behaviour
I don't just see, that there are warnings, but I also get indications of where those warnings happen. In order to be able to fix them, I'd atleast need to know the file where they actually come up.

#### Version Information

```
ng-packagr:            3.0.0-rc.5
@angular/compiler:     6.0.2
rollup:                0.58.2
tsickle:               0.27.2
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
This is not something coming from `ng-packagr`, but rather https://github.com/mishoo/UglifyJS2

**Comment by abbazabacto** [comment]
👍 for showing the filename the uglify warning originated from, maybe even with mention this is coming from uglify

with the commit from @pfeigl I was able to solve the warnings in no time

**Comment by dherges** [comment]
Ok, I'll close the issue now. At least it's a little bit better!

**Comment by nayfin** [comment]
@dherges can we get this change? I copy pasted it in as well and found it very helpful. I can make a PR if it is helpful.
