### ISSUE TITLE
@Self() decorated dependency throws an error

### ISSUE THREAD

**Issue by abbazabacto** [dherges/ng-packagr#897]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

With the new `ng-packagr@3.0.0-rc.5` when building my package I noticed an error: 

```sh
BUILD ERROR
: No provider for NgControl ("[ERROR ->]<custom-form-field></custom-form-field>")
```

The line it originated from came from the `constructor` of a custom form component using a `ControlValueAccessor`, it seems that `@Self()` decorator made the DI fail. If I remove the build passed again.

When using the `@Self()` decorator, the only place allowed to find the injector is the component itself.

The same issue doesn't appear for other DI-decorators like `@Host()` and `@Optional`

#### How To Reproduce

Setup a minimal custom form field component using the `@Self()` decorator.

```typescript
import { Component, Self } from '@angular/core';
import { ControlValueAccessor, NgControl } from '@angular/forms';

@Component({
  selector: 'custom-form-field',
  template: ''
})
export class CustomFormFieldComponent implements ControlValueAccessor {
  constructor(
    @Self() public controlDir: NgControl
  ) {
    controlDir.valueAccessor = this;
  }

  onChange: (val: any) => void;
  onTouched: () => void;

  writeValue(val: any) {

  }

  registerOnChange(fn: (val: any) => void) {
    this.onChange = (val) => fn(val);
  }

  registerOnTouched(fn: any) {
    this.onTouched = fn;
  }
}
```
When building this package where this file is included it will result into:
```sh
BUILD ERROR
: No provider for NgControl ("[ERROR ->]<custom-form-field></custom-form-field>")
```

#### Expected Behaviour

I assume it would be able to build this just fine, as the module where the component is used is using the `ReactiveFormsModule` which provides this `NgControl`. Not sure if `ng-packagr` has special rules in place for injecting dependencies with `@Self()`.

#### Version Information

```
ng-packagr:            3.0.0-rc.5
@angular/compiler:     6.0.2
rollup:                0.58.2
tsickle:               0.27.5
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
This doesn’t seem to be a bug, ngControl can be optional and thus apart from ‘self’ one should add ‘optional’ as well, as your component in reality doesn’t get inject like a normal service for instance like httpClient, it gets injected based on the usage of the component.

Check an example;
https://github.com/angular/material2/blob/master/src/lib/input/input.ts

Also ng-packagr doesn’t have any logic for this, its alll done by the Angular Compiler.

**Comment by abbazabacto** [comment]
Thanks for the amazing quick reply @alan-agius4 

Adding `@Optional()` seems to make the compiler happy:
```
constructor(
    @Optional() @Self() public controlDir: NgControl,
```

**Comment by sanbagh** [comment]
![image](https://user-images.githubusercontent.com/60337853/81481445-ec21da00-924d-11ea-8c69-8f3b95973298.png)

After adding @optional(), it gives me the following error: 
`main-es2015.dfd3fc047972bfa56e6c.js:1 ERROR NullInjectorError: StaticInjectorError(s)[yt -> t]: 
  StaticInjectorError(Platform: core)[yt -> t]: 
    NullInjectorError: No provider for t!
    at $.get (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:37927)
    at https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55365
    at t (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55745)
    at Ge.get (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55896)
    at https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55365
    at t (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55745)
    at Ge.get (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:55896)
    at Qi (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:79230)
    at br.get (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:87841)
    at jr (https://localhost:5001/main-es2015.dfd3fc047972bfa56e6c.js:1:91686)`
