### ISSUE TITLE
Stripe Integration and typings.d variables

### ISSUE THREAD

**Issue by phixMe** [dherges/ng-packagr#908]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I am encountering an issue with my Stripe integration, but I believe the issue to be more general with variables added into the `src/typings.d` file. I cannot seem to find a way to provide ng-packagr with information about this variable.

#### How To Reproduce

This variable is declared in my `src/typings.d` file:
```typescript
declare var Stripe: any;
```

It is referenced in a component: 
```typescript
this.stripe = Stripe(environment.stripeToken);
```

My index.html file includes the Stripe V3 script tag:
```html
<script src="https://js.stripe.com/v3/"></script>
```

When running the `ng-packagr -p ng-package.json` command I get the following errors.
```sh
error TS2304: Cannot find name 'Stripe'.
```

#### Expected Behaviour

My expectation is that ng-packagr has a mechanism to be informed about the existence of this variable and whitelist it.

#### Version Information

```
ng-packagr: 3.0.0
@angular/*: 6.0.3
typescript: 2.7.2
rxjs: 6.2.0
node: 8.9.4
npm/yarn: 6.0.0
```

**Comment by alan-agius4** [comment]
You need to reference `src/typings.d.ts` in your component using the triple slash reference https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

example in your `whatever.component.ts` you need to add the following
```ts

/// <reference path="../typings.d.ts" />
```

**Comment by phixMe** [comment]
This ended up working out for me. Thanks so much.

Perhaps this should be documented somewhere in the repository.
