### ISSUE TITLE
[Question] README files per sub folders are not copied to dist

### ISSUE THREAD

**Issue by AhnpGit** [dherges/ng-packagr#910]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

I create a library using Angular CLI v6 (which integrates ng-packagr) with a structure like this
![image](https://user-images.githubusercontent.com/27772165/40711775-5d162b9e-63fc-11e8-9082-463225a9317b.png)

and I notice that when I build the library, only the README on the `src` level is copied to the dist but not the one inside my panel-header folder.
Is this the expected behavior or this is a bug ?

#### How To Reproduce

- Generate a library using Angular CLI v6 by `ng g lib test-lib`
- Create a `README.md` inside folder `projects/test-lib/src/lib`
- Run `ng build test-lib --prod`
- Observe that `README.md` is not inside `dist`

#### Expected Behaviour
**N.A.**

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0
@angular/*: 6.0.3
typescript: 2.7.2
rxjs: 6.2.0
node: 8.11.2
yarn: 1.7.0
```

**Comment by alan-agius4** [comment]
Yes, this is the correct behaviour, only the main`ReadMe.md` file is copied. If you want to do documentation for components/features, I strongly suggest you use  compodoc[https://github.com/compodoc/compodoc] togather with js and ts docs

**Comment by AhnpGit** [comment]
Thank you for your response !
