### ISSUE TITLE
Search for secondary entry point takes a VERY long time

### ISSUE THREAD

**Issue by CarstenLeue** [dherges/ng-packagr#921]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

With v3.x under Windows I experience that the build with ng-packagr takes a long time in "Building Angular Package" (about 1 minute), then completes with expected performance.

After adding some debug info, I think that the responsible piece of code is:

```typescript
const filePaths = await globFiles(`${directoryPath}/**/package.json`, {
    ignore: EXCLUDE_FOLDERS,
    cwd: directoryPath
});
```

in "discover-packages.ts". 

The EXCLUDE_FOLDERS structure correctly excludes all package files in node_modules, but the complete node_modules file tree is still scanned. This takes a lot of time for projects with many (dev)Dependencies.

The structure looks like this for me:

```typescript
[ '**/node_modules/**/package.json',
  '**/node_modules/**/ng-package.json',
  '**/dist/**/package.json',
  '**/dist/**/ng-package.json',
...]
```

The "node_modules" directory is not excluded as a whole, but just the package files.

### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.1
```

**Comment by elclanrs** [comment]
We have a library with about 60 components each as a secondary entry point. It takes a few minutes to build, and it does get stuck for a while during "Building Angular Package". We even had to increase the memory limit to 8GB to be able to compile the library, otherwise it runs of of memory. We did this:

```
node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng build components --prod
```
