### ISSUE TITLE
[Question]  What is the preffered way to publish a package generated by ng-packagr?

### ISSUE THREAD

**Issue by Itrulia** [dherges/ng-packagr#922]
I currently use use these npm scripts

```
"publish:package": "npm run build && npm publish dist",
"prepublishOnly": "printf '\\n\\n Use npm run publish:package` instead! \\n\\n\\n\\n' && exit 1"
```

Is there a method that you guys prefer? Because my solution feels like a terrible hack.

Using `npm publish dist` has 2 problems, someone might publish the root folder and `prepublishOnly` nor `prepare` will not get fired at all.

**Comment by JrPribs** [comment]
@Itrulia from my experience I publish from inside the built package directory:

```
"publish:lib": "yarn build:lib && cd dist/ngx-lib/ && npm publish"
```

**Comment by Itrulia** [comment]
Yeah this has the problem that you can accidentally publish the root repository (which happened to me) :(

**Comment by JrPribs** [comment]
If you are inside of the built library's directory (where the package.json is for the library) then there should be no chance of the root repository being built instead of the package for which you are in the root of. To be sure you can also add the package name to the end of the command `npm publish @org/package`

**Comment by Itrulia** [comment]
Yes but thats not my point. My point is that it actually can happen when you don't watch the directory and I don't want this ever to happen.

Human errors happen, and this is a very easy one for mitigate by validating it.

**Comment by paulsouche** [comment]
Hi,

Assuming your output folder is `dist` you can run `npm pack dist/` in the root folder (`/` is mandatory). This will generate a `*.tgz` file in the root path. You can run `npm publish ${your_file_name}.tgz` to publish your package.

Hope it helps

**Comment by Itrulia** [comment]
I know, the problem is rather that you can accidentally publish the root directory.

Unfortunately `private` is not stripped when generating the bundle, and `scripts` is stripped because of security reasons.

**Comment by paulsouche** [comment]
Oh I see ! You can always use `.npmignore` in your root folder and | or `"files"` entry in your `package.json` to only publish dist at root level. Root `package.json` entries such as `main`, `module`, `es2015`, `types`... must import dist files.

**Comment by Itrulia** [comment]
But I want to publish the content of dist, not from root and only dist (difference where package.json for example is). Afaik ng-packagr doesn't support that anyway (it creates a new package.json in dist) so thats out of the question anyway.

**Comment by Itrulia** [comment]
Im just going to close this here, I have changed my workflow and disallow publishing completly without the CI/CD credentials.
