### ISSUE TITLE
How do you override / turn off fullTemplateTypeCheck?

### ISSUE THREAD

**Issue by andrewling89** [dherges/ng-packagr#923]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description
I'm wondering how you can override / turn-off fullTemplateTypeCheck? I have a few third party libraries that aren't yet updated to work for Angular 6 and I need to have this setting turned off to get my library to compile. Changing **angularCompilerOptions.fullTemplateTypeCheck** to false in lib/ts/conf/tsconfig.ngc.json gets things to compile, but I'd like to know how to do this without trying to change my node_modules folder.

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.1
@angular/*: 6.0.3
typescript: 2.7.2
rxjs: x.y.z
node: x.y.z
npm/yarn: x.y.z
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
You’d need to use the Ng-packagr API.

You can find an example here: https://github.com/dherges/ng-packagr/blob/master/integration/samples/api/ng-packagr-api.js

**Comment by andrewling89** [comment]
How would you reference the API in your package.json file?

**Comment by alan-agius4** [comment]
You can use ts-node or node directly.

You’d do: “build”: node ./ng-packagr-api.js
