### ISSUE TITLE
Enhanced object literals ES6 support

### ISSUE THREAD

**Issue by beatadelura** [dherges/ng-packagr#939]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[X] Not sure
```

## Description

There is an error during `ng-packagr` running script:
```
Dropping unreachable code [0:371,8]
Declarations in unreachable code! [0:371,8]
```

I found out, method which returns object with enhanced object literals cuase an error above:
```
  private _exampleMethod(): any {
    return {
        [`${TestComponent.prefix}disabled`]: this.disabled,
        [`${TestComponent.prefix}${this.type}`]: this.type,
    };
  }
```

#### Expected Behaviour

No error
```
Dropping unreachable code [0:371,8]
Declarations in unreachable code! [0:371,8]
```

#### Version Information

```
ng-packagr:            2.4.2
@angular/compiler:     5.2.10
@angular/compiler-cli: 5.2.10
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.5.3
rxjs: 5.5.10
node: 8.11.1
npm 6.1.0
```

**Comment by alan-agius4** [comment]
Hi @beatadelura, those warnings are from `uglify-js` as we used that to minify the UMD bundle and not directly caused by `ng-packagr`.

**Comment by beatadelura** [comment]
@alan-agius4 Thanks for the answer!

**Comment by beatadelura** [comment]
@alan-agius4 Do you have any knowledge from `uglify-js` for support similar issues?

**Comment by alan-agius4** [comment]
Not really, I guess what’s best is to open an issue with them. And explain
the problem. By grabbing the outputted unminified UMD bundle and try to
uglify it

If you need any further help you report the problem. Let me know.
