### ISSUE TITLE
[Bug] libraries dependencies using index.ts

### ISSUE THREAD

**Issue by piernik** [dherges/ng-packagr#943]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I thinks it's a angular-cli issue, but what do I know :)
I posted it there and here as well: https://github.com/angular/angular-cli/issues/11210

Here is project: https://github.com/piernik/lib-deps-bug

It contains two libraries. Second is dependent on First. Build first lib using `npm run first:build`, then build second using `npm run second:build` - it fails.
Now go to https://github.com/piernik/lib-deps-bug/blob/master/projects/first/src/lib/first.module.ts and comment in `import {MyPipePipe} from './pipes';` and comment out `// import {MyPipePipe} from './pipes/my-pipe/my-pipe.pipe';`
It is working now.

#### Expected Behaviour

Pipes folder is exported as a whole with index.ts so it should work.

#### Version Information

In project I use `"ng-packagr": "^3.0.0-rc.2",` that comes with angular-cli but also tried `3.0.1` this the same result.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/dherges/ng-packagr/issues/917

**Comment by piernik** [comment]
So for now I have to skip `index.ts` files? Or maybe there is other solution? 
It's completely `angular-cli` bug?

**Comment by alan-agius4** [comment]
It's not an `angular-cli` bug, but more of an `angular` compiler bug.

Can you try to import `import {MyPipePipe} from './pipes/index` instead?

**Comment by piernik** [comment]
Ok thanks for help. Hope they fix it soon.
