### ISSUE TITLE
Module not found: Error: Can't resolve ' commonjs-proxy:../..

### ISSUE THREAD

**Issue by yorkie-m** [dherges/ng-packagr#944]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

Unsure if this is an angular-cli issue or ng-packagr.

Have an angular 6 application containing a library project.  When I build using ng-packagr directly the resulting npm package can be consumed from another Angular 6 application.  When I build using the angular-cli the resulting package cannot be consumed from another Angular 6 application and get multiple errors as follows when trying to build the consuming Angular 6 app:

ERROR in ./node_modules/c-lib/fesm5/c-lib.js
Module not found: Error: Can't resolve ' commonjs-proxy:../../a-service/a.service' in 'C:\data\sandbox\angular\example-ng6-lib-app\node_modules\c-lib\fesm5'

#### How To Reproduce

1. Given the following configuration in angular.json, build the library using the angular cli and then package using npm:

```
ng build --prod c-lib
cd dist/c-lib && npm pack
```

angular.json:
```
"architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/c-lib/tsconfig.lib.json",
            "project": "projects/c-lib/ng-package.json"
          },
          "configurations": {
            "production": {
              "project": "projects/c-lib/ng-package.prod.json"
            }
          }
        },
```

2. Install the library into another angular 6 application and attempt to consume a component from the installed library

3. Build the consuming application

#### Expected Behaviour

Expect the consuming application to build successfully and consumed component to function correctly.

This expected behaviour is achieved when using ng-packagr directly replacing step 1 above with the following:

```
ng-packagr -p ./projects/c-lib/ng-package.prod.json
cd dist/c-lib && npm pack
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.0.0-rc.0
@angular/compiler:     6.0.0
rollup:                0.59.4
tsickle:               0.27.5
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Can you please provide a reproduction?

**Comment by AlexanderKozhevin** [comment]
Same problem. I got after upgrading the project from 5 to 6.

**Comment by alan-agius4** [comment]
Can someone please provide a reproduction?, As I am unable to replicate this issue

**Comment by AlexanderKozhevin** [comment]
@alan-agius4 30 min, I'll make the repose.

**Comment by AlexanderKozhevin** [comment]
@alan-agius4 https://github.com/AlexanderKozhevin/angular6-library-test
Here we are.
Created project from scratch, added library, got an error. 
Please, let me know if you know how to fix that.

**Comment by alan-agius4** [comment]
@AlexanderKozhevin, for thanks the reproduction. And as always in the open source community a good reproduction always gets things solved fast.

What I noticed is that the module format used in `esm5` and `fesm5` is `commonjs`. This is due that in `tsconfig.lib.json` you don't have a module specified. Please add the following.

```json
"compilerOptions": {
    "module": "es2015",
     ...
},
```

**Comment by AlexanderKozhevin** [comment]
@alan-agius4 👍 
Thank you so much!  It worked.

**Comment by alan-agius4** [comment]
Just a small update, this look like it's a regression from https://github.com/angular/angular-cli/pull/11196

Thus, ideally the `module` should be added in the root tsconfig.

**Comment by yorkie-m** [comment]
@alan-agius4 @AlexanderKozhevin Thanks so much both.  Sorry for lack of reproduction, had to move onto some other work.  I'll switch back to using ng build and use the module setting. Cheers

**Comment by AlexanderKozhevin** [comment]
Alright wrote quick overview. 
https://medium.com/@alexpolymath/migrate-from-angular-5-to-6-cli-8840a4b6df99

**Comment by egdraper** [comment]
This got me on the right track, so I thought I would add this as well incase someone else has the same issue. 
Even though we had the `tsconfig.lib.json` compilerOptions with `module: es2015` it still wasn't working. We had to add `Target: es2015` as well to get it to work.
Thanks, all y'all.

**Comment by debugguru** [comment]
I have the entries in the tsconfig.lib.json but I am still seeing the error if I do ng build and reference the package in another angular 6 project.
`   "target": "es2017",
    "module": "es2017",`

**Comment by alan-agius4** [comment]
Target should be es2015 not es2017.

**Comment by debugguru** [comment]
> Target and module should be es2015 not es2017.

Should it matter? Is it tied down to es2015. I am going to try it out with 2015 now.

**Comment by debugguru** [comment]
Thanks Alan. Changing the module to es2015 sorted the issue

**Comment by harishrathor** [comment]
Hi All,
I am using Angular 7.2.0 and Angular Compiler 7.3.1. I am getting below error:

Module not found: Error: Can't resolve 'ngx-custom-validators' in 'D:\Naehas\Google Drive\SOP\projects\baseProject\node_modules\simple-form-generator\fesm2015'
--


In my tsconfig.json
`"module": "es2015", "target": "es5"` and I also tried with `"target": "es2015",`.
When I give relative path such as: 
`import { CustomValidators } from '../../../../../../../node_modules/ngx-custom-validators'`

then it is working.

I am not getting how to resolve this issue.
