### ISSUE TITLE
Looking for secondary entry points is VERY slow

### ISSUE THREAD

**Issue by CarstenLeue** [dherges/ng-packagr#948]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

On Windows, the call "const findSecondaryPackagesPaths = (directoryPath, excludeFolder) =>" takes a very long time (about 1 minute). This slows down the build process tremendously.

I assume that this is because the file search does not exclude node_modules as a whole but only the package.json files inside the folder. This causes the scan to iterate over the complete directory, which is very slow.

#### How To Reproduce

Use ng-packager on Windows with a project that has a relatively large dependency tree.

#### Expected Behaviour

I would expect the scan for the secondary entry point to be either faster or see a way to disable it.

#### Version Information

```
ng-packagr:            3.0.2
@angular/compiler:     6.0.1
rollup:                0.59.4
tsickle:               0.27.5
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This is strange as in `3.0.2` all node_modules are excluded.
https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/discover-packages.ts#L90

**Comment by CarstenLeue** [comment]
If I replace 

```typescript
  const filePaths = await globFiles(`${directoryPath}/**/package.json`, {
    ignore,
    cwd: directoryPath
});
```
with

```typescript
  const filePaths = [];
```

(which I now do during development), the build performs as expected, so I am confident that the cause of the poor performance is the "globFiles" call. I also see in my disk monitoring tools that the time is spent iterating the "node_modules" folder. 

My guess is that the glob pattern 
```
**/node_modules/**/*
```

does exclude all files inside the node_modules tree, but it does so by excluding the files individually, not by preventing the node_modules folder from being iterated.

Semantically the result is as expected, I do NOT see hundreds of files.

Concerning performance across OS: I do not have access to a Mac, but I know that on *nix based systems the scan of the file system is by far faster compared to Windows. 

My suggestion would be to use a glob pattern that excludes "node_modules" as a folder and does not iterate into the sub directories.

**Comment by alan-agius4** [comment]
I'll try to investigate this a bit further, but the last time I checked though `**/node_modules/**/*` was the only glob that was properly ignoring `node_modules` files and folders.

**Comment by CarstenLeue** [comment]
This pattern works for me:

```
'**/node_modules/**'
```

I have actually done a simple testcase to validate what files glob iterates over:

```javascript
const Promise = require('bluebird');
const globFiles = Promise.promisify(require('glob'));

const directoryPath = __dirname;

const ignore = ['**/node_modules/**'];

const cache = {};

const res = globFiles(`${directoryPath}/**/package.json`, {
  ignore,
  cwd: directoryPath,
  cache
});

res.then(console.log).then(() => console.log('cache', cache));
```

The content of "cache" shows the touched files.

With the original pattern, the cache is filled with all files in node_modules. With the updated pattern this is not the case.

**Comment by alan-agius4** [comment]
I’ll have a look at this tomorrow and try check the glob that you provided as if I recall correctly, that was not ignoring on OS X, but maybe I was doing something wrong.
