### ISSUE TITLE
Referencing files in primary folder from a secondary entry point

### ISSUE THREAD

**Issue by danielmhair** [dherges/ng-packagr#959]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have a secondary entry point for my Angular Library such as `@mylib/core` and `@mylib/core/testing`. My package.json file in `@mylib/core/testing` looks like this:

```
{
  "ngPackage": {
    "lib": {
      "entryFile": "lib/index.ts"
    }
  }
}
```

My folder structure in my folder called `my-lib` is like this:

![image](https://user-images.githubusercontent.com/7373734/41623014-ad867584-73ce-11e8-8b6e-d49f8d60dbd9.png)

My `lib/index.ts` is:
```
export * from "../../src/lib/common/navigator/navigator.component.stubs"
...
export * from "./templates/index"
export * from "./third-party.stubs"
```

Where the first import is going to a stub not located in the testing folder. The reason I desire this is because we have our stubbed files next to the components they are stubbing. Then the testing package will collect all those stubs.

However, when running `ng build my-lib`, I receive the following error:

```
error TS6059: File 'C:/Users/I20649/Workspace/angular-app/my-lib/src/lib/common/navigator/navigator.component.stubs.ts' is not under 'rootDir' 'C:\Users\I20649\Workspace\angular-app\my-lib\testing\lib'. 'rootDir' is expected to contain all source files.
...
    at Object.<anonymous> (C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at C:\Users\I20649\Workspace\angular-app\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

where the reoccuring error is `...'my-lib/src/lib/common/navigator/navigator.component.stubs.ts' is not under 'rootDir' 'C:\Users\I20649\Workspace\angular-app\my-lib\testing\lib'. 'rootDir' is expected to contain all source files.`

#### How To Reproduce

1. Create a main entry point
2. Create a secondary entry like I described above
3. Import a file from "../../src/lib/*.ts"
4. Run `ng build my-lib`

#### Expected Behaviour

I hope that I can somehow include all `*stubs.ts` files in the `src/lib` folder and include them in my secondary package. Also, something important to note is that these `*.stubs.ts` files use imports like `import { SomeModel } from "@my-lib/core"` (imports things from the primary entry point package).

#### Version Information

```
ng-packagr: 3.0.2
@angular/*: 6.0.4
@angular-devkit/build-ng-packagr: 0.6.8
@angular-devkit/build-angular: 0.6.8
typescript: 2.7.2
rxjs: 6.0.0
node: 8.11.2
yarn: 1.7.0
```

**Comment by danielmhair** [comment]
I also thought that perhaps, to satisfy this error, I can have a prebuild script that will copy all stubs to a `stubs` folder inside `my-lib/testing/stubs` with an index.ts exporting all those files. But if I don't have to do this, I would prefer that.

**Comment by alan-agius4** [comment]
From the screenshot it looks like the secondary entrypoint package.json is under lib. That is incorrect, the should be directly under testing as that is your entrypoint.

In order to reference symbols in the secondary entrypoint from the primary or vice verbs. This needs to be done like extral module inports and not relative paths.

Such as: import. {foo} from “my-lib” in your secondary entry point

**Comment by danielmhair** [comment]
Yeah, your right, it does look like that. However, let me hide the contents of that folder.

![image](https://user-images.githubusercontent.com/7373734/41651075-e4db9a28-743c-11e8-936b-53a291014b5d.png)

In other words, the package.json is directly under the testing folder.

**Comment by danielmhair** [comment]
The thing is, I'm not referencing files that are in "my-lib", it just happens to be files that are in the same location as files in "my-lib". I ignore all `*.stubs.ts files` in "my-lib" since they are only useful in the `testing` folder. However, for easier understanding where a stub is, we keep it in `src/lib`.

**Comment by alan-agius4** [comment]
From the issue desribed above in the first export you are referencing files from the primary entrypoint as relative paths. This is not correct. But rather you need to reference them using the library name example: ‘my-lib’.

You cannot reference anything above the entrypoint package.json using relative paths. Secondary entry points are separate typescript compilations, which will fail if you try to resolve something with is not under that entrypoint ‘src’

**Comment by danielmhair** [comment]
I appreciate your help!

Before I create a small reproduction, I think I may understand what I need to do. Please give me advice, if I misunderstand.

Because my stubs are above my secondary library's package.json (`my-lib/testing/package.json`), that this error is correct to say that it cannot build this library until those exports are removed.

I have created a pre-packager that does the following:
1. Find all `*.stubs.ts` files in `src/lib`
2. For any relative imports that are from 'my-lib' (any file that is not a .stubs file), change to `my-lib` imports. For example, if `navigator.component.stubs.ts` had an import like this `import { MlNavigatorComponent } from "./navigator.component"`, then the code would change that import to `import { MlNavigatorComponent } from "my-lib"`
3. Save `navigator.component.stubs.ts` as a new file (not changing the original), in the folder `my-lib/testing/lib/stubs` -- I would repeat this for every stubs file
4. Collect all the stubs' paths and generate an index file at: `my-lib/testing/lib/stubs/index.ts`
5. Ensure that `my-lib/testing/lib/index.ts` (my secondary entry point) looks like this:
```
export * from "./stubs/index"
export * from "./templates/index"
export * from "./third-party.stubs"
```

Your thoughts, @alan-agius4?

**Comment by danielmhair** [comment]
Okay, so I no longer have this bug issue. I understand that I may have to make another issue from this. When I run `ng build my-lib`, it is now saying:
```
forms-plus/testing/lib/stubs/common/model/form-template.stubs.ts(3,34): error TS2307: Cannot find module 'my-lib'.
```
I realize that I don't have a tsconfig file. Will I need to set one up for it to recognize that I have a path like so?
```
{
  "compilerOptions": {
    "paths": {
      "@xprm/forms-plus": [
        "../../dist/forms-plus"
      ]
    }
  }
}
```

**Comment by danielmhair** [comment]
@alan-agius4 I have now tested this and it looks like my steps above resolved this issue. It seems to be running well. I am still receiving some errors, but it's not related to this error. It is related to another error I have, which I will create another issue for.
