### ISSUE TITLE
Priority in secondary packages

### ISSUE THREAD

**Issue by danielmhair** [dherges/ng-packagr#960]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I have multiple secondary packages for my library `my-lib` as follows:
- `my-lib/defaults`
- `my-lib/testing`

However, `my-lib/testing` depends on `my-lib/defaults` and therefore `my-lib/defaults` needs to make sure it is built before `my-lib/testing`. Is there a way to ensure that the defaults package is built before the testing package?

#### Version Information

```
ng-packagr: 3.0.2
@angular/*: 6.0.4
@angular-devkit/build-ng-packagr: 0.6.8
@angular-devkit/build-angular: 0.6.8
typescript: 2.7.2
rxjs: 6.0.0
node: 8.11.2
yarn: 1.7.0
```

**Comment by alan-agius4** [comment]
This is done automatically. As ng-packagr analysis the dependencies and builds a dependency graph used to build the entry points in order

**Comment by danielmhair** [comment]
Exciting! Thanks @alan-agius4

**Comment by Hobart2967** [comment]
This is anyhow not working.

using a class exported from

module/entryPointA/src/class1.ts
=> import {class2} from 'module/entryPointB';

while entryPointB exports class2 it shows:

Cannot find module 'module/entryPointB'.

As it's not built yet...

**Comment by johnny-mh** [comment]
@Hobart2967 In my case. fixing `tsconfig.json` paths for `module/entryPointB' is work.

You can check right path by seeing `entryPointA` dist folder.

If your dist folder look like below

```
dist/
  my-lib/
    bundles/
    esm5/
    ...
    src/
      lib/
        entryPointA/    <-- right `entryPointA` paths
        entryPointB/         
```

So you need to set paths to

```
paths: {
  "my-lib/*": ["dist/my-lib/src/lib/*"]
}
```

**Comment by johnny-mh** [comment]
@Hobart2967 This not work.

@alan-agius4 It seems to building secondary packages follow sorting directory name.

for example. entryPointB use entryPointA is work fine. but opposite case is not work.

If entryPointA reference entryPointB. For my opinion.. Build entryPointB is right.

**Comment by alan-agius4** [comment]
@johnny-mh, which version of ng-packagr are to using?

**Comment by johnny-mh** [comment]
@alan-agius4 I'm tested that with `ng-packagr@5.7.1`

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.25
Node: 10.16.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.25
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.25
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.25
@angular-devkit/schematics         8.3.25
@angular/cli                       8.3.25
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.25
@schematics/update                 0.803.25
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by alan-agius4** [comment]
Can you please provide a minimal repro?

**Comment by johnny-mh** [comment]
[nglib-test.tar.gz](https://github.com/ng-packagr/ng-packagr/files/4363420/nglib-test.tar.gz)

If `my1-sub1` import `my1-sub2`'s hello method. It cause cannot find module error.

But `my1-sub2` import `my1-sub1` hello method. I can build without any error.

**Comment by johnny-mh** [comment]
@alan-agius4  [nglib-test.tar.gz](https://github.com/ng-packagr/ng-packagr/files/4363420/nglib-test.tar.gz)

If `my1-sub1` import `my1-sub2`'s hello method. It cause cannot find module error.

But `my1-sub2` import `my1-sub1` hello method. I can build without any error.
