### ISSUE TITLE
Function calls are not supported in decorators but 'ReducersManager' was called.

### ISSUE THREAD

**Issue by WafaaNasr** [dherges/ng-packagr#961]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

I am using Angular 6 to create library "FlightTrackingLib" where I am using another Angular 6 library "ngrx-app-store" after calling one of the classes in this library in the new library. and compile and I'm getting an error saying " Function calls are not supported in decorators but 'ReducersManager' was called."

#### How To Reproduce
Create new angular 6 library use the "ngrx-app-store" as a dependency.  Import the NgrxAppStoreModule in the library module, create a file and use this line
export const flightReducer= new ReducersManager<any>();

#### Expected Behaviour

Want to build with AOT without errors (I need this to be compatible with Angular Universal)

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
"@angular/cdk": "^6.2.1",
 "ngrx-app-store": "^1.0.17",
"zone.js": "^0.8.26",
"rxjs": "^6.2.1",
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This is an angular bug and is being tracked here: https://github.com/angular/angular/issues/23609

**Comment by alan-agius4** [comment]
This is an angular bug and is being tracked here: https://github.com/angular/angular/issues/23609

Also, can you actually run this command ` node_modules/.bin/ng-packagr --version` and provide the output?

Thanks

**Comment by WafaaNasr** [comment]
When I ran the command without npm, I got this error:
'node_modules' is not recognized as an internal or external command,
operable program or batch file.

How are you using ng-packagr? Is it with Angular-ClI? And which version of ng-packagr are you using?

I am using Angular 6 libraries, Yes using the Angular-CLI
This is the current version  "ng-packagr": "^3.0.0-rc.2"

**Comment by alan-agius4** [comment]
Can yo try to update to ng-packagr to the latest stable version?

We have added the fullTemplateTypeCheck which should suppress the error.

**Comment by WafaaNasr** [comment]
Still The same :( . I have updated the ng-packagr in both the inner library ( and publish to npm ) , and in the outer library and build but still the same error

**Comment by WafaaNasr** [comment]
@alan-agius4  I found yesterday another workaround is to export the function that's inside the exported class instead of exporting the class, Because as far as I think the metadata is generated for the outer exported objects.

Thank you for your cooperation
