### ISSUE TITLE
CI: add windows-based CI checks

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#962]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

see #890 

#### How To Reproduce

n/a

#### Expected Behaviour

CI checks on a windows system, e.g. AppVeyor

#### Version Information

n/a

**Comment by dherges** [comment]
SOmething is broken in the integration specs on windows. We get a "module not found" from typescript:

```
$ integration/samples.sh
FIND: Parameter format not correct
$ cross-env TS_NODE_PROJECT=integration/tsconfig.specs.json mocha --require ts-node/register "integration/samples/*/specs/**/*.ts"
C:\projects\ng-packagr\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
integration/samples/core/specs/ts-api.ts(2,26): error TS2307: Cannot find module '../dist/sample-core'.

```

**Comment by alan-agius4** [comment]
Can it be that the build for the packages failed?  Do you have a link for
the CI or a full long of the build step?

Thanks.

**Comment by alan-agius4** [comment]
Looks like this is the issue

https://github.com/dherges/ng-packagr/blob/master/integration/samples.sh
