### ISSUE TITLE
build error when a method has documentation with annotations above it ie. @param 

### ISSUE THREAD

**Issue by aykutyararbas** [dherges/ng-packagr#964]
## Type of Issue
Build error  
```
[X] Bug Report
[ ] Feature Request
```

## Description

Adding doc with method signature annotations causing packager to error.

LIKE 
BUILD ERROR
src/app/common/featureflags.service.ts(59,3): warning TS0: the type annotation on @param is redundant with its TypeScript

Example service method

/**
   * Returns the service label for a given service
   * Returns the id , if the service is not available
   * **@param** {string} id
   * **@returns** {string}
   */
  public getServiceLabel(id: string): string {
    if(this.SERVICE_REGISTRY[id]) {
      return this.SERVICE_REGISTRY[id].label;
    } else {
      return id;
    }
  }

 

#### How To Reproduce
 Steps
1 -  Add a documentation to one of your service
     Like the one above start with / * *  and add @param 
     End your documentation

2 - Run ng-packagr -p ng-package.json

>> _Can you reproduce the error in the integration tests in ng-packagr?_
>>_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of >>these builds!_

>>_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

>> _A bug: please describe what behavior or result you expected_
Build without erroring out.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.6.0
@angular/*: 5.2.10
typescript: ~2.6.2
"rxjs": "^5.5.11",
node: v8.11.1
npm: 5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

Thanks and regards,

Aykut~

**Comment by aykutyararbas** [comment]
I see. Updated the js documentation. It worked. 

I still think that it can be improved to keep js doc, by making it context-aware, which in this case context is documentation.

Hope to see changes in the future to keep documentation as it is.

**Comment by aykutyararbas** [comment]
Closing the issue.
Resolution is to remove @ annotation sign inside the js doc 

Instead of using @param you can manually remove @ sign.

**Comment by Aphax** [comment]
Having the same troubles. Removing @ annotation sign juste makes jsdoc not interpreted, how comes ng build isn't affected by those annotations but ng-packagr does ? I don't see why this error should be an expected behavior since ng build does not fail.

**Comment by alan-agius4** [comment]
When building a library tstickle is used while when building an application
it isn’t.

**Comment by Aphax** [comment]
Thanks @aykutyararbas

**Comment by Aphax** [comment]
@alan-agius4 Thanks for clarifying, wondering why do we need two different tools to do the same thing ?

**Comment by alan-agius4** [comment]
At application level, you know what bundler you are going to use etc, while
when building a library you don’t know. Apart from that when building s
library there are several different AngularCompilerOptions that needs to be
switched on which when building an application needs to be switched off.

In a nutshell, building an app, is not the same as building a library.
