### ISSUE TITLE
Angular cli 6 and ng-packagr 3.0.3

### ISSUE THREAD

**Issue by gagle** [dherges/ng-packagr#971]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

Angular cli 6 installs ng-packagr v3.0.0-rc2 if I recall correctly. Each lib is built inside dist/_lib-name_. If I try to upgrade ng-packagr to 3.0.3 (last of v3.x.x) the build no longers works, it generates a dist/_lib_ folder alogn with an npm error:

npm ERR! enoent ENOENT: no such file or directory, open '_root_\dist\_lib_name_\package.json'

Is this issue something more related to angular cli than to ng-packagr?

#### Version Information

ng-packagr 3.0.3
@angular/cli 6.0.8
@angular-devkit/build-ng-packagr 0.6.8

**Comment by alan-agius4** [comment]
`ng-packagr` configuration hasn't changing between rc2 and the final version. And ng-packagr v3 shouldn't have any issue with Angular CLI as even within the CLI repo, there are integration tests testing the integration between ng-packagr v3 final and Angular CLI V6+

Can you provide you provide a small reproduction please?

**Comment by gagle** [comment]
For any reason I had this in the ng-package.prod.ts file:

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/lib",
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
```

I just fixed the dist folder to `"dest": "../../dist/<lib_name>"`

**Comment by alan-agius4** [comment]
There was a bug in Angular CLI when generating a new library.

https://github.com/angular/angular-cli/issues/11251
