### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by epelc** [dherges/ng-packagr#976]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_
Seems to be when using a component with a templateUrl in 4.0.0 rc2 it always returns this error. Note my component is in a sub package within a regular angular cli project's generated library.

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

Components with template urls should compile.

_A feature: do you have a first draft or an idea how to implement?_

```
Error: : TypeError: Cannot read property 'length' of undefined
    at new _Tokenizer (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:4535:38)
    at tokenize (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:4493:12)
    at HtmlParser.Parser.parse (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:5121:31)
    at HtmlParser.parse (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:7768:39)
    at I18NHtmlParser.parse (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:7957:44)
    at DirectiveNormalizer._preparseLoadedTemplate (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:2035:51)
    at /Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:2030:76
    at Object.then (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:292:77)
    at DirectiveNormalizer._preParseTemplate (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:2030:26)
    at DirectiveNormalizer.normalizeTemplate (/Users/ed/someproject/node_modules/@angular/compiler/bundles/compiler.umd.js:2015:36)

    at Object.<anonymous> (/Users/ed/someproject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/ed/someproject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ed/someproject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/ed/someproject/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/ed/someproject/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:28:32)
    at Generator.next (<anonymous>)
    at /Users/ed/someproject/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.0.0-rc.2
@angular/compiler:     6.0.6
rollup:                0.60.7
tsickle:               0.30.0
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Did you enable ‘enableResourceInlining’ in your tsconfig?

Check here for a list of breaking changes https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md

**Comment by alan-agius4** [comment]
Can you please provide a small reproduction?

**Comment by devbean** [comment]
Sorry I made a mistake. I built a newer library with ng-packagr 4 and enableResourceInlining mixed dependencies without enableResourceInlining. When I fixed this, everything went OK. Maybe that's the problem. ng-packagr 4 could work without enableResourceInlining?

**Comment by alan-agius4** [comment]
This is required if you are building components, however we are thinking of switching this on by default

**Comment by udnisap** [comment]
in the latest umd it is `node_modules/@angular/compiler/bundles/compiler.umd.js: 10463`

**Comment by beac0n** [comment]
> I ran into this with 1.6.2 RC0 and was able to debug it by adding a console log to the lexer.
> In lexer.js, (line 77 as of writing), replace this:
> 
> ```js
> return new _Tokenizer(new parse_util_1.ParseSourceFile(source, url), getTagDefinition, tokenizeExpansionForms, interpolationConfig).tokenize();
> ```
> 
> with this:
> 
> ```js
> var parsedFile = new parse_util_1.ParseSourceFile(source, url);
> if (parsedFile.content === undefined) {
>     console.log("ERROR File not found: ", url);
> }
> return new _Tokenizer(parsedFile, getTagDefinition, tokenizeExpansionForms, interpolationConfig).tokenize();
> ```
> 
> This showed me the missing file and I was able to fix it within minutes. Hope this helps someone.

This was extremly helpful. Thank you so much for figuring that out.
You should create a pull request for that. This error log is a no-brainer. Why is this not included in the source code?

**Comment by mikegoodstadt** [comment]
To clarify the comment @udnisap:
> in the latest umd it is `node_modules/@angular/compiler/bundles/compiler.umd.js: 10463`
replace this:
```js
return new _Tokenizer(new ParseSourceFile(source, url), getTagDefinition, options).tokenize();
```
with this:
```js
var parsedFile = new ParseSourceFile(source, url);
        if (parsedFile.content === undefined) {
            console.log("ERROR File not found: ", url);
        }
        return new _Tokenizer(parsedFile, getTagDefinition, options).tokenize();
```
Many thanks @johnnyprogger and @udnisap!

**Comment by rovico** [comment]
@johnnyprogger you saved my day!

**Comment by ImJohnDoe** [comment]
@rovico  Thanks for pointing out that this error could be caused by incorrect template file, this was my issue as well!

**Comment by ahmadalsadder** [comment]
@rovico Thanks a lot ,same issue and same solution :)

**Comment by totszwai** [comment]
Why is the suggestion from @mikegoodstadt not committed or fix in the actual code?

**Comment by bes1002t** [comment]
@rovico  had the solution. It was just a wrong typed template path in my case. I don't know why such an issue generates this error message. Addtionally there was no stack trace to follow. Please change the error message for the case the template path is wrong.
