### ISSUE TITLE
Unable to compile packages because it's not under the rootDir

### ISSUE THREAD

**Issue by mogusbi** [dherges/ng-packagr#987]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have a mono repo that contains an Angular app with a library within it generated by the angular CLI alongside the code for the API and a shared folder for models to be used across both the client and the API

The Library contains services that reference these shared models, however when I go to compile I get the following error;

`error TS6059: File '/path/to/mono-repo/models/article/article.model.ts' is not under 'rootDir' '/path/to/mono-repo/angular/projects/core/src'. 'rootDir' is expected to contain all source files.`

#### How To Reproduce

You can reproduce by simply trying to include a file from outside the rootDir that's automatically generated by ng-packagr.

Here is the folder structure

```
- angular
-- projects
--- core
---- src
----- lib
------ article
------- article.service.ts
- models
-- article
--- article.model.ts
```

#### Expected Behaviour

For the library to compile or for a way to get around this stumbling block.

#### Version Information

```
ng-packagr: 3.0.3
@angular/compiler: 6.0.7
rollup: 0.59.4
tsickle: 0.29.0
typescript: 2.7.2
```

**Comment by JoostK** [comment]
You'll have to setup the `models` as a library of its own. It is not possible for libraries to reference files outside of their library root directory, because these files cannot be included into the final library package.

**Comment by mogusbi** [comment]
Is there a pre build hook where it can copy the models folder into the library? I don't want to move the models into the library because they are being used outside of Angular

**Comment by alan-agius4** [comment]
You can do prebuild hooks using standard npm scripts

https://docs.npmjs.com/misc/scripts

**Comment by mogusbi** [comment]
No worries, I've just restructured my project and made the models folder into it's own library instead. The bits outside of Angular appear to be happy enough to consume the library after it's been compiled by packagr

**Comment by MurhafSousli** [comment]
I have the same issue, But I am using a secondary entry point as stated in the [secondary-entrypoints.md](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md) .

The secondary entry point exports its own module that imports a file from the main entry endpoint, building the library throw this error:

`BUILD ERROR
error TS6059: File 'D:/Projects/ngx-scrollbar/projects/ngx-scrollbar/smooth-scroll/smooth-scroll.module.ts' is not under 'rootDir' 'D:\Projects\ngx-scrollbar\projects\ngx-scrollbar\src'
. 'rootDir' is expected to contain all source files.`

@alan-agius4 @JoostK How can I fix it?

**Comment by JoostK** [comment]
@MurhafSousli The import into the main entrypoint from the secondary entrypoint must not be relative. A relative import would result in the imported file to become part of the compilation of the secondary entrypoint, which results in a file outside of the root directory of the secondary entrypoint (the error you are seeing).

Instead, use the library name itself. This requires that the thing you import must be exported from your public api file.

**Comment by MurhafSousli** [comment]
@JoostK, Ok I tried to do like you said, my main entry point has the following module and I am importing a module from the second entry point without using relative path

```ts
import { SmoothScrollModule } from 'ngx-scrollbar/smooth-scroll';

@NgModule({
  imports: [
    ...
    SmoothScrollModule
  ]
})
export class NgScrollbarModule {
}
```
In order to be able to import from `ngx-scrollbar/smooth-scroll` I have to build it then link it, right?

How can I link the secondary entry point if I am unable to build it?

**Comment by MurhafSousli** [comment]
@JoostK  Ok, I think I misunderstood, linking the library makes no sense in this case.

I tried exporting the module in `public-api` 

```ts
/*
 * Public API Surface of ngx-scrollbar
 */

export * from './lib/ng-scrollbar.module';
export * from './lib/ng-scrollbar-config';
export * from './lib/ng-scrollbar';
export * from './lib/scroll-viewport';

export * from '../smooth-scroll/src/public-api';
```
Then I import it in the main module 

```ts
import { SmoothScrollModule } from '../public-api';

@NgModule({
  imports: [
    ...
    SmoothScrollModule
  ]
})
export class NgScrollbarModule {
}
```

Error 
`BUILD ERROR
error TS6059: File 'D:/Projects/ngx-scrollbar/projects/ngx-scrollbar/smooth-scroll/src/public-api.ts' is not under 'rootDir' 'D:\Projects\ngx-scrollbar\projects\ngx-scrollbar\src'. 'roo
tDir' is expected to contain all source files.
error TS6059: File 'D:/Projects/ngx-scrollbar/projects/ngx-scrollbar/smooth-scroll/src/smooth-scroll-manager.ts' is not under 'rootDir' 'D:\Projects\ngx-scrollbar\projects\ngx-scrollbar
\src'. 'rootDir' is expected to contain all source files.
error TS6059: File 'D:/Projects/ngx-scrollbar/projects/ngx-scrollbar/smooth-scroll/src/smooth-scroll.module.ts' is not under 'rootDir' 'D:\Projects\ngx-scrollbar\projects\ngx-scrollbar\
src'. 'rootDir' is expected to contain all source files.
error TS6059: File 'D:/Projects/ngx-scrollbar/projects/ngx-scrollbar/smooth-scroll/src/smooth-scroll.ts' is not under 'rootDir' 'D:\Projects\ngx-scrollbar\projects\ngx-scrollbar\src'. '
rootDir' is expected to contain all source files.`

**Comment by JoostK** [comment]
You have the determine if `ngx-scrollbar` is dependent upon `ngx-scrollbar/smooth-scroll` or the other way around. From the above code, it seems like your main entrypoint is dependent upon the secondary entrypoint. In that case, the `SmoothScrollModule` from the secondary entrypoint needs to be exported from the public api file of the secondary entrypoint and be imported from `NgScrollbarModule` using `ngx-scrollbar/smooth-scroll` (this import is not allowed to be relative as it crosses an entrypoint boundary).

But please verify if that is the correct dependency edge, as it means `ngx-scrollbar/smooth-scroll` cannot have imports into `ngx-scrollbar` (it would introduce a circular dependency).

**Comment by MurhafSousli** [comment]
@JoostK To clarify, I have a custom scrollbar library. This library provides a cross-browser smooth scroll functionality.

I would like to export this functionality not only in the _custom scrollbars_ but also as an independent module.

Therefore I created a secondary entry point and exported the module `SmoothScrollModule`.

So the main library `ngx-scrollbar` imports `SmoothScrollModule` from the secondary entry point.

**Comment by JoostK** [comment]
@MurhafSousli that sounds fine, so you'd need two changes:

You added the following to the public api of `ngx-scrollbar` (the main entrypoint)

```
export * from '../smooth-scroll/src/public-api';
```

This is fine, as it is perfectly valid to re-export stuff from dependent entrypoints to become part of your own api surface, however the import specifier needs to become absolute:

```
export * from 'ngx-scrollbar/smooth-scroll';
```

This prevents the secondary entrypoint from becoming part of the compilation of the main entrypoint, avoiding the "not in rootDir" error.

---

Secondly, you added an import from `NgScrollbarModule` in the main entrypoint as follows:

```
import { SmoothScrollModule } from '../public-api';
```

This introduces a circular dependency issue, as the `../public-api` file itself has an import into the `./lib/ng-scrollbar.module` file, which introduces a cycle. In general, you should never import through the public api within the entrypoint itself, but instead import from the location where the dependency is declared. In your case for `SmoothScrollModule`, that would be `ngx-scrollbar/smooth-scroll`.

**Comment by MurhafSousli** [comment]
Now I got it, thank you very much for the explanation, it worked!
