### ISSUE TITLE
[v4.0.0-rc3] Components don't get compiled SCSS inlined

### ISSUE THREAD

**Issue by bboehm86** [dherges/ng-packagr#990]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When using a generated lib (build with no errors or warnings and `4.0.0-rc.3`) the styles doesn't seem to be inlined when using an external `*.scss`-file

The `styles: []` is missing in the compiled lib `@Component()` and the browser complains correctly:
``` 
:49152/random.component.scss:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

#### How To Reproduce

- Generate a new Angular CLI project, add a lib, add ng-packagr `4.0.0-rc.3`, add a component with external `scss`-file, compile, inspect the output

or

1. Clone https://github.com/bboehm86/ng-packagr-scss
2. `yarn`
3. `yarn build dummy`
4. Inspect the output in the `dist/`-dir or use the lib in the app ( `yarn start`)

#### Expected Behaviour

The `scss`-files should be compiled and be included with the components as it is the case in  `3.0.3`

#### Version Information

```
ng-packagr: 4.0.0-rc.3 (+ 4.0.0-rc.2 / 4.0.0-rc.1)
@angular/compiler: 6.0.7
rollup: 0.62.0
tsickle: 0.32.0
typescript: 2.7.2
rxjs: 6.2.1
node: 8.9.0
yarn: 1.7.0
```

**Comment by alan-agius4** [comment]
From your example it looks like you didn't enable `enableResourceInlining` in your `tsconfig`

Please take a look at the breaking changes
https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by bboehm86** [comment]
You are absolutely right! Thanks & sorry I totally missed that :-)
