### ISSUE TITLE
Unable to use exported models

### ISSUE THREAD

**Issue by sataqi** [dherges/ng-packagr#992]
## Type of Issue

[ ] Bug Report
[ ] Feature Request
[x] Question

## Description
How to create sub package for each kind of export? For example, I want `import` statement to look like this for each type of file exported:

**Models (inluding interfaces and classes)**
`import {FooModel, BarModel} from 'my-lib/models'`;

**Enums**
`import {FooTypes, BarTypes} from 'my-lib/enums'`;

Right now, as all the exports are from `public_api.ts` file, my `import` statements look like this:

**Models (inluding interfaces and classes)**
`import {FooModel, BarModel} from 'my-lib'`;

**Enums**
`import {FooTypes, BarTypes} from 'my-lib'`;

I tried creating export files but `webpack` fails to compile. Here's the link to full question, with code and error statement: [StackOverflow](https://stackoverflow.com/questions/51186867/unable-to-use-exported-models-from-custom-angular-library)

**Comment by sataqi** [comment]
@alan-agius4 

Model class: _src/app/modules/my-custom-module/models/my-model.ts_
```
export class MyModel {
  constructor() {
    // default values for props here
  }

  // ...props here
}
```

Index file: _src/app/modules/my-custom-module/models/index.ts_
```
export * from './my-model';
export * from './my-other-model';
```

Export file at root: _models.ts_
`export * from './src/app/modules/my-custom-module/models/index';`

ng-packagr file at root: _public_api.ts_
```
export * from './models';

export * from './src/app/modules/my-custom-module/my-custom-module.module';
export * from './src/app/modules/my-custom-module/components/index';
```

Main project code:
```
import {MyCustomModule} from 'my-custom-library'; // works
import {MyModel} from 'my-custom-library'; // works
import {MyModel} from 'my-custom-library/models'; // does not work
```

I believe, I'm missing something about mapping `webpack` module resolution because VS Code recognizes the import, intellisense works and even Ctrl + Click navigates to right file but `webpack` fails in compilation.

*Error:*

> module not found error can't resolve my-custom-library/models

**Comment by alan-agius4** [comment]
You need to export the models from models/index in your public_api

**Comment by sataqi** [comment]
Ok but wouldn't my `import` still look like this:

`import {MyModel} from 'my-custom-library';` // as models are exported from public_api.ts

but I want my models `import` to look something like this:

`import {MyModel} from 'my-custom-library/models'` // note the /models sub path in the end

**Comment by alan-agius4** [comment]
If you want to import `my-custom-library/models` you need to use secondary entrypoints and create a subpackage https://github.com/dherges/ng-packagr/blob/master/docs/secondary-entrypoints.md

**Comment by alan-agius4** [comment]
If you wish to use `import {MyModel} from 'my-custom-library/models'` you'd need to create secondary entrypoints.

With your current implementation that is something not possible.

Take a look at this documentation; https://github.com/dherges/ng-packagr/blob/master/docs/secondary-entrypoints.md

**Comment by sataqi** [comment]
I'll try that and update. thank you!

**Comment by alan-agius4** [comment]
Can you create a small reproduction please?

**Comment by sataqi** [comment]
nvm. It worked using `secondary-endpoints`.  Thank you for your help!
