### ISSUE TITLE
Ionic Failing Build Process

### ISSUE THREAD

**Issue by ehorodyski** [dherges/ng-packagr#999]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

I'm trying to build a monorepo with reusable Ionic components. When trying to package a sample app with nothing but a blank Ionic starter and `ng-packagr`, I get the following error during `npm run packagr`:

```
BUILD ERROR
node_modules/ionic-angular/components/picker/picker-component.d.ts.PickerCmp.html(13,71): : Expected 0 arguments, but got 1.
node_modules/ionic-angular/components/input/input.d.ts.TextInput.html(1,928): : Expected 0 arguments, but got 1.
node_modules/ionic-angular/components/input/input.d.ts.TextInput.html(1,961): : Expected 0 arguments, but got 1.

Error: node_modules/ionic-angular/components/picker/picker-component.d.ts.PickerCmp.html(13,71): : Expected 0 arguments, but got 1.
node_modules/ionic-angular/components/input/input.d.ts.TextInput.html(1,928): : Expected 0 arguments, but got 1.
node_modules/ionic-angular/components/input/input.d.ts.TextInput.html(1,961): : Expected 0 arguments, but got 1.
```
#### How To Reproduce

1. Create a blank Ionic starter project: `ionic start ionic-packagr-test blank`.
2. Import needed libraries (see below).
3. Setup `public_api.ts` (see below).
4. Run `npm run packagr`.

package.json:
```
{
  "name": "ionic-packagr-test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "packagr": "ng-packagr -p ng-package.json"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "4.9.1",
    "@ionic-native/splash-screen": "4.9.1",
    "@ionic-native/status-bar": "4.9.1",
    "@ionic/storage": "^2.1.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "^5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^5.2.11",
    "@angular/language-service": "^6.0.7",
    "@ionic/app-scripts": "3.1.10",
    "@types/node": "^10.5.2",
    "ng-packagr": "^3.0.3",
    "ts-node": "^7.0.0",
    "tslint": "^5.10.0",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}
```

public_api.ts:
```
export * from './src/app/app.module';
```

#### Expected Behaviour

Just to build, I suppose.

#### Version Information

See above.

**Comment by alan-agius4** [comment]
Unfortunitly Ionic 3 doesn’t support fullTemplateTypeChecks as they have some errors within their templates. Also, more unfortunate that Ionic V3 is not maintained any longer.

A work around would be to change the tsconfig setting mentioned above. More info on how to change the tsconfig can be found 
https://github.com/dherges/ng-packagr/blob/master/docs/override-tsconfig.md

**Comment by alan-agius4** [comment]
For future visitors, note the same error can occure when having something like the below

```
@HostListener("onScroll", ["$event"]) someFunction(event) {

}
```

And the `event` parameter is omitted.

**Comment by ehorodyski** [comment]
I was able to fix this by moving all my `dependencies` into `devDependencies` and only including what was being used (`ionic-angular`, `ionicons`) into `peerDependencies`.

**Comment by sreerajkarippala** [comment]
In the case of ionic 4, check your code using ionic-angular then replace with @ionic/angular

**Comment by aditodkar** [comment]
I am getting same error how to fix it? I tried changing es2015 to es5 in tsconfig file but it doesn't work. 
![Screenshot_6](https://user-images.githubusercontent.com/16613832/71578336-bd685a00-2b1d-11ea-9d4e-ca934a4b4ba5.png)
